feat(CategoriesChart): add categories chart
toptal/picasso pull request #2024
Opened 2021-04-07 07:20 UTC by hweeTan

[SPT-1430](https://toptal-core.atlassian.net/browse/SPT-1430)

### Description

CategoriesChart is a wrapper for BarChart to handle all business logic from kipper api.

In this PR:
- Add `getBarColor` to `BarChart` to customize each bar's color
- Add `labelKey` to `BarChart` to customize the key for x labels

### How to test

- Go to `?path=/story/picasso-charts-categorieschart--categorieschart`
- The chart should display correct data, colors and tooltip as in legacy
![image](https://user-images.githubusercontent.com/18625278/113826137-050f7400-97ac-11eb-900e-36f5432d765f.png)

### Screenshots

![image](https://user-images.githubusercontent.com/18625278/113826175-0fca0900-97ac-11eb-810b-1f1945b6c8fd.png)

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-04-19 11:06 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/story/index.jsx
> +// .addExample('CategoriesChart/story/Multiple.example.tsx', 'Multiple')
Shouldn't it be deleted?

2021-04-19 11:12 UTC, hweeTan commented on packages/topkit-analytics-charts/src/CategoriesChart/CategoriesChart.tsx
> +const CustomTooltip = ({
I just hesitate to write tests for these at the moment since we don't have the final design yet. All of these can change quite a lot after new design comes in.

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/CategoriesChart.tsx
> +        // @ts-expect-error: There is some magic in recharts that adding the props for us
Can you explain this part in detail, please?

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/utils/get-display-texts/get-display-texts.ts
> +    teamTexts: originalTeamValues
I'd extract `teamTexts` and `userTexts` generation into a helper function to avoid duplication. (the only thing that differs is `user/team`)

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/types.ts
> +export type Bar = {
```suggestion
export type DataItem = {
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/types.ts
> +export type Labels = Record<string, string>
nit: `Labels` variable name\ makes me think that it's an array type.

```suggestion
export type LabelMap = Record<string, string>
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/types.ts
> +export type Tooltips = Record<string, Record<string, Record<string, string>>>
nit:

```suggestion
export type TooltipMap = Record<string, Record<string, Record<string, string>>>
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/format-data/format-data.ts
> +const sum = (values: number[]) =>
Let's extract it into `@toptal/picasso/utils'

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/get-color/get-color.ts
> +const COLORS: Record<string, string[]> = {
```suggestion
const COLOR_MAP: Record<string, string[]> = {
```

or

```suggestion
const COLOR_OF: Record<string, string[]> = {
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> +      <Paper data-testid='tooltip'>
It's not a tooltip but content.

```suggestion
      <Paper data-testid='tooltip-content'>
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/test.tsx
> +const arrangeTest = (props: Partial<Props>) => {
```suggestion
const renderTooltip = (props: Partial<Props>) => {
```

2021-05-31 05:32 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/test.tsx
> +jest.mock('@toptal/picasso', () => ({
What's the reason behind this mock?

2021-05-31 06:53 UTC, hweeTan commented on packages/topkit-analytics-charts/src/CategoriesChart/CategoriesChart.tsx
> +        // @ts-expect-error: There is some magic in recharts that adding the props for us
There are 2 other props Recharts passes to this tooltip component under the hood: `active` and `payload`. We need to assume they are there without explicitly passing them. Please see https://recharts.org/en-US/api/Tooltip#active : `..., usually calculated internally.`

2021-05-31 06:56 UTC, hweeTan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/test.tsx
> +jest.mock('@toptal/picasso', () => ({
Ah I forgot to remove it. Thanks

2021-05-31 07:22 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/CategoriesChart.tsx
> +        // @ts-expect-error: There is some magic in recharts that adding the props for us
Let's replace the comment then

```suggestion
        // @ts-expect-error: Recharts passes 2 props under the hood: active and payload. We need to assume they are there without explicitly passing them.
```

2021-05-31 07:23 UTC, teimurjan approved these changes
Great job!

2021-06-01 06:45 UTC, denieler requested changes

2021-06-01 06:45 UTC, denieler commented on packages/topkit-analytics-charts/src/CategoriesChart/CategoriesChart.tsx
> +        // @ts-expect-error: Recharts passes 2 props under the hood: active and payload. We need to assume they are there without explicitly passing them.
👍 thank you for the comment 🙇‍♂️

2021-06-01 06:45 UTC, denieler commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/format-data/format-data.ts
> +import { sum } from '@toptal/picasso/utils'
to be honest, I don't see a need to have a separate sum utility file, I would place the implementation of `sum` in this file instead

2021-06-01 06:45 UTC, denieler commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/get-color/get-color.ts
> +  pending: [palette.yellow.main, palette.yellow.main]
this looks too connected to the implementation details, even to the shape of the API data. Before in this package, we had more or less reusable component, but this is very feature specific looks like

2021-06-01 06:45 UTC, denieler commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/get-color/get-color.ts
> +  pending: [palette.yellow.main, palette.yellow.main]
this probably should be part of the API and to be specified by the component user

2021-06-01 07:41 UTC, teimurjan commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/format-data/format-data.ts
> +import { sum } from '@toptal/picasso/utils'
It was made by my recommendation. I see this function as an abstract one. Why don't extract it? We don't use any package to avoid utils duplications (ex. `lodash`). I'd extract them into our own package then.

PS:
- We have `isNumber` function, which is not used anywhere
- We have `isOverflown` function, which is used in 1 place

2021-06-01 07:44 UTC, denieler commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/format-data/format-data.ts
> +import { sum } from '@toptal/picasso/utils'
I don't have very strong opinion regarding this utility function 👍

2021-06-01 08:11 UTC, hweeTan commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/get-color/get-color.ts
> +  pending: [palette.yellow.main, palette.yellow.main]
IMO, it is just like why `AnalyticsChart` is created in the first place, if I understood it correctly. This `topkit-analytics-chart` package is a middle man to use charts with Kipper API. So I think it should mirror [this component in legacy](https://github.com/toptal/platform/blob/master/app/assets/features/platform/analytics/js/components/charts/views/categories_chart.js)

2021-06-01 11:15 UTC, vedrani reviewed
@hweeTan can you provide docs or more info on what is Kipper, how API looks like? Thanks.

2021-06-01 11:15 UTC, vedrani commented on packages/topkit-analytics-charts/src/CategoriesChart/utils/get-color/get-color.ts
> +  pending: [palette.yellow.main, palette.yellow.main]
This looks like it's Staff portal feature. To me it looks like we need to separate logic into 3 different places:

- picasso-charts
  - components for charts connected only with BASE
- topkit/kipper-analytics-charts
  - integration of picasso-charts with Kipper API
- StaffPortal/modules/*
  - specific implementation for Staff portal feature

2021-06-01 11:15 UTC, vedrani commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> +    const { teamTexts, userTexts } = getDisplayTexts({
Is `team` and `user` part of Kipper API or Staff portal feature?

2021-06-02 03:35 UTC, hweeTan commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> +    const { teamTexts, userTexts } = getDisplayTexts({
`team` and `user` are part of Kipper API as you can see [here](https://github.com/toptal/platform/blob/0e0a056f03f64de9db423366f201f8bf7627d90b/app/assets/features/platform/analytics/js/components/charts/views/categories_chart.js#L81)

2021-06-02 03:41 UTC, hweeTan commented
> @hweeTan can you provide docs or more info on what is Kipper, how API looks like? Thanks.

@vedrani Thanks for having a look. Honestly, I kind of just followed the directly already set for the existed `AnalyticsChart`. My understanding is that Kipper will provide some KPI related to data to show various charts in legacy platform, I am not sure if those are shown on other Portal but @denieler have asked the other teams.

So based on what I understood, these `topkit-analytics-charts` should mirror [these charts](https://github.com/toptal/platform/tree/master/app/assets/features/platform/analytics/js/components/charts/views) in legacy platform.

2021-06-02 11:37 UTC, denieler approved these changes

2021-06-02 12:38 UTC, vedrani approved these changes
Based on what I learned I think topkit-analytics-charts need to be moved into topkit repo. this shouldn't be done in this PR. We will discuss this in FX arch meeting

2021-06-02 13:40 UTC, merged