feat(menu): add drilldown mode
toptal/picasso pull request #2041
Opened 2021-04-22 14:48 UTC by alexanderpolyankin

[FX-1126]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-04-26 07:35 UTC, denieler commented on packages/picasso/src/NonNativeSelect/styles.ts
> -import '../MenuItem/styles'
we probably don't need to remove them from `NonNativeSelect`, because when picasso installed in the real project and only Select will be used there we can be missing those styles, because of tree-shaking
(NonNativeSelect uses ScrollMenu, which uses Menu)

2021-04-26 07:39 UTC, denieler commented on packages/picasso/src/Menu/Menu.tsx
> +  mode: 'slider',
can we also discuss this name of the menu with designers? so we can call it in the same way in Abstract as well

2021-04-26 07:42 UTC, denieler commented on packages/picasso/src/Menu/styles.ts
> +  }
can we use not an override from MUI here, but pass a class from `createStyles` 👇 ?

2021-04-26 09:25 UTC, teimurjan approved these changes
Looks good to me. 👍

2021-04-26 09:25 UTC, teimurjan commented on packages/picasso/src/AccountSelect/AccountSelect.tsx
> +export interface Props extends BaseProps, Omit<MenuAttributes, 'onSelect'> {
`MenuAttributes` looks a bit weird to me. What if we call it `BaseMenuProps`?

2021-04-26 09:25 UTC, teimurjan commented on packages/picasso/src/Menu/styles.ts
> +  }
What's the reason behind it?

2021-04-26 11:13 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/styles.ts
> +  }
Styles are the same that were used before splitting Menu into logic and UI parts. I haven't changed them.

2021-04-26 11:15 UTC, alexanderpolyankin commented on packages/picasso/src/NonNativeSelect/styles.ts
> -import '../MenuItem/styles'
Fixed

2021-04-26 11:16 UTC, alexanderpolyankin commented
> What's the reason behind it?
These are the same styles that were before the components split, I haven't changed them.

2021-04-26 11:17 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/Menu.tsx
> +  mode: 'slider',
The `slider` name was confirmed by @havenchyk after conversation with the base team.

2021-04-26 19:12 UTC, alexanderpolyankin commented on packages/picasso/src/AccountSelect/AccountSelect.tsx
> +export interface Props extends BaseProps, Omit<MenuAttributes, 'onSelect'> {
It's Attributes from native elements, e.g. `HTMLAttributes<HTMLButtonElement>`

2021-04-29 13:36 UTC, havenchyk requested changes
### Menu Item Selected state

Starting from the last children all it's parents should be highlighted

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1291032/116555574-3c81c400-a905-11eb-84df-e7123a8184c1.png">

### Back button in the main menu should keep first menu opened

![Kapture 2021-04-29 at 16 11 18](https://user-images.githubusercontent.com/1291032/116555921-92ef0280-a905-11eb-9fa6-66627c921ff3.gif)

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/AccountSelect/AccountSelect.tsx
> +export interface Props extends BaseProps, Omit<MenuAttributes, 'onSelect'> {
why not to use `HTMLAttributes<HTMLButtonElement>` in this case?

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/Menu/Menu.tsx
> +  mode?: MenuMode
are you okay with `variant`?

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/Menu/Menu.tsx
> +  mode: 'slider',
it wasn't confirmed 😢

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/Menu/Menu.tsx
> +export default Menu
Menu has a static prop Item, is everything okay with type?

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/Menu/MenuContext.tsx
> +  mode?: MenuMode
variant

2021-04-29 13:36 UTC, havenchyk commented on packages/picasso/src/Menu/hooks/use-drilldown-menu/test.tsx
> +    act(() => result.current.context.onItemMouseEnter?.('1', menu))
why do you use `?.` here? is it you're passing this handler, no? is it for TS only?

2021-04-29 14:04 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/hooks/use-drilldown-menu/test.tsx
> +    act(() => result.current.context.onItemMouseEnter?.('1', menu))
Because the onItemMouseEnter can be undefined from TS perspective

2021-04-29 14:04 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/test.tsx
> -  it('has back button when in submenu', () => {
And in cypress test

2021-04-29 20:25 UTC, havenchyk commented on packages/picasso/src/Menu/Menu.tsx
> +  mode: 'slider',
@alexanderpolyankin approved variant is "slide" 😄

2021-04-29 20:26 UTC, havenchyk commented on packages/picasso/src/Menu/hooks/use-drilldown-menu/test.tsx
> +    act(() => result.current.context.onItemMouseEnter?.('1', menu))
I expected more generic answer like "onItemMouseEnter" is an optional function and typescript will treat it like possible undefined 🙁

2021-04-30 10:13 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/MenuContext.tsx
> +  mode?: MenuMode
FIxed

2021-04-30 10:14 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/Menu.tsx
> +export default Menu
It's ok because `Menu` is casted to `CompoundedComponentWithRef`

2021-04-30 10:14 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/Menu.tsx
> +  mode?: MenuMode
Renamed to variant

2021-04-30 10:17 UTC, alexanderpolyankin commented
@havenchyk Renamed to `variant`, fixed hover issue in the `drilldown` variant. I'll fix the back button issue soon.

About the default `slide` mode, my reasoning was that we can release the `drilldown` variant without a breaking change, and then change the default value with another PR. Please confirm if that's ok.

Please also confirm that there are no other issues that I should address in this PR.

2021-04-30 17:02 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/Menu.tsx
> +  mode: 'slider',
Fixed

2021-04-30 17:02 UTC, alexanderpolyankin commented
@havenchyk fixed all the issues, please have a look

2021-05-03 10:50 UTC, alexanderpolyankin commented on packages/picasso/src/Menu/styles.ts
> +  }
I mean that the styles are not changed at all. I only reverted changes with extracting `MenuList`.

2021-05-04 07:42 UTC, havenchyk approved these changes
LGTM, only minor comments left

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/MenuItem/story/index.jsx
> +      ) // picasso-skip-visuals
👍

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/MenuItem/index.ts
> +export type { MenuItemAttributes } from './MenuItem'
make sure that `type` word is not removed during prepublish

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/MenuItem/hooks/use-slide-menu-item/test.tsx
> +    expect(onItemClick).toHaveBeenCalledTimes(1)
what do you check here if you call `result.current.onItemClick` at the previous line?

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/Menu/hooks/use-drilldown-menu/use-drilldown-menu.ts
> +    innerMenu: undefined,
explicit return of innerMenu: undefined? is there any reason for it?

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/Menu/hooks/use-menu/use-menu.ts
> +  return variant !== 'drilldown' ? slide : drilldown
nit: `return variant === 'slide' ? useSlideMenu(): useDrilldownMenu()`

2021-05-04 07:42 UTC, havenchyk commented on packages/picasso/src/Menu/index.ts
> -export * from './Menu'
can be a breaking change

2021-05-04 07:57 UTC, polyankin-globaldots commented on packages/picasso/src/Menu/hooks/use-menu/use-menu.ts
> +  return variant !== 'drilldown' ? slide : drilldown
We should not call hooks conditionally

2021-05-04 07:58 UTC, polyankin-globaldots commented on packages/picasso/src/Menu/hooks/use-drilldown-menu/use-drilldown-menu.ts
> +    innerMenu: undefined,
To return the same value from both hooks

2021-05-04 07:58 UTC, polyankin-globaldots commented
/rebase

2021-05-04 08:00 UTC, merged