feat: add grid support for radio and checkbox group
toptal/picasso pull request #2042
Opened 2021-04-23 14:59 UTC by sergiubutnarasu

[SPT-1530](https://toptal-core.atlassian.net/browse/SPT-1530)

### Description

Adding grid support to the radio group and the checkbox group.
Instead of replacing the horizontal property, which will add breaking changes, to display a grid like radio group, you need to pass the small/medium/large property. Also, you can define space between radio/checkbox.

### How to test

- Check /?path=/story/forms-radio--radio#radio-group-grid
- Check /?path=/story/forms-checkbox--checkbox#checkbox-group-grid

### Screenshots

![image](https://user-images.githubusercontent.com/2583281/115890158-4fa41800-a45d-11eb-89ca-589fa2883908.png)

![image](https://user-images.githubusercontent.com/2583281/115890225-6480ab80-a45d-11eb-82af-4610db932f56.png)

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-04-26 06:28 UTC, sergiubutnarasu commented
@toptal-bot run package:alpha-release

2021-04-26 07:46 UTC, denieler commented on packages/picasso/src/CheckboxGroup/CheckboxGroup.tsx
> +  const gridSpacing = spacing ?? horizontal ? 16 : 0
we should use here instead of `16` some variable, probably from the `theme.spacings`

2021-04-26 07:51 UTC, denieler commented on packages/picasso/src/Radio/story/RadioGroupGrid.example.tsx
> +  const [value, setValue] = useState<string>('')
wouldn't it understand the type if we just use `useState('')`?

2021-04-28 08:44 UTC, sashuk approved these changes
Tested on temploy for `Radio` and `Checkbox` groups, looks good!

2021-04-28 11:49 UTC, sergiubutnarasu commented on packages/picasso/src/RadioGroup/RadioGroup.tsx
> +  spacing?: GridSpacing
@havenchyk it's the same naming as we have to the grid component, but I will change it.

2021-04-28 12:03 UTC, havenchyk reviewed
PR looks really great, please check the comments

2021-04-28 12:15 UTC, alexanderpolyankin commented on packages/picasso/src/CheckboxGroup/styles.ts
> +      paddingTop: '0 !important',
Could we add a nested rule under `grid` to remove `!important`? I've checked - adding 1 extra CSS class would be enough to match the specificity of the source selector.
<img width="451" alt="Screen Shot 2021-04-28 at 3 13 50 pm" src="https://user-images.githubusercontent.com/77451815/116402036-96668900-a834-11eb-983a-2cd076c2f647.png">

2021-04-28 12:16 UTC, alexanderpolyankin requested changes
Please check if it's possible to remove `!important`, details in comments.

2021-04-28 12:27 UTC, havenchyk commented on packages/picasso/src/CheckboxGroup/styles.ts
> +      paddingTop: '0 !important',
there is a trick like `&&` to achieve this

2021-04-28 13:07 UTC, havenchyk commented on packages/picasso/src/CheckboxGroup/CheckboxGroup.tsx
> +  /** Defines amount of space between checkbox components (in px) */
👍 😄

2021-04-28 13:10 UTC, havenchyk approved these changes

2021-04-28 13:13 UTC, alexanderpolyankin approved these changes

2021-04-28 13:43 UTC, merged