feat(Tag): add styles for tag content overflow
toptal/picasso pull request #2048
Opened 2021-04-26 16:14 UTC by s0ber

### Description

The `min-width: 0` rule allows the content not to stretch beyond the width of the parent component. Without this rule we have no way to prevent the tag from stretching (and though applying additional layout-based styles like `text-overflow: ellipsis` or using the `TypographyOverflow` component).

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

<img width="1004" alt="Снимок экрана 2021-04-26 в 19 10 20" src="https://user-images.githubusercontent.com/763624/116116211-93985680-a6c3-11eb-8c4f-885ce348cdfe.png">

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-04-26 16:14 UTC, s0ber commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
I can remove this rule as it can be applied on a client side.

2021-04-26 16:24 UTC, s0ber commented on packages/picasso/src/Tag/styles.ts
> +      minWidth: 0
Alternatively we can use `width: 100%`

2021-04-28 09:42 UTC, havenchyk commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
@s0ber could you please clarify why is this needed?

2021-04-28 10:14 UTC, havenchyk commented
Two points: 

- please explain why max-width on the root is needed
- I think this example is not okay, what do you think?
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1291032/116387543-96aa5880-a823-11eb-8e68-d6aae4e874d0.png">

2021-04-28 13:16 UTC, havenchyk commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
I think it will be a breaking change. Can you add 'fullWidth' prop instead?

2021-04-28 13:16 UTC, havenchyk commented on packages/picasso/src/Tag/styles.ts
> +      minWidth: 0
minWidth is fine

2021-04-28 13:17 UTC, havenchyk requested changes
Please remove width: 100% from the root and add a new property instead on Tag to handle such case.

2021-04-28 14:35 UTC, s0ber commented
@havenchyk it's not `width: 100%`, but `max-width: 100%`, it will prevent the component from stretching past the parent component boundaries. But I can remove it completely and add it on a client side as a `css` prop.

2021-04-28 14:49 UTC, s0ber commented
@havenchyk thank you for taking a look! I'll push a fix!

2021-04-28 14:49 UTC, havenchyk approved these changes
My bad, misread the code :D

2021-04-28 15:05 UTC, havenchyk commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
this is fine

2021-04-28 15:58 UTC, s0ber commented
@havenchyk I think I'll leave the `max-width` property because we use it almost everywhere where we use tags. It's hard to imagine the case where we would like the tag to stretch past the layout boundary.

2021-05-12 11:02 UTC, havenchyk commented
/rebase

2021-05-13 07:46 UTC, OleksandrNechai commented on packages/picasso/src/Tag/story/Overflown.example.tsx
> +      </TypographyOverflow>
To me, his example does not demonstrate the capabilities of the component but rather tests its boundaries. Therefore the better place for this example would be in Cypress tests + Happo.

2021-05-13 07:58 UTC, OleksandrNechai commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
@havenchyk are you sure that messing with the width will not cause problems with reusing this component?

2021-05-13 08:02 UTC, havenchyk commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
I checked at codesandbox and it worked fine by me. Any specific example of when it can cause the problem?

2021-05-13 08:40 UTC, OleksandrNechai commented on packages/picasso/src/Tag/styles.ts
> +      maxWidth: '100%'
Well, it will work. But is it reusable? Is it a concern of a component to set its width? This [presentation](https://www.youtube.com/watch?v=XR6eM_5pAb0) always inspires me, I find ideas very appealing.

2021-05-13 08:43 UTC, OleksandrNechai requested changes
I reject because of example. I think it should be rather test, overflow does not really demonstrate features of the component

2021-05-14 06:26 UTC, s0ber commented
@OleksandrNechai do you have any other visual tests in Picasso apart the ones that are checking the storybooks?

2021-05-14 09:22 UTC, havenchyk commented
/rebase

2021-05-14 09:23 UTC, OleksandrNechai commented
@s0ber hey! Yes. We use Happo. Have a look at Happo tested example here https://github.com/toptal/picasso/blob/master/cypress/component/Accordion.spec.tsx

2021-05-14 11:39 UTC, havenchyk commented
/rebase

2021-05-31 15:21 UTC, OleksandrNechai approved these changes

2021-05-31 15:22 UTC, merged