feat(ProgressBar): [TEA-2569] Introduce ProgressBar component
toptal/picasso pull request #2063
Opened 2021-05-05 23:21 UTC by besirovic

[TEA-2569]

[BASE design](https://share.goabstract.com/4bd9b65d-c997-4c2a-a656-fcf29694cb20?mode=design&sha=ff4cdea1e7d6422f35083b4c419155d0eb92ea5a)

### Description

Introduce `ProgressBar` component to `@toptal/picasso-lab` package.

### How to test

- Run storybook locally or visit temploy
- Under `Picasso Lab`, find `ProgressBar` component
- Check if component covers all requirements from ticket description
- Check if component is implemented according [BASE design](https://share.goabstract.com/4bd9b65d-c997-4c2a-a656-fcf29694cb20?mode=design&sha=ff4cdea1e7d6422f35083b4c419155d0eb92ea5a)

### Screenshots

<img width="371" alt="Screenshot 2021-05-06 at 01 20 25" src="https://user-images.githubusercontent.com/7594216/117221291-43c73700-ae09-11eb-92a5-d34c89f03f09.png">

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-05-05 23:22 UTC, besirovic commented
@toptal-bot run all

2021-05-06 02:19 UTC, besirovic commented
@toptal-bot run all

2021-05-06 09:14 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/story/Default.example.tsx
> +      <Container top='small'>
I think we are missing `0` value example here

2021-05-06 09:17 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/story/WithPercentage.example.tsx
> +    <Container top='small'>
I think we are missing `0` value example here

2021-05-06 09:19 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/story/AnimatingProgressChange.example.tsx
> +const AnimatingProgressChange = () => {
As far as I remember discussions, this component is not going to be used in dynamic contexts. Could you, please, point to the requirements of animations? If there is no such explicit requirement I would remove it for now.

2021-05-06 09:25 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      marginLeft: '0.5em'
On designs, this is what required for percentage indicator. Looks like font, font-weight and line-height are off when rendered. 
![image](https://user-images.githubusercontent.com/14070311/117274681-f7f6ab00-ae65-11eb-8983-d58e72c683dd.png)

2021-05-06 09:28 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/story/index.jsx
> +  .addExample('ProgressBar/story/Default.example.tsx', 'Default')
Please, use `// picasso-skip-visuals` comment. Weare using Happo now for testing. Consult `Accordion` component as an example of how components should be tested visually.

2021-05-06 09:33 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      height: '0.5em',
To safely use `em` we need to have a root of the component set with `rem` so all other parts of it refer to it. Otherwise, the context of the component will influence its look

2021-05-06 09:37 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/test.tsx
> +  it('renders empty progress bar when value <0', () => {
The above 2 cases are capturing the DOM structure. This case and the next one are others capturing the same. Do we need them?

2021-05-06 09:41 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/ProgressBar.tsx
> +    const classes = useStyles()
We usually do not use `style`. I guess here we could pass in percentage to be used in `styles.ts`

2021-05-06 09:42 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/ProgressBar.tsx
> +  /** Show percentage value */
Maybe `Whether to show percentage value`?

2021-05-06 09:47 UTC, OleksandrNechai requested changes
Thank you so much for contributing to Picasso! :bow: 
Please react to the feedback :point_up: and add Cypress test with Happo (inspire by Accordion component). 
There is a ticket on our board https://toptal-core.atlassian.net/browse/FX-1897 with @vedrani assigned to it. So contact him if you have troubles to move this forward.

2021-05-06 11:25 UTC, vedrani requested changes

2021-05-06 11:25 UTC, vedrani commented on packages/picasso-lab/src/ProgressBar/story/AnimatingProgressChange.example.tsx
> +const AnimatingProgressChange = () => {
There is a problem with label size, so it messes with animation. I like this behaviour https://material-ui.com/components/progress/#linear-with-label

We need to check with designers what is spacing for the label and should 100% have less spacing or should it move to the right.

https://user-images.githubusercontent.com/11500666/117290295-eaddba00-ae6d-11eb-86f1-e1c05060175b.mov

2021-05-06 11:25 UTC, vedrani commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      marginLeft: '0.5em'
Yes, I checked, fonts are too big.

2021-05-06 12:33 UTC, besirovic commented on packages/picasso-lab/src/ProgressBar/story/AnimatingProgressChange.example.tsx
> +const AnimatingProgressChange = () => {
`ProgressBar` component should be used in file upload component to display progress of file uploading.
When we change the percentage of uploaded part of file we should change value in progress bar as well.
I added this animation to ensure nice transition between two values(widths) of progress bar.

Please check the design to see how progress bar is used in file upload component
https://share.goabstract.com/2556a122-6443-4546-96db-3d40c37b2a0d?mode=design&sha=0aeb05e01da837c228249c74cc79ec21280f8b6d

2021-05-06 13:12 UTC, havenchyk commented
Thanks @besirovic My only concern is about font size for tooltips - it's 14px vs 12px in design, also @vedrani found a glitch with move from 90% to 100%. I didn't check code though 🙂

2021-05-06 14:59 UTC, besirovic commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      marginLeft: '0.5em'
I fixed style of label so now it should have all properties applied.

2021-05-06 15:01 UTC, besirovic commented on packages/picasso-lab/src/ProgressBar/story/AnimatingProgressChange.example.tsx
> +const AnimatingProgressChange = () => {
I addressed this issue to work in the same way as one you proposed from MUI.
Please let me know how do you like it.

2021-05-07 04:41 UTC, OleksandrNechai commented on cypress/component/ProgressBar.spec.tsx
> +          <ProgressBar value={50} showPercentage />
Full is 50%? :thinking:

2021-05-07 04:41 UTC, OleksandrNechai commented on cypress/component/ProgressBar.spec.tsx
> +          <ProgressBar value={50} showPercentage />
Full is 50%? :thinking:

2021-05-07 04:47 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      lineHeight: '18px'
I think it's better to do `rem('18px')` for consistency.

2021-05-07 04:47 UTC, OleksandrNechai commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      minWidth: '29px',
I think we should use `rem`.  Where `29` is coming from?

2021-05-07 04:51 UTC, OleksandrNechai requested changes
Almost there. I have noticed few small improvements. I guess you also forgot to update snapshots :-)

2021-05-07 11:40 UTC, vedrani commented
Animation work nice. I think we need to check with designers is it ok to change the width of the component based on progress value.

![image](https://user-images.githubusercontent.com/11500666/117444314-9c95ed00-af39-11eb-8f48-68ee31f6c8b6.png)

2021-05-07 11:45 UTC, vedrani commented
Will this component be used as inline?

2021-05-07 12:28 UTC, besirovic commented on cypress/component/ProgressBar.spec.tsx
> +          <ProgressBar value={50} showPercentage />
🤦

2021-05-07 12:37 UTC, besirovic commented on packages/picasso-lab/src/ProgressBar/styles.ts
> +      minWidth: '29px',
It's from design

https://share.goabstract.com/f971a601-5f77-4c32-8852-7fdddbd02bb7?mode=build&sha=ff4cdea1e7d6422f35083b4c419155d0eb92ea5a

<img width="1483" alt="Screenshot 2021-05-07 at 14 35 47" src="https://user-images.githubusercontent.com/7594216/117450551-a885ad00-af41-11eb-8ec5-55524ba6487d.png">

2021-05-07 13:00 UTC, besirovic commented
@vedrani Only use case of `ProgressBar` component for now should be inside `FileUpload` component. On design, progress bar is displayed inline with `Uploading...` text, so **yes**, it should be used inline.

https://share.goabstract.com/0241f38a-5b16-44aa-84f7-0138f0422785?collectionLayerId=eb858ce1-17b3-41e6-ac65-a056e1a9e713&mode=design

2021-05-07 14:12 UTC, OleksandrNechai commented
Is there a way to avoid twice `ProgressBar` in the name of the test? 
![image](https://user-images.githubusercontent.com/14070311/117462568-7717dc00-af57-11eb-8421-a91f36fcea54.png)

2021-05-10 09:52 UTC, vedrani reviewed
I want you to check this small detail with width, others look good.

2021-05-10 11:47 UTC, vedrani approved these changes

2021-05-10 12:13 UTC, merged