feat(FileList): [TEA-2545] Implement internal file list component
toptal/picasso pull request #2067
Opened 2021-05-12 00:18 UTC by besirovic

[TEA-2545]

[DESIGN](https://share.goabstract.com/2556a122-6443-4546-96db-3d40c37b2a0d?mode=build&sha=0aeb05e01da837c228249c74cc79ec21280f8b6d)

### Description

Implement internal `FileList` component needed for `FileInput` component. Component will be added to `FileInput` as part of  [TEA-2546](https://toptal-core.atlassian.net/browse/TEA-2546).

> NOTE
>
> `FileList` example inside `FileInput` section is added just for testing purpose and will be removed as part of  [TEA-2546](https://toptal-core.atlassian.net/browse/TEA-2546)

### How to test

- In storybook, open `FileInput` component and find `FileList` section on the bottom
- Check if list of files is implemented according design

### Screenshots

<img width="347" alt="Screenshot 2021-05-12 at 02 14 06" src="https://user-images.githubusercontent.com/7594216/117899600-bcc20500-b2c7-11eb-938f-315b21fea1ae.png">

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-05-12 00:19 UTC, besirovic commented on packages/picasso/src/FileInput/story/FileList.example.tsx
> +const Example = () => {
As mentioned in description of PR, this example is added just for testing purpose and will be removed as part of  [TEA-2546](https://toptal-core.atlassian.net/browse/TEA-2546).

2021-05-12 00:19 UTC, besirovic commented on packages/picasso/src/FileInput/story/index.jsx
> +  })
As mentioned in description of PR, this example is added just for testing purpose and will be removed as part of  [TEA-2546](https://toptal-core.atlassian.net/browse/TEA-2546).

2021-05-12 00:22 UTC, besirovic commented
@toptal-bot run all

2021-05-12 05:46 UTC, teimurjan requested changes

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/FileList.tsx
> +const FileListItem = ({ file, onRemove }: FileListItemProps) => {
We're trying to keep one component per file. It'd be awesome if you move it to a separate module with its own styles and tests.

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/FileList.tsx
> +  const renderUploading = (
It's not a function, so it shouldn't contain a verb in its name.

```suggestion
  const renderUploading = () => (
```

or 

```suggestion
  const uploadingNode = (
```

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/FileList.tsx
> +  const renderFile = (
Fix the naming here, too, please.

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/FileList.tsx
> +          <Button.Circular variant='flat' onClick={() => onRemove(name)}>
Let's extract the inline function.

```suggestion
          <Button.Circular variant='flat' onClick={handleRemove}>
```

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/test.tsx
> +    const { container } = render(<FileList files={[file]} />)
It'd be great if you create a render function with the default arguments like this:

https://github.com/toptal/picasso/blob/0d61c462669455c207854f380ebe8963688841a4/packages/picasso/src/Accordion/test.tsx#L22

We're following this pattern in the codebase.

2021-05-12 05:46 UTC, teimurjan commented on packages/picasso/src/FileList/test.tsx
> +  })
```suggestion
it('fires callback on remove', () => {
  const handleIItemRemove = jest.fn()

  const { getByRole } = render(
    <FileList files={[file]} onItemRemove={handleIItemRemove} />
  )

  fireEvent.click(getByRole('button'))

  expect(handleIItemRemove).toHaveBeenCalled()
})
```

2021-05-13 08:59 UTC, teimurjan approved these changes

2021-05-13 08:59 UTC, teimurjan commented on packages/picasso/src/FileListItem/FileListItem.tsx
> +    }
```suggestion
    onRemove?.(name)
```

2021-05-13 09:06 UTC, teimurjan commented
/rebase

2021-05-13 11:14 UTC, eduardoportilho approved these changes

2021-05-14 07:56 UTC, havenchyk commented
/rebase

2021-05-14 10:44 UTC, merged