feat(FileInput): implement multiple file input
toptal/picasso pull request #2077
Opened 2021-05-18 19:42 UTC by eduardoportilho

[TEA-2546]

### Description

Implement the new `FileInput` component with multiple file selection abilities.

[Designs on Abstract](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/0aeb05e01da837c228249c74cc79ec21280f8b6d/files/13531207-e094-44ec-ae1f-f27628c1aea5/layers/27C9F1FA-E469-4AA4-936C-DD752F77ADE3?mode=design)

### How to test

- In storybook, open `FileInput` component and test the different usage scenarios.
- In storybook, open `Picasso Forms` / `Form` component and test the usage inside a form controlled by final-form.

### Screenshots

![image](https://user-images.githubusercontent.com/895865/118713103-ef07c100-b7f7-11eb-881c-634368141a2f.png)

![image](https://user-images.githubusercontent.com/895865/118713123-f4fda200-b7f7-11eb-8927-0ff24b6e8d36.png)

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-05-18 19:45 UTC, eduardoportilho commented
@toptal-bot run all

2021-05-18 23:21 UTC, eduardoportilho commented
@toptal-bot run all

2021-05-19 06:29 UTC, teimurjan requested changes
Found some differences with the designs:

1. Hint's `line-height` is `16.5px`. Should be `16px`.
2. `FileListItem`'s `line-height` is `21px`. Should be `22px`.
3. `FileListItem`'s `padding` is `4px`. Should be `5px`.<br/><img width="322" alt="Screen Shot 2021-05-19 at 12 22 10" src="https://user-images.githubusercontent.com/17337276/118765412-d8677580-b89c-11eb-9931-f524d221e38c.png">
4. Trash icon's tooltip is `Remove file`. Should be `Remove File`.
5. Reset icon's tooltip is `Dismiss error`. Based on the point above it should be `Dismiss Error` (Ask the designers).
6. Invalid `line-height` for errored `FileListItem`. Filename has `21px`, when should be `22px`. Error has `18px`, when should be `16px`.<br/><img width="311" alt="Screen Shot 2021-05-19 at 12 27 13" src="https://user-images.githubusercontent.com/17337276/118765923-8d019700-b89d-11eb-9625-c0dc824d3dd7.png">

2021-05-19 06:29 UTC, teimurjan commented on packages/picasso/src/FileInput/story/Uploader.example.tsx
> +    const intervalID = setInterval(() => {
nit: in case the component is unmounted during the upload, your interval won't clear (you should have a global interval var and clear it in `useEffect`).

2021-05-19 06:56 UTC, ertrzyiks commented on packages/picasso/src/FileInput/story/Error.example.tsx
> +      onRemove={() => undefined}
Is this callback required here?

2021-05-19 06:56 UTC, ertrzyiks commented on packages/picasso/src/FileList/FileList.tsx
>  export interface Props extends BaseProps, HTMLAttributes<HTMLDivElement> {
It's possible to import this file from Picasso and use without the input, but it's not documented on the website.
```
import {FileList } from '@toptal/picasso'
```

I see this component as an internal one like `OutlinedInput` which is not exported. I suggest to remove
```
export { default as FileList } from './FileList'
export type { FileListProps } from './FileList'
```
it from the index.ts.

Otherwise this component should be documented on the website and this particular change is then incorrect, as you shouldn't expect `File` object passed to such a visual component.

2021-05-19 12:00 UTC, eduardoportilho commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    onChange: (event: ChangeEvent<HTMLElement> | any) => {
This function is mimicking the types of react-final-form's `FieldInputProps.onChange`, so I think any is the correct type here. Do you have any other suggestions?

```ts
interface FieldInputProps<FieldValue, T extends HTMLElement = HTMLElement>
  extends AnyObject {
  ...
  onChange: (event: React.ChangeEvent<T> | any) => void;
  ...
}
```

2021-05-19 13:15 UTC, eduardoportilho commented on packages/picasso/src/FileInput/story/Error.example.tsx
> +      onRemove={() => undefined}
The `FileListItem` component hides the remove button when the callback is not provided.

2021-05-19 13:30 UTC, eduardoportilho commented on packages/picasso/src/FileList/FileList.tsx
>  export interface Props extends BaseProps, HTMLAttributes<HTMLDivElement> {
`FileList` is not exported on `packages/picasso/src/index.ts`, so it shouldn't be possible to import it from `@toptal/picasso`, right? Am I missing something?

2021-05-19 14:35 UTC, eduardoportilho commented
@teimurjan Thanks for the review 👍

> Reset icon's tooltip is Dismiss error. Based on the point above it should be Dismiss Error (Ask the designers).

Milos Milikic suggested "Dismiss" for the tooltip.

2021-05-19 15:22 UTC, havenchyk requested changes

2021-05-19 15:22 UTC, havenchyk commented on packages/picasso/src/FileInput/story/Uploading.example.tsx
> +        <Typography variant='heading' size='medium'>
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1291032/118837844-dc5fbb80-b8cd-11eb-9dd9-5a3bc3d37b36.png">
I do not see such example in the designs, did you get any confirmation for such use case from designers/ stakeholder?

2021-05-19 15:22 UTC, havenchyk commented on packages/picasso/src/FileInput/story/Disabled.example.tsx
> +        <Typography variant='heading' size='medium'>
I think first example is enough

2021-05-19 15:22 UTC, havenchyk commented on packages/picasso/src/FileInput/story/Default.example.tsx
> +    <Container bottom='medium'>
I would split this example into 3 different.
We use screenshots comparing and it's almost the same as a unit test - you expect to catch the exact problem when you have any, but if you have 3 assertions in the same test, you'll need to understand what's the reason

2021-05-19 15:22 UTC, havenchyk commented on packages/picasso/src/FileInput/FileInput.tsx
> +      singleFile,
what do you think if we use anothe property like `multiple` or `allowMany` instead of singleFile?

2021-05-19 15:22 UTC, havenchyk commented
Great first iteration @eduardoportilho please address the feedback from Teimur and answer my questions and we'll continue

2021-05-19 17:49 UTC, eduardoportilho commented on packages/picasso/src/FileInput/story/Uploading.example.tsx
> +        <Typography variant='heading' size='medium'>
I believe that we have API endpoints that don't inform the upload progress and I've confirmed with Milos Milikic that we can use the spinner in this case.

2021-05-19 17:52 UTC, eduardoportilho commented on packages/picasso/src/FileInput/story/Disabled.example.tsx
> +        <Typography variant='heading' size='medium'>
The second example shows the file items with hidden delete buttons so I'll keep it and remove the first one.

2021-05-19 17:54 UTC, eduardoportilho commented on packages/picasso/src/FileInput/FileInput.tsx
> +      singleFile,
It seems to me that this component was designed to support multiple attachments by default and forcing it to accept only one is the exception. Do you agree?

2021-05-19 18:28 UTC, eduardoportilho commented on packages/picasso/src/FileInput/FileInput.tsx
> +      singleFile,
Milos pointed out that the component should have an property to set the maximum number of files that can replace this one.

2021-05-19 21:39 UTC, eduardoportilho commented
@toptal-bot run all

2021-05-20 01:17 UTC, eduardoportilho commented
@toptal-bot run all

2021-05-20 06:46 UTC, teimurjan approved these changes
Looks 👍

2021-05-20 06:46 UTC, teimurjan commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    onChange: (event: ChangeEvent<HTMLElement> | any) => {
Hmm, didn't know about that. I'd keep `any` then.

2021-05-20 07:34 UTC, ertrzyiks commented
Since it's a breaking change it would be nice to document the migration path, instruct people what to do in order to correct switch to the new API.

2021-05-20 08:33 UTC, havenchyk commented on packages/picasso/src/FileInput/story/Uploading.example.tsx
> +        <Typography variant='heading' size='medium'>
Nice, thanks

2021-05-20 08:34 UTC, havenchyk commented on packages/picasso/src/FileInput/FileInput.tsx
> +      singleFile,
Yes, it is even better

2021-05-20 11:13 UTC, eduardoportilho commented
@toptal-bot run all

2021-05-20 14:47 UTC, havenchyk commented on packages/picasso-forms/src/Form/story/Default.example.tsx
> +        singleFile
I thought you were going to change it to maxFiles?

2021-05-20 15:35 UTC, eduardoportilho commented on packages/picasso-forms/src/Form/story/Default.example.tsx
> +        singleFile
I did, this one slipped 🙈 Good catch!

2021-05-21 07:07 UTC, havenchyk commented on packages/picasso-forms/src/Form/story/Default.example.tsx
> +        maxFiles={1}
shouldn't 1 be by default?

2021-05-21 14:59 UTC, havenchyk approved these changes
LGTM

2021-05-21 16:31 UTC, merged