fix(Slider): overlapping labels on range slider
toptal/picasso pull request #2092
Opened 2021-06-02 13:07 UTC by krasai

[SPC-1098]

### Description

The labels for range sliders are overlapping themself when they are close to each other. We need to change tooltip placement when labels intersect. 

### How to test

- Go to the `Slider` story: `/?path=/story/components-slider--slider`
- Test Range Slider. 

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
|![Kapture 2021-06-02 at 15 05 09](https://user-images.githubusercontent.com/11710994/120485047-fa401c80-c3b3-11eb-9a7f-5e208e108a16.gif)|![Kapture 2021-06-02 at 14 59 41](https://user-images.githubusercontent.com/11710994/120484316-3d4dc000-c3b3-11eb-892b-2888ccbf3d08.gif)|

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-06-02 17:54 UTC, hmschreiner commented on packages/picasso/src/Slider/Slider.tsx
> +  // eslint-disable-next-line max-params
NIT: change `DefaultTooltip` to receive an object as a param so you can get rid of the `eslint-disable-next-line max-params` comment:

```javascript
  const DefaultTooltip = ({
    isTooltipAlwaysVisible: boolean,
    disablePortal?: boolean,
    compact?: boolean,
    isTooltipReversed?: boolean
  }): FC<ValueLabelComponentProps> => ({
  ...
```

2021-06-02 18:29 UTC, elviocb commented on packages/picasso/src/Slider/Slider.tsx
> +  // eslint-disable-next-line max-params
if the interface changes this will become a breaking change, not sure if it's worth only to get rid of eslint comment

2021-06-04 16:02 UTC, s0ber commented
The placement works as expected, but the tooltips are blinking when being dragged. It looks like a glitch.

2021-06-07 09:21 UTC, krasai commented
@s0ber this problem existed before. We pass the props to the tooltip via callback, and the tooltip component is re-rendered on every change. Anyway, I wrapped it inside useMemo, and the issue is less visible now.

2021-06-07 10:08 UTC, OleksandrNechai requested changes
@krasai I see the following problems with this solution:
* the problem is not solved, we still have overlaps but on the boundaries: 
![Peek 2021-06-07 12-56](https://user-images.githubusercontent.com/14070311/120997393-d43dc200-c78f-11eb-9a90-1645e871961f.gif)
* this switching of both tooltips doesn't look nice to me
![Peek 2021-06-07 12-58](https://user-images.githubusercontent.com/14070311/120997887-3eeefd80-c790-11eb-9521-b381ce419d47.gif)
WDYT about the following next steps?
* Go consult with designers on how tooltips should behave. With the current design, overlapping seems unavoidable. Hence I don't see why we should complicate code to avoid it.
* Discuss what to do next having the designer's input. If they are fine with the current implementation, I would always render tooltips by default like this: 
![image](https://user-images.githubusercontent.com/14070311/120998789-14517480-c791-11eb-8022-726335b6b9a8.png)
and only switch when tooltip begins to overlap with component boundary on the left or the right. This will probably generate less switching and simpler implementation.

2021-06-18 11:37 UTC, krasai commented
@OleksandrNechai 
After the discussion on the # -base-core channel, I implemented it according to the provided projects: https://toptal-core.atlassian.net/browse/CSPR-293
I think sometimes overlapping is unavoidable. If there is no space on the right side we should display it a bit closer to the left side.

2021-06-24 07:16 UTC, OleksandrNechai commented
@krasai hey! I have some feedback from Milos Milikic

> I found a couple of things that are not the same as in the designs:
> * know size should be 11px (currently it’s 9px)
> * Filled line should be blue (currently it’s gray on some examples)

Do you think it is related to the current PR?

2021-06-24 19:29 UTC, OleksandrNechai reviewed
First of all, thank you @krasai for the contribution to Picasso! We really appreciate it! :bow: 

And sorry about a very late review, we are a bit understaffed now and vacation season so :man_shrugging: 

Now, I will be clear, I find the solution hacky. I do realize that there might be no elegant way to do things. Maybe we will need to negotiate with designers again if there is no way we can improve it. So can we somehow not rely on selecting DOM elements using `mui` markup. If they change it, our component breaks. Can we maybe use an intersection observer?  See other questions above.

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +      const tooltips: NodeListOf<HTMLElement> = sliderRef.current.querySelectorAll(
I am concerned with this approach of getting references for tooltips. What happens if MUI changes roles?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +  const watchTooltipsPlacement = () => {
From the code of the function, I find its name confusing. It just does a bunch of calculations, what does it watch? BTW can we use Intersection Observer API instead? Like switch placement, if tooltips intersect?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +  const placement = () => {
Looks like it could be just a variable not a function. Or maybe this function can be taken out of the component so we avoid creating it each render?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +  const [isTooltipReversed, setIsTooltipReversed] = useState(false)
Maybe `flipped`? :)

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +        })) as typeof UserDefinedTooltip,
Can we avoid `as typeof UserDefinedTooltip` and instead tune `DefaultTooltip` typing?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +      if (sliders.length === 2 && tooltips.length === 2) {
How about reusing `isRange`?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +          Array.from(tooltips).reduce((acc, cur) => {
Why reduce? :) Maybe we could do just map(...).sum()?
Where this min distance algo comes from?

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +    if (isRange && disablePortal) {
why is this only working with disabled portals? I find its weird to have people remember to pass this prop so their tooltips do not overlap

2021-06-24 19:29 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +          (ValueLabelComponent as unknown) as React.ElementType<ValueLabelProps>
Eh? :)

2021-06-24 19:31 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +      const tooltips: NodeListOf<HTMLElement> = sliderRef.current.querySelectorAll(
This could be a performance hit to run dom select on each change? :thinking:

2021-06-29 08:49 UTC, OleksandrNechai commented on packages/picasso/src/Slider/Slider.tsx
> +          Array.from(tooltips).reduce((acc, cur) => {
or tooltips[0].offsetWidth + tooltips[1].offsetWidth :-D

2021-06-30 08:18 UTC, teimurjan commented
I created an alternative solution by using refs instead of `document.querySelector`. It's not clean because I wanted to show the approach: https://github.com/toptal/picasso/compare/SPC-1098-overlapping-labels-on-range-filters-2

2021-07-08 13:31 UTC, krasai commented
Closing it, the work is continued on https://github.com/toptal/picasso/pull/2108

2021-07-08 13:31 UTC, closed without merging