feat: [FX-1956] Add picasso-provider package
toptal/picasso pull request #2104
Opened 2021-06-22 15:05 UTC by denieler

[FX-1956]

### Description

Detachment of the global Picasso provider and context to the separate `@toptal/picasso-provider` package.

Because this functionality almost never changes in Picasso lifetime it looks like it makes sense to detach this as a separate package, which would simplify the version management of Picasso in monorepos and micro-frontends architectures (each MFE can have its own version of Picasso components, while all will be using the same version of picasso-provider).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-06-22 15:10 UTC, denieler commented
@toptal-bot run package:alpha-release

2021-06-22 15:13 UTC, denieler commented
@toptal-bot run package:alpha-release

2021-06-22 16:48 UTC, denieler commented
@toptal-bot run package:alpha-release

2021-06-23 07:05 UTC, denieler commented
@toptal-bot run package:alpha-release

2021-06-23 08:09 UTC, denieler commented on .eslintrc
> +      }
there shouldn't be any references from provider to shared. Because we use provider in shared.

2021-06-23 08:09 UTC, denieler commented on packages/picasso-provider/bin/build.js
> +function copyIcons () {
linter/prettier

2021-06-23 08:11 UTC, denieler commented on packages/picasso/src/index.ts
> +export default PicassoFallback
I've added this fallback component to raise an error when Picasso is used in the old way (from `@toptal/picasso` package). Because by default vscode don't raise any errors, because default imported Picasso looks like can be used in a way `Picasso.Edit24` for icons.

2021-06-23 10:03 UTC, teimurjan approved these changes

2021-06-23 10:03 UTC, teimurjan commented on packages/picasso/src/index.ts
> +const PicassoFallback = () => {
👍

2021-06-23 12:12 UTC, denieler commented
/rebase

2021-06-24 09:49 UTC, vedrani requested changes
I have doubts that this will solve problem of multiple Picasso versions due to MUI provider and context. 

I would like to see how can we ensure we at least use same version of notistack and more importantly MUI.

2021-06-24 09:49 UTC, vedrani commented on packages/picasso/package.json
> +    "@toptal/picasso-provider": "^0.0.1",
Should picasso-provider drive notistack version? 
We could get in lot of problems if those 2 diverge because we will lose notification functionality.

2021-06-24 09:49 UTC, vedrani commented on packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
> +import { useDrawer, usePageTopBar } from '../RootContext'
Seems we cannot move this to Page as I suggested, because it's used on higher level.

Side question, do we ensure drawer and pageTopBar flags are reseted if we route to Page that doesn't have Drawer or Topbar?

2021-06-24 09:49 UTC, vedrani commented on packages/picasso-provider/src/Picasso/Picasso.tsx
>    MuiThemeProvider,
I think this will create problems for us, because it's same problem but on MUI level, with MUI provider `MuiThemeProvider` and `StylesProvider`. Different versions of MUI in Picasso-provider and Picasso will create problem of MUI accessing `theme` from React context.

Basically we can have Picasso-provider but afaik it doesn't solve problem of having multiple versions of Picasso in MFE.

2021-06-24 10:21 UTC, denieler commented on packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
> +import { useDrawer, usePageTopBar } from '../RootContext'
> Side question, do we ensure drawer and pageTopBar flags are reseted if we route to Page that doesn't have Drawer or Topbar?

I haven't checked, but I'm pretty sure they are refreshed. At least we never had such complains before

2021-06-25 07:12 UTC, denieler commented
/rebase

2021-06-25 07:27 UTC, denieler commented on packages/picasso/package.json
> +    "@toptal/picasso-provider": "^0.0.1",
done 👍

2021-06-25 07:27 UTC, denieler commented on packages/picasso-provider/src/Picasso/Picasso.tsx
>    MuiThemeProvider,
moved dependencies from `@topta/picasso` package to `@toptal/picasso-provider`

2021-06-25 07:36 UTC, denieler commented
@toptal-bot run package:alpha-release

2021-06-25 07:58 UTC, denieler commented
**Title:**

feat: [FX-1956] Add picasso-provider package

BREAKING CHANGE: We moved the root Picasso component to the separate package - `@toptal/picasso-provider`. This should help us in managing multiple different versions of Picasso package (`@toptal/picasso`) for sub-applications, while the main host application would be able to share Picasso Context via the locked version of `@toptal/picasso-provider` package.

To migrate to the new version you need to change

```
import Picasso from '@toptal/picasso'
```

to

```
import Picasso from '@toptal/picasso-provider'
```

2021-06-25 09:10 UTC, vedrani approved these changes

2021-06-25 09:10 UTC, vedrani commented on packages/picasso-provider/package.json
> +  "dependencies": {
Sorry, should we put `^`?

2021-06-25 09:29 UTC, denieler commented on packages/picasso-provider/package.json
> +  "dependencies": {
I would keep fixed versions to avoid possible bugs, we had pretty critical recently with `notistack` bumping patch version 😞

2021-06-25 09:30 UTC, merged