feat: add hasDarkerVerticalSeparator prop for OverviewBlock
toptal/picasso pull request #2121
Opened 2021-07-23 03:32 UTC by pudek357

[SPT-1788](https://toptal-core.atlassian.net/browse/SPT-1788)

### Description
...

### How to test
...

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-07-23 03:33 UTC, pudek357 commented
@toptal-bot run package:alpha-release

2021-07-23 08:22 UTC, pudek357 commented
@toptal-bot run package:alpha-release

2021-07-26 06:19 UTC, pudek357 commented
@toptal-anvil ping reviewers

2021-07-26 06:29 UTC, teimurjan requested changes

2021-07-26 06:29 UTC, teimurjan commented on packages/picasso-lab/src/OverviewBlock/OverviewBlock.tsx
> +    hasDarkerVerticalSeparator?: boolean
This name looks long and unclear to me. What do you think about making such a prop?

```suggestion
    separatorVariant?: 'default' | 'dark'
```

2021-07-26 06:29 UTC, teimurjan commented on packages/picasso-lab/src/OverviewBlock/story/DarkerVerticalSeparator.example.tsx
> +      <OverviewBlock hasDarkerVerticalSeparator value='4249' label='ACH' />
I think this prop should be passed to `OverviewBlock.Group` and provided via context just like `blockWidth` (https://github.com/toptal/picasso/blob/056761c706d5945916499c85242244570b8cd551/packages/picasso-lab/src/OverviewBlockGroup/OverviewBlockGroup.tsx#L38)

2021-07-26 07:06 UTC, denieler commented
Has this change being discussed with the `#base-core` channel/designers?

2021-07-26 07:13 UTC, pudek357 commented
@denieler in **Description**, you have a link to the thread in Slack.

2021-07-26 07:13 UTC, teimurjan commented
> Has this change being discussed with the `#base-core` channel/designers?

https://toptal-core.slack.com/archives/CM8KE183V/p1626279193238100?thread_ts=1626277935.236400&cid=CM8KE183V

2021-07-26 07:18 UTC, denieler commented
thank you @pudek357 @teimurjan 🙇 I've read that slack thread, but not that far.

@pudek357 did designers change the design in Abstract in BASE project?

2021-07-26 07:20 UTC, denieler commented
https://share.goabstract.com/39332544-280f-4103-8908-b04220d5932b?mode=design&sha=b17f1de5aad308ae26d90e16bc0d7073d4330b68

It looks like it's not. Please ask `#base-core` to update the design 🙇‍♂️

2021-07-26 07:21 UTC, denieler commented on packages/picasso-lab/src/OverviewBlock/OverviewBlock.tsx
> +    hasDarkerVerticalSeparator?: boolean
do we really need 2 types of the separator? It looks like they just asked to change the color. Am I missing something?

2021-07-27 10:29 UTC, pudek357 commented on packages/picasso-lab/src/OverviewBlock/OverviewBlock.tsx
> +    hasDarkerVerticalSeparator?: boolean
We don't need, via: [Slack](https://toptal-core.slack.com/archives/CCC3GP6CC/p1627379282026500?thread_ts=1627284635.023100&cid=CCC3GP6CC).

2021-07-27 10:30 UTC, pudek357 commented
@denieler abstract has been updated [here](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/550eaf1f40f66ec5bcc307ea06962f0eb0f7fbd3/files/4ba86227-d49e-435b-92d3-1b41a4b9531a/layers/3B863FAB-C94C-4EE2-8061-FBFAB45778AE?mode=design&sha=550eaf1f40f66ec5bcc307ea06962f0eb0f7fbd3).

2021-07-27 10:34 UTC, denieler approved these changes

2021-07-27 11:41 UTC, teimurjan approved these changes

2021-07-27 11:43 UTC, merged