DO NOT REVIEW. [FX-2016] Horizontal layout for TreeView
toptal/picasso pull request #2122
Opened 2021-07-27 08:45 UTC by danganiev-tt

[FX-2016]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-07-27 11:21 UTC, dmaklygin1 commented on packages/picasso/src/TreeView/TreeView.tsx
> +  isHorizontal?: boolean
I would add a `direction` prop, instead of `isHorizontal` with two possible options: vertical, horizontal

2021-07-27 11:22 UTC, dmaklygin1 commented
@toptal-bot run all

2021-07-27 14:45 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  isHorizontal?: boolean
Agreed, this would allow for better expandability later, if for example somebody would need something like inverse vertical layout (bottom to top)

2021-08-06 09:45 UTC, TomasSlama commented on packages/picasso/src/TreeView/PointLink/PointLink.tsx
> +      (direction === 'horizontal'
U changed `isHorizontal` to `direction`, but many times you are using it still as isHorizontal.

This will of course work, but I personally like it prepared for an extension.

For example:
```js
const rectHeightByDirection = {
  horizontal: source.rect?.height / 2,
  vertical: source.rect?.height 
}
const source Y = source.y + (rectHeightByDirection[direction] || 0)
```

What do you think about it?

2021-08-06 09:50 UTC, danganiev-tt commented on packages/picasso/src/TreeView/PointLink/PointLink.tsx
> +      (direction === 'horizontal'
Sure, this is a better way. There might be similar code improvements with `variant` too.

2021-08-06 09:52 UTC, danganiev-tt commented
![image](https://user-images.githubusercontent.com/87463933/128492673-d5330f30-cf1a-4ec7-9655-6a06e72ba29c.png)

Found a bug, do not merge yet

2021-08-10 12:41 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/story/Horizontal.example.tsx
> +      direction='horizontal'
What makes us to name prop "horizontal direction", but example to name "horizontal layout"?

2021-08-10 12:56 UTC, OleksandrNechai approved these changes
Could not understand most of the code. 
But I have now a strong feeling that this component should go to TopTeam repo if it is not used in other projects and is not part of the base library. WDYT @havenchyk

2021-08-10 13:05 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/story/Compacted.example.tsx
> +import React from 'react'
To me, the name of the example `Compact` sounds better :-)

2021-08-10 13:22 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/TreeView.tsx
> +  horizontalMargin?: number
Its too many properties to my taste. Maybe we should collect some of them into config object?

2021-08-10 13:23 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/TreeView.tsx
> +    horizontalMargin,
No default values for these?

2021-08-10 13:24 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/story/Compacted.example.tsx
> +import React from 'react'
How compact differs from non-compact? To me, it looks like it's a matter of zooming to make the tree compact.

2021-08-10 13:32 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/useTree.ts
> +const calculateNodeXorYPosition = (isX: boolean) => {
This function calculates nothing, just returns another function. What it exists for? It is called calculate? Is not `boolean` param a well-known antipattern?

2021-08-10 13:33 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/useTree.ts
> +    }
It would be easier to read if types were extracted

2021-08-10 13:36 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/useTree.ts
> +    if (!node.children || !node.children.length) {
I wonder, is not linter failing for this code? It is too large and too complicated. I think it should be refactored so someone could understand it. I have not seen 4 nested `if`s for quite some time already :sweat_smile:

2021-08-10 13:42 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/utils/getDefaultMargins.ts
> +}
Is everything that this code does is `return [verticalMargin || defaultVMargin, horizontalMargin || defaultHMargin]`?

2021-08-10 13:43 UTC, OleksandrNechai commented on packages/picasso/src/TreeView/utils/getDefaultMargins.ts
> +export const getDefaultMargins = (
This function does not do what it says it does.

2021-08-10 13:46 UTC, OleksandrNechai requested changes
After the second read, I realized the quality of the code is not right. It's too complex, very hard to read, badly structured and many functions are telling lies, meaning they don't do what they say they do.

2021-08-10 14:03 UTC, havenchyk approved these changes
Topteam is the only user of TreeView, so I'm fine with this change

2021-08-19 13:18 UTC, danganiev-tt commented on packages/picasso/src/TreeView/story/Horizontal.example.tsx
> +      direction='horizontal'
Yes, I should choose one or the other and make the code and definitions more uniform

2021-08-19 14:06 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  horizontalMargin?: number
Limiting to variant is not what I had in mind, since I have a use case where default margin had to be overridden, so I tried to implement the solution in a very universal way, where you could override any margin for any tree variant.

I agree about the collecting properties into a config option though. I should only collect my new options not to break current component interface

2021-08-19 14:10 UTC, danganiev-tt commented on packages/picasso/src/TreeView/useTree.ts
> +const calculateNodeXorYPosition = (isX: boolean) => {
It was not a well-known antipattern _to me_, but after some googling it is, and I'm starting to catch up :)

2021-08-19 14:11 UTC, danganiev-tt commented on packages/picasso/src/TreeView/useTree.ts
> +    if (!node.children || !node.children.length) {
I completely agree, it's probably almost incomprehensible in its complexity, I'll try to refactor and simplify it as much as I can

2021-08-19 14:13 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +    horizontalMargin,
I'll check if this, and the issues within the `packages/picasso/src/TreeView/utils/getDefaultMargins.ts` file can be somehow solved in combination

2021-08-19 14:15 UTC, danganiev-tt commented on packages/picasso/src/TreeView/utils/getDefaultMargins.ts
> +export const getDefaultMargins = (
I'll either rename the function or rethink it's code to match the name then

2021-08-19 14:17 UTC, danganiev-tt commented on packages/picasso/src/TreeView/PointLink/PointLink.tsx
> +      horizontal: source.rect?.height / 2,
No, but I will

2021-08-19 14:20 UTC, danganiev-tt commented on packages/picasso/src/TreeView/utils/getDefaultMargins.ts
> +}
I guess 😅

2021-08-19 14:39 UTC, danganiev-tt commented on packages/picasso/src/TreeView/story/Compacted.example.tsx
> +import React from 'react'
Compact is the TreeView that is rendered in a specific way. It **only** works for trees in which only one node per depth has children, which also happens to be the only use case we have in Top Team 🙃 Here is the description I made in the `-frontend-exp-core` slack channel:

> Basically we have a tree in which only one node on each level of depth can have children. Current TreeView creates big space gaps around tree nodes which have children, to account for overall width/height (depending on layout) of the whole tree. This makes sense as it prevents nodes overlapping each other (maybe the picture at the bottom will help in understanding this better)
> But in our case we know for sure that overlapping won’t happen, and we do not want these gaps to exist. So I want to add an optional prop like allowOverlap?:boolean to the TreeView that will prevent addition of space gaps like the ones I described. 

Then @havenchyk suggested the `variant: compact` prop & name instead of `allowOverlap`, and I couldn't think of anything better, so I just went with it.

![image](https://user-images.githubusercontent.com/87463933/130088300-10286959-8aa4-424c-8149-323a60ec30f3.png)

2021-09-01 07:49 UTC, dmaklygin1 commented
> Topteam is the only user of TreeView, so I'm fine with this change

Nope, Staff portal also uses TreeView: https://github.com/toptal/staff-portal/blob/ebb05a0f5de92a0f69e6050edc3308b969bec85e/src/modules/summary-sidebar/components/StaffTreeModal/StaffTreeModal.tsx

2021-09-01 09:05 UTC, dmaklygin1 commented
I was playing locally, and just assigned horizontal direction to the `With selected node` example:

```
directionOptions={{
  verticalMargin: 20,
  direction: 'horizontal'
}}
```


<img width="1536" alt="Picasso | TreeView 🔊 2021-09-01 12-04-01" src="https://user-images.githubusercontent.com/76203853/131643906-03e78d64-e5b2-4096-bced-653a062f351b.png">

2021-09-01 09:24 UTC, dmaklygin1 commented on packages/picasso/src/TreeView/TreeView.tsx
> +  } = directionOptions || {}
wdyt about adding default values to the `defaultProps `?

2021-09-01 10:17 UTC, dmaklygin1 commented
> I was playing locally, and just assigned horizontal direction to the `With selected node` example:
> 
> ```
> directionOptions={{
>   verticalMargin: 20,
>   direction: 'horizontal'
> }}
> ```
> 
> <img alt="Picasso | TreeView 🔊 2021-09-01 12-04-01" width="1536" src="https://user-images.githubusercontent.com/76203853/131643906-03e78d64-e5b2-4096-bced-653a062f351b.png">

isn't it because defaultHeight wasn't specified? if yes, then this is okay

2021-09-01 10:32 UTC, dmaklygin1 approved these changes

2021-09-01 11:48 UTC, danganiev-tt commented
@dmaklygin1 the default height should not be a problem, this looks like a bug. Although maybe adding default values to the `defaultProps` like you suggested might solve this. Anyway, I'll take a look

2021-09-02 07:43 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  } = directionOptions || {}
I'm against it because this causes a lot of issues with Typescript due to `directionOptions` being a possible undefined type. Also, `defaultProps` will be eventually deprecated for functional components according to Dan Abramov https://twitter.com/dan_abramov/status/1133878326358171650?lang=en, so it's better to use object default values (but this also causes same Typescript issues here)

2021-09-02 11:14 UTC, danganiev-tt commented
@toptal-bot run all

2021-09-02 11:29 UTC, danganiev-tt commented
@toptal-bot run happo

2021-09-02 11:45 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-03 11:25 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-03 11:29 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-03 12:28 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-06 13:33 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-07 07:21 UTC, danganiev-tt commented
@toptal-bot run package:alpha-release

2021-09-07 10:15 UTC, havenchyk commented on packages/picasso/src/TreeView/useTree.ts
> +const getPositionNoLeavesButChildren = (
this is still overcomplicated, but I don't see any better solution

2021-09-07 10:15 UTC, havenchyk commented on packages/picasso/src/TreeView/useTree.ts
> +      calculateNodePosition({ ...options, node: child })
inside calculateNodePosition are again check on `node.children`, can it be simplified?

2021-09-07 10:15 UTC, havenchyk commented on packages/picasso/src/TreeView/useTree.ts
> +  node.children.reduce((acc, child) => {
I do not understand why do you use `reduce` here if you don't change `acc` at all. Can it be `forEach`?

2021-09-07 10:15 UTC, havenchyk commented on packages/picasso/src/TreeView/useTree.ts
> +      (node.children[halfLength][coordinateType] +
nit: combination of middle, right, left words for variable name could help to understand this code better

2021-09-07 10:15 UTC, havenchyk commented on packages/picasso/src/TreeView/TreeView.tsx
> -TreeView.defaultProps = {
as I mentioned, we use defaultProps for storybook rendering. can you verify that with removing you didn't miss some important information on Props table?

2021-09-07 10:23 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  } = directionOptions || {}
if there is a specific reason of using defaultProps then I'll backtrack the changes. Still the values of directionOptions need to be overridden inside the component even if I'll declare them in default props

2021-09-07 10:28 UTC, danganiev-tt commented on packages/picasso/src/TreeView/useTree.ts
> +  node.children.reduce((acc, child) => {
Probably just because I used reduce in `getPositionLeavesAndChildren`

2021-09-07 10:34 UTC, danganiev-tt commented on packages/picasso/src/TreeView/useTree.ts
> +      (node.children[halfLength][coordinateType] +
If you're talking about the `position` variable, then `rightPosition` and `leftPosition` would be wrong here in case of regular vertical tree (it should be `topPosition` and `bottomPosition` then).

2021-09-07 10:38 UTC, danganiev-tt commented on packages/picasso/src/TreeView/story/Compact.example.tsx
> +const NodeContainer = styled<typeof Container>(Container)<{
I just copied all examples from` Default.example.tsx` 🤷🏻‍♂️. If we want to change this, it needs to be done in all of the examples I suppose

2021-09-07 10:42 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  } = directionOptions || {}
Also I'll move the default props from function component to `defaultProps` to avoid duplication

2021-09-07 11:53 UTC, danganiev-tt commented on packages/picasso/src/TreeView/TreeView.tsx
> +  } = directionOptions || {}
Actually I had to duplicate `defaultProps` as object default values instead

2021-09-07 13:06 UTC, OleksandrNechai approved these changes

2021-09-07 13:13 UTC, TomasSlama commented
/rebase

2021-09-07 14:16 UTC, danganiev-tt commented on packages/picasso/src/TreeView/useTree.ts
> +      calculateNodePosition({ ...options, node: child })
This is done to not recalculate the whole tree for the child with children again, since it's done before.

2021-09-07 14:50 UTC, TomasSlama approved these changes

2021-09-08 06:31 UTC, havenchyk commented on packages/picasso/src/TreeView/story/Compact.example.tsx
> +const NodeContainer = styled<typeof Container>(Container)<{
got it, keep it like this in this case

2021-09-08 06:40 UTC, havenchyk approved these changes
LGTM, thanks for your work!

2021-09-08 08:18 UTC, merged