Fx 1388 new component notes
toptal/picasso pull request #2128
Opened 2021-08-09 07:49 UTC by TomasSlama

[FX-NNNN]

### Description

Create a new compound component for Notes

- [FX-1388](https://toptal-core.atlassian.net/browse/FX-1388)

### How to test

- check [storybook](http://localhost:9001/?path=/story/components-notes--notes#default)

### Screenshots

![image](https://user-images.githubusercontent.com/6830426/128674326-e862bf7f-c05d-486e-a900-f87fa9269f43.png)

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-08-09 07:59 UTC, TomasSlama commented
According to [picasso tutorial](https://picasso.toptal.net/?path=/story/tutorials-how-to-use-spacings--how-to-use-spacings) we should use `Container` component for spacings and recommended way is using the key from enum. Values in enums are [8, 16, 24, 32, ...], but the design is using 4px, 28px, so I ended up using custom CSS with rem.

I don't like this approach much, I think the design and Picasso base components should use the same spacings so it's consistent across all components. What do you think guys?

2021-08-09 08:18 UTC, TomasSlama commented
@toptal-bot run all

2021-08-09 08:26 UTC, teimurjan requested changes

2021-08-09 08:26 UTC, teimurjan commented on cypress/component/Notes.spec.tsx
> +const NotesTest = () => (
We used to add `Example` postfix for Cypress component tests.

```suggestion
const NotesExample = () => (
```

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/Notes.tsx
> +    <Container
Do you really need 3 containers? I think this nesting can be simplified.

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/Notes.tsx
> +export const Notes = forwardRef<HTMLDivElement, Props>(function Notes (
In the story's Acceptance Criteria I see this component should be called `Note`.

```suggestion
export const Note = forwardRef<HTMLDivElement, Props>(function Note (
```

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/test.tsx
> +})
Was extraction of `api` to the upper scope intentional?

```suggestion
describe('Notes', () => {
  it('default render', () => {
    const { container } = renderNotes()

    expect(container).toMatchSnapshot()
  })
})
```

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/NotesSubtitle/styles.ts
> +import { PicassoProvider } from '@toptal/picasso-provider'
Why do you need empty styles?

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/styles.ts
> +// import { PicassoProvider } from '@toptal/picasso-provider'
```suggestion
```

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/styles.ts
> +// PicassoProvider.override(({ palette }: Theme) => ({}))
```suggestion
```

2021-08-09 08:26 UTC, teimurjan commented on packages/picasso/src/Notes/styles.ts
> +        content: '""',
I think it should work

```suggestion
        content: '',
```

2021-08-09 08:38 UTC, teimurjan commented
@toptal-bot run danger

2021-08-09 09:54 UTC, TomasSlama commented on packages/picasso/src/Notes/Notes.tsx
> +    <Container
you are right

2021-08-09 09:58 UTC, TomasSlama commented on packages/picasso/src/Notes/styles.ts
> +        content: '""',
I was surprised too, but sadly it doesn't work with only `''` 

https://stackoverflow.com/questions/40965977/cant-target-before-pseudo-selector-in-jss

2021-08-09 11:03 UTC, OleksandrNechai commented on packages/picasso/src/NoteContent/test.tsx
> +    expect(container).toMatchSnapshot()
Guys, can we have a single snapshot of all parts of the compound component on the compound component level and skip doing snapshots here?

2021-08-09 12:03 UTC, teimurjan commented on packages/picasso/src/Note/story/index.jsx
> +page.createChapter().addExample('Note/story/Default.example.tsx', 'Default')
You have added a Happo visual test, so you can ignore the legacy visual tests

```suggestion
page.createChapter().addExample('Note/story/Default.example.tsx', 'Default') // picasso-skip-visuals
```

2021-08-09 12:26 UTC, TomasSlama commented on packages/picasso/src/NoteContent/test.tsx
> +    expect(container).toMatchSnapshot()
I agree, I removed these tests.

2021-08-10 07:06 UTC, OleksandrNechai commented
@TomasSlama every new component should first live in the `lab` package, so we need to move it there.

2021-08-10 07:19 UTC, teimurjan commented on packages/picasso/src/Note/test.tsx
> +  it('default render', () => {
```suggestion
  it('renders', () => {
```

2021-08-10 07:38 UTC, OleksandrNechai commented on packages/picasso/src/Note/story/Default.example.tsx
> +  <div>
What is the purpose of this `div`?

2021-08-10 07:44 UTC, OleksandrNechai commented on packages/picasso/src/Note/styles.ts
> +      borderRadius: '0.4rem',
Please use `borderRadius` enum like here https://github.com/toptal/picasso/blob/master/packages/picasso/src/Notification/styles.ts#L38

2021-08-10 07:50 UTC, OleksandrNechai commented on packages/picasso/src/Note/Note.tsx
> +    <div ref={ref} className={cx(classes.root, className)} {...rest}>
I wonder if this is not a mistake having different horizontal and vertical padding? Maybe we should double-check with designers and if paddings should be the same everywhere we could use Container here.

2021-08-10 07:56 UTC, OleksandrNechai commented on packages/picasso/src/NoteTitle/NoteTitle.tsx
> +    <div ref={ref} className={cx(classes.root, className)} {...rest}>
Can we use Container here and avoid special styles?

2021-08-10 07:59 UTC, OleksandrNechai commented on packages/picasso/src/index.ts
> +export type { NoteProps } from './Note'
The component is named `Notes` in the base. We are trying to have 100% match between BASE and Picasso names. So either ask designers whether they are willing to rename or we need to rename Note --> Notes

2021-08-10 08:00 UTC, OleksandrNechai commented on yarn.lock
> +debuglog@^1.0.1:
What caused updates to the files?

2021-08-10 08:03 UTC, OleksandrNechai requested changes
Congrats on the first Picasso contribution! :rose: :smile: 
Good job! Please address the comments above and you have my approval :wink:

2021-08-10 12:39 UTC, TomasSlama commented on packages/picasso/src/Note/Note.tsx
> +    <div ref={ref} className={cx(classes.root, className)} {...rest}>
I guess it has only left padding 28px because of that colored banner witch is absolute and is 4px wide. So it actually has 24px padding.

2021-08-10 12:41 UTC, TomasSlama commented on packages/picasso/src/NoteTitle/NoteTitle.tsx
> +    <div ref={ref} className={cx(classes.root, className)} {...rest}>
We can use Container, but we can't avoid using custom CSS, because Container doesn't allow us set 4px margin. Lowest is 8px.

2021-08-10 12:44 UTC, TomasSlama commented on yarn.lock
> +debuglog@^1.0.1:
I'm not sure, I just used `yarn install` on cloned project

2021-08-10 13:05 UTC, TomasSlama commented on packages/picasso/src/index.ts
> +export type { NoteProps } from './Note'
Asked Milos about it, they will change it in Abstract. So `Note` it is.

2021-08-10 16:59 UTC, OleksandrNechai commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
ATM I see in Happo two identical pictures, nothing is blue :shrug:

2021-08-10 17:08 UTC, OleksandrNechai commented on packages/picasso-lab/src/Note/styles.ts
> +      }px`,
We don't really use px, but rather em or rem

2021-08-10 17:11 UTC, OleksandrNechai approved these changes

2021-08-10 17:27 UTC, TomasSlama commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
Well, it's a white note on blue background with no padding. In my understanding this is right output. Before style fixes there was transparent bg.

2021-08-10 17:33 UTC, TomasSlama commented on packages/picasso-lab/src/Note/styles.ts
> +      }px`,
I know, but I wanted to keep using enums from the theme and it returns number in px. It should be the same as If I would have used `<Container padded="medium" />`

2021-08-10 17:37 UTC, TomasSlama commented on packages/picasso/src/Note/test.tsx
> +  it('default render', () => {
fixed

2021-08-10 17:38 UTC, TomasSlama commented on packages/picasso/src/Note/story/Default.example.tsx
> +  <div>
none, removed.

2021-08-10 17:47 UTC, OleksandrNechai commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
What is the purpose of having 2 of them then?

2021-08-10 17:53 UTC, TomasSlama commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
TBH I copied from another test, maybe if I add padding to the blue container, it will show that it's always white. Maybe I should check with the base team If I understood the design correctly.

2021-08-11 11:06 UTC, OleksandrNechai commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
Or we can remove the second one :)

2021-08-11 14:06 UTC, TomasSlama commented on cypress/component/Note.spec.tsx
> +        <Container variant='blue'>
I removed the second one ;-)

2021-08-12 07:12 UTC, OleksandrNechai commented
/rebase

2021-08-12 07:34 UTC, OleksandrNechai commented
/rebase

2021-08-13 09:46 UTC, teimurjan approved these changes

2021-08-13 10:35 UTC, merged