style(EnvironmentBanner): update to BASE 2.0 design
toptal/picasso pull request #2135
Opened 2021-08-16 09:36 UTC by TomasSlama

[FX-1097]
[Abstract](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/011fae1db1014d08e4a63534e2ec772b788e1eb4/files/a5d56a4c-1c16-4631-a2f7-8868c49147d9/layers/3B863FAB-C94C-4EE2-8061-FBFAB45778AE?mode=design&selected=94452457-16FA1855-19A1-4947-BE9C-2B8B48350992)

### Description

Update component to BASE 2.0 design

### How to test

- compare storybook with abstract

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/6830426/129543153-b793ddbd-0589-4c6e-b757-1fb1c651745b.png) | ![image](https://user-images.githubusercontent.com/6830426/129542728-f601858c-4e58-4768-b6d3-a6d3d1a99391.png) |

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-08-16 16:12 UTC, OleksandrNechai commented on cypress/component/EnvironmentBanner.spec.tsx
> +    <Container style={{ position: 'relative', height: CONTAINER_HEIGHT }}>
Definetlly this would be amazing to have this in Happo. However atm it looks not right in Happo:
![image](https://user-images.githubusercontent.com/14070311/129595072-5b79c03e-abd4-49d6-8ce0-389dd6f59e81.png)


Can we avoid doing style thing?

2021-08-16 16:16 UTC, OleksandrNechai commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      fontWeight: 600,
I guess we should use this constant https://github.com/toptal/picasso/blob/master/packages/picasso-provider/src/Picasso/config/typography.ts#L32

2021-08-16 16:25 UTC, OleksandrNechai commented on packages/picasso/src/EnvironmentBanner/styles.ts
>        lineHeight: '1em',
line-hight renders as 12px. I design it seems to be 18px.

2021-08-16 16:26 UTC, OleksandrNechai requested changes
Looks fine with small improvements :point_up: :smile: 
However to approve we need to invent something better for the Happo test as it does not look good ATM.

2021-08-17 13:55 UTC, havenchyk commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      padding: '0.25em 0.5rem',
0.25rem?

2021-08-17 14:41 UTC, havenchyk commented
I'm waiting for an updated spec to approve this PR

2021-08-17 15:05 UTC, TomasSlama commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      padding: '0.25em 0.5rem',
according to design, it should be 3px, it would be very messy in rems.

2021-08-17 15:07 UTC, TomasSlama commented on cypress/component/EnvironmentBanner.spec.tsx
> +    <Container style={{ position: 'relative', height: CONTAINER_HEIGHT }}>
its fixed now

2021-08-17 17:09 UTC, OleksandrNechai commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      lineHeight: 1.5,
1.5 of what? :-) can we use em/rem?

2021-08-17 17:09 UTC, OleksandrNechai approved these changes

2021-08-18 06:24 UTC, TomasSlama commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      lineHeight: 1.5,
line-height is using em by default

2021-08-18 07:20 UTC, OleksandrNechai commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      lineHeight: 1.5,
ok, nice, but lets have it explicit so we don't have to remember this rule :smile:

2021-08-18 09:18 UTC, teimurjan approved these changes

2021-08-19 09:40 UTC, havenchyk commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      fontWeight: 600,
I second that `600` can be replaced with `typography.fontWeights.semibold`

2021-08-19 11:23 UTC, TomasSlama commented on packages/picasso/src/EnvironmentBanner/styles.ts
> +      padding: '0.25em 0.5rem',
@havenchyk updated to rems.

2021-08-19 13:05 UTC, merged