style(Link): update to BASE 2.0 design
toptal/picasso pull request #2141
Opened 2021-08-19 08:12 UTC by TomasSlama

[FX-1963]

### Description

Adopt the Link component to the latest design.

changes in API:
 - remove prop underline
   - after consulting Milos, we decided to remove the possibility to change underline property.
 - new prop disabled
   - `not-allowed` cursor on hover
   - removes `onClick` and `href`
   - adds `aria-disabled`  

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/6830426/130032064-c06486b8-09f0-4a18-acc7-f297abc2a1eb.png) | ![image](https://user-images.githubusercontent.com/6830426/130032162-3a81e0d5-c0b8-417b-853e-ff44c33d1b03.png) |

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-08-23 07:59 UTC, teimurjan reviewed
1. Can you add a link to [Abstract]((https://share.goabstract.com/6b34cc9e-5316-4703-a7a0-d01d24b1ae17?mode=design&sha=c1f02ee345bc43e9617f5339aaa3eff1b2501d85)) on the Link's Storybook page, please?
2. Is `font-size` for link 14px? Looks like it's larger.

2021-08-23 07:59 UTC, teimurjan commented on packages/picasso/src/Link/Link.tsx
>      underline?: UnderlineType
If it's a one-value prop, why not make it boolean (ex. `container?: boolean`)?

2021-08-23 07:59 UTC, teimurjan commented on packages/picasso/src/Link/story/Underline.example.tsx
> +const UnderlineExample = () => {
When I look at an example with **Underline** title I hope to see a link with an underline. Instead, I see a custom user badge link.

2021-08-23 07:59 UTC, teimurjan commented on packages/picasso/src/Link/styles.ts
> +        '&:not([aria-disabled="true"])': {
```suggestion
        '&:not($disabled)': {
```

2021-08-23 07:59 UTC, teimurjan commented on packages/picasso/src/Link/Link.tsx
>      underline?: UnderlineType
Another idea is to move this prop to `VariantType`. (ex. `type VariantType = 'action' | 'anchor' | 'container'` or `type VariantType = 'action' | 'anchor' | 'wrapper'`)

2021-08-23 08:30 UTC, TomasSlama commented on packages/picasso/src/Link/Link.tsx
>      underline?: UnderlineType
I wanted to keep it for back compatibility. If it would be a new prop I would definitely choose `variant`. But I was afraid that everybody who used this prop would have to make changes.

2021-08-23 08:34 UTC, TomasSlama commented on packages/picasso/src/Link/story/Underline.example.tsx
> +const UnderlineExample = () => {
I wanted to showcase that underline should be used for cases like this. `<Link underline>verify</Link>` is against base design.

2021-08-23 08:48 UTC, teimurjan commented on packages/picasso/src/Link/Link.tsx
>      underline?: UnderlineType
@TomasSlama hm, sounds reasonable. @havenchyk is it OK for you?

2021-08-23 08:49 UTC, teimurjan commented on packages/picasso/src/Link/story/Underline.example.tsx
> +const UnderlineExample = () => {
I'd rename it to `Container` and add a paragraph about the restrictions (whenever you need to use `Link` as a container, set `underline` to `none`).

2021-08-23 10:46 UTC, TomasSlama commented on packages/picasso/src/Link/Link.tsx
>      underline?: UnderlineType
@teimurjan maybe it would be great if We support both versions and somehow make the underline deprecated so we could remove it so we have the API right in the future.

2021-08-23 16:55 UTC, TomasSlama commented on packages/picasso/src/Link/styles.ts
> +        '&:not([aria-disabled="true"])': {
done

2021-08-23 16:55 UTC, TomasSlama commented on packages/picasso/src/Link/story/Underline.example.tsx
> +const UnderlineExample = () => {
done

2021-08-24 07:51 UTC, teimurjan commented on packages/picasso/src/Link/styles.ts
> +      'div > &': {
Hmm, this selector doesn't look reliable to me. What if a link will be rendered in `Typography` with `as="div"`? IMO we should have an optional prop `size` with values `'default' | 'inherit'`.

2021-08-24 09:32 UTC, TomasSlama commented on packages/picasso/src/Link/styles.ts
> +      'div > &': {
you are right, that looks much better. It should be breaking change probably. If you use the `Link` inside heading you have to set the `size` prop.

Now it makes sense to change the underline to `variant='container'` because we will have breaking change anyway.

2021-08-24 13:47 UTC, havenchyk requested changes
![image](https://user-images.githubusercontent.com/1291032/130627077-5df9f698-b3ab-4592-8663-e1bc4472015f.png)

Please, fix the type errors in development, squash commits locally, and mark them as a breaking change. Change the underline property type to boolean (maybe `noUnderline` is better or `showUnderline='false'`)

2021-08-24 14:01 UTC, TomasSlama commented on packages/picasso/src/Link/Link.tsx
> +      href={disabled ? undefined : href}
I think so, if we would just use `pointerEvents: none`, users with basic knowledge of CSS can just turn it off in developer tools.

2021-08-24 15:18 UTC, TomasSlama commented on packages/picasso/src/Button/story/Augmentation.example.tsx
> +    <Button as={ActionLink} href='/#home'>
sadly I can't, variant is used by Button

2021-08-25 10:53 UTC, havenchyk commented on packages/picasso/src/Button/story/Augmentation.example.tsx
> +    <Button as={ActionLink} href='/#home'>
good point :)

2021-08-25 10:54 UTC, havenchyk commented on packages/picasso/src/Link/Link.tsx
> +      href={disabled ? undefined : href}
this is not a problem, but `pointersEvent: none` is worse solution to me by many reasons

2021-08-25 10:57 UTC, havenchyk commented on packages/picasso/src/Link/Link.tsx
> +type SizeType = 'default' | 'inherit'
https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md#a-use-a-size-prop-with-an-enum-of-limited-values

2021-08-25 10:57 UTC, havenchyk commented on packages/picasso/src/Link/Link.tsx
> +        [classes[`size${size ? capitalize(size) : 'Default'}`]]: size
too dynamic 😄

2021-08-25 11:03 UTC, havenchyk commented
@teimurjan please take a look once again

2021-08-25 11:08 UTC, TomasSlama commented on packages/picasso/src/Link/Link.tsx
> +      href={disabled ? undefined : href}
If we want Link to be disabled, I think there should be no `href` or `onClick` available. So it actually does nothing. Don't you agree?

2021-08-25 11:14 UTC, TomasSlama commented on packages/picasso/src/Link/Link.tsx
> +type SizeType = 'default' | 'inherit'
So If I understand correctly, I shouldn't use `size` prop because users are used to using values from SizeType enum, right?

So I should use some custom prop? Because values in SizeType don't make sense here. We want to give to users the choice to use default font size or inherit font size from a parent.

2021-08-25 13:09 UTC, havenchyk commented on packages/picasso/src/Link/Link.tsx
> +type SizeType = 'default' | 'inherit'
exactly, it's not about size, it's about font size, so font size can inherit or not

2021-08-30 15:21 UTC, havenchyk approved these changes

2021-08-31 06:56 UTC, denieler reviewed
Do you know why the change for file permissions has being made?

```
Notification/__image_snapshots__/notification-closable-notification-snap.png  100644 → 100755
```

2021-08-31 06:56 UTC, denieler commented on packages/picasso/src/Link/Link.tsx
> -    underline?: UnderlineType
looks like a breaking change, right?

2021-08-31 06:57 UTC, havenchyk commented on packages/picasso/src/Link/Link.tsx
> -    underline?: UnderlineType
![image](https://user-images.githubusercontent.com/1291032/131456913-c18ead8f-447d-4093-beeb-261cb71e0e38.png)
yes 😄

2021-08-31 06:59 UTC, denieler commented on packages/picasso/src/Link/Link.tsx
> -    underline?: UnderlineType
cool 👍

2021-09-01 07:30 UTC, denieler commented on packages/picasso/src/Link/story/Container.example.tsx
> +          Whenever you need to use Link as a container, use 'container' variant
this phrase is not clear to me 😞 what does it mean to use a Link as a container? is it about wrapping other components inside the link and behave as a link when clicking on this wrapped group of components?

2021-09-01 07:56 UTC, TomasSlama commented on packages/picasso/src/Link/story/Container.example.tsx
> +          Whenever you need to use Link as a container, use 'container' variant
yeah, you got it right. Do you think we should rephrase it?

2021-09-01 12:10 UTC, denieler commented on packages/picasso/src/Link/story/Container.example.tsx
> +          Whenever you need to use Link as a container, use 'container' variant
yeah, I would change it to something like "If you need to wrap a group of components or a single component into a Link - use the 'container' variant."

2021-09-01 12:58 UTC, havenchyk approved these changes

2021-09-01 13:45 UTC, denieler approved these changes
🎉 great work 💪 🙇‍♂️

2021-09-01 16:24 UTC, TomasSlama commented
@havenchyk cypress tests for Tooltip were not working for me locally. And one sometimes didn't work here. So I have updated those tests so they work every time.

2021-09-03 06:58 UTC, havenchyk approved these changes

2021-09-03 07:00 UTC, merged