feat(Pagination): [FX-2059] update pagination to the latest design
toptal/picasso pull request #2155
Opened 2021-09-06 09:13 UTC by teimurjan

[FX-2059](https://toptal-core.atlassian.net/browse/FX-2059)

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-09-06 11:58 UTC, TomasSlama requested changes
Looks good, only one small issue - it doesn't work correctly for 0 pages.

2021-09-06 11:58 UTC, TomasSlama commented on packages/picasso/src/Pagination/__snapshots__/test.tsx.snap
> -  />
This seems as unexpected behavior to me. As tests says, it should render nothing for 0 pages. But it works only for 1 page.

2021-09-06 11:58 UTC, TomasSlama commented on packages/picasso/src/Pagination/story/index.jsx
> +        description: '(page‰: number) => void'
is `‰` intentional? or typo?

2021-09-07 07:28 UTC, teimurjan commented on packages/picasso/src/Pagination/story/index.jsx
> +        description: '(page‰: number) => void'
a typo. I will fix, thanks!

2021-09-07 07:48 UTC, TomasSlama approved these changes

2021-09-07 20:43 UTC, havenchyk approved these changes
LGTM, just a couple of questions/comments

2021-09-07 20:43 UTC, havenchyk commented on packages/picasso/src/PaginationButton/styles.ts
> +      '&$active': theme.palette.grey.dark
that's new to me. how is it possible `palette.grey.dark` doesn't exist?

2021-09-07 20:43 UTC, havenchyk commented on packages/picasso/src/Button/index.ts
> +export { createVariant } from './styles'
this is needed for internal usage only but the user will be able to import it from '@toptal/picasso/Button', so idk if this export should be here or not

2021-09-07 20:43 UTC, havenchyk commented on packages/picasso/src/Pagination/utils/get-siblings/test.ts
> +    ).toStrictEqual([[], [2]])
is `toStrictEqual` a preferable way now? I see no difference with `toEqual` for our cases

2021-09-07 20:43 UTC, havenchyk commented on packages/picasso/src/PaginationButton/PaginationButton.tsx
> +        root: cx(paginationButtonClass, classes?.root, {
can you explain, why `classes?.root` are here? seems useless to me

2021-09-08 06:28 UTC, havenchyk commented
/rebase

2021-09-08 06:29 UTC, havenchyk commented
@teimurjan oh, wait, we collect breaking changes in the PR https://github.com/toptal/picasso/pull/2157
please rebase on top of `feature/picasso-compliance` branch

2021-09-08 08:32 UTC, teimurjan commented on packages/picasso/src/PaginationButton/styles.ts
> +      '&$active': theme.palette.grey.dark
Grey in Material UI is optional, that's why it potentially can be undefined.

2021-09-08 08:37 UTC, teimurjan commented on packages/picasso/src/PaginationButton/PaginationButton.tsx
> +        root: cx(paginationButtonClass, classes?.root, {
`Pagination` overrides `Button`'s margin. That's why it accepts `classes`.

https://github.com/toptal/picasso/blob/9a36a1ab9b3eb83885900d53d6adfaed63a892b4/packages/picasso/src/Pagination/styles.ts#L5

2021-09-08 10:11 UTC, havenchyk commented on packages/picasso/src/PaginationButton/styles.ts
> +      '&$active': theme.palette.grey.dark
that's true, I checked briefly and didn't find a way to override this declaration from MUI. But I found that in our code base we used `theme.palette.grey.dark!` to bypass it, I think here it also can be used

2021-09-08 10:14 UTC, havenchyk commented on packages/picasso/src/PaginationButton/PaginationButton.tsx
> +        root: cx(paginationButtonClass, classes?.root, {
you're right, but from where do you expect `classes.root` will come? useStyles are created from styles of PaginationButton, not Button

2021-09-08 13:11 UTC, havenchyk approved these changes
Great job!

2021-09-08 13:12 UTC, havenchyk commented
/rebase

2021-09-09 12:26 UTC, TomasSlama commented
@toptal-bot run all

2021-09-10 08:11 UTC, teimurjan commented
@toptal-bot run visual

2021-09-10 08:25 UTC, merged