feat: expose vertical orientation property in tabs
toptal/picasso pull request #2156
Opened 2021-09-06 10:25 UTC by pkondzior

Component: https://picasso.toptal.net/?path=/story/layout-tabs--tabs

### Description

This change exposes orientation property from MaterialUi Tabs component. 

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-09-06 10:30 UTC, havenchyk commented on packages/picasso/src/Tabs/styles.ts
> +        left: (props: Props) =>
we use different way of doing the same: create a class with desired css and conditionally include it in tsx file please

2021-09-06 10:30 UTC, havenchyk commented on packages/picasso/src/Tabs/Tabs.tsx
> +export const Tabs = forwardRef<HTMLButtonElement, Props>(function Tabs (
please do not forget to update to run `yarn install` on top of master

2021-09-06 10:30 UTC, havenchyk commented on packages/picasso/src/Tab/styles.ts
> +      marginRight: '2em',
does it mean that last child will have marginRight as well?

2021-09-06 10:37 UTC, pkondzior commented on packages/picasso/src/Tab/styles.ts
> +      marginRight: '2em',
Yes, but I've didn't noticed that this change makes them look bad anyhow in horizontal representation (which is default here). Also not having that margin in vertical orientation is going to make last element always shifted slightly. So to make this works and looks good in both cases I've made the margin appear always. I don't think we can have here a conditional class approach because tab don't know if they are layout i horizontal or vertical orientation (that property exists only in the Tabs component and AFAIK is not being passed to Tab component)

2021-09-06 10:58 UTC, pkondzior commented on packages/picasso/src/Tab/styles.ts
> +      marginRight: '2em',
This is what I'm trying to solve here
<img width="1168" alt="Screen Shot 2021-09-06 at 12 58 12 PM" src="https://user-images.githubusercontent.com/6011/132207232-b9f7afe9-9058-44e7-aedc-9041542110f2.png">

2021-09-06 11:52 UTC, pkondzior commented on packages/picasso/src/Tab/styles.ts
> +      marginRight: '2em',
This is how the horizontal will look by default (no changes in margin CSS):
<img width="1382" alt="Screen Shot 2021-09-06 at 1 47 43 PM" src="https://user-images.githubusercontent.com/6011/132212905-78ec4de5-a3aa-4bdd-8d34-90459bf17084.png">

This is how it will look with my change
<img width="1372" alt="Screen Shot 2021-09-06 at 1 48 57 PM" src="https://user-images.githubusercontent.com/6011/132213086-a3400936-2fef-476f-a023-089d2cac3bfa.png">

So I don't know why we have this margin there at all, but as first screenshot shows it will affect vertical layout of tabs. Making it to appear on the final element will fix my problem but it wont affect horizontal layout:

<img width="1385" alt="Screen Shot 2021-09-06 at 1 51 59 PM" src="https://user-images.githubusercontent.com/6011/132213400-bf3d5df2-0f7d-47b1-a94f-63c8f4debb9a.png">

2021-09-08 13:45 UTC, TomasSlama requested changes
We should also create a visual test in happo using cypress. Check `/cypress/component` for inspiration. 

I have noticed that you reached out to base team with questions about design, we should wait for the design before merging.

Otherwise LGTM

2021-09-08 13:45 UTC, TomasSlama commented on packages/picasso/src/Tabs/Tabs.tsx
> +  orientation?: TabsProps['orientation']
we agreed on TreeView and Stepper to use `direction` instead of orientation, so we should change it here too, so we are consistent.

2021-09-08 13:45 UTC, TomasSlama commented on packages/picasso/src/Tab/styles.ts
> +      marginRight: '2em',
It might be a signal to move this margin to parent, so Tabs will decide what margin to use on children. What do you think guys?

2022-02-25 12:11 UTC, closed without merging