feat(Badge): [FX-2057] update badge
toptal/picasso pull request #2160
Opened 2021-09-09 09:14 UTC by TomasSlama

[FX-2057]

[design](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/060a08494feb5a14a7a0a31797d5cb1b75021cbb/files/c64770f3-7c15-4b47-be53-7e2eb1679f41/layers/1DE6B39D-9967-43F7-BC80-BA66C07F3EB6?collectionId=15c8313a-830d-4af3-8d9d-416bb0d4c882&collectionLayerId=45b45dcc-3c86-4960-9538-58a979233959&mode=design&present=true)

### Description

BREAKING CHANGES:
- old `medium` size is now `large` and we add a new `medium`.
- `content` type changed to `number` to transform content to 99+
  - I have checked the Staff portal and it uses only numbers anyway

### How to test

- compare storybook with design

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/6830426/132658233-700691b4-c08d-4571-ab9d-ef8f6d710543.png) | ![image](https://user-images.githubusercontent.com/6830426/132658144-cae199bb-72a8-471e-b7d7-cf948f354219.png) |

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-09-09 13:09 UTC, denieler commented on packages/picasso/src/Badge/test.tsx
> +    expect(getByText('99')).toBeVisible()
these unit tests look pretty useless if we would like to check how the component looks and displays correctly content - it's better doing that by using visual tests

2021-09-09 13:10 UTC, denieler commented on packages/picasso/src/Badge/test.tsx
> -    expect(spiedOnTitleCase).toHaveBeenCalledTimes(0)
I would not also remove this test, because it was testing `titleCase` functionality

2021-09-09 13:10 UTC, denieler commented on packages/picasso/src/Badge/test.tsx
> -    expect(screen.getByTestId('badge-root')).toBeInTheDocument()
and this one, because it was testing that `data-testid` is passed to the DOM

2021-09-09 13:11 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> -    titleCase: propsTitleCase,
why we want to remove `titleCase`?

2021-09-09 13:16 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +  if (!content) {
I would change to `content === 0`, because it's the only case when this condition can be false according to the `content` type

2021-09-09 13:17 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +  if (!content) {
but in general, I think this component shouldn't have this functionality. I would say it's up to the component user to decide whether they need to hide `Badge` component with zero number as a content.

2021-09-09 13:18 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +  content: Props['content'],
```suggestion
  content: number,
```

2021-09-09 13:19 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +const getTransformedContent = (
I'm not sure it's a good idea to have this functionality inside this component, it makes it way less universal and containing logic. It looks like Topkit is a better place for such components

2021-09-09 13:57 UTC, TomasSlama commented on packages/picasso/src/Badge/test.tsx
> -    expect(spiedOnTitleCase).toHaveBeenCalledTimes(0)
`titleCase` is no longer necessary, because according to design, badge should accept only numeric values

2021-09-09 13:59 UTC, TomasSlama commented on packages/picasso/src/Badge/test.tsx
> -    expect(screen.getByTestId('badge-root')).toBeInTheDocument()
you are right, this one I will return back.

2021-09-09 14:16 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> -    titleCase: propsTitleCase,
since content accepts only numbers, it doesn't make any sense.

2021-09-09 14:19 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> +  if (!content) {
even when design documentation explicitly says so?
![image](https://user-images.githubusercontent.com/6830426/132703200-f41a0b4d-0c08-4a36-9bc7-03ad0e765e4c.png)

2021-09-10 06:57 UTC, OleksandrNechai commented on packages/picasso/src/Badge/Badge.tsx
> +  if (!content) {
I think yes, documentation is the design guideline. Designers do not care how we split the code. But from the development perspective deciding whether to render itself or not is probably not the component's responsibility the same way as deciding what should be its margin and positioning. It's all the parent component's responsibility.

2021-09-10 07:13 UTC, OleksandrNechai requested changes
In Ubuntu, chrome renders this 
![image](https://user-images.githubusercontent.com/14070311/132814679-21e72373-9c0e-446d-9162-5d57f695ac7b.png)

2021-09-10 07:14 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> +  if (!content) {
I have removed the condition.

2021-09-10 07:55 UTC, OleksandrNechai commented on packages/picasso/src/Badge/Badge.tsx
> +const getTransformedContent = (
Whether this is Topkit or not we shell discuss on offsite. Because people have different feelings about it. For example, I perceive Picasso as a library of reusable visual components. Topkit is a library of non-ui functionality like integrations with different services like GQL or Sentry. But will see what we agree. 

To me, this is just a `formatter`.   While separate functionality, it is closely related to this component. How about having a separate formatter component? This way we keep generic basic components and at the same time give the ability to replace the formatting logic if needed.
```
<Badge>
    <Badge.TrimNumber>10000</Badge.TrimNumber>
<Badge>
```

2021-09-10 07:56 UTC, OleksandrNechai commented on packages/picasso/src/Badge/Badge.tsx
> +const getTransformedContent = (content: number, size: SizeType): string => {
```suggestion
const format = (content: number, size: SizeType): string => {
```

2021-09-10 07:59 UTC, OleksandrNechai commented on packages/picasso/src/Badge/story/Sizes.example.tsx
> +    <Container top='small' bottom='medium' flex style={{ gap: '1rem' }}>
`style={{ gap: '1rem' }}` - in a way, we are teaching people to use this pattern and we don't want to do this. I guess unless we have finally layouting the solution we should rather do Container and it spaces.

2021-09-10 08:05 UTC, OleksandrNechai commented on packages/picasso/src/Badge/styles.ts
> +    },
idk. looks like hacking with paddings does not perfectly align numbers in badge :man_shrugging:

2021-09-10 16:13 UTC, TomasSlama commented on packages/picasso/src/Badge/styles.ts
> +    },
I'm not sure what you think. This padding is added so it matches the design when content is trimmed and it's not a perfect circle anymore. Until then it should be always a perfect circle with aligning content to the center. I don't see any problem, please make a screenshot if you see some problem.

2021-09-10 18:25 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> +const getTransformedContent = (
using max as we agreed on it

2021-09-10 18:39 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> +const getTransformedContent = (content: number, size: SizeType): string => {
👍

2021-09-10 18:40 UTC, TomasSlama commented on packages/picasso/src/Badge/story/Sizes.example.tsx
> +    <Container top='small' bottom='medium' flex style={{ gap: '1rem' }}>
👍

2021-09-10 18:42 UTC, TomasSlama commented on packages/picasso/src/Badge/styles.ts
> +    },
Ah, I see the screenshot now, didn't scroll down :), I will look at it.

2021-09-14 13:15 UTC, OleksandrNechai approved these changes

2021-09-15 16:20 UTC, denieler approved these changes

2021-09-20 08:53 UTC, merged