feat(Dropzone): create new component
toptal/picasso pull request #2174
Opened 2021-09-23 18:46 UTC by TomasSlama

[FX-1870]
[Abstract](https://app.abstract.com/share/2556a122-6443-4546-96db-3d40c37b2a0d?mode=design&sha=58ee1df911f7d6ca2d9214171088a69bdff23401)

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-09-24 17:40 UTC, OleksandrNechai reviewed
WOW :+1: 

But not there yet :point_down:

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +    if (acceptedFiles.length) {
```suggestion
    if (acceptedFiles.length > 0) {
```

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      setFiles([...previousFiles, ...newFiles])
Hmm, why is `previousFiles` introduced? What would happen if we did `[...files, ...newFiles]`

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +    }
I don't get what is this code doing. Why is this gradual increase of progress needed? To me, it looks like a simple setTimeout after 2500ms.

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Hover.example.tsx
> +const Example = () => {
I think this example should be the only one that demonstrates how things work. All other examples just demonstrate different possible states of the `dropzone` and probably should be static ones with static data and no interactivity.

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +    accept: {
I think exposing react-dropzone libraries props directly is a mistake. We need to sit down and think about which props do we really need and what their names should be. End-user should not know which library we use.

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      borderWidth: 1,
`sizes.borderWidth`

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +    value.length &&
```suggestion
    value.length > 0 &&
```

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
why can't we use standard Container padding?

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      transition: 'border .24s ease-in-out',
How did designers specify this to you? :smiley:

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/test.tsx
> +    ).toContain('completed')
Can we check it without resorting to checking class? It looks like an implementation check. If we are after visual appearance, then maybe worth checking with Happo only?

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/test.tsx
> +  })
Can we check it without resorting to checking class? It looks like an implementation check. If we are after visual appearance, then maybe worth checking with Happo only?

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +    value.filter(filterByUploading).length === 0
```suggestion
    value.some(file=>file.uploading)
```

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +        {...getRootProps({
now you see why I asked you to take that course? :)

2021-09-24 17:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            <FormError key={`${error}-${String(index)}`}>{error}</FormError>
`String` probably is redundant

2021-09-24 17:40 UTC, OleksandrNechai commented on cypress/component/Dropzone.spec.tsx
> +        {renderDropzone({ className: '__hover', hint: 'Max file size: 25MB' })}
is `__hover` something standard?

2021-09-24 17:40 UTC, OleksandrNechai commented on cypress/component/Dropzone.spec.tsx
> +    cy.get('[class*=completed]').should('not.exist')
I am not sure if querying classes is reliable. I have a belief that we should only check how things look and how they behave. And try to avoid looking inside. As soon as you look inside, the test becomes dependent on implementation and hence fragile.

2021-09-27 08:44 UTC, TomasSlama commented on cypress/component/Dropzone.spec.tsx
> +        {renderDropzone({ className: '__hover', hint: 'Max file size: 25MB' })}
not really, I didn't want to create a new prop `hover` only for visual testing purposes, so I created `__hover` class which simulates the hover effect. What do you think about it?

2021-09-27 08:49 UTC, TomasSlama commented on cypress/component/Dropzone.spec.tsx
> +    cy.get('[class*=completed]').should('not.exist')
you are probably right, I wanted to be sure, that states are changing when value changes. But it's probably overkill, I will remove this part.

2021-09-27 08:53 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            <FormError key={`${error}-${String(index)}`}>{error}</FormError>
we have been discussing this topic with others. This is how MUI is approaching keys in arrays when you can't find another unique key.

`key={`${error}-${index}`}` would generate an error, since we can not use the index in keys. But this hack allows us to use the index in some cases.

2021-09-27 08:56 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +    }
it simulates upload, I took this example from FileInput. If you try to add some files in the default example in a storybook, it will show you this nice progress bar.

2021-09-27 08:58 UTC, TomasSlama commented on packages/picasso/src/Icon/svg/upload16.svg
> +</svg>
will do.

2021-09-27 13:30 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      setFiles([...previousFiles, ...newFiles])
we need `previousFiles` to keep reference of previous files in setInterval

2021-09-27 13:56 UTC, denieler commented on cypress/component/Dropzone.spec.tsx
> +    mount(<TestingPicasso>{renderDropzone({})}</TestingPicasso>)
```suggestion
    mount(<TestingPicasso>{renderDropzone()}</TestingPicasso>)
```

2021-09-27 13:56 UTC, denieler commented on cypress/component/Dropzone.spec.tsx
> +    <Dropzone style={{ width: 300 }} {...props} />
```suggestion
    <Dropzone style={{ width: '300px' }} {...props} />
```
?

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +const useStyles = makeStyles<Theme>(styles, { name: 'FileInputContent' })
```suggestion
const useStyles = makeStyles<Theme>(styles, { name: 'Dropzone' })
```

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +    <Container style={style} ref={ref}>
why we don't have `className` applied at the same level as `style` prop?

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            <FormError key={`${error}-${String(index)}`}>{error}</FormError>
eslint even has a rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +const page = PicassoBook.section('Forms').createPage(
why in `Forms`? it should be probably in lab?

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +    accept: {
I agree, I would not list them all. Maybe even none from the beginning

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      lineHeight: rem('22px')
why do we need to change line height for the Typography? Does it mean that this text is not compatible with BASE in the dropzone component?

2021-09-27 13:56 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      '&:hover, &$dragActive, &.__hover': {
uh, this looks dirty with `__hover` only for visual tests 😃

2021-09-27 14:10 UTC, TomasSlama commented on cypress/component/Dropzone.spec.tsx
> +    <Dropzone style={{ width: 300 }} {...props} />
It's the same, but if you think it's better, why not.

2021-09-27 14:16 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      lineHeight: rem('22px')
exactly, there is even a ticket in todo, to deal with this in general. We are using line-height 1.5em everywhere, but Milos was saying that line-height can't be an odd number. So for 14px it's supposed to be 22px not 21px.

2021-09-27 14:24 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +    accept: {
I think we need to keep the most important ones since they are needed for basic functionality. At least these which we are using in examples

2021-09-27 14:25 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
design says 20px, container allowes as 8, 16, 24, ....

2021-09-27 14:30 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      '&:hover, &$dragActive, &.__hover': {
yeah, it was my suggestion how to solve problem with states in happo Uladzimir shared with us. And we are doing something similar with button where we have props like hover, focused which are used also only in tests, or at least I don't see any other real usage scenario.

2021-09-27 14:31 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/test.tsx
> +    ).toContain('completed')
className is only difference, I agree we can check only with happo.

2021-09-27 14:41 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      lineHeight: rem('22px')
let's fix it in Typography then instead of adding new class, which we eventually will forget to remove 😃

2021-09-27 14:42 UTC, denieler commented on cypress/component/Dropzone.spec.tsx
> +    <Dropzone style={{ width: 300 }} {...props} />
it's just more clear which unit is used

2021-09-27 15:42 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
Let's maybe check if this is not a designer's mistake?

2021-09-27 16:00 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      '&:hover, &$dragActive, &.__hover': {
Hmm, interesting hack :) I think either we do it the same way as Button does or we don't do it. Other teams might also need it for tests. I don't see the need of introducing a new pattern.

2021-09-27 16:10 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +export interface Props extends BaseProps, Omit<DropzoneOptions, 'children'> {
I think we should not expose `DropzoneOptions`.

2021-09-27 16:33 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            <FormError key={`${error}-${String(index)}`}>{error}</FormError>
I mean if you concat string and number you get string, no need to apply String :smile:

2021-09-27 16:35 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  multiple: true
It is weird not seeing these props in `Props`

2021-09-27 16:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Error.example.tsx
> +    />
These properties need to be in the `Props` of Dropzone explicitly defined.

2021-09-27 16:46 UTC, OleksandrNechai commented on packages/picasso/src/ModalTitle/ModalTitle.tsx
> +})
reformatting?

2021-09-27 16:46 UTC, OleksandrNechai approved these changes

2021-09-27 16:48 UTC, OleksandrNechai requested changes
Looks like Dropzone's interface is not defined properly yet

2021-09-28 05:39 UTC, teimurjan approved these changes

2021-09-28 05:39 UTC, teimurjan commented on cypress/component/Dropzone.spec.tsx
> +        {renderDropzone({ className: '__hover', hint: 'Max file size: 25MB' })}
Usually, we do not rely on the classes. It isn't good to have a prop just for VT, but we do the same for `Button`. That's why I'd do it with the prop just for consistency.

2021-09-28 05:39 UTC, teimurjan commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +import FormHint from '@toptal/picasso/FormHint'
I'd add an export of `FormHint` to the index file and import from `@toptal/picasso`.

2021-09-28 05:41 UTC, teimurjan commented
Is it OK that `Dropzone` in the uploading state allows uploading another file? Gray background makes me think that it should be disabled.

2021-09-28 07:59 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +export interface Props extends BaseProps, Omit<DropzoneOptions, 'children'> {
I will expose only some specific props, that are most important.

2021-09-28 08:01 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            <FormError key={`${error}-${String(index)}`}>{error}</FormError>
that is true, but without String will eslint throw error

2021-09-28 08:59 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
I don't think its a mistake, they use quite commonly lot of different paddings

2021-09-28 09:00 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      transition: 'border .24s ease-in-out',
they didn't I will check with other components how hover transition is set

2021-09-28 09:07 UTC, TomasSlama commented on packages/picasso/src/ModalTitle/ModalTitle.tsx
> +})
yep, it was done by `yarn lint`

2021-09-28 11:23 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
I will ask Milos when I will be showing him

2021-09-29 06:16 UTC, OleksandrNechai commented on cypress/component/Dropzone.spec.tsx
> +      const [value, setValue] = useState<DropzoneProps['value']>([
Why do we need useState? It looks like there is no interaction with Dropzone in this test.

2021-09-29 06:26 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  accept?: DropzoneOptions['accept']
Although simpler, I think we should avoid using DropzoneOptions in type definitions. If we do that, we make our clients depend on `DropzoneOptions` type definition. If we update our deps, our code might be fine but the client's code may fail to compile and there is no way we can discover that.

On the other hand, if we define the interface on our own, we will get type mismatches after the update while compiling Picasso.

2021-09-29 06:27 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  validator?: DropzoneOptions['validator']
Do we really need it atm? If not I would avoid adding props just in case. We don't yet know what our users will need. When we discover the needs, we will add more props.

Please, make sure each prop is documented.

2021-09-29 06:29 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +    ...dropzoneOptions
let's list the options explicitly. It would be easier to read the code.

2021-09-29 06:33 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            [classes.focused]: focused
Can't it be that the Dropzone is hovered and is focused at the same time? In the code above, it looks like states are mutually exclusive.

2021-09-29 06:38 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  maxSize: Infinity,
IDK, maybe we can set some reasonable limit here?

2021-09-29 06:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      validator={customSizeValidator}
Why such validator is needed if we have maxSize prop?

2021-09-29 06:44 UTC, OleksandrNechai commented on packages/picasso/src/index.ts
> +export type { FormHintProps } from './FormHint'
Why and how is this related to Dropzone?

2021-09-29 06:45 UTC, OleksandrNechai approved these changes
I still have a bunch of questions. I hope you will figure them out. So I am approving to avoid blocking you.

2021-09-29 08:11 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +            [classes.focused]: focused
I'm not sure what you mean. Dropzone can be focused and hovered at the same time, these props are just to showcase these states in the story and cypress. This same approach we use in Button.

2021-09-29 08:12 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  maxSize: Infinity,
I don't think it is up to us, users should define these restrictions.

2021-09-29 08:13 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      validator={customSizeValidator}
For custom error message

2021-09-29 08:15 UTC, TomasSlama commented on packages/picasso/src/index.ts
> +export type { FormHintProps } from './FormHint'
This was a suggestion of @teimurjan. Since we use FormHint inside Dropzone, we can import FormHint as any other Component `import { FormHint } from '@toptal/picasso'` and not `import FormHint from '@toptal/picasso/FormHint`

2021-09-29 09:23 UTC, TomasSlama commented on cypress/component/Dropzone.spec.tsx
> +      const [value, setValue] = useState<DropzoneProps['value']>([
fixed, it was leftover

2021-09-29 09:24 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/Dropzone.tsx
> +  validator?: DropzoneOptions['validator']
I think we need it, default validation error messages aren't the same as in design and I don't think we can predict the use cases of other developers. I have added documentation into the storybook, so I will add them here also.

2021-09-29 10:29 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +const customSizeValidator: DropzoneProps['validator'] = file => {
I would not enforce people to use proxying of types, like `DropzoneProps['validator']`. For projects who use such props if any breaking changes happen would be pretty difficult to upgrade Picasso and find problems. I would create types in examples and use them

2021-09-29 11:48 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      code: 'size-too-large',
good point, I will use the enum.

2021-09-29 14:42 UTC, TomasSlama commented
@toptal-bot run build

2021-09-30 07:33 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +const customSizeValidator: ValidatorType = file => {
maybe make this to simplify? so we would always return array of `DropzoneFileError` even if single error has happened
```suggestion
const customSizeValidator: DropzoneFileError[] | null = (file: File) => {
```

2021-09-30 07:35 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +  const addFiles: OnDropType = (acceptedFiles, rejectedFiles) => {
I would also inline types here
```suggestion
  const addFiles = (
    acceptedFiles: File[],
    fileRejections: DropzoneFileRejection[],
    event: DropzoneDropEvent
  ) => {
```

2021-09-30 07:36 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      const newFiles = Array.from(acceptedFiles).map(file => ({
Looks like it is already an array `File[]`
```suggestion
      const newFiles = acceptedFiles.map(file => ({
```

2021-09-30 07:38 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      }, 250)
this doesn't look like a real example of file download 😃 can we get the real progress of the file upload?

2021-09-30 07:40 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/Default.example.tsx
> +      validator={customSizeValidator}
can we use it with some default error message from Dropzone?
If so - I would show Default example with super minimum configuration and add another example with the custom error message capabilities

2021-09-30 07:43 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +      padding: '20px',
@TomasSlama what was the conclusion from Milos? 😃

2021-09-30 07:43 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +        lineHeight: rem('16px')
isn't it just `1em`?

2021-09-30 07:44 UTC, denieler commented on packages/picasso-lab/src/Dropzone/test.tsx
> +  it('renders', () => {
we need also one snapshot test of html generated for Dropzone render

2021-09-30 07:44 UTC, denieler commented on packages/picasso-lab/src/Note/story/index.jsx
> +const page = PicassoBook.section('Picasso Lab').createPage(
👍 🙇‍♂️

2021-09-30 08:44 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +        lineHeight: rem('16px')
you are right, '1rem'

2021-09-30 08:48 UTC, denieler commented on packages/picasso-lab/src/Dropzone/styles.ts
> +        lineHeight: rem('16px')
but what about `1em`? will it work, or is the font-size not default?

2021-09-30 11:50 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +        'Cb for when the drop event occurs. Note that if no files are accepted, this callback is not invoked.'
```suggestion
        'Callback for when the drop event occurs. Note that if no files are accepted, this callback is not invoked.'
```

2021-09-30 11:51 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +        'Cb for when the drop event occurs. Note that if no files are rejected, this callback is not invoked.'
```suggestion
        'Callback for when the drop event occurs. Note that if no files are rejected, this callback is not invoked.'
```

2021-09-30 11:51 UTC, denieler commented on packages/picasso-lab/src/Dropzone/story/index.jsx
> +Cb for when the drop event occurs. Note that this callback is invoked after the getFilesFromEvent callback is done.
```suggestion
Callback for when the drop event occurs. Note that this callback is invoked after the getFilesFromEvent callback is done.
```

2021-09-30 11:58 UTC, denieler commented on packages/picasso-lab/src/Dropzone/test.tsx
> +    expect(queryByText('Click or drag file to upload')).toBeVisible()
if we have snapshot we probably don't need even this expectation 😃

2021-09-30 12:17 UTC, denieler approved these changes

2021-09-30 13:55 UTC, TomasSlama commented on packages/picasso-lab/src/Dropzone/styles.ts
> +        lineHeight: rem('16px')
it wouldnt work, because there is 11px font-size

2021-10-01 07:54 UTC, merged