feat: add large input variants
toptal/picasso pull request #2180
Opened 2021-09-30 16:30 UTC by 109149

[FX-2125](https://toptal-core.atlassian.net/browse/FX-2125)

### Description

- Add large `Input` variant, with the height of `48px`.

### How to test

### Screenshots

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- `N/A` Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- `N/A` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-09-30 16:52 UTC, TomasSlama reviewed
On a first look, it seems good to me. I will do a proper test tomorrow.

2021-09-30 16:53 UTC, TomasSlama reviewed
and I think you are missing updated visual snapshots

2021-10-04 08:23 UTC, 109149 commented on packages/picasso/src/OutlinedInput/OutlinedInput.tsx
> -  ReactType,
ReactType is deprecated

2021-10-04 08:26 UTC, TomasSlama approved these changes

2021-10-05 07:14 UTC, teimurjan requested changes
Good job, man!

There is only one problem. The text for large input is cut at the bottom.

![](https://user-images.githubusercontent.com/17337276/135977072-59d8d4e3-66a8-4893-90f8-547e34b7d4f8.png)

2021-10-05 09:41 UTC, teimurjan commented on packages/picasso/src/OutlinedInput/styles.ts
> +      padding: '0.25rem 0.625rem',
You cannot just decrease the padding because it's defined in Abstract as 16px(1rem). The problem with the text cut is that the `font-size` of large input is 18px but should be `16px`.

You should have a className `inputLarge` (like `inputSmall` and `inputMedium`) where you'll override the original MUI `font-size`. In this case `padding: '1rem'` will work.

2021-10-05 09:43 UTC, teimurjan commented
I found another problem. Counter's `font-size` should also be increased to `12px` for the large input.

<img width="325" alt="Screen Shot 2021-10-05 at 15 42 44" src="https://user-images.githubusercontent.com/17337276/135999671-25374372-1eb9-4f06-b3d6-db3c7f081415.png">

2021-10-05 10:03 UTC, 109149 commented on packages/picasso/src/OutlinedInput/styles.ts
> +      padding: '0.25rem 0.625rem',
Completely missed that part! Thank you, I will fix it.

2021-10-07 08:07 UTC, denieler commented on packages/picasso/src/TimePicker/__snapshots__/test.tsx.snap
> +          class="PicassoSvgTime16-root PicassoTimePicker-icon PicassoInput-icon PicassoInput-iconMedium"
why for TimePicker icon size has been changed?

2022-01-11 09:39 UTC, closed without merging