feat(Select): add disabled option
toptal/picasso pull request #2195
Opened 2021-10-19 16:47 UTC by teimurjan

[FX-2160](https://toptal-core.atlassian.net/browse/FX-2160)

[Abstract](https://share.goabstract.com/b2f57088-6713-47f1-a4fd-2f3f60a9d648?mode=design&sha=3674422f1a9915b54bb950319af52986416c311c)

### Description

- Added a disabled option.
- Fixed Sidebar disabled items' colors
  - [Abstract (light)](https://share.goabstract.com/3d7f8be3-40f1-48a0-933e-b80929348cfc?mode=design&sha=77ad4a4f04f395e22be2a1309c60385c2be6784b)
  - [Abstract (dark)](https://share.goabstract.com/dda60d94-5f1a-4ed8-895d-44d6ec5bd116?mode=design&sha=77ad4a4f04f395e22be2a1309c60385c2be6784b)

### How to test

1. Go to the Select storybook page.
2. Open the disabled options example.
3. Click on the select.
4. Hover over a disabled option.
5. Be sure that it can't be highlighted.
6. Click on a disabled option.
7. Be sure that it's not selected.
8. Highlight a non-disabled option.
9. Press arrow down and arrow up multiple times.
10. Be sure that the disabled items are skipped.

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-10-19 20:52 UTC, vshyrokov requested changes
Please fix bugs. Videos attahced.

2021-10-20 10:34 UTC, teimurjan commented
@vshyrokov Great catch! Fixed ✅

2021-10-20 12:21 UTC, vshyrokov commented
The color of the disabled item is still incorrect because we have an opacity of 0.5 there.

2021-10-21 08:44 UTC, teimurjan commented on packages/picasso/src/Select/types.ts
> -  selectedIndexes: number[]
It's not used anywhere.

2021-10-21 12:30 UTC, vshyrokov commented on packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
>  })
it seems we are missing tests when we have a Select with group options, WDYT?

2021-10-26 12:14 UTC, merged