feat(datepicker): add support for custom value
toptal/picasso pull request #2203
Opened 2021-11-02 08:32 UTC by MrBra1nwash

[SPT-2061](https://toptal-core.atlassian.net/browse/SPT-2061)

Add a boolean flag that allows using string values. It is useful for Staff Portal's users because we have this behavior in [Platform](https://staging.toptal.net/platform/staff/engagements/283531)

https://user-images.githubusercontent.com/16545305/139810245-20266335-8fad-4da0-a059-c48cfb647071.mov

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

https://user-images.githubusercontent.com/16545305/139812134-8fd8ae67-8e46-4294-97b5-c0dd1878599b.mov

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-11-02 10:22 UTC, TomasSlama approved these changes
LGTM 👍

2021-11-02 10:50 UTC, MrBra1nwash commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  }
Thank you, renamed to the `dateValue`, because `value` is already taken for the prop

2021-11-03 06:50 UTC, teimurjan requested changes
We've discussed the implementation inside FX and concluded that the current implementation is not perfect. We'd not want to have a prop for some custom value because it's hacky.

There was a nice proposal from @dmaklygin:

> For my perspective of view, it should be like a prepareFunction which expect any value from the input and returns a Date object.
by default it expects a stringified Date object, but it also might be extended. wdyt?

I'd go this way. cc @toptal/fx-codeowners

2021-11-05 11:41 UTC, dmaklygin1 commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  ): dateValue is DateOrDateRangeType => typeof dateValue !== 'string'
the definition of this function might be outside of the DatePicker component

2021-11-05 11:42 UTC, dmaklygin1 commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +      return formatInputValue(convertedValue)
```suggestion
     if (!isValidDateValue(value)) return value
     
     return formatInputValue(timezoneConvert(value, timezone))
```

wdyt?

2021-11-05 12:15 UTC, MrBra1nwash commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  ): dateValue is DateOrDateRangeType => typeof dateValue !== 'string'
Thank you, fixed.

2021-11-05 12:15 UTC, MrBra1nwash commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +      return formatInputValue(convertedValue)
Thank you, fixed.

2021-11-05 12:38 UTC, teimurjan approved these changes

2021-11-05 12:41 UTC, teimurjan commented
@MrBra1nwash I've fixed invalid commit title

2021-11-05 14:57 UTC, dmaklygin1 approved these changes

2021-11-08 09:43 UTC, merged