feat(prompt modal): [FX-2217] add data-testid into PromptModal
toptal/picasso pull request #2205
Opened 2021-11-02 12:14 UTC by vshyrokov

[FX-2217](https://toptal-core.atlassian.net/browse/FX-2217)

### Description

Added data-testid's according to the https://toptal-core.atlassian.net/wiki/spaces/TA/pages/1528758363/Data-TestID+naming+convention

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- `N/A` Annotate all `props` in component with documentation
- `N/A` Create `examples` for component
- `N/A` Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- `N/A` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-11-02 14:40 UTC, dmaklygin1 commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +      )}
as now we have a `data-testid`, it would be great to replace some selectors in tests: https://github.com/toptal/picasso/blob/08837cfe5754e60e84928e65aef626407c8e90d4/packages/picasso/src/PromptModal/test.tsx#L55

...but I'm not sure, because some of these tests are obsolete and should be reworked

2021-11-02 14:43 UTC, denieler commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +const displayName = 'PromptModal'
we should not set the value of `data-testId`, only the opportunity to set it from the outside of the component through props

2021-11-02 14:44 UTC, denieler requested changes
we should not have hardcoded data-testids

2021-11-02 14:49 UTC, dmaklygin1 commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +        <Modal.Title data-testid={`${displayName}-title`}>{title}</Modal.Title>
@denieler is right: we do not know where exactly this component will be used, so if someone will place thhis component twice with a different `data-testid` prop — anyway it will be rendered the same `data-testid` for both instances.
However, some internal logic is valuable, sometimes: I'm talking about buttons, links, you name it. And it would be great to have access to such internal elements outside of a component.

2021-11-02 14:52 UTC, dmaklygin1 commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +        <Modal.Title data-testid={`${displayName}-title`}>{title}</Modal.Title>
so, at least, let's make a `data-testid` of `Modal.Title` depended of root `data-testid`

2021-11-02 14:55 UTC, vshyrokov commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +        <Modal.Title data-testid={`${displayName}-title`}>{title}</Modal.Title>
I have updated the code already

2021-11-02 15:26 UTC, denieler commented on packages/picasso/src/PromptModal/PromptModal.tsx
> +      )}
for such inner components we have this way of solving them - https://github.com/toptal/picasso/blob/8fc36971759d289331168353a29a11f2a438b0fd/packages/picasso/src/ApplicationUpdateNotification/ApplicationUpdateNotification.tsx#L21

@vshyrokov

2021-11-03 07:51 UTC, denieler approved these changes

2021-11-03 09:05 UTC, dmaklygin1 approved these changes

2021-11-03 09:30 UTC, merged