feat(icon): add dialpad16 icon
toptal/picasso pull request #2211
Opened 2021-11-05 18:44 UTC by yvniTop

[CT-2094]

### Description

Added Dialpad16 icon.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | ![___](https://content.screencast.com/users/YoavNino/folders/Default/media/479d85a3-97db-428a-b36e-a3bb79156d72/Screen%20Shot%202021-11-05%20at%2015.41.32.png) |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-11-08 07:10 UTC, dmaklygin1 approved these changes

2021-11-09 09:00 UTC, OleksandrNechai commented on packages/picasso/src/Icon/Dialpad16.tsx
> +import React, { forwardRef, Ref } from 'react'
Hey! Thanks for your contribution!
I don't see this icon in BASE documentation. https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/files/2fbda9fd-63f3-42e7-a9a8-135a6562ac01?s=dial

We either need designers to add it or this icon should go to the respective project as project-specific and not useful for other Picasso users.

2021-11-09 09:00 UTC, OleksandrNechai requested changes
Icon seems to be missing in BASE docs

2021-11-09 12:42 UTC, yvniTop commented on packages/picasso/src/Icon/Dialpad16.tsx
> +import React, { forwardRef, Ref } from 'react'
Hey @OleksandrNechai , isn't it that one? https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/93003c4321691ec9a25851a46b6bc247f88aa2c6/files/2fbda9fd-63f3-42e7-a9a8-135a6562ac01/layers/00EEBF49-F0F0-454C-B616-F744B8796629?mode=build&selected=158798760-83BB22BF-61F3-45B9-A3B1-A6CA9E07FA22

2021-11-09 13:35 UTC, TomasSlama commented on packages/picasso/src/Icon/Dialpad16.tsx
> +import React, { forwardRef, Ref } from 'react'
![image](https://user-images.githubusercontent.com/6830426/140933491-56e21a35-a108-4375-9abb-4ad04698836d.png)
yep it is there

2021-11-09 13:49 UTC, OleksandrNechai approved these changes

2021-11-09 15:24 UTC, merged