refactor: [FX-2205] Remove hardcoded data testid values
toptal/picasso pull request #2226
Opened 2021-11-12 07:43 UTC by LashaJini

[FX-2205](https://toptal-core.atlassian.net/browse/FX-2205)

### Description

- Replace hardcoded data testid values with dynamic ones

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

2021-11-12 07:48 UTC, LashaJini commented on packages/picasso/src/Input/test.tsx
> +  return render(<Input data-testid='input' testIds={testIds} {...props} />)
I've noticed other components have `data-testid='LowerCaseComponentName'` in tests, so I've also added for `Input` as well, and of course I've updated unit tests because of that.

2021-11-12 08:17 UTC, OleksandrNechai commented on packages/picasso/src/Menu/Menu.tsx
> -            <MenuItem key='back' data-testid='menu-back' onClick={onBackClick}>
I wonder, why `cypress/component/Menu.spec.tsx` still depends on this id and does not crash? :thinking:

2021-11-12 08:25 UTC, OleksandrNechai submitted a review, later dismissed
LGTM :+1: 
I reject for now because I would like you to double-check references to deleted ids in our tests. Also, search fo these deleted ids throughout TT repos to make sure that if others use them they have a way to fix their tests (proper `testIds` props are added.)

2021-11-12 08:25 UTC, OleksandrNechai commented on packages/picasso/src/OutlinedInput/OutlinedInput.tsx
> +  testId = 'reset-adornment'
What is this default for? Can we remove it as well? To me no hardcoded testids means no hardocded testids :smile:

2021-11-12 08:25 UTC, OleksandrNechai commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> -      <Paper data-testid='tooltip-content'>
IDK. when I search for `tooltip-content` I find a lot of instances referring to this id. How all these tests are not failing? :thinking:

2021-11-12 08:28 UTC, LashaJini commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> -      <Paper data-testid='tooltip-content'>
There is also another one in `packages/picasso-charts/src/BarChart/BarChart.tsx`.

2021-11-12 08:29 UTC, LashaJini commented on packages/picasso/src/Menu/Menu.tsx
> -            <MenuItem key='back' data-testid='menu-back' onClick={onBackClick}>
It crashes and I am currently looking at it.

2021-11-12 08:30 UTC, LashaJini commented on packages/picasso/src/OutlinedInput/OutlinedInput.tsx
> +  testId = 'reset-adornment'
Ok, I will remove it. With default value I've skipped refactoring of other ones :smile:.

2021-11-12 08:33 UTC, dmaklygin1 commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  }
what do you think about input, I guess it's usable to have data-testid is assigned to Input as well.

2021-11-12 08:41 UTC, LashaJini commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  }
Sorry, could you clarify it, please.

You mean this:

```jsx
      <Container inline={width !== 'full'} ref={inputWrapperRef}>
        <Input
          {...inputProps}
          ref={inputRef}
          onKeyDown={handleInputKeydown}
          onClick={handleFocusOrClick}
          onFocus={handleFocusOrClick}
          onBlur={handleBlur}
          value={inputValue}
          onChange={handleInputChange}
          size={size}
          startAdornment={startAdornment}
          width={width}
          testIds={testIds} // here?
        />
      </Container>
```

2021-11-12 08:45 UTC, dmaklygin1 reviewed
I also think this task is a little bit more than just remove static data-testids. It's more about realizing which exactly internal elements are really needed outside of a Component to properly cover this component with tests: integration or e2e.
So, it means, better to try covering these components with cypress tests to determine which internal elements are really affected and vital for the component's life cycle.

2021-11-12 08:45 UTC, dmaklygin1 commented on packages/picasso/src/Accordion/Accordion.tsx
> +        <EmptyAccordionSummary testId={testIds?.emptyAccordionSummary} />
do we also need to have `data-testid` assigned on `AccordionSummary` ?

2021-11-12 08:45 UTC, dmaklygin1 commented on packages/picasso/src/Autocomplete/Autocomplete.tsx
> +        testId={testIds?.loadingAdornment}
please take a look on https://github.com/toptal/picasso/pull/2226/files#diff-1c2f594fc7c0f3f0bd497380f0dfd753b54af7c75802b2530406a161da9d8499R209
not sure whether it's valid data-testid or not. The name is different.

2021-11-12 08:45 UTC, dmaklygin1 commented on packages/picasso/src/Autocomplete/Autocomplete.tsx
> +        testId={testIds?.loadingAdornment}
Btw, to test Autocomplete component, it would be useful to have `Input` (https://github.com/toptal/picasso/pull/2226/files#diff-1c2f594fc7c0f3f0bd497380f0dfd753b54af7c75802b2530406a161da9d8499R284) assignable for `data-testid`

2021-11-12 08:45 UTC, dmaklygin1 commented on packages/picasso/src/Autocomplete/test.tsx
> +      const loader = getByTestId(testIds.loadingAdornment)
here, in this test, we assign `data-test` directly to Autocomplete (https://github.com/toptal/picasso/pull/2226/files#diff-b004d3c5d8bef3d92e7b0c51340021cd70c126168436ae0e0ff0292486a9ed15R34)
and it automatically is assigned to Input.
Actually, it's not consistent if we want to have a single prop `testIds` for all internal elements. wdyt?

2021-11-12 08:53 UTC, LashaJini commented on packages/picasso/src/Accordion/Accordion.tsx
> +        <EmptyAccordionSummary testId={testIds?.emptyAccordionSummary} />
I am not sure what do you mean by that. `AccordionSummary` did not have any `data-testid`, only `EmptyAccordionSummary` had. Can you clarify please.

2021-11-12 09:16 UTC, dmaklygin1 commented on packages/picasso/src/Accordion/Accordion.tsx
> +        <EmptyAccordionSummary testId={testIds?.emptyAccordionSummary} />
Yeah, I mean (according to the tests), when we directly assign a `data-testid` to the `Accordion ` Component, this `data-testid` is reassigned to `AccordionSummary`. It's confusing a little bit. As soon this PR is merge, we will have a specified list of `testIds` for the `Accordion`, and to specify `data-testid` for `EmptyAccordionSummary` we have to specify `testIds.emptyAccordionSummary`, but if we want to specify `AccordionSummary`, we must assign `data-testid` directly to the `Accordion`. 

As a user I expect to have a similar attribute of `testIds`, like `testIds.accordionSummary` to specify `data-testid` for the `AccordionSummary`. I hope, it's clear now :)

2021-11-12 09:19 UTC, dmaklygin1 commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  }
yeah, they are not compatible. Currently, according to our tests, we may take `input` only by placeholder: https://github.com/toptal/picasso/pull/2226/files/2233b6c8dca37b97deba127fd4160b2fc7b0f51e#diff-95fccc0debaacb97ed10f23af045a8b6dd5bc8edb5c5518b4a49c478242cda22R53
Not sure, whether it's proper way or not. What if I want to specify a `data-testid` for an input.

2021-11-12 10:40 UTC, TomasSlama requested changes
I left some comments, that I think needs to be addressed

2021-11-12 10:40 UTC, TomasSlama commented on packages/picasso/src/Accordion/test.tsx
`accordion-summary` and `accordion-details` where do we set these? To me this indicates, that they are harcoded somewhere?

2021-11-12 10:40 UTC, TomasSlama commented on packages/picasso/src/Input/Input.tsx
> +      testId={testIds?.limit}
```suggestion
      testId={testIds?.inputAdornment}
```

2021-11-12 10:40 UTC, TomasSlama commented on packages/picasso/src/Input/test.tsx
> +  return render(<Input data-testid='input' testIds={testIds} {...props} />)
I dont like it, why you add `data-testid='input'` to all tests, when you are not using it anywhere?

Also you add `testIds` everywhere, even when you are not using them. I would set it directly in tests that are actually using it.

2021-11-12 10:40 UTC, TomasSlama commented on packages/picasso/src/InputAdornment/InputAdornment.tsx
> +  testId?: string
I'm not sure about this, do we have some rule somewhere to name this `testId`? I would expect
```suggestion
  'data-testid'?: string
```
but I might be wrong.

2021-11-12 10:40 UTC, TomasSlama commented on packages/picasso/src/Menu/Menu.tsx
> -            <MenuItem key='back' data-testid='menu-back' onClick={onBackClick}>
We should definitly allow users to set their own test id here

2021-11-12 10:40 UTC, TomasSlama commented on packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
> -      <Paper data-testid='tooltip-content'>
and other projects needs to have opportunity to set this test id

2021-11-18 06:45 UTC, LashaJini commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +    calendar?: string
But `Input` didn't have any `testIds` set in `DatePicker`.

2021-11-18 07:09 UTC, LashaJini commented on packages/picasso/src/Accordion/test.tsx
But according to I shouldn't remove from `text.tsx` files. 

![screenshot](https://user-images.githubusercontent.com/72510037/141429312-b87a89bc-cb6e-4f89-b988-5830e408eb9f.png)

But I will wait for your confirmation.

2021-11-18 09:46 UTC, denieler commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  testIds?: InputProps['testIds'] & {
why not to add just
```
{
  input?: string
  calendar?: string
}
```
? 😃

2021-11-18 09:49 UTC, denieler commented on packages/picasso/src/Autocomplete/Autocomplete.tsx
> +  testIds?: InputProps['testIds'] & {
same here 😃

2021-11-18 09:51 UTC, denieler commented on packages/picasso/src/Input/test.tsx
> +    const { container } = renderInput({ icon: <Search16 /> })
idk, I personally like more JSX syntax used. It gives me more understanding what test renders

2021-11-18 09:52 UTC, denieler commented on packages/picasso/src/PageAutocomplete/test.tsx
> +      testIds: { resetButton: testIds.resetButton }
why not inline here the value?

2021-11-18 09:53 UTC, denieler commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +          data-testid={testIds?.input}
it feels to me that we should use `testIds` or `data-testid` on the component, but never both at the same time. WDYT?

2021-11-18 12:21 UTC, LashaJini commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  testIds?: InputProps['testIds'] & {
Because `DatePicker`'s `testIds` is not compatible with `Input`'s `testIds`

2021-11-18 12:22 UTC, LashaJini commented on packages/picasso/src/Autocomplete/Autocomplete.tsx
> +  testIds?: InputProps['testIds'] & {
same https://github.com/toptal/picasso/pull/2226#discussion_r752188852 :smile:

2021-11-18 12:23 UTC, LashaJini commented on packages/picasso/src/Input/test.tsx
> +    const { container } = renderInput({ icon: <Search16 /> })
I am not sure about this one. I saw in other tests where using same approach. If you would I will refactor it.

2021-11-18 12:25 UTC, LashaJini commented on packages/picasso/src/PageAutocomplete/test.tsx
> +      testIds: { resetButton: testIds.resetButton }
Can you clarify this, please?

2021-11-18 12:27 UTC, LashaJini commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +          data-testid={testIds?.input}
I did this refactoring according to https://github.com/toptal/picasso/pull/2226#discussion_r748094092

2021-11-19 12:47 UTC, denieler commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +  testIds?: InputProps['testIds'] & {
but it will be just a different set of testIds, so "duck typing"

2021-11-22 08:19 UTC, denieler commented on packages/picasso/src/Input/test.tsx
> +    const { container } = renderInput({ icon: <Search16 /> })
it's up to you, maybe other guys @toptal/frontend-experience-eng can share your opinions

2021-11-22 08:20 UTC, denieler commented on packages/picasso/src/PageAutocomplete/test.tsx
> +      testIds: { resetButton: testIds.resetButton }
I mean `testIds` object is used only once here in this file, why not make it simply
```
testIds: { resetButton: 'reset-button-test-id' }
```
?

2021-11-22 08:28 UTC, denieler commented on packages/picasso-lab/src/DatePicker/DatePicker.tsx
> +          data-testid={testIds?.input}
I see, so the purpose was to add `data-testid` to the input itself, which makes sense to me. But I see issue with the implementation 😃 `Input` looks like need also 2 other `data-testids`: `inputAdornment` and `resetButton`, so 3 `data-testids` in total. To implement that I would suggest to use only `testIds`:

```
testIds?: {
  input?: string
  inputAdornment?: string
  resetButton?: string
}
```

2021-11-22 13:16 UTC, LashaJini commented on packages/picasso/src/PageAutocomplete/test.tsx
> +      testIds: { resetButton: testIds.resetButton }
For future reference. Yes, it's used once, but what if someone adds new test that would use `resetButton`? In that case, he/she won't have to modify code in two places.

2021-11-22 13:51 UTC, dmaklygin1 approved these changes

2021-11-23 08:08 UTC, TomasSlama reviewed
I have left one comment. And I don't see changeset file here, we should prepare one.

Could you abstract the changes, where we removed hardcoded 'data-testid' and write it in changelog?, since it is breaking change for lot of project, we should try to make it as easy as possible for everyone to find what they will have to do in their projects.

2021-11-23 08:08 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/Autocomplete.tsx
> +  testIds?: InputProps['testIds'] & {
we are missing here the most important part, we want to be able to test the Input, but in `InputProps[testIds]` is only `resetButton` and `adornment`, but where is the Input  itself?

2021-11-24 08:09 UTC, TomasSlama approved these changes

2021-11-24 08:10 UTC, merged