fix(link): [FX-2298] remove fontSize
toptal/picasso pull request #2280
Opened 2021-11-23 14:07 UTC by vshyrokov

[FX-2298](https://toptal-core.atlassian.net/browse/FX-2298)

### Description

Removed fontSize prop from the Link.

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-11-23 15:28 UTC, TomasSlama approved these changes
LGTM 👍, should we create alpha package and test it on SP? If it solves all the problems for you?

2021-11-23 15:30 UTC, OndrejTuma approved these changes
Code looks good 👍

2021-11-23 15:35 UTC, vshyrokov commented
@TomasSlama it would be great to do that, could you help me with creating an alpha package?

2021-11-23 15:39 UTC, TomasSlama commented
@toptal-bot run package:alpha-release

2021-11-23 15:39 UTC, TomasSlama commented
@vshyrokov ☝️

2021-11-23 15:42 UTC, TomasSlama reviewed
I have checked that Happo tests, and I don't think, that these changes are expected.

2021-11-23 16:04 UTC, denieler commented on .changeset/dirty-months-float.md
> +Removed fontSize prop from the Link
can we please also explain to users of the Link how to deal if they use fontSize prop right now?

```
BREAKING CHANGE:
...
```

2021-11-23 16:04 UTC, denieler commented on .changeset/dirty-months-float.md
> +'@toptal/picasso': patch
```suggestion
'@toptal/picasso': major
```

2021-11-23 16:05 UTC, vshyrokov commented on .changeset/dirty-months-float.md
> +Removed fontSize prop from the Link
Hey @denieler, sure! I'll update as a major version

2021-11-23 16:07 UTC, denieler commented
by visual tests it looks like that all links started to inherit the font size of the container where they are defined, wouldn't this break many and many product pages layouts? do we really want to have such a harsh breaking change?

2021-11-23 16:09 UTC, vshyrokov commented
@denieler, as I see, it was working like this before, update was added in the v12 and it seems, it works as expected now.

@TomasSlama, could you confirm?

2021-11-23 16:09 UTC, denieler commented
also looks like many unrelated to Link components change their look, for example, `Notification` or `PageBanner`

<img width="1329" alt="Screenshot 2021-11-23 at 18 09 22" src="https://user-images.githubusercontent.com/2836281/143060823-6a580a58-e4e2-4870-b136-d4c471f31bc7.png">

which shouldn't happen

2021-11-23 16:10 UTC, denieler requested changes
other components visual test failing, not related to Link

2021-11-23 16:23 UTC, vshyrokov commented
@denieler 

actually, it's correct now

https://app.abstract.com/share/aa04519f-5383-4555-9574-521d7afec32d?collectionLayerId=363d365b-d0db-4db2-a7d3-08c83c092930&mode=design&present=true - fontSize is 13px

same to Body Small link

https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=218%3A4060

12px, we in UserBadge a Typography 

https://github.com/toptal/picasso/blob/49d75d543244a197e0b0127be8a3e84989f31242/packages/picasso/src/UserBadge/story/Title.example.tsx#L52

2021-11-23 16:40 UTC, denieler commented
@vshyrokov can't agree with you:

Font size of the Action (Link) is `14px`
<img width="1179" alt="Screenshot 2021-11-23 at 18 39 23" src="https://user-images.githubusercontent.com/2836281/143066238-c2d5c738-bebd-4f3a-b0fe-108655a3dda7.png">

master Picasso - `14px`
<img width="528" alt="Screenshot 2021-11-23 at 18 39 15" src="https://user-images.githubusercontent.com/2836281/143066228-1c0b59b5-722e-47e2-bad6-675182d3b26d.png">

2021-11-23 16:46 UTC, vshyrokov commented
@denieler we have one more example there
![image](https://user-images.githubusercontent.com/55978500/143067232-93354f81-cc1c-4621-a6d7-6f1d461400c7.png)


https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/0707c36cbb23914c365419f1083c142fcd57f269/files/e1d69403-65c3-4a24-927e-5d5f06eaff22/layers/18C44FCF-A16D-4A25-A48D-5267EA182970?collectionId=c39c2374-aeec-40e3-bfb4-18878dde3a4d&collectionLayerId=363d365b-d0db-4db2-a7d3-08c83c092930&mode=build&selected=root-E5B3DFB3-559A-4047-A5F7-0C8ADB30D5E0

2021-11-23 20:22 UTC, denieler approved these changes
Yep, my bad, thank you @vshyrokov, I've checked all the visual screenshots updated and it looks like all of them are according to BASE (except some I couldn't find in Abstract 🤷‍♂️ )

2021-11-23 21:49 UTC, vshyrokov commented
@toptal-bot run package:alpha-release

2021-11-24 10:49 UTC, TomasSlama approved these changes

2021-11-24 13:00 UTC, merged