refactor: [FX-2146] Make List base 2 compliant
toptal/picasso pull request #2285
Opened 2021-11-25 10:43 UTC by LashaJini

[FX-2146](https://toptal-core.atlassian.net/browse/FX-2146)

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-11-26 08:01 UTC, LashaJini commented on packages/picasso/src/List/styles.ts
> +      '& > :last-child': {
We don't want margin on last child list item.

2021-11-26 09:56 UTC, OndrejTuma commented on packages/picasso/src/List/List.tsx
> +        className={cx(classes.root, classes.ul)}
Maybe add also `props.className` here? In case someone used it like this before

2021-11-26 12:06 UTC, dmaklygin1 commented on packages/picasso/src/List/List.tsx
> +        className={cx(classes.root, classes.ul)}
wdyt, @LashaJini if we use the same names for classnames as for variants. Let's see an example: https://github.com/toptal/picasso/blob/b0a00a0a8d3d92fcd7930a4a0bf0fdc09103ac6c/packages/picasso/src/Button/Button.tsx#L161

2021-11-29 08:51 UTC, TomasSlama requested changes

2021-11-29 08:51 UTC, TomasSlama commented on packages/picasso/src/List/test.tsx
> +    expect(container).toMatchSnapshot()
If I'm not mistaken, we should use snapshots only when we reuse MUI component, for our own components we should avoid snapshots

2021-11-29 08:51 UTC, TomasSlama commented on packages/picasso/src/ListItem/ListItem.tsx
> +          className={cx(classes.iconContainer, {
why not just `classes[variant]`? it will end up having one classname. In your approach you would end up with two classnames when `variant === 'ordered'`

2021-11-29 08:51 UTC, TomasSlama commented on packages/picasso/src/List/styles.ts
> +      height: '1.375em',
this is not correct, why having static height on whole list?, it breaks `list-custom-snap.png`

2021-11-30 11:44 UTC, OndrejTuma commented on packages/picasso/src/List/List.tsx
> +  )
why not use jsx here? 🤔

2021-11-30 12:47 UTC, TomasSlama reviewed
changeset is missing, added some more questions

2021-11-30 12:47 UTC, TomasSlama commented on packages/picasso/src/List/styles.ts
> +      color: palette.grey.dark
```suggestion
      color: palette.text
```

It is the same color, but more specific

2021-11-30 12:47 UTC, TomasSlama commented on packages/picasso/src/ListItem/ListItem.tsx
> +          className={cx(classes.iconContainer, {
? why resolve?

2021-12-01 13:29 UTC, LashaJini commented
> What is the benefit of using `createElement`? :thinking:

The only way to use jsx was with self-closed tag: `<ListTag {...}/>`, and but `List` should have child elements, when I used `<ListTag {...}>{listItems}</ListTag>` it threw [ts(2322)](https://stackoverflow.com/questions/63252161/ts2322-property-children-does-not-exist-on-type-intrinsic-attributes-and-prop) error about `intrinsic` attributes. (Same thing Ondra was wondering and I've answered him, but couldn't reference that comment, so I just copy pasted here)

2021-12-03 06:57 UTC, TomasSlama approved these changes
LGTM 👍, only please remove the old image snapshots from `List/__image_snapshots__/`

2021-12-03 07:42 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
maybe we should make a slightly different format?

```
# List

- Unordered list item's bullet has primary text color, which is dark gray
...
```

2021-12-03 07:43 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +'@toptal/picasso': patch
it's not a bug fix, it's an intentional change of the design, I think it should be treated as a feature, so we should bump minor version here

2021-12-03 07:46 UTC, denieler commented on packages/picasso/src/List/List.tsx
> +    }
why do we need this check?

2021-12-03 07:47 UTC, denieler commented on packages/picasso/src/List/List.tsx
> +    <ListTag
nice solution with `ListTag` 👍

2021-12-03 07:50 UTC, denieler commented on packages/picasso/src/List/styles.ts
> +      }
to be this style looks wrong because each our component should be self-sufficient, its state and look should be defined only by its props. But in this case, the look of ListItem in fact defined by the parent component.

2021-12-03 07:52 UTC, denieler commented on packages/picasso/src/List/test.tsx
> +    expect(list.children).toHaveLength(0)
what exactly we are trying to test here? at least I see that the description of the test `enders unordered list` does not correspond to the test expectations

2021-12-03 07:54 UTC, denieler commented on packages/picasso/src/List/List.tsx
> +  const ListTag = Tags[variant]
this variable probably can be moved out from the iteration (`map`), because all list items would have the same tag

2021-12-03 08:04 UTC, LashaJini commented on packages/picasso/src/List/List.tsx
> +    <ListTag
It was Tomas idea.

2021-12-03 08:05 UTC, LashaJini commented on packages/picasso/src/List/styles.ts
> +      }
Yes, kinda, but only parent `List` knows which element is last, thus we can't have this styling on child `ListItem`.

2021-12-03 08:07 UTC, denieler commented on packages/picasso/src/List/styles.ts
> +      }
but `List` can pass a "flag" to the last list item to show that it is last, for example (it's only one of the solutions)

2021-12-03 08:08 UTC, LashaJini commented on packages/picasso/src/List/List.tsx
> +  const ListTag = Tags[variant]
But `ListTag` is outside `map` already. Am I missing something?

2021-12-03 08:11 UTC, LashaJini commented on packages/picasso/src/List/List.tsx
> +    }
To avoid `tsserver 2769: no overload matches this call`.

2021-12-03 08:14 UTC, denieler commented on packages/picasso/src/List/List.tsx
> +    }
stupid typescript 😃

2021-12-03 08:15 UTC, denieler commented on packages/picasso/src/List/List.tsx
> +  const ListTag = Tags[variant]
sorry, probably my bad 🙇‍♂️

2021-12-03 08:15 UTC, LashaJini commented on packages/picasso/src/List/styles.ts
> +      }
I will refactor it.

2021-12-03 09:25 UTC, LashaJini commented on packages/picasso/src/List/utils/generateListItems.tsx
> +const generateListItems = (total: number, listItemProps?: any) =>
I have to use this function in two places, 1 in unit test and 1 in cypress test.

2021-12-03 09:43 UTC, LashaJini commented on packages/picasso/src/List/test.tsx
> +    expect(list.children).toHaveLength(0)
@denieler refactored!

2021-12-03 09:44 UTC, LashaJini commented on packages/picasso/src/List/styles.ts
> +      }
@denieler refactored!

2021-12-03 09:44 UTC, LashaJini commented on .changeset/tidy-sloths-invite.md
> +'@toptal/picasso': patch
@denieler done!

2021-12-03 09:44 UTC, LashaJini commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
@denieler done!

2021-12-03 10:19 UTC, LashaJini commented on cypress/component/List.spec.tsx
> +const generateListItems = (total: number, listItemProps?: any) =>
I don't like re-defining same function in two places, but can't figure out another solution. Any suggestions? The other one is in `picasso/src/List/utils/generateListItems.tsx`

2021-12-03 10:22 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +'@toptal/picasso-lab': patch
if we have 2 different bumps for 2 packages it means each of them need to have its own changelog. So I would suggest to have 1 changeset file for picasso with its changes and 1 changeset file for picass-lab

2021-12-03 10:29 UTC, denieler commented on cypress/component/List.spec.tsx
> +const generateListItems = (total: number, listItemProps?: any) =>
it's ok to duplicate such a tiny function to keep modules independency

2021-12-03 10:30 UTC, denieler commented on packages/picasso/src/List/styles.ts
> +    ul: {
sorry, I'm not sure where this class is used?

2021-12-03 10:34 UTC, denieler approved these changes

2021-12-03 10:37 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
@LashaJini sorry, I haven't seen the change in the changeset log

2021-12-03 10:53 UTC, LashaJini commented on packages/picasso/src/List/styles.ts
> +    ul: {
It should be `unordered`, thanks.

2021-12-03 11:21 UTC, LashaJini commented on .changeset/tidy-sloths-invite.md
> +'@toptal/picasso-lab': patch
@denieler I've separated them.

2021-12-03 11:43 UTC, denieler commented on .changeset/short-onions-cheer.md
> +Update image snapshots
If this is the only change in this package - it looks like it doesn't affect our users. But in fact `picasso-lab` depends on `picasso` package, so the real reason why we need to bump a version is that `picasso` package version bump, so I would share this in a changelog

2021-12-03 11:44 UTC, denieler commented on packages/picasso/src/ListItem/styles.ts
> +    isLastElement: {
```suggestion
    lastElement: {
```

2021-12-03 11:45 UTC, denieler commented on packages/picasso/src/List/test.tsx
> +    expect(list.tagName).toBe('UL')
why not to use snapshots here?

2021-12-03 11:45 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
@LashaJini this is still valid ☝️

2021-12-03 11:46 UTC, denieler commented
https://github.com/toptal/picasso/pull/2285#discussion_r761867578

2021-12-03 11:49 UTC, OndrejTuma approved these changes

2021-12-03 11:54 UTC, LashaJini commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
@denieler Can you suggest something please? 

I thought this was good enough.

> Unordered list item's bullet has dark gray `#455065` color.

2021-12-03 12:03 UTC, LashaJini commented on packages/picasso/src/ListItem/styles.ts
> +    isLastElement: {
Refactored!

2021-12-03 12:04 UTC, LashaJini commented on packages/picasso/src/List/test.tsx
> +    expect(list.tagName).toBe('UL')
Not sure, thb. I didn't want to add additional snapshots, because I've already did cypress tests. @denieler Should I instead replace them with snapshot matches?

2021-12-03 12:14 UTC, LashaJini commented on .changeset/short-onions-cheer.md
> +Update image snapshots
Not sure about this. Can you clarify please?

2021-12-03 12:45 UTC, denieler commented on packages/picasso/src/List/test.tsx
> +    expect(list.tagName).toBe('UL')
no, I think they are needed for different purposes. So I don't see a problem having both at the same time 👍

2021-12-03 12:46 UTC, denieler commented on .changeset/short-onions-cheer.md
> +Update image snapshots
I would write in changeset only this:

```
Bump of the @toptal/package
```

Because all the rest for picasso-lab our users don't care

2021-12-03 12:47 UTC, denieler commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
yeah, I would just add `### List` heading before the changelog. Because it might not be clear in changelog for which component are all those changes

2021-12-03 14:30 UTC, LashaJini commented on .changeset/tidy-sloths-invite.md
> +- Unordered list item's bullet has primary text color, which is dark gray
@denieler done!

2021-12-06 09:30 UTC, denieler commented on .changeset/neat-glasses-compete.md
> +`packages/picasso/src/List` and `packages/picasso/src/ListItem`
I would maybe leave a link to https://picasso.toptal.net/?path=/story/components-list--list instead and call `List.Item` (as in docs) instead of `ListItem` (internal name)

2021-12-06 09:30 UTC, denieler approved these changes

2021-12-06 09:53 UTC, merged