fix(Select): fix disabled and selected option is highlighted initially
toptal/picasso pull request #2294
Opened 2021-11-30 04:46 UTC by teimurjan

[FX-2322](https://toptal-core.atlassian.net/browse/FX-2322)

### Description

Fixed the bug when a disabled & selected option is highlighted initially. Added a test to prevent this bug in the future.

### How to test

1. Go to Select story in the temploy.
2. Make the first option selected & disabled (with the built-in editor).
3. Open the Select.
4. Be sure that the first option is selected, disabled & not highlighted.
5. Be sure that the second option is highlighted.

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-11-30 07:06 UTC, OleksandrNechai commented
Not sure if this is related, but we have yet another bug. I think we should not have a few highlighted items at the same time (one highlighted by mouse and another by keyboard)
![Peek 2021-11-30 09-04](https://user-images.githubusercontent.com/14070311/144001329-55924ab1-416a-44e8-879a-00c76db6931d.gif)
.

2021-11-30 08:00 UTC, OleksandrNechai requested changes
I had very hard time understanding the code. Improvements needed. Also tehre are some other bugs.

2021-11-30 08:05 UTC, OleksandrNechai commented on packages/picasso/src/Select/hooks/use-highlighted-index/use-highlighted-index.ts
> +      : nonDisabledIndicies[0]
I think this is not completely correct logic. The code disables the logic of having the selected option highlighted. If there are few selected options, one disabled, the highlight goes to non-selected options:
![image](https://user-images.githubusercontent.com/14070311/144008775-05ac769c-b124-4ef0-8c48-f042eb75e513.png)

2021-11-30 09:10 UTC, vshyrokov reviewed
Left comments, related to the mocking

2021-11-30 09:10 UTC, vshyrokov commented on packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
> +            isSelected: jest.fn().mockReturnValue(true),
could we just pass `() => true` instead of `jest.fn().mockReturnValue(true)`?

2021-11-30 09:10 UTC, vshyrokov commented on packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
> +            display: jest.fn()
same here, we could just use `display: () => ''` nothing is mocked in the test, related to the display function, it's not necessary to use jest.fn() in this case, because it confuse a reviewer, I expect, that something would be done, related to the display.

2021-11-30 09:42 UTC, teimurjan commented on packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
> +            display: jest.fn()
It's about consistency. I can do differently in this place and it will confuse the reviewers as well (because some functions are jest mocks and some are not). I'd keep it as it is before we decide to refactor. I'd not refactor the whole test file in a fix PR.

2021-12-01 05:43 UTC, LashaJini approved these changes

2021-12-01 06:09 UTC, merged