fix(Typography): default size inherits line-height
toptal/picasso pull request #2295
Opened 2021-11-30 09:55 UTC by OndrejTuma

[FX-2313]

### Description

Typography in its default setting should inherit parent's line-height.

### How to test

There is a cypress test written for this case, but generally put `Typography` inside `Table` and it should inherit font-size and line-height

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/22159416/144025116-6d2b03b5-4268-43df-a108-e9ed17a09463.png) | 
![image](https://user-images.githubusercontent.com/22159416/144025288-a8b036a3-e5b8-4895-a8d6-adc4d7fa5519.png)
 |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-11-30 12:55 UTC, TomasSlama commented on packages/picasso/src/Typography/styles.ts
> +      lineHeight: 'inherit',
this seems to be pretty scary to me :)

2021-12-01 09:48 UTC, denieler commented on packages/picasso/src/Typography/styles.ts
> +    bodyXxsmall: {
nit: I'm not sure, but it looks like this will be nicer:
```suggestion
    bodyXXsmall: {
```

2021-12-01 09:49 UTC, denieler commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
I think we need to discuss naming with BASE designers because `small` size means `12px` and now we have inconsistency between our API and BASE

<img width="897" alt="Screenshot 2021-12-01 at 11 48 44" src="https://user-images.githubusercontent.com/2836281/144211663-526ade44-2f80-486d-9767-63dbd204f3db.png">

2021-12-01 09:50 UTC, denieler requested changes
we need to find a better name for Typography variant or change a BASE name for this variant

2021-12-01 09:56 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
I talked to Milos and it was his idea. I should probably ask him to prepare changes to BASE once we release this one

2021-12-01 10:00 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +    bodyXxsmall: {
I agree its more readable, but these classnames are composed from props `variant` and `size` in camel case - and correct size type is `xxsmall`

2021-12-01 10:42 UTC, denieler commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
no, @OndrejTuma he even should change in BASE before this change will happen in Picasso 🙇‍♂️ (or at least at the same time)

2021-12-01 11:45 UTC, OndrejTuma commented
> we need to find a better name for Typography variant or change a BASE name for this variant

Its done: https://toptal-core.atlassian.net/browse/FX-2326

2021-12-01 11:46 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
OK, so Milos was quite fast and [did it already](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/e57f5ed8efdd4351cfb8cce8f524e88a33894ba6/files/e67e971a-851c-4375-9821-686c7d4c57e6/layers/BA5476AB-47D9-414D-9FCA-59021BC47C92?mode=design&sha=e57f5ed8efdd4351cfb8cce8f524e88a33894ba6)
cc @denieler

2021-12-01 14:12 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
Good to know! I'll keep that in mind 👍

2021-12-01 14:14 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +      lineHeight: 'inherit',
We discussed to keep it like this. But I think there will be some feedback once it's released.
That can be scary :)
Do you have some ideas how to ensure smooth transition @TomasSlama ?

2021-12-02 11:49 UTC, TomasSlama commented on packages/picasso/src/TableCell/TableCell.tsx
> +    const contentWeight = isHead || isFooter ? 'semibold' : undefined
```suggestion
    const fontSettingsBySection = {
      [TableSection.HEAD]: {
        color: 'dark-grey',
        size: 'xsmall',
        weight: 'semibold'
      },
      [TableSection.Footer]: {
        color: 'black',
        size: 'small',
        weight: 'semibold'
      },
      body: {
        color: 'dark-grey',
        size: 'small'
      }
    }
    const { color, size, weight } = fontSettingsBySection[tableSection || 'body]
```

What do you think? I feel little bit lost in all those conditions at first look. This constant can be moved out of component.

2021-12-02 12:32 UTC, OndrejTuma commented on packages/picasso/src/TableCell/TableCell.tsx
> +    const contentWeight = isHead || isFooter ? 'semibold' : undefined
I like it! 👍  🙇  thanks

2021-12-02 12:55 UTC, OndrejTuma commented on packages/picasso/src/TableCell/TableCell.tsx
> +    const contentWeight = isHead || isFooter ? 'semibold' : undefined
It's done @TomasSlama feel free to check it out :-)

2021-12-02 13:42 UTC, denieler commented on packages/picasso/src/Typography/styles.ts
> +    bodyXsmall: {
amazing 👍 🙇

2021-12-02 14:05 UTC, denieler reviewed
ready to approve, but we need changeset and good migration guide there

2021-12-02 14:05 UTC, denieler commented on packages/picasso/src/TableCell/TableCell.tsx
> +        <Typography as='div' {...getTypographySettings(tableSection)}>
we need to mention this change of `display` for chldren content from `table-cell` to `block` in a migration guide

2021-12-02 14:05 UTC, denieler commented on packages/picasso/src/Typography/styles.ts
> +      lineHeight: 'inherit',
we should do that, be strong 💪 😄 and write good migration guides

2021-12-03 12:25 UTC, OndrejTuma commented on packages/picasso/src/Tab/Tab.tsx
> +    label: propsLabel,
Yeah thats more readable 🎉

2021-12-03 12:26 UTC, OndrejTuma commented on packages/picasso/src/TableCell/TableCell.tsx
> +        <Typography as='div' {...getTypographySettings(tableSection)}>
Right.. hope no one relies on that specific styling props 🤔

2021-12-05 21:56 UTC, OndrejTuma commented on cypress/component/Table.spec.tsx
> +    cy.get('table > tbody > tr > td:last-child > div > button:last-child')
I better fixed it #supreme-experience

2021-12-14 10:48 UTC, OndrejTuma commented on packages/picasso/src/Typography/styles.ts
> +      lineHeight: 'inherit',
Resolving this, as lineHeight is not changed

2021-12-14 12:51 UTC, TomasSlama reviewed
GJ, I left some comments, overall it looks good to me, I was thinking if we can solve the `inherit` issue differently, but I didn't come up with another solution. Since Daniel will be on vacation for another 10 days, I think you can remove his review and ask for another one, so you are not blocked

2021-12-14 12:51 UTC, TomasSlama commented on packages/picasso-lab/package.json
> +    "@toptal/picasso": "^17.0.0",
I think we don't need this right now, because changeset will do it automatically for us. Until it is fixed, we probably shouldn't do it by ourself, when we merge in master, picasso-lab will require picasso@17, but it will not be released at that point, so we will need to do these changes in Version Packages PR

2021-12-14 12:51 UTC, TomasSlama commented on packages/picasso/src/TableCell/styles.ts
> +  padding: '0.0625rem 0.5rem',
```suggestion
  padding: `${rem(1px) 0.5rem`,
```

when using unusual numbers in rem, we are using `rem` util function, so it is clear to everybody on first view what number it actually holds

2021-12-14 12:51 UTC, TomasSlama commented on packages/picasso/src/TableSectionHead/styles.ts
> +      marginTop: '-0.0625rem',
same as previous comment `rem('1px')`

2021-12-14 12:51 UTC, TomasSlama commented on packages/picasso/src/Tooltip/styles.ts
> +      padding: '0.125rem 0.5rem',
```suggestion
      padding: `${rem('2px') 0.5rem`,
```

2021-12-14 13:44 UTC, OndrejTuma commented on packages/picasso-lab/package.json
> +    "@toptal/picasso": "^17.0.0",
sure, I will revert it then 👍

2021-12-14 13:48 UTC, OndrejTuma commented on packages/picasso/src/TableCell/styles.ts
> +  padding: '0.0625rem 0.5rem',
got it 🙂  thank you

2021-12-14 13:51 UTC, OndrejTuma commented on packages/picasso/src/Tooltip/styles.ts
> +      padding: '0.125rem 0.5rem',
✅

2021-12-14 14:07 UTC, TomasSlama approved these changes

2021-12-14 14:22 UTC, dmaklygin1 commented on cypress/component/Table.spec.tsx
> +    cy.get(`[data-testid="expand-button-${localData[0].id}"]`)
he you use `expand-button` as a testId, however, line below, you name the selection as `collapseButton` :)

2021-12-14 14:29 UTC, dmaklygin1 commented on packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
> +const affectedComponents = ['Typography', 'TypographyOverflow', 'Amount']
There might be other components that are based on `Typography`, because we allow to extend our components via `styled` components. This is an example:
https://github.com/toptal/topteam-frontend/blob/e51e4c08b0be1c9aab2b9d53f69893b8bd41bd3c/src/modules/org-unit/components/SlackChannelLink/style.ts#L10

2021-12-14 14:33 UTC, dmaklygin1 commented on packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
> +export default transform
very nice! :)

2021-12-14 14:33 UTC, dmaklygin1 commented on packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
> +      })
whether we can join these two filters in a single one?

2021-12-14 14:37 UTC, dmaklygin1 commented on packages/picasso/src/Notification/__snapshots__/test.tsx.snap
> +            class="MuiTypography-root PicassoTypography-bodySmall Notification-content Notification-contentYellow MuiTypography-body1"
the test case here is useless or at least incomprehensible.
it's called `Notification renders 1`...
Here, in the snapshot, the className has been changed, but for me it's unclear why it's changed and whether it should be small or not. I would rework/remove this unclear test.

2021-12-14 14:45 UTC, dmaklygin1 commented on packages/picasso/src/TableCell/TableCell.tsx
> +        <Typography as='div' {...getTypographySettings(tableSection)}>
hm, I would think about this change. what if developer wants to override a `size` — seems to be no possible to do it. right?

2021-12-14 14:50 UTC, dmaklygin1 commented on packages/picasso/src/Tooltip/Tooltip.tsx
> +    </Typography>
👍

2021-12-14 14:51 UTC, dmaklygin1 commented on packages/picasso/src/TableSectionHead/TableSectionHead.tsx
> +        <TableSectionContext.Provider value={TableSection.HEAD}>
Could you please explain, what's the goal are you pursuing by adding this additional Provider?

2021-12-14 14:56 UTC, dmaklygin1 commented on packages/picasso/src/Typography/Typography.tsx
> +  const tableSection = useContext(TableSectionContext)
oh, I insist to avoid this. `Typography` shouldn't know anything about `Table` or other components where it might be rendered.

2021-12-14 14:58 UTC, dmaklygin1 requested changes
Good work!
there are couple things we need to discuss maybe.

2021-12-15 13:56 UTC, dmaklygin1 commented on packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
> +const affectedComponents = ['Typography', 'TypographyOverflow', 'Amount']
Yeah, I think we should add this to changeset

2021-12-15 14:02 UTC, OndrejTuma commented on packages/picasso/src/Typography/Typography.tsx
> +  const tableSection = useContext(TableSectionContext)
OK so this was removed after we agreed on it in our daily ✅ 
@dmaklygin1

2021-12-16 13:51 UTC, merged