chore: [FX-2178] Remove colored container borders
toptal/picasso pull request #2308
Opened 2021-12-06 07:24 UTC by LashaJini

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-12-06 13:35 UTC, LashaJini commented on cypress/component/Container.spec.tsx
> +      colors.forEach(color => {
I am not sure if this is a good practice.

2021-12-06 13:42 UTC, OndrejTuma commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
```suggestion
            bordered && variantsWithBorder.includes(variant as string),
```
WDYT?

2021-12-06 13:45 UTC, OndrejTuma commented on cypress/component/Container.spec.tsx
> +      colors.forEach(color => {
it looks good to me 👍

2021-12-06 13:45 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
But there is only one `white` container that can actually have border. So, I think it's better like it is now.

2021-12-06 13:45 UTC, OndrejTuma approved these changes

2021-12-06 13:47 UTC, OleksandrNechai commented on cypress/component/Container.spec.tsx
> +      colors.forEach(color => {
1) No, it's probably not a good practice. Looks like we are testing implementation and I always against doing this.
2) In case we need to test few similar cases, we use
```
it.each([2,4,6])('should be even', (n) => {
    expect(n % 2).toBe(0);
});
3) This problem you are trying to test, I believe we can ensure with type system ;)
```

2021-12-06 13:49 UTC, OleksandrNechai commented on packages/picasso/src/Container/Container.tsx
> +const variantsWithoutBorder = ['red', 'green', 'yellow', 'blue', 'grey']
```suggestion
const borderlessVariants = ['red', 'green', 'yellow', 'blue', 'grey']
```

2021-12-06 13:53 UTC, OleksandrNechai commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
Can we ensure bordered can only accept `white` as a variant by type system?
Probably cleaner solution would be to add one new variant:
```
['white', 'bordered-white', 'red', 'green', 'yellow', 'blue', 'grey']
```

2021-12-06 13:56 UTC, OleksandrNechai commented on packages/picasso/src/Container/test.tsx
> +  it.each([...colors] as VariantType[])(
IMO the test is redundant. 1) Already tested with Cypress 2) If such tests needed we probably need to think how to improve API or check things with type system.

2021-12-06 13:58 UTC, OleksandrNechai requested changes
I think we could do better with API of the component. Now nothing prevents user to do
`<Container variant='red' bordered />` which probably does not make much sense :man_shrugging:

2021-12-06 14:00 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
Actually, when it is applied only for `white` container it breaks, because `variant` is optional and some of the components are not using any of colored `variants`. If I remember this also breaks a lot of tests.

2021-12-06 14:14 UTC, OleksandrNechai commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
I don't understand :)

2021-12-06 14:16 UTC, OndrejTuma commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
That was my point, its easier to see one variant that allows border than 5 that doesn't :-)
But its a nit, up to you

2021-12-06 14:19 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
My bad. It is not important, but I think I will be able to do as suggested.

2021-12-06 14:28 UTC, OleksandrNechai commented on packages/picasso/src/Container/Container.tsx
> +            bordered && !variantsWithoutBorder.includes(variant as string),
Sure! I appreciate you being candid! :) Please, bring API discussion to the team chat, see what others think, mine is only suggestion, it is not request to do exactly that :wink:

2021-12-09 07:37 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +export interface Props<V extends VariantType = VariantType>
@teimurjan :bowing_man:

2021-12-09 11:17 UTC, OleksandrNechai commented on .changeset/chilled-gifts-reply.md
> +'@toptal/picasso': minor
hm, I thought it was breaking change, why minor?

2021-12-09 11:22 UTC, OleksandrNechai commented on cypress/component/Container.spec.tsx
> +]
we also have transparent now, why not test it on darker background?
why not have also bordered tests for white and transparent?

2021-12-09 11:33 UTC, OleksandrNechai commented on packages/picasso/src/Container/Container.tsx
> +export { VariantType, BorderableType }
Sure we want to export BorderableType?

2021-12-09 11:42 UTC, OleksandrNechai approved these changes

2021-12-09 11:48 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +export { VariantType, BorderableType }
Not really tbh. I just thought maybe someone would want it in the future 🤔

2021-12-09 11:49 UTC, LashaJini commented on .changeset/chilled-gifts-reply.md
> +'@toptal/picasso': minor
I will change it to major.

2021-12-09 12:06 UTC, LashaJini commented on packages/picasso/src/Container/Container.tsx
> +export { VariantType, BorderableType }
Yeah, probably no1 will use it anyway.

2021-12-10 08:25 UTC, teimurjan commented on packages/picasso/src/utils/forward-ref.ts
> +    props: P & { ref?: React.Ref<T> }
It worked incorrectly before, and the final component returned by `forwardRef` didn't have `ref` prop.

Fixed it :)

2021-12-14 06:45 UTC, merged