[FX-2345] Extend Accordion and Modal components with TransitionProps support
toptal/picasso pull request #2315
Opened 2021-12-08 11:27 UTC by ascrazy

[FX-2345]

### Description

This adds correct `TransitionProps` prop support for Modal and Accordion components.

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-12-09 09:29 UTC, dmaklygin1 commented on packages/picasso/src/Modal/Modal.tsx
> +  TransitionProps?: TransitionProps
the only one doubt, about the capital letter of the name.

2021-12-10 07:43 UTC, OleksandrNechai commented on packages/picasso/src/Modal/Modal.tsx
> +  TransitionProps?: TransitionProps
@ascrazy we have different design philosophies. Picasso is not a MUI wrapper. It is a full-blown UI kit that just happens to be implemented ATM with MUI. We might use a different approach in the future.

And to be able to do it, we set up our own interface. For these reasons we should `transitionProps` and also we need to define our own type, not re-export TransitionProps

2021-12-10 07:48 UTC, OleksandrNechai requested changes
Please, see the comment below :point_down:

2021-12-10 08:15 UTC, OleksandrNechai commented
BTW, this PR still has no changeset generated

2021-12-10 09:36 UTC, ascrazy commented on packages/picasso/src/Modal/Modal.tsx
> +  TransitionProps?: TransitionProps
Well,

Hi @OleksandrNechai,

Ok, I'll rename the prop, though as I already mentioned that means consumers will effectively be able to use both `transitionProps` and `TransitionProps`. IMO we might need to think of a generic approach that would block that possibility.

2021-12-10 09:48 UTC, ascrazy commented on packages/picasso/src/Modal/Modal.tsx
> +  TransitionProps?: TransitionProps
Regarding defining own interface for `transitionProps`, would like to discuss this a bit more.

As I already mentioned this is actually backed by `react-transition-group/Transition` and `material-ui` basically re-exports `TransitionProps` interface from `react-transition-group` package. I'd prefer to re-export it directly form `react-transition-group` rather then from `material-ui`, but we do not have react-transition-group in direct deps of the package, so it's probably not a good idea to directly reference a dependency that comes as a transitive dependency of another package. 

On the other hand I do not quite get the purpose of defining own `TransitionProps` interface. It would make sense If we are to have own abstraction for animation transitions, but then IMO we might need to develop this abstraction first, define clear principles of how they are handled, which callbacks are supported and so on. 

In case we are to rely on `react-transition-group` as a standard for transitions (which is a good option from my understanding as this one seem to be kind of a de-factor standard for transitions in react world), then introducing own interface in between will just add unnecessary friction.

2021-12-10 10:28 UTC, ascrazy commented
- [ ] Add changeset

2021-12-10 10:29 UTC, ascrazy commented on packages/picasso/src/Modal/Modal.tsx
> +  TransitionProps?: TransitionProps
- [ ] Rename `TransitionProps -> transitionProps`
- [ ] Define own type for TransitionProps

2021-12-10 12:30 UTC, OleksandrNechai approved these changes

2021-12-10 16:30 UTC, merged