fix(Forms): add ability to disabled auto-focus and auto-scroll on Form submission error
toptal/picasso pull request #2324
Opened 2021-12-13 13:39 UTC by inemiro

[SPB-2864]

### Description

1. If there multiple form on page and we submit them, we have to manually control auto-focus, since, Picasso is doing it wrong.
2. Sometimes you don't need an auto-focus for error fields or auto-sroll to error fields.

### How to test

Submit form with an error (try switching off internet connection), see no scroll or auto-focus.

### Screenshots

N/A

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and
1. You have no extra requests.
2. You have optional requests.
   1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because
1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-12-14 07:54 UTC, TomasSlama reviewed
I think this is really cool feature, and probably it will be commonly used. Do you think we should maybe provide an example in the storybook for this? For example Form in Modal or something.

2021-12-14 08:01 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
Do you think it makes sense to do one without other? Like auto-scroll but not focus or focus but not auto-scroll? If not, maybe we could just have one prop: `noScrollToErros`. It is nice for API to have false value as default

2021-12-14 08:04 UTC, OleksandrNechai commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +const scrollTo = (
IMO no need to change the function. Better would be to control when it is called:
```
      if (field && autoFocusOnScrollToErrors) {
        scrollTo(field)
      }
```

2021-12-14 08:07 UTC, OleksandrNechai commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +    if (autoScrollOnErrors) {
We probably could avoid deep nesting by
```
if(!autoScrollOnErrors){
   return result
}
```

2021-12-14 08:10 UTC, inemiro commented
> I think this is really cool feature, and probably it will be commonly used. Do you think we should maybe provide an example in the storybook for this? For example Form in Modal or something.

I can do small inline edits, as it's being used on the Staff portal
![image](https://user-images.githubusercontent.com/67374194/145958401-8af16c71-1eef-482b-b554-f8e44bd9cd0e.png)

WDYT?

2021-12-14 08:11 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
Yeah, initially wanted to do a single prop, but decided to split for clarity, will join them, thanks

2021-12-14 08:13 UTC, teimurjan commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
Or `disableScrollOnError`

2021-12-14 08:19 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
Or to have it more positive: `skipScrollToErros` :smile:

2021-12-14 13:10 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
Changed to `scrollOnError` with a default `true` value

2021-12-14 13:10 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +const scrollTo = (
removed additional nesting

2021-12-14 13:10 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +    if (autoScrollOnErrors) {
nice, done

2021-12-14 13:41 UTC, inemiro commented
@TomasSlama @OleksandrNechai comments addressed, example has been added

2021-12-14 13:41 UTC, inemiro commented on packages/picasso-forms/src/Form/story/index.jsx
> +        defaultValue: 'false'
was not displaying a value unless it's a string

2021-12-14 19:51 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +  autoScrollOnErrors?: boolean
✅

2021-12-14 19:51 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +const scrollTo = (
✅

2021-12-14 19:51 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> +    if (autoScrollOnErrors) {
✅

2021-12-14 19:51 UTC, inemiro commented
✅

2021-12-15 07:53 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/Form.tsx
> +  scrollOnError?: boolean
It is a good practice to have bool prop on component to have `false` default value. So that when you have to use it you write simply `<Form disableScrollOnError />` instead of `<Form scrollOnError={false}/>`. Tiny thing, I agree, but still reduces the noise in JSX.

2021-12-15 08:00 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
> +  </Container>
Can we preserve the style of field titles?

![image](https://user-images.githubusercontent.com/14070311/146146607-5ac90fb7-a728-4e18-95da-a37e66dcc4ab.png)
vs

![image](https://user-images.githubusercontent.com/14070311/146146710-ba925533-e6fa-4ca9-ac2c-10c14e60c7d8.png)

2021-12-15 08:03 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/story/index.jsx
> +        description: `Screen going to be scrolled to the first occur error field of the form on the page. Field is gonna be auto-focused. If disabled, no scroll will occur.`,
```suggestion
        description: `Whether to scroll to the failed field on the form error.`,
```

2021-12-15 08:05 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/story/index.jsx
> +        defaultValue: 'false'
Maybe I missed it, but did yo set the default in the code itself?

2021-12-15 08:07 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/story/index.jsx
> +      'Showcase with a form without scrolling on form submission error.'
```suggestion
      'Showcase Form's behavior on form submission error.'
```

2021-12-15 08:11 UTC, OleksandrNechai requested changes
:+1: LGTM, rejecting due to missing automated tests.

2021-12-15 09:28 UTC, inemiro commented on packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
> +  </Container>
There are issues with layout, but I'll try

2021-12-15 10:14 UTC, OleksandrNechai commented
Oh, btw, why is this a fix? Sounds like a new feature to me

2021-12-15 12:23 UTC, inemiro commented
> Oh, btw, why is this a fix? Sounds like a new feature to me

It might be a future for the Picasso itself, but it's required to fix an issue within Staff portal.
Tell me if I need to alter it.

> rejecting due to missing automated tests.
I'll cover, `Form` is not covered at all, though

2021-12-15 13:43 UTC, inemiro commented
@OleksandrNechai ✅

2021-12-15 14:01 UTC, inemiro commented on packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
> +  </Container>
✅

2021-12-15 14:01 UTC, inemiro commented on packages/picasso-forms/src/Form/story/index.jsx
> +        defaultValue: 'false'
yes, it was specified. but now default value is `false`

2021-12-15 14:07 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
> -const scrollTo = (field: HTMLElement) => {
extracted to a file to properly mock

2021-12-15 14:16 UTC, inemiro commented on packages/picasso-forms/src/Form/story/index.jsx
> +        defaultValue: 'false'
without these quotes it is not shown, check default value for the `autoComplete` here:
https://picasso.toptal.net/?path=/story/picasso-forms-form--form

2021-12-15 14:16 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +  scrollOnError?: boolean
✅

2021-12-15 14:17 UTC, inemiro commented on packages/picasso-forms/src/Form/story/index.jsx
> +        description: `Screen going to be scrolled to the first occur error field of the form on the page. Field is gonna be auto-focused. If disabled, no scroll will occur.`,
✅

2021-12-15 14:17 UTC, inemiro commented on packages/picasso-forms/src/Form/story/index.jsx
> +      'Showcase with a form without scrolling on form submission error.'
✅

2021-12-15 15:55 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/test.tsx
> + * form submit is not linked to any process,
Not sure what does this means: linked to any process?
```suggestion
 * form submit does not return Promise or accept callback,
```

2021-12-15 15:57 UTC, OleksandrNechai commented on packages/picasso-forms/src/Form/test.tsx
> + * so where is no other way to wait when error is gonna be displayed
```suggestion
 * so there is no way to know when an error is displayed
```

2021-12-15 15:58 UTC, OleksandrNechai commented on packages/picasso-forms/src/utils/scroll-to.ts
> +  // scrollIntoView is not defined for Jest
This comment is probably not useful. Do we really need to please Jest in the code? :thinking:

2021-12-15 15:58 UTC, OleksandrNechai approved these changes

2021-12-15 16:05 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to.ts
> +  // scrollIntoView is not defined for Jest
Without that it might be unclear why do we need to check `typeof === 'function'` for something that is stated as mandatory to present function in typescript.
I can remove it if it's obsolete, WDYT?

2021-12-15 16:08 UTC, inemiro commented on packages/picasso-forms/src/Form/test.tsx
> + * form submit is not linked to any process,
✅

2021-12-15 16:08 UTC, inemiro commented on packages/picasso-forms/src/Form/test.tsx
> + * so where is no other way to wait when error is gonna be displayed
✅

2021-12-15 16:08 UTC, inemiro commented on packages/picasso-forms/src/utils/scroll-to.ts
> +  // scrollIntoView is not defined for Jest
✅

2021-12-16 10:19 UTC, TomasSlama reviewed
Good job 👍, we are only missing changeset. 👉 [docs](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md#release)

2021-12-16 11:58 UTC, dmaklygin1 commented on packages/picasso-forms/src/Form/Form.tsx
> +      }),
shouldn't we add `disableScrollOnError` as a dependency to `useMemo`?

2021-12-16 12:02 UTC, dmaklygin1 commented on packages/picasso-forms/src/Form/Form.tsx
> +      }),
silly question: why if we do not create a decorator at all if `disableScrollOnError` is true?
So:
```
const scrollToErrorDecorator = useMemo(() => !disableScrollOnError && createScrollToErrorDecorator(), [])
```

2021-12-16 14:17 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +      }),
✅

2021-12-16 14:18 UTC, TomasSlama approved these changes

2021-12-16 14:21 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +      }),
Good call, makes sense, I wanted to less changes initially, but it does make sense. If you don't mind to unblock the bug on Staff portal side, I'll merge without additional changes, but I will create a follow-up to address it.

2021-12-16 14:21 UTC, dmaklygin1 commented on packages/picasso-forms/src/Form/test.tsx
> +  it('does not auto-scroll form to the error field if `disableScrollOnError` is specified', async () => {
please, you `describe` for explaining a condition:
```suggestion
  describe('when `disableScrollOnError` is specified', () => 
    it('does not auto-scroll form to the error field ', async () => {
```

2021-12-16 14:23 UTC, inemiro commented on packages/picasso-forms/src/Form/Form.tsx
> +      }),
https://toptal-core.atlassian.net/browse/FX-2366

2021-12-16 14:24 UTC, inemiro commented on packages/picasso-forms/src/Form/test.tsx
> +  it('does not auto-scroll form to the error field if `disableScrollOnError` is specified', async () => {
✅

2021-12-16 14:25 UTC, dmaklygin1 approved these changes

2021-12-16 17:25 UTC, merged