WIP: add List + Table composition example
toptal/picasso pull request #2351
Opened 2021-12-27 09:17 UTC by ascrazy

### Description

**TBA** Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| **TBA** | **TBA** |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-12-27 09:19 UTC, ascrazy commented
`ListItem`'s bullets alignment is font-size dependent. When you put `List` into a `Table` (that has reduced font-size by default), `ListItem`'s bullets alignment breaks.  

<img width="447" alt="image" src="https://user-images.githubusercontent.com/903437/147456367-7e49b864-2cf7-40bb-a338-03c4fe03a014.png">

2021-12-27 11:43 UTC, ascrazy commented
@toptal-devbot run all

2021-12-27 12:38 UTC, denieler commented on .changeset/witty-brooms-sin.md
> +'@toptal/picasso': minor
```suggestion
'@toptal/picasso': patch
```
because it's not a new feature, but rather fixing some corner cases

2021-12-27 12:39 UTC, denieler commented on .changeset/witty-brooms-sin.md
> +List base font-size
I would write more explicit changelog message, which you would personally want to see in Picasso changelog, when using this component

2021-12-27 12:40 UTC, denieler commented on packages/picasso/src/List/story/index.jsx
> +  )
we don't need a special example in Picasso for that, but if you want to have a test - please write a Cypress test with Happo snapshot 🙇

2021-12-27 12:40 UTC, denieler requested changes
we need probably remove example and replace with a Cypress test

2021-12-27 12:49 UTC, ascrazy commented on .changeset/witty-brooms-sin.md
> +List base font-size
Yep, sure. Was planning to do that but then missed.

- [ ] Add more explicit changeset description

2021-12-27 12:49 UTC, ascrazy commented on .changeset/witty-brooms-sin.md
> +'@toptal/picasso': minor
- [ ] Fix changeset version level

2021-12-27 12:50 UTC, ascrazy commented on packages/picasso/src/List/story/index.jsx
> +  )
- [ ] Replace CustomFontSizeContainer example with cypress/happo test

2021-12-27 15:21 UTC, denieler commented on .changeset/witty-brooms-sin.md
> +- set List's root element font-size to 1rem to fix unordered list bullets alignment
👍 ❤️

2021-12-27 15:22 UTC, denieler approved these changes
Please remove only `picasso/src/List/__image_snapshots__/list-custom-fontsize-container-snap.png` file 🙇

2021-12-27 15:28 UTC, ascrazy commented
> Please remove only `picasso/src/List/__image_snapshots__/list-custom-fontsize-container-snap.png` file 🙇

👌

2021-12-28 10:55 UTC, denieler approved these changes

2021-12-28 11:33 UTC, OleksandrNechai approved these changes

2021-12-28 11:59 UTC, merged