chore: [FX-2390] Make text editor vertically resizable
toptal/picasso pull request #2353
Opened 2021-12-27 13:33 UTC by LashaJini

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2021-12-27 18:59 UTC, dmaklygin1 approved these changes

2021-12-28 08:18 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  height?: string // TODO: change to Height type?
I think we should not commit TODOs. I have problems with specifying TextEditor's height this way. Can we ask if designers can suggest default height and always have it of that height?

2021-12-28 08:19 UTC, OleksandrNechai requested changes
I am not `convinced` by height prop :)

2021-12-28 08:35 UTC, LashaJini commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  height?: string // TODO: change to Height type?
Talked to Milos, he said `200px`.

2021-12-28 08:40 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  /** Text editor height */
eh?

2021-12-28 08:40 UTC, OleksandrNechai approved these changes

2021-12-28 08:41 UTC, LashaJini commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  /** Text editor height */
:grin:

2021-12-28 09:06 UTC, denieler commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
```suggestion
      height: '12.5em',
```
?

2021-12-28 09:07 UTC, denieler approved these changes

2021-12-28 09:13 UTC, LashaJini commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
Font-size is `14px`.

2021-12-28 09:14 UTC, denieler commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
but it will be using not the texteditor font-size, but the environment font-size where it's placed to

2021-12-28 09:23 UTC, OleksandrNechai approved these changes

2021-12-28 09:25 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
> but it will be using not the texteditor font-size, but the environment font-size where it's placed to
is not it placed in a text editor? :smile:

2021-12-28 09:30 UTC, denieler commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
@OleksandrNechai I mean `ems` will be calculated not based on the TextEditor editor font-size, but based on the container font-size where TextEditor is rendered

2021-12-28 09:31 UTC, merged

2021-12-28 09:52 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
this is only in case when TextEditor itself does not have font size set. But if it does? :)

2021-12-28 09:54 UTC, denieler commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      height: rem('200px'),
it should I think 🤔