feat(TextEditor): connect Toolbar with editor
toptal/picasso pull request #2363
Opened 2022-01-05 08:54 UTC by TomasSlama

[FX-2394]

### Description

To use the custom toolbar, we need to stop using `theme` property in Editor, so quill doesn't rewrite the inner HTML of buttons. Quill automatically connects with custom buttons when we pass the correct class names. For select, we must have our own handlers.

Header select is not styled properly and we have different task for it.

### How to test

- play with toolbar features.
- - proper feature should be selected when the format is provided

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-01-05 09:48 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +icons.bold = boldIcon
What do you achieve by this? 🤔

2022-01-05 09:48 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +icons.bold = boldIcon
ah, this is leftover, ty for pointing it out, I will delete it.

2022-01-05 11:10 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  const handleHeaderChange = (
I think it can be inlined. Looks like this function is just a proxy.

2022-01-05 11:13 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +  setHeaderValue: Dispatch<SetStateAction<HeaderValueType>>
This is wierd type of the prop. Yes, this is type of useState return but it should not be type of option IMO

2022-01-05 11:15 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +        headerCustom: function (this: { quill: Quill }, value?: 3) {
we usually do not use `function` keyword.

2022-01-05 11:16 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +        headerCustom: function (this: { quill: Quill }, value?: 3) {
oh, we use this keyword and therefore we need function? :facepalm: :)

2022-01-05 11:26 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +      }
Can you see how this hook violates SRP? It both handles subscriprions and executes logic about setting logic.

2022-01-05 11:30 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +      }
I am very confused with above code. We query ql-headerCustom (header?) but get Select. headerChangeHandler does not handle header value but handles some range, what range? However editorChangeHandler does handle header and does it twice depending on eventName :)

2022-01-05 11:31 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +  setHeaderValue: Dispatch<SetStateAction<HeaderValueType>>
@OleksandrNechai so you mean, that simple `() => void` or `Function` would be enough here?

2022-01-05 11:33 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
> +          value={headerValue}
Is header value is really header value? I mean in web if we have <h1>Here is header value</h1>

2022-01-05 11:34 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
> +          className={cx('ql-headerCustom', classes.textStylesSelect)}
can we avoid messing with styles of Select? It demonstrates we are failing as Picasso developers showing we can't ourself use our components without messing with their styles.

2022-01-05 11:34 UTC, OleksandrNechai commented on packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
> +          className={cx(classes.button, 'ql-bold')}
Can we also not mess with styles of the buttons?

2022-01-05 11:39 UTC, OleksandrNechai commented on packages/picasso/src/NativeSelect/NativeSelect.tsx
> +              inputProps={{ multiple, className }}
This is maybe a mistake. className passed into component already used below on the wrapper of the component. This is not intended to be used here AFAIK.

2022-01-05 11:45 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
> +          className={cx('ql-headerCustom', classes.textStylesSelect)}
From what I understand, this class is needed so that quill can connect handlers to this component

2022-01-05 11:46 UTC, OleksandrNechai requested changes
I think many things need to be improved. But I am not sure, let's have a discussion if I have missed some constraints.

2022-01-05 12:29 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +      }
`.ql-headerCustom` is select box with `Heading | Normal`. Quills default name is `quill-header` I have just added Custom

`editor-change` event is triggered by another two events: `text-change | selection-change`, these events have different arguments. 

`text-change` event happens when you change some text in editor if changed text involves updating header, we need to update the value in toolbar select box `.ql-headerCustom`

`selection-change` event is triggered when you select some text, or simply click somewhere in the text. When you click inside the header, you want to see the selected `Heading` value in the toolbar selectbox.

so this `editorChangeHandler` only takes care of showing proper value in the toolbar select box.

When I double tested, it seems Quill attach listener to headerSelect automatically, so we don't need this second listener.

2022-01-05 12:30 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useInitEditor.tsx
> +        headerCustom: function (this: { quill: Quill }, value?: 3) {
yes, exactly, we need scope

2022-01-06 09:18 UTC, OndrejTuma approved these changes
Good job! This looks very readable. Only one nit: I'd consider more generic approach to select - something like `textFormat`. 
Now its only header and normal format but in the future it can support small format as well and headerValue will become confusing

2022-01-06 09:18 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +   * both have different arguments in handler and we need to handle both.
handling `text-change` event is not necessary now

2022-01-06 09:18 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +      if (eventName === 'selection-change' && quill) {
```suggestion
      if (eventName === 'selection-change' && quill && rangeOrDelta) {
```

2022-01-06 09:18 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +          console.log({ header })
```suggestion

```

2022-01-10 08:58 UTC, denieler commented on .eslintrc.js
> +    'no-undef': 'error'
why not to add to `node_modules/@toptal/davinci-syntax/src/configs/.eslintrc` instead?

2022-01-10 09:06 UTC, TomasSlama commented on .eslintrc.js
> +    'no-undef': 'error'
@denieler yes, this is a mistake, I was just playing with it, if it would break something. But it seems it works properly. So I will add to davinci

2022-01-10 09:43 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor.tsx
> +      console.log('unknown action type')
bad handling of the state change 😃 better to throw the error

2022-01-10 09:43 UTC, denieler commented on packages/picasso-lab/src/TextEditor/quill.snow.css
> +/* .ql-container {
do we need to keep those classes commented?

2022-01-10 09:44 UTC, denieler commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      '&.ql-active': {
quill class name leak 😃

2022-01-10 09:46 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  value: T | ''
it already extends a string, but can be a number, so we can't keep `""` as a valid value here

2022-01-10 09:50 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useToolbarActiveStates.tsx
> +      if (quill) {
```suggestion
      if (!quill) {
        return
      }
```

2022-01-10 09:51 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useToolbarActiveStates.tsx
> +            setToolbarState({})
`{}` should be moved to `const` probably as `EMPTY_STATE` or something like that

2022-01-10 09:53 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useAutofocus.tsx
> +      console.log('autofocus')
☝️

2022-01-10 10:05 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/quill.snow.css
> +/* .ql-container {
I want to remove this file at the end, but probably in separate PR. We will move these not commented styles to our styles.

2022-01-10 10:06 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/styles.ts
> +      '&.ql-active': {
will be removed. Not necessary anymore, just forgot to remove.

2022-01-10 10:11 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  value: T | ''
this looks like a bad API

2022-01-10 13:50 UTC, TomasSlama commented on packages/picasso/src/Select/types.ts
> +  disablePortal?: boolean
hm, I thought that we do, but I double-checked and we don't. Will be removed

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useDisableEditor.tsx
no real change, only clean up.

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useAutofocus.tsx
> +import { useEffect, useRef } from 'react'
no real change, I changed hook name to follow `useNoun`

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  const { toolbarState, toolbarHandlers } = useTextEditor({
all quill logic moved to `useTextEditor`. We only pass editors state and handlers to connect Toolbar with quill.

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useEditorLooseFocusFix.tsx
> +import { useEffect, useCallback } from 'react'
Common [issue](https://github.com/quilljs/quill/issues/1290) of custom toolbar,

When clicking anywhere, quill loses focus, we need to prevent it when clicking inside the toolbar

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useOnChange.tsx
> +import { useCallback, useEffect } from 'react'
only rename file and early return

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useOnValueChange.tsx
> +import { useEffect } from 'react'
only rename file and early return

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useToolbarActiveStates.tsx
> +      quill.on('editor-change', handler)
whenever textEditor changes (selection or text changes), we update the toolbar state. I tried to add condition to shallow compare new state with previous state and after some changes in editor it started to be slow.

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useToolbarHandlers.tsx
> +  return toolbarHandlers
we prepare custom handlers for Toolbar buttons, so we don't have use `ql-*` classes

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/story/Disabled.example.tsx
>      </>
since editor is disabled, we don't need to showcase data

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/styles.ts
>      }
we don't want to write any custom CSS for buttons or select. We need to update the CSS of these separately (other tasks)

2022-01-10 14:17 UTC, TomasSlama commented on packages/picasso/src/Select/types.ts
> +  value: T | ''
@denieler I tried to play with it, and didn't come up with anything better. Do you have some suggestions?

When I pass option with value `"3" | ""` it would work, but then I would have to parse it to int before using with the quill. When I thought about it, I think an empty string is a valid value for a select option even when other options are numbers.

2022-01-11 15:53 UTC, TomasSlama commented
will split it into separate PRs

2022-01-11 15:53 UTC, closed without merging