[FX-2389] Style header options
toptal/picasso pull request #2375
Opened 2022-01-11 12:46 UTC by LashaJini

[FX-2389](https://toptal-core.atlassian.net/browse/FX-2389)

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-01-11 12:52 UTC, LashaJini commented on packages/picasso/src/Menu/styles.ts
> +      padding: '0.5rem 0'
This is actually a solution, but some of the other visual tests are broken, because they depend on the `Menu`. I can't  approve those changes for them, because I haven't found designs for them yet.

2022-01-12 10:07 UTC, denieler reviewed
I think this is a wrong change

<img width="537" alt="Screenshot 2022-01-12 at 12 06 47" src="https://user-images.githubusercontent.com/2836281/149119940-e916143c-73cd-4780-8bb8-bf430599fe20.png">

2022-01-12 10:09 UTC, LashaJini commented
> I think this is a wrong change
> 
> <img alt="Screenshot 2022-01-12 at 12 06 47" width="537" src="https://user-images.githubusercontent.com/2836281/149119940-e916143c-73cd-4780-8bb8-bf430599fe20.png">

hmm, it's reversed? Weird. I will check it.

2022-01-12 10:12 UTC, LashaJini commented
> I think this is a wrong change
> 
> <img alt="Screenshot 2022-01-12 at 12 06 47" width="537" src="https://user-images.githubusercontent.com/2836281/149119940-e916143c-73cd-4780-8bb8-bf430599fe20.png">

@denieler You mean padding should be between `search` and `option 1`?

2022-01-12 10:15 UTC, denieler commented
> @denieler You mean padding should be between search and option 1?

@LashaJini I'm not sure, probably better to discuss that with Milos, but yes

2022-01-12 10:16 UTC, denieler commented
@LashaJini I also found that the box-shadow is not according to the design:

<img width="350" alt="Screenshot 2022-01-12 at 12 14 52" src="https://user-images.githubusercontent.com/2836281/149121341-491109ac-ceb5-43c2-811b-035f9c33e2ee.png">

<img width="409" alt="Screenshot 2022-01-12 at 12 14 45" src="https://user-images.githubusercontent.com/2836281/149121332-169cfa32-9962-4d36-ae72-54d88338c327.png">

2022-01-12 10:17 UTC, LashaJini commented
> > @denieler You mean padding should be between search and option 1?
> 
> @LashaJini I'm not sure, probably better to discuss that with Milos, but yes

@denieler  Got it thank you. Milos is OOO until 14.

2022-01-13 10:07 UTC, LashaJini commented
![drawer-without-title-effect-1-diff](https://user-images.githubusercontent.com/72510037/149309688-6ec1a752-9382-44c6-ad6d-5a1da6588094.png)

:thinking:

2022-01-13 11:43 UTC, denieler commented on packages/picasso/src/ScrollMenu/ScrollMenu.tsx
> +          [classes.notLastChild]: isValidElement(fixedFooter)
it makes more sense to have a class `lastChild`

2022-01-13 11:44 UTC, denieler commented on packages/picasso/src/ScrollMenu/ScrollMenu.tsx
> +        [classes.withHeader]: isValidElement(fixedHeader),
`Boolean(fixedHeader)` can do a job for you if you really need this

2022-01-13 11:45 UTC, denieler commented on packages/picasso/src/ScrollMenu/styles.ts
> +      paddingBottom: '0.5rem'
I think `ScrollMenu` is not a correct place to add those styles, because the responsibility of `ScrollMenu` is to provider key navigation support for the menu only

2022-01-13 13:12 UTC, LashaJini commented on packages/picasso/src/ScrollMenu/styles.ts
> +      paddingBottom: '0.5rem'
I agree this solution sucks, but I don't see any other way styling it as we can't change styling of `header` and `footer` components.

2022-01-17 07:17 UTC, dmaklygin1 approved these changes

2022-01-17 07:32 UTC, TomasSlama approved these changes
LGTM 👍 good job

2022-01-17 08:36 UTC, denieler commented on .changeset/swift-moles-shave.md
> +### NonNativeSelect
missing `---` in changeset 😃 https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md#summary-of-the-change-changelog-message

2022-01-17 08:37 UTC, denieler commented on .changeset/swift-moles-shave.md
> +### NonNativeSelect
also `NonNativeSelect` is not a public component, we don't need to write changelog for it

2022-01-17 08:38 UTC, denieler commented on packages/picasso/src/ScrollMenu/styles.ts
> +      paddingBottom: 0
`ScrollMenu` is not a good place to style Select component 🤷‍♂️ if you think it is the only place - I would write a component wrapper around `ScrollMenu` to apply styling

2022-01-17 08:39 UTC, denieler requested changes
We need to change changesets and styling `ScrollMenu` in my opinion is not a correct thing to do

2022-01-17 08:43 UTC, LashaJini commented on .changeset/swift-moles-shave.md
> +### NonNativeSelect
What about the other changeset `.changeset/perfect-apes-perform.md`? We didn't change component and there is not template for that in confluence.

2022-01-17 08:46 UTC, OndrejTuma commented on packages/picasso-provider/src/Picasso/config/shadows.ts
> +  ...muiShadows.slice(6)
I cant help but think that this way we are replacing `muiShadows[5]` with your custom one
Did you check that its not used anywhere?

2022-01-17 08:46 UTC, denieler commented on .changeset/swift-moles-shave.md
> +### NonNativeSelect
I would do something like, just to make the change visible:

```
---
'@toptal/picasso-provider': minor
---

---
### Common

- Add new `scroll menu` shadow 
```

2022-01-17 08:56 UTC, LashaJini commented on packages/picasso-provider/src/Picasso/config/shadows.ts
> +  ...muiShadows.slice(6)
It's not used in Picasso.

2022-01-17 09:00 UTC, LashaJini commented on packages/picasso-provider/src/Picasso/config/shadows.ts
> +  ...muiShadows.slice(6)
I just checked and it's not used anywhere in Toptal. But the change marked as major update :thinking: it is a breaking change isn't it?

2022-01-17 10:16 UTC, denieler commented on packages/picasso/src/Autocomplete/test.tsx
> +    it('prevents mouseDown on SelectOptions', () => {
this test probably shouldn't change 🤔

2022-01-17 10:17 UTC, denieler commented on packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
> +// component and selectedIndex in SelectOptions component.
I think `selectedIndex` is still calculated in `ScrollMenu` component

2022-01-17 10:20 UTC, denieler commented on packages/picasso/src/SelectOptions/SelectOptions.tsx
> +
I'm not sure, that all our components have `defaultProps` and `displayName`

2022-01-17 10:21 UTC, LashaJini commented on packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
> +// component and selectedIndex in SelectOptions component.
Correct, but I thought if future developer checks the `NonNativeSelectOptions` component at first glance he/she won't understand where this `ScrollMenu` component comes from, but if we replace it with `SelectOptions` it will redirect him/her.

2022-01-17 10:21 UTC, LashaJini commented on packages/picasso/src/Autocomplete/test.tsx
> +    it('prevents mouseDown on SelectOptions', () => {
> Correct, but I thought if future developer checks the NonNativeSelectOptions component at first glance he/she won't understand where this ScrollMenu component comes from, but if we replace it with SelectOptions it will redirect him/her.

same here

2022-01-17 10:21 UTC, denieler commented on packages/picasso/src/SelectOptions/SelectOptions.tsx
> +      className={cx(className, classes.menu, {
I guess `className` has to be applied as a last one in this chain, because it should have opportunity to override any of the specified styles

2022-01-17 10:22 UTC, LashaJini commented on packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
> +// component and selectedIndex in SelectOptions component.
@denieler Should I still revert it?

2022-01-17 10:23 UTC, denieler commented on .changeset/swift-moles-shave.md
> +### ScrollMenu
`ScrollMenu` is not an external Picasso component. I think we need to write changeset for `Select`, `Autocomplete`, etc. all components which use `ScrollMenu`

2022-01-17 10:23 UTC, LashaJini commented on packages/picasso/src/SelectOptions/SelectOptions.tsx
> +
Sorry, I didn't understand, could you explain it, please?

2022-01-17 10:25 UTC, LashaJini commented on .changeset/swift-moles-shave.md
> +### ScrollMenu
Something like this?

```md
### Component 1

- Replace `ScrollMenu` with `SelectOptions`

### Component 2

- Replace `ScrollMenu` with `SelectOptions`
```

2022-01-17 10:33 UTC, denieler commented on .changeset/swift-moles-shave.md
> +### ScrollMenu
I guess
```
Select
- Changed the look of the options list (added shadows, increased top/bottom margins), ...
```

2022-01-17 10:34 UTC, denieler commented on packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
> +// component and selectedIndex in SelectOptions component.
idk, to me this comment now don't have sense, because I go to `SelectOptions` component and there are no any calculations 🤷‍♂️

2022-01-17 10:35 UTC, denieler commented on packages/picasso/src/SelectOptions/SelectOptions.tsx
> +
I mean any component has this part https://github.com/toptal/picasso/blob/1ed32e745766ba1d8675fa309207d20f6791e7da/packages/picasso/src/Autocomplete/Autocomplete.tsx#L315. I think this component also should have it to keep consistency

2022-01-17 10:57 UTC, LashaJini commented on packages/picasso/src/SelectOptions/SelectOptions.tsx
> +
I guess I should also add in `ScrollMenu` as well.

2022-01-17 11:37 UTC, denieler commented on .changeset/swift-moles-shave.md
> +- `Autocomplete` component depends on `Select` component, thus it is also
I don't see a problem to copy the same items from the changelog for `Select`, but the current variant is created additional work for readers to figure out what exactly is changed in `Autocomplete` component

2022-01-17 12:06 UTC, LashaJini commented on packages/picasso-provider/src/Picasso/config/shadows.ts
> +  ...muiShadows.slice(6)
We discussed this with Daniel and we can safely ignore this.

2022-01-17 12:07 UTC, merged