feat(TextEditor): toolbar disabled when editor not focused
toptal/picasso pull request #2406
Opened 2022-01-25 22:51 UTC by TomasSlama

[FX-2449]

### Description

After discussion with Milos, we decided to follow Slacks' example. When the editor is not focused, we will disable the toolbar.

### How to test

- try temploy, when editor focused, toolbar should be active, when not focused, disabled.

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-01-26 08:51 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useHasFocus/useHasFocus.tsx
> +export default useHasFocus
what about this?
```
import { Sources } from 'quill'
import { useState, useCallback } from 'react'

import { EditorRefType } from '../../types'
import useSelectionChange from '../useSelectionChange'

type Props = {
  ref: EditorRefType
}

const useHasFocus = ({ ref }: Props) => {
  const [hasFocus, setHasFocus] = useState<boolean>(false)
  const quill = ref.current

  const handleSelectionChange = useCallback((_, __, source: Sources) => {
    const canReceiveFocus = source !== 'silent'
    const hasCurrentFocus = quill!.hasFocus()

    setHasFocus(canReceiveFocus && hasCurrentFocus)
  }, [quill, setHasFocus])
  
  useSelectionChange({
    ref,
    handler: handleSelectionChange
  })

  return { hasFocus }
}

export default useHasFocus

```

2022-01-27 08:20 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
>    }
this should not be necessary anymore

2022-01-27 08:20 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
> +  quill: Quill | undefined
quill can't be undefined

2022-01-27 08:22 UTC, denieler commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
>    })
just wrap all that into 
```
useEffect(() => {
  if (!quill) {
    return
  }
  
  // do stuff
}, [quill])
```

2022-01-27 09:50 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
> +  quill: Quill | undefined
I think it can, if its initialized in useEffect

2022-01-27 10:11 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  const { toolbarState, toolbarHandlers, isToolbarDisabled } = useTextEditor({
I'm wondering why `isToolbarDisabled ` isn't in the `toolbarState`? Fix me please, but seems, `disabled` is somehow related to the state, isn't it?

2022-01-27 10:14 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
> +type HandlerType = ({ quill, onChange }: Props) => TextChangeHandler
I would avoid creating an extra type `Props` — it's used only once.

2022-01-27 10:17 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
about onChange, I would reuse `TextEditorChangeHandler` type instead.

2022-01-27 10:22 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
> +    ])
this is quite difficult to understand. 
is it possible to use `useTextChange` hook in any other place of the TextEditor? Is it intentional to split useTExtChange hook and `getTextChangeHandler` function?

2022-01-27 10:28 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
> +  const quill = useQuillInstance({ id, placeholder, actions })
I'm thinking about `useQuillInstance` — it must return a quill. 
what if we use `useMemo` inside `useQuillInstance` instead of `useEffect` to immediately return an instance of quill ?

2022-01-27 10:33 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useToolbar/useToolbar.tsx
> +  quill: Quill | undefined
do you think, the existence of the Hook is still expedient if quill is undefined?

2022-01-27 10:34 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useToolbar/useToolbar.tsx
> +  quill: Quill | undefined
I'm thinking about keeping quill in a context instead of passing it from parent to child. I guess, it would be more optimal

2022-01-27 10:42 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useSelectionChange/useSelectionChange.tsx
> +}
```suggestion
const useSelectionChange = (handler: SelectionChangeHandler) => {
  const quill = useQuillContext(QuillContext)
  
  useEffect(() => {
    quill.on('selection-change', handler)

     return () => {
        quill.off('selection-change', handler)
      }
  }, [quill, handler])
}
```

wdyt?

2022-01-27 10:42 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/useQuillInstance.tsx
> +  return quill
```suggestion
  return useContext(QuillContext)
```

2022-01-27 10:43 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/useQuillInstance.tsx
> +  return quill
```
return useContext(QuillContext)
```

2022-01-27 10:46 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useHasFocus/useHasFocus.tsx
> +  setHasFocus(hasCurrentFocus)
having `setHasFocus ` here, is quite cut from the context. The name of the function is `getSelectionChangeHandler`, but it calls `setHasFocus` under the hood. it's quite confusing...

2022-01-27 10:47 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useHasFocus/useHasFocus.tsx
> +  setHasFocus(hasCurrentFocus)
I would check:
1. whether the selection change event is silent or not
2. take current focus state
3. return it from the hook
4.

2022-01-27 11:02 UTC, dmaklygin1 commented on packages/picasso-lab/src/TextEditor/hooks/useHasFocus/useHasFocus.tsx
> +const useHasFocus = ({ quill }: Props) => {
Although the name of the hook exposes the functionality it implements, the granularity of functionality is quite small.
You've already implemented `useAutofocus`, `useEditorLoseFocusFix` hooks. I would implement the one: `useEditorFocus` to cover the area of responsibility: new hook will be in charge of Focus state

2022-01-27 12:38 UTC, OndrejTuma commented on packages/picasso-lab/src/TextEditor/hooks/useEditorLoseFocusFix/useEditorLoseFocusFix.tsx
>  export default useEditorLooseFocusFix
I didnt find any use of this hook - if its used in some other branch, then no problem 🙂

2022-01-27 15:35 UTC, LashaJini commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  const { toolbarState, toolbarHandlers, isToolbarDisabled } = useTextEditor({
This is how toolbar state looks like currently.

![Screenshot from 2022-01-27 19-32-15](https://user-images.githubusercontent.com/72510037/151390589-c45f3b15-ca53-4c48-9099-48c926d1e2a1.png) 

So, `disabled` is not directly related to the state, but I agree naming is kinda confusing.

2022-01-27 19:55 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  const { toolbarState, toolbarHandlers, isToolbarDisabled } = useTextEditor({
this is a good question, maybe I need to think more about the structure of the state.

```js
const toolbarState = {
  format: {
    bold: boolean,
    italic: boolean,
    header: '3' | '',
    list: string
  },
  disabled: boolean
}
```

To explain how it works, `isToolbarDisabled` is `true` when we don't have focus inside the editor.

2022-01-27 20:19 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/getTextChangeHandler/getTextChangeHandler.tsx
those are two different types.

`onChange` - callback, that user provides, that is called inside `TextEditorChangeHandler`
`TextEditorChangeHandler` - internal quills function, that is called on `text-changed` event.

`onChange` - `(HTML: string) => void`
``TextEditorChangeHandler` - `(delta, oldDelta, source) => void`

and we do not want users to use `delta` format

2022-01-27 20:20 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
> +    ])
I agree, that it is not clean code, I will refactor it. `useTextChange` is also used in new PR of Lasha.

2022-01-27 20:24 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
> +  const quill = useQuillInstance({ id, placeholder, actions })
yes, this is a good idea, after Daniels suggestions I also came to this idea, but it sadly doesn't work. Quill needs to be initialiezed after DOM is rendered, because quill internally works with it. So when `new Quill('#id')` is called, the container already needs to be rendered.

Daniel after that suggested another approach, how we can keep using `useEffect` and still be sure, that quill is not `undefined`. I will show tomorrow on mob review

2022-01-27 20:24 UTC, TomasSlama commented on packages/picasso-lab/src/TextEditor/hooks/useToolbar/useToolbar.tsx
> +  quill: Quill | undefined
we can discuss this on tomorrows mob

2022-02-02 10:00 UTC, separatio commented on packages/picasso-lab/src/TextEditor/InitEditor.tsx
> +  // TODO: refactor toolbarState to editorState and keep this info there.
You should create a ticket for this. It's tech debt, and needs to be handled.
We're going to forget about it if you leave it as a TODO.

2022-02-02 10:01 UTC, separatio commented on packages/picasso-lab/src/TextEditor/TextEditor.tsx
> +  setBla: (sharedState: SharedState) => void
What's `setBla`? :smile:

2022-02-02 10:25 UTC, separatio requested changes
I see there are some picasso-lab additions. Considering we removed picasso-lab, you should probably move stuff around.

2022-02-08 08:46 UTC, closed without merging