fix: add sticky header
toptal/picasso pull request #2416
Opened 2022-02-03 15:53 UTC by VictorBaba

[SPC-1621]

### Description

Transform from fixed `Page.TopBar` to a sticky one. 
On mobile header was shrink and we were not able to have a horizontal scroll, same as page content and transforming to a sticky header solves this issue.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| https://user-images.githubusercontent.com/20658410/152377798-eeb4cafa-09fa-49ea-83f3-e145246b506f.mov | https://user-images.githubusercontent.com/20658410/152377759-32d62a07-b412-4170-92de-9eb99b7d54ab.mov |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-02-04 05:51 UTC, workitponiedzialek reviewed
Hmm shouldn't this be a prop, so each project could decide if they want it or not?

2022-02-04 09:07 UTC, separatio requested changes
According to the ticket AC, the profile menu shouldn't disappear. According to `after` the video, the profile disappears.

I think the implementation should have been done strictly on the SP side, and add a minimum width for the Search bar.

2022-02-04 10:41 UTC, separatio approved these changes
This looks good to me. I'd wait for another approval from FX before merging, though.

2022-02-07 09:28 UTC, denieler commented on .changeset/afraid-poets-begin.md
> +Update PageTopBar from fixed to sticky position
Please follow those guidelines for writing the changeset - https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md 🙇‍♂️

2022-02-07 09:29 UTC, denieler commented on packages/picasso/src/PageTopBar/PageTopBar.tsx
> +    <div className={classes.wrapper} style={style}>
this is correct 👍  but might be a breaking change for users of this component 🤔  so I would at least mention this in the changelog (changeset)

2022-02-07 11:14 UTC, VictorBaba commented on .changeset/afraid-poets-begin.md
> +Update PageTopBar from fixed to sticky position
I updated the changeset, Thank you!

2022-02-07 11:14 UTC, VictorBaba commented on packages/picasso/src/PageTopBar/PageTopBar.tsx
> +    <div className={classes.wrapper} style={style}>
That's a good idea, I updated the changeset.
Thank you ! 👍

2022-02-09 13:32 UTC, separatio commented
Found one more that needs fixing.

https://user-images.githubusercontent.com/8407461/153211320-1c228e95-53d3-4da1-bbb4-3475fb514f5a.mp4

2022-02-09 14:09 UTC, OndrejTuma commented on packages/picasso/src/PageTopBar/PageTopBar.tsx
> +    <div className={classes.wrapper} style={style}>
I noticed that there is this `position: absolute;` style added on mobile possibly passed via this style prop, because it used to be on `header` element.
Problem is that this wrapper was originally static and had set its height so that when header was positioned absolutely, TopBar preserved its height, and that is not happening now:
| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/22159416/153217439-1abb82a0-37e7-4393-9812-fed3ab38e737.png) | ![image](https://user-images.githubusercontent.com/22159416/153217553-09a3cf3e-8929-46c3-925c-5af71b0e2d1f.png) |

2022-02-10 20:19 UTC, OndrejTuma commented on packages/picasso/src/PageTopBar/styles.ts
> +      width: '100%'
this probably can be safely removed?

2022-02-11 13:27 UTC, VictorBaba commented on packages/picasso/src/PageTopBar/PageTopBar.tsx
> +    <div className={classes.wrapper} style={style}>
Issue is still there because of that `position: absolute` that is injecting in storybook.
Other than that, everything is working great.

2022-02-14 09:11 UTC, VictorBaba commented
I will close this PR because there are more breaking changes.
I fixed the issue inside Staff Portal project.

2022-02-14 09:11 UTC, closed without merging