feat(PasswordInput): add new component
toptal/picasso pull request #2462
Opened 2022-02-20 14:57 UTC by ozgurkececioglu

[FX-2482]

### Description

- this PR is about adding a new component called PasswordInput. It will have a toggle button to show and hide the password.
- I also fixed a visual bug for NumberInput (on hover state, background-color for control buttons was exceeding the container)

### How to test

// I will provide a link when available

### Screenshots
<img width="359" alt="Screen Shot 2022-02-17 at 17 15 30" src="https://user-images.githubusercontent.com/7733167/154848516-0f512010-4c45-4f9d-ad2b-ffc244fc30d5.png">
<img width="359" alt="Screen Shot 2022-02-17 at 17 15 37" src="https://user-images.githubusercontent.com/7733167/154848518-c3b6d8d9-68ce-4ce4-98da-4d110fdda5d2.png">

NumberInput
<img width="128" alt="Screen Shot 2022-02-20 at 17 52 53" src="https://user-images.githubusercontent.com/7733167/154848644-570139c3-e009-4761-afba-932f0bf9ebb9.png">
<img width="128" alt="Screen Shot 2022-02-20 at 17 53 33" src="https://user-images.githubusercontent.com/7733167/154848647-cc35b527-0d1b-4fa8-8a88-d02891433531.png">

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-02-21 06:48 UTC, ozgurkececioglu commented on packages/picasso/src/NumberInput/styles.ts
> +      },
As I mentioned in the PR description, I fixed the exceeding background color for control buttons while hovering here.

2022-02-21 07:54 UTC, LashaJini commented on packages/picasso/src/PasswordInput/styles.ts
> +      '-moz-appearance': 'textfield'
Not sure about safari, but I think we can ignore styling for firefox :man_shrugging:

2022-02-21 07:55 UTC, LashaJini approved these changes
Awesome :+1:

2022-02-21 08:43 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/styles.ts
> +      '-moz-appearance': 'textfield'
I've just copied what we have for NumberInput 🙂 we can discuss if something is missing for both of these components

2022-02-21 09:06 UTC, dmaklygin commented on cypress/component/PasswordInput.spec.tsx
> +    cy.get('body').happoScreenshot()
this screenshot is completely the same as in the previous use case. I'm not willing to add this screnshot to happo, because it does not add value for us. WDYT?

2022-02-21 09:19 UTC, dmaklygin commented on cypress/component/PasswordInput.spec.tsx
> +  it('shows password after toggle click', () => {
please, wrap it with `describe` block:
```
desribe('when toggle icon is clicked', () => {
  it('show password', () => {
})
```

2022-02-21 09:21 UTC, dmaklygin commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid='password-input-toggle'
I think, this `data-testid` should be dynamic and should be taken from dataTestID. wdyt?

2022-02-21 09:24 UTC, dmaklygin commented on packages/picasso/src/PasswordInput/test.tsx
> +    expect(container.firstChild).toMatchSnapshot()
I think snapshot tests are leftover: you've already covered the Component with internal visual tests as well as Happo's tests

2022-02-21 09:26 UTC, denieler commented on packages/picasso/src/NumberInput/styles.ts
> +      },
very nice 👍 ❤️  especially that you've spotted this issue 🤗

2022-02-21 09:26 UTC, dmaklygin commented on packages/picasso/src/PasswordInput/test.tsx
> +    const toggle = getByRole('button')
we prefer selectors by ID than by other attributes: https://toptal-core.atlassian.net/wiki/spaces/ENG/pages/1321992553/Frontend+Testing+-+React+Testing+Library+selectors#Which-selector-to-choose

2022-02-21 11:59 UTC, ozgurkececioglu commented on packages/picasso/src/NumberInput/styles.ts
> +      },
We talked with @separatio and decided to move this change into his PR. Because he is working on NumberInput and the change may look more relevant to that PR. So, I reverted this change.

2022-02-22 02:37 UTC, augustobmoura requested changes

2022-02-22 02:37 UTC, augustobmoura commented on packages/picasso/src/PasswordInput/styles.ts
> +      '-moz-appearance': 'textfield'
Also, MUI [already handles auto-preffixing](https://mui.com/getting-started/supported-platforms/#css-prefixing), I think we don't need to prefix `appeareance` by ourselves. `-webkit-inner-spin-button` still need to be prefixed though, because it is not specified on CSS and is WebKit specific

2022-02-22 02:37 UTC, augustobmoura commented on .changeset/twenty-clocks-yell.md
> +- add new component for form wrapper
I think this changeset can be merged with the other one at `.changeset/forty-cooks-flash.md`, it should be a good practice to keep just one changeset per PR

2022-02-22 02:37 UTC, augustobmoura commented on packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
> +PasswordInput.defaultProps = {}
I don't think this line is necessary. It's here because of the initial boilerplate? I think we should remove it

2022-02-22 02:37 UTC, augustobmoura commented on packages/picasso/src/PasswordInput/story/index.jsx
> +  .addExample('PasswordInput/story/Errored.example.tsx', 'Errored')
We should skip on the legacy visual-testing, we are migrating them to Happo. Just add `// picasso-skip-visuals` to them and remove the `__image_snapshot__` png files. Without the comment the legacy framework will try to run them as a normal test
```suggestion
  .addExample('PasswordInput/story/Default.example.tsx', 'Default') // picasso-skip-visuals
  .addExample('PasswordInput/story/Disabled.example.tsx', 'Disabled') // picasso-skip-visuals
  .addExample('PasswordInput/story/Errored.example.tsx', 'Errored') // picasso-skip-visuals
```

2022-02-22 07:14 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/test.tsx
> +    const toggle = getByRole('button')
Thanks for the information 🙂

2022-02-22 07:15 UTC, ozgurkececioglu commented on .changeset/twenty-clocks-yell.md
> +- add new component for form wrapper
I talked with @dmaklygin and we decided to go separate since these are different packages. Wdyt @dmaklygin? Should I merge them into one?

2022-02-22 07:20 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/story/index.jsx
> +  .addExample('PasswordInput/story/Errored.example.tsx', 'Errored')
Good catch man! Thank you

2022-02-22 08:49 UTC, separatio commented
Noting the issue we talked about here as well.

Clicking the space around the eye icon does not hide/show the password. It re-focuses the PasswordInput field, even if it is already focused.

https://user-images.githubusercontent.com/8407461/155095977-1cc2ce6c-6305-49fa-ba84-e1cb50cc1121.mp4

2022-02-22 09:07 UTC, ozgurkececioglu commented
@toptal-bot run all

2022-02-22 09:37 UTC, separatio approved these changes
Tested the component. Works as expected.
The bug I mentioned is universal for Inputs. Will add a separate bug.

2022-02-22 12:52 UTC, augustobmoura commented on .changeset/twenty-clocks-yell.md
> +- add new component for form wrapper
Oh ok, I didn't noticed the different packages, but yeah we need to bump both versions

2022-02-22 13:50 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid='password-input-toggle'
Sure, why not. Makes sense 👍

2022-02-22 13:54 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid='password-input-toggle'
But, it can be confusing since the `PasswordInput` already has `dataTestId` as a prop for the `outlined-input`. So, were you thinking about something a prop like `toggleButtonDataTestId`? @dmaklygin

2022-02-22 13:56 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +      'defaultValue' | 'type' | 'rows' | 'rowsMax' | 'multiline'
should we also omit `enableReset`? I am not sure how reset should work when there is an eye button on the right?

2022-02-22 13:56 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/story/Disabled.example.tsx
> +      <PasswordInput disabled value={value} onChange={handleChange} />
I clicked and the eye button works on disabled control. I wonder if this is the correct behavior?

2022-02-22 13:58 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid='password-input-toggle'
Ok, I think you mentioned something like:
```
data-testid={`${dataTestId}-toggle-button`}
```

2022-02-22 13:58 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
What is the value of this function? :)

2022-02-22 14:01 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid='password-input-toggle'
Please have a look at other components like Autocomplete for inspiration. They have `testIds`.

2022-02-22 14:37 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
You mean the operation can be done as an inline arrow function?

2022-02-22 14:55 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
yeah :) I inclined to think that if we create and abstraction, it should abstract something considerable inside. In this case, it looks like it is easier to understand the implementation than the name of the function :)

2022-02-22 15:01 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
Ok, since I don't have a preference for 1 liner function, I will follow yours because you have a reason 🙂

2022-02-22 15:02 UTC, denieler commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid={`${rest['data-testid']}-toggle`}
we need to make `testIds` object in the components and one of values will be `toogle`. Similar to https://github.com/toptal/picasso/blob/ffd0ef0610853b78ef902c41654ebb9d3a2164d5/packages/picasso/src/Avatar/Avatar.tsx#L28

2022-02-22 15:02 UTC, denieler commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +        }}
we also need to proxy `className` and `style`

2022-02-22 15:34 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +          data-testid={`${rest['data-testid']}-toggle`}
And values should be passed outside. We do not hardcore test ids inside components. @denieler looks like nice item for your Picasso guidelines.

2022-02-22 15:48 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
why :)

2022-02-22 15:50 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +      'defaultValue' | 'type' | 'rows' | 'rowsMax' | 'multiline'
We usually leave commenter to resolve comments. This way we make sure commenter is satisfied with changes :)

2022-02-22 15:57 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/test.tsx
> +const renderPasswordInput = (
Looks like you took this pattern form NumberInput test. Still I wonder if this function brings any value. Without it the code of the test would be
```
describe('PasswordInput', () => {
  it('shows and hides password', async () => {
    const { getByDisplayValue, getByTestId } = render(<PasswordInputRenderer dataTestid="password-input" />)

    const input = getByDisplayValue('asd') as HTMLInputElement
    const toggle = getByTestId('password-input-toggle')

    expect(input.type).toBe('password')

    fireEvent.click(toggle)

    expect(input.type).toBe('text')
  })
})
```
seems clear to me :man_shrugging:

2022-02-23 05:24 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +    const handleToggleVisibilityClick = () => {
Because, `Button.Circular` (or even more nested child components) might be using this callback function in some of the useEffects. So, if we won't provide useCallback here, there may be a party on some level 🙂

2022-02-23 07:26 UTC, separatio commented
![image](https://user-images.githubusercontent.com/8407461/155276668-c86833f2-1ad8-4f11-a544-32b3658065d9.png)

Disabled adornment is interactive. If I'm not mistaken, it should've been disabled as well.

2022-02-23 07:31 UTC, OleksandrNechai commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +        }}
I am not sure, but maybe since we use `classes` we could do root in it as well, and className just proxy?
```ts
...
        className={className}
        classes={{
          root: classes.root,
          input: classes.input
        }}
...

```

2022-02-23 07:32 UTC, OleksandrNechai approved these changes

2022-02-23 09:24 UTC, vvmarulin commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +      'defaultValue' | 'type' | 'rows' | 'rowsMax' | 'multiline' | 'enableReset'
If `enableReset` is omitted should we remove `onResetClick` too? Otherwise, it's confusing why we have `onResetClick` if we can't enable the reset button

2022-02-23 09:43 UTC, ozgurkececioglu commented on packages/picasso/src/PasswordInput/PasswordInput.tsx
> +      'defaultValue' | 'type' | 'rows' | 'rowsMax' | 'multiline' | 'enableReset'
Good catch! Thanks, I will also omit `onResetClick` 👍

2022-02-23 12:55 UTC, augustobmoura approved these changes

2022-02-23 13:13 UTC, merged