feat(FieldRequirements): add new component
toptal/picasso pull request #2476
Opened 2022-02-28 15:16 UTC by ozgurkececioglu

[FX-2525]

### Description

- FieldRequirements: added a new component
- forms/PasswordInput

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-02-28 15:21 UTC, ozgurkececioglu commented on packages/picasso/src/FormField/FormField.tsx
> +      {fieldRequirements}
To achieve placing the field-requirements below our generic field error, I had to do this.

2022-02-28 15:22 UTC, ozgurkececioglu commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    renderFieldRequirements?: (props: {
This has to be like that to get the latest value and error state from form-context.

2022-02-28 20:18 UTC, dmaklygin commented on packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
> +  )
:+1:

2022-02-28 20:23 UTC, dmaklygin commented on packages/picasso/src/FieldRequirements/types.ts
> +  validator: (value: any) => boolean
I'm thinking about possible types of `value`. Maybe we could be more specific about possible types?

2022-02-28 20:28 UTC, dmaklygin commented on packages/picasso/src/FieldRequirements/story/Default.example.tsx
> +    validator: value => value.length < 10
shouldn't it be: `value.length <= 10` ?

2022-02-28 20:44 UTC, dmaklygin approved these changes
Great job!

2022-03-01 07:19 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/story/Default.example.tsx
> +    validator: value => value.length < 10
Copilot mistake 🙂 I'll fix it.

2022-03-01 07:21 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/types.ts
> +  validator: (value: any) => boolean
There is a perfect match [ValueType](https://github.com//toptal/picasso/blob/f3da7ae3a8bc3aad1ea67ff8ad81ce2de45aa989/packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx#L23) but it is not exported. And most other places also use `any`. I would prefer exporting ValueType and using it around the repo. WDYT?

2022-03-01 08:31 UTC, vvmarulin commented
@ozgurkececioglu 

Checked the demo. Everything works great except for one small thing. When I tried to click submit button after I entered the password (focus on password field), the button wasn't clicked because there is an animation. That is a UX problem because it's unclear from the user's perspective that the button hasn't been clicked.

https://user-images.githubusercontent.com/3861498/156132937-b1a2cf48-8fb1-4972-b148-51e83ff4df66.mp4

You can see on the video, that after the first click on the submit button nothing happened. And only after the second click a validation error for the second field was shown.

Maybe we need some delay for animation so the button doesn't move immediately? WDYT?

2022-03-01 09:54 UTC, OndrejTuma commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        />
I'm wondering in which case this can happen. Because to me it seems that either valid or error state are possible. I can only think of some validation that is somewhat informative only (does not reach a valid state) but is not considered in the `validate` function of FieldWrapper. And that seems like a hell of an edgecase 🙂

2022-03-01 10:00 UTC, vvmarulin commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        />
When you focus on the password field for the first time it will show a list with bullet icons. Also while you typing a new value for the first time the requirements will either have a bullet icon or check icon.

2022-03-01 11:19 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        />
@OndrejTuma according to our designs here: https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=702%3A11760 there is a default state that we are showing bullets only as @vvmarulin explained perfectly.

2022-03-01 12:12 UTC, ozgurkececioglu commented on packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
> +          setTimeout(() => {
According to our decision, there should be a delay to start hiding animation for the requirements after onBlur. `transitionDelay` didn't work so I had to provide this solution.

Another possibility is that I can implement my own transition animation with pure CSS, rather than using MUI's Collapse component.

2022-03-01 12:15 UTC, OndrejTuma commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        />
Oh, I missed that 🙇  thanks for explanation

2022-03-01 12:18 UTC, OndrejTuma approved these changes
GJ 👍

2022-03-01 12:39 UTC, vvmarulin approved these changes

2022-03-01 14:45 UTC, separatio commented on .changeset/dirty-points-applaud.md
> +- add new prop to render field requirements if exist
I'd rephrase this to: `- add new prop to render passed field requirements`

2022-03-01 15:28 UTC, TomasSlama commented on packages/picasso/src/FieldRequirements/FieldRequirements.tsx
> +  timeout: 500
is this related to the `TIMEOUT` const in the PasswordInput file? maybe we can reuse it?

2022-03-01 15:28 UTC, TomasSlama commented on packages/picasso/src/FieldRequirements/styles.ts
> +    fieldRequirementItem: {
maybe I'm blind, but I didn't find usage of this class?

2022-03-01 15:28 UTC, TomasSlama commented on packages/picasso-forms/src/PasswordInput/validators.ts
> +}
Should we unit test those validators?

2022-03-01 15:51 UTC, ozgurkececioglu commented on packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
> +    const validationResult =
I was planning something different but forgot to update this after changing my mind. Good catch!

2022-03-01 16:46 UTC, augustobmoura requested changes

2022-03-02 09:29 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/styles.ts
> +    fieldRequirementItem: {
It is being used inside `FieldRequirementItem`. see [here](https://github.com//toptal/picasso/blob/c157f45afe2907210b0ba8840c52f4e950c468c8/packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx#L39)

2022-03-02 11:25 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/types.ts
> +  validator: (value: any) => boolean
I created an identical clone type into FieldRequirements and started using it as generic base type 👍

2022-03-02 12:30 UTC, TomasSlama commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        />
```suggestion
      const Icons = {
        error: CloseMinor16,
        // ..
      }
      const IconComponent = Icons[status]
```

and also I think we should not hard code test id `data-testid={`${dataTestId}-valid-icon`}`. So I would suggest `testIds.validIcon`

2022-03-02 13:27 UTC, TomasSlama commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +import { CheckMinor16, CloseMinor16 } from '../Icon'
```suggestion
import Typography from '../Typography'
import Grid from '../Grid'
import styles from './styles'
import { CheckMinor16, CloseMinor16, Bullet16 } from '../Icon'
```

2022-03-02 13:27 UTC, TomasSlama commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +        data-testid={`${dataTestId}-${status}-icon`}
we should not have any hardcoded data test id in Picasso. `testIds: { successIcon: string, ...}`

2022-03-02 14:12 UTC, ozgurkececioglu commented on packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
> +import { CheckMinor16, CloseMinor16 } from '../Icon'
I'm so use to clean these imports with some shortcuts but here, we are not using I guess 🙂 thanks 👍

2022-03-02 16:48 UTC, augustobmoura requested changes

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +      value?: ValueType
Shouldn't this type be `TInputValue`? This value would be the same as the input right? So in a number input a number, in a password a string, etc

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    }) => React.ReactNode
I don't know if I understood it correctly. I'm not seeing the difference between a function returning a ReactNode and a common component (in fact, FunctionComponents have essentially the same signature as this prop).

Why would calling a function that returns a new ReactNode not trigger a react re-render, but directly creating a ReactNode would do it?

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
> +      value={(value ?? '') as string}
Why not type `value` as a `string` instead of type asserting it? Passwords will always be a `string` (at least for now)

If the problem is that `FieldWrapper` on accepts an non-generic `value`, refer to my comment on `FieldWrapper.tsx` about using `TInputValue` as the type of value

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso/src/FieldRequirements/FieldRequirements.tsx
> +export interface Props<TInputValue extends ValueType = ValueType>
I don't think that this should have a default type, it's better to require the developer to specify it. Being too generic of type can lead to type assertion hacks or untyped code.

FieldWrapper for example, requires it to be defined by the developer https://github.com/toptal/picasso/blob/510c31766197cce7df7191cb8c27df4b967920e0/packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx#L36

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso/src/FieldRequirements/FieldRequirements.tsx
> +  TInputValue extends ValueType = ValueType
I don't think that this should have a default type, same argument as in the first comment on `FieldRequirements.tsx`

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso/src/FieldRequirements/index.ts
> +  TInputType extends ValueType = ValueType
I don't think that this should have a default type, same argument as in the first comment on `FieldRequirements.tsx`

2022-03-02 16:48 UTC, augustobmoura commented on packages/picasso/src/FieldRequirements/types.ts
> +export interface FieldRequirement<TInputType extends ValueType = ValueType> {
I don't think that this should have a default type, same argument as in the first comment on `FieldRequirements.tsx`

2022-03-03 10:23 UTC, ozgurkececioglu commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    }) => React.ReactNode
Your logic is totally fine. I like it. I've just not been able to find a solution to pass the same component result to `FieldWrapper`, before passing it as `ReactNode` to `FormField`. I've created a variant branch to talk with more solid examples here: https://github.com/toptal/picasso/tree/fx-2525-add-strength-validations-section-to-passwordinput-variant

To achieve your suggestion, as you can see [here](https://github.com/toptal/picasso/blob/4f3d761e4296be3d817121333d6df2624a9d607c/packages/picasso-forms/src/PasswordInput/PasswordInput.tsx#L54), I had to add one more wrapper to pass `showContent` to my `FieldRequirementsComponent` to start and stop the animation. If you run storybook for this variant branch, you would see that `FieldRequirementsComponent` is being recreated after each focusing and bluring. Even if we accept that, because of the recreation, animations couldn't work.

With the render function solution, I've just postponed the return phase to `FieldWrapper's render` and it solved the issue.

If you assist on this variant branch with a working solution, I would definitely be happy and accept that 🙂

2022-03-03 12:44 UTC, separatio commented
Didn't finish manually testing, but please pay attention to min-maxing. I have exactly 10 characters written, and the field is red.
![image](https://user-images.githubusercontent.com/8407461/156566949-1b800938-c1f0-4fc1-87c8-99dcd2e6c7c8.png)

2022-03-03 12:44 UTC, separatio commented
Haven't checked designs yet, but it feels weird that the field is not red while it's clearly failing validation.
![image](https://user-images.githubusercontent.com/8407461/156567233-296a38ed-e1a7-49c0-be7b-35a9baeae640.png)

2022-03-03 12:56 UTC, ozgurkececioglu commented
> Haven't checked designs yet, but it feels weird that the field is not red while it's clearly failing validation. ![image](https://user-images.githubusercontent.com/8407461/156567233-296a38ed-e1a7-49c0-be7b-35a9baeae640.png)

Again, it is about our input fields globally. I've just used a very simple one to accommodate the validations running. You can check others from: https://picasso.toptal.net/?path=/story/forms-input--input

I think in focus, none of our fields provide an error signal.

2022-03-04 02:05 UTC, augustobmoura commented on packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
> +    }) => React.ReactNode
Hmmm, I think I understand the problem now. `FieldRequirements` needs an intermediate value, so we create an anonymous component to wrap it up.

The difference between a simple function and a component, in this case, is that when using the JSX syntax the function identity is used on reconciliation. Because we are creating an anonymous component every time, the reconciliation fails every time.

Maybe there's a way to work around that, but I don't think the effort is worth it. We can keep it as a function then. Thanks for writing the example repo for illustration!

2022-03-04 02:06 UTC, augustobmoura approved these changes

2022-03-04 06:38 UTC, merged