feat(Rating.Stars): rename old Rating component to Rating.Stars
toptal/picasso pull request #2481
Opened 2022-03-03 00:17 UTC by augustobmoura

[FX-2521](https://toptal-core.atlassian.net/browse/FX-2521)

### Description

Renaming component `Rating` to `Rating.Stars`

### How to test

- FIXME: Add the steps describing how to verify your changes

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-03 12:36 UTC, ozgurkececioglu commented on packages/picasso-forms/src/Rating/Rating.tsx
> +  Stars
What about the thumb? Shouldn't it be included?

2022-03-03 12:47 UTC, ozgurkececioglu requested changes

2022-03-03 12:47 UTC, ozgurkececioglu commented on packages/picasso-forms/src/Form/story/TitleCase.example.tsx
> +      <Form.Rating.Stars
Not sure why but this example is not working on storybook. You can't change the field's value and submit

2022-03-03 15:36 UTC, augustobmoura commented on packages/picasso-forms/src/Form/story/TitleCase.example.tsx
> +      <Form.Rating.Stars
It also doesn't work on [master](https://picasso.toptal.net/?path=/story/picasso-forms-form--form), I think it's an issue with how the test was written, but I'm not so sure

2022-03-03 15:37 UTC, augustobmoura commented on packages/picasso-forms/src/Rating/Rating.tsx
> +  Stars
The `Rating.Thumbs` component will be added in a different [issue](https://toptal-core.atlassian.net/browse/FX-2538), because we actually missed adding it to picasso-forms when creating it

2022-03-03 15:40 UTC, separatio commented on bin/build.js
> +const compile = function (tsConfig, packageJson, packageRootDir) {
What's up with so many unrelated changes? Did you run prettier on the whole codebase?

2022-03-03 16:06 UTC, separatio reviewed
`describe('Rating', () => {` can be found in `cypress/component/RatingThumbs.spec.tsx`. This should be changed as well to describing `Rating.Thumbs`. It would make it clearer.

Can you please add it to this PR since it concerns renaming of Rating components?

2022-03-03 16:13 UTC, separatio requested changes
Comparing picasso.toptal.net with your version, it seems like we lost some props for the Rating component overall.

![image](https://user-images.githubusercontent.com/8407461/156604872-64d14640-0d86-437f-9293-263442087e27.png)
![image](https://user-images.githubusercontent.com/8407461/156604946-6cc32679-8ca6-412b-8458-f9b4931e2fc6.png)

2022-03-03 16:57 UTC, separatio commented
@toptal-bot run all

2022-03-04 08:14 UTC, OndrejTuma commented on packages/picasso-codemod/src/v19.0.0/rename-rating-stars/rename-rating-stars.js
> +        )
👍

2022-03-04 08:18 UTC, OndrejTuma commented on .changeset/grumpy-crabs-exist.md
> +consistently accomodate new variants, like the recently implemented `Rating.Thumbs`
I think its good to know why the change was introduced. There might always be someone who'd like to know 🙂

2022-03-04 09:47 UTC, OndrejTuma commented
Please @augustobmoura add also changeset for codemod, don't make the same mistake I did 😁

2022-03-04 09:59 UTC, OndrejTuma requested changes
Please @augustobmoura add also changeset for codemod, don't make the same mistake I did 😁

2022-03-04 10:07 UTC, OndrejTuma commented on packages/picasso-forms/src/Form/story/TitleCase.example.tsx
> +      <Form.Rating.Stars
You're right @augustobmoura - there are two Ratings on the page and both have same `name` - and the id for each star is composed of name and value. Rename it and it should work just fine 👍

2022-03-04 10:09 UTC, OndrejTuma commented on packages/picasso-forms/src/Form/story/TitleCase.example.tsx
>          name='rating'
```suggestion
        name='rating2'
```

2022-03-08 05:29 UTC, ozgurkececioglu approved these changes
Tested. Looks good 👍

2022-03-08 09:17 UTC, OndrejTuma approved these changes
LGTM

2022-03-08 11:20 UTC, separatio approved these changes
Looks good! :+1: Tested and checked code.

2022-03-08 15:00 UTC, augustobmoura commented
@toptal-bot run package:alpha-release

2022-03-10 20:44 UTC, merged