chore: [SAT-1211] Add useIsomorphicLayoutEffect for SSR support
toptal/picasso pull request #2521
Opened 2022-03-15 11:21 UTC by deniskaber

[FX-NNNN]

### Description

This adds `useIsomorphicLayoutEffect` hook to support using Picasso components in SSR mode. 
Also adds an eslint rule to use `useIsomorphicLayoutEffect` over `useLayoutEffect`

### How to test

- FIXME: Add the steps describing how to verify your changes

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-21 09:34 UTC, TomasSlama commented on packages/shared/src/hooks/use-isomorphic-layout-effect.ts
> +  typeof document !== 'undefined' ? useLayoutEffect : useEffect
I'm wondering if it might be even useful for users of Picasso in their projects. Maybe we can reexport this hook from `@toptal/picasso/utils` what do you think?

Also we already have `isBrowser` util function in Picasso. Maybe we could move the implementation to shared so we are able to reuse the function here. And just reexport it from `picasso/utils`

What do you think?

2022-03-22 07:13 UTC, TomasSlama commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
> +import useIsomorphicLayoutEffect from '@toptal/picasso/utils/use-isomorphic-layout-effect'
here in the Picasso provider package, we should use the implementation from picasso-shared, because this way we are introducing circular dependency. Picasso is depending on the provider and vice versa.

2022-03-22 07:13 UTC, TomasSlama commented on packages/picasso/src/utils/index.ts
> +export { default as useIsomorphicLayoutEffect } from './use-isomorphic-layout-effect'
I would move implementation back to shared and here we can just reexport it. We can do the same with `isBrowser` so we can use it even in shared.

2022-03-22 08:54 UTC, deniskaber commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
>  import { useLayoutEffect } from 'react'
It was done because we restricted import of picasso-shared here - https://github.com/toptal/picasso/blob/master/.eslintrc.js#L5, but since we moved useIsomorphicLayoutEffect to picasso/utils - it's no longer the case, it's fixed

2022-03-22 08:54 UTC, deniskaber commented on packages/shared/src/hooks/use-isomorphic-layout-effect.ts
> +  typeof document !== 'undefined' ? useLayoutEffect : useEffect
Yep, that's actually a great idea! Thanks! I've moved the hook to utils and reused isBrowser helper.

2022-03-22 09:03 UTC, denieler commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
> +import useIsomorphicLayoutEffect from '@toptal/picasso/utils/use-isomorphic-layout-effect'
interesting, our eslint rules or syncpack checks should fail on such imports, which are not mentioned in `package.json` file. We need to check them out.

2022-03-22 09:03 UTC, denieler requested changes
we should not import in picasso-provider package anything from picasso package

2022-03-22 09:08 UTC, denieler commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
can this be converted to `useEffect` maybe instead?

2022-03-22 09:08 UTC, denieler commented on packages/picasso/src/TreeView/PointNode/PointNode.tsx
> -    useLayoutEffect(() => {
maybe convert it to `useEffect`?

2022-03-22 09:08 UTC, denieler commented on packages/picasso/src/StaticTreeView/StaticTreeView.tsx
> -  useLayoutEffect(() => {
same here, maybe to `useEffect`?

2022-03-22 09:09 UTC, denieler commented on packages/picasso/src/DatePicker/DatePicker.tsx
> -  useLayoutEffect(() => {
maybe also possible to convert to `useEffect`

2022-03-22 11:17 UTC, deniskaber commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
> +import useIsomorphicLayoutEffect from '@toptal/picasso/utils/use-isomorphic-layout-effect'
The same works for picasso-shared - it also depends on picasso-provider and it can also cause circular dependency.

2022-03-22 11:17 UTC, deniskaber commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
I suggest to do it in a separate ticket as it doesn't relates to the current one and it will require testing in the projects that use this component in order to be shure that applied changes does not break anything.

2022-03-22 11:20 UTC, denieler commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
it does relate, because then you don't need to convert it to isomorphic effect

2022-03-22 11:21 UTC, denieler commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
> +import useIsomorphicLayoutEffect from '@toptal/picasso/utils/use-isomorphic-layout-effect'
exactly... then probably if you need such hook in a provider - implement it in the picasso-provider package

2022-03-22 15:01 UTC, deniskaber commented on packages/picasso-provider/src/Picasso/FontsLoader.tsx
> +import useIsomorphicLayoutEffect from '@toptal/picasso/utils/use-isomorphic-layout-effect'
I would suggest to keep using `useLayoutEffect` as this logic for font loading would require a bigger re-factoring to support SSR and we can move to isomorphic version when we'll refactor FontLoader to fully support SSR.

2022-03-22 15:24 UTC, deniskaber commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
Do you know projects that use this component?

2022-03-22 15:25 UTC, deniskaber commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
We now stick with the same `useLayoutEffect` hook when using component in browser. If we would change it to `useEffect` in browser we can experience undesirable glitches in projects using these components.

2022-03-22 16:15 UTC, denieler commented on packages/picasso/src/TreeView/useNodes.ts
> -  useLayoutEffect(() => {
> If we would change it to useEffect in browser we can experience undesirable glitches in projects using these components.

I understand that, but usage of `useLayoutEffect` could be a mistake from the beginning. If it's possible - I would double-check that, because in this case we would have less tech debt if we can just replace it to `useEffect`

2022-03-24 08:55 UTC, denieler commented on .eslintrc.js
> +                '`useLayoutEffect` causes a warning in SSR. Use `useIsomorphicLayoutEffect`'
I would add also from where to use `useIsomorphicLayoutEffect`, like `Use useIsomorphicLayoutEffect from @toptal/picasso-shared`, or something like that

2022-03-24 08:56 UTC, denieler approved these changes

2022-03-24 12:42 UTC, TomasSlama approved these changes

2022-03-24 13:02 UTC, OndrejTuma approved these changes
Good job 👍

2022-03-24 13:56 UTC, dmaklygin commented
Hey :)
Actually, I didn't get one thing: why only part of `useLayoutEffect` usages was replaced by `useIsomorphicLayoutEffect`. I can see some of the components are not touched.

2022-03-24 15:26 UTC, merged

2022-03-24 16:47 UTC, denieler commented
@deniskaber @dmaklygin did you guys find those missing `useLayoutEffect`, which were not replaced?