FX-2502 Introduce status feature
toptal/picasso pull request #2536
Opened 2022-03-24 11:09 UTC by ozgurkececioglu

[FX-2502]

### Description

- updated `OutlinedInput` to support `status`
- extracted some common logic from `FieldWrapper` to new `InputFieldWrapper` for the input components which renders `OutlinedInput` underneath.
- all of the input components and their field wrappers were updated to support `status` prop
- also deprecation warnings are added for `error` prop to related input components

### How to test

- testing all input components and some of the form usages would be many helpful

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-24 11:18 UTC, denieler approved these changes

2022-03-24 11:51 UTC, vvmarulin requested changes
I've just tested the new story locally and I got the following issues:

1. If the input value is invalid it doesn't have a red border

    <img width="816" alt="Screenshot 2022-03-24 at 18 44 54" src="https://user-images.githubusercontent.com/3861498/159909879-c96cbd6f-fe5d-430a-bd33-a1f552834367.png">

2. When I entered the correct value I didn't see the green check icon

    <img width="811" alt="Screenshot 2022-03-24 at 18 45 08" src="https://user-images.githubusercontent.com/3861498/159910124-8a4addb3-b482-4f25-a7ee-ae94971eba48.png">

Also, I think that would be great to have more examples. The form itself can stay simple. But at least add client validation so the field is more interactive. And also I would add two more forms so you can test and understand how it works depending on when validation taking place: on change, on blur, and on submit

2022-03-24 12:17 UTC, vvmarulin commented on packages/picasso-forms/src/InputFieldWrapper/InputFieldWrapper.tsx
> +export default InputFieldWrapper
There is a small concern I have regarding this new field wrapper. As I know `<FieldWrapper />` is used in other projects to create new custom fields that behave similarly to Picasso input fields. https://github.com/toptal/talent-portal-frontend/search?q=FieldWrapper

But in this PR some of the functionality was exported to the new `<InputFieldWrapper />` that isn't exported from `@toptal/picasso-forms` as `<FieldWrapper />` does ([code](https://github.com/toptal/picasso/blob/fa0bacb0e48852a7d1063f69f4ecc8d54184f456/packages/picasso-forms/src/index.ts#L45)). Also there is no information about the change in the changeset. I think that might lead to some unexpected behavior in the other projects.

As a solution, I'd do `export InputFieldWrapper as FieldWrapper` in this [file](https://github.com/toptal/picasso/blob/master/packages/picasso-forms/src/index.ts#L45).

2022-03-25 10:16 UTC, OndrejTuma commented on cypress/component/NumberInput.spec.tsx
> +  })
Since we are adding visual test for NumberInput, is it worth adding also error state? 🤔

2022-03-29 09:32 UTC, vvmarulin approved these changes
There is one small thing left (see the comment) but everything else looks good! You've done an amazing job! 🔥 👍

2022-03-29 09:32 UTC, vvmarulin commented on packages/picasso-forms/src/Form/story/Status.example.tsx
> +const Example = () => (
I think you forgot to add this story to `packages/picasso-forms/src/Form/story/index.jsx`. At least I can't find it in the storybook when I'm running it locally.

2022-03-29 09:39 UTC, ozgurkececioglu commented on packages/picasso-forms/src/Form/story/index.jsx
> -  }) // picasso-skip-visuals
Do we have a reason for removing this example?

2022-03-29 11:53 UTC, ozgurkececioglu commented on cypress/component/NumberInput.spec.tsx
> +  })
@OndrejTuma I added it here: https://github.com/toptal/picasso/pull/2536/commits/37620ef429b0598f1f8a0bea14e91e408aa5f4bf

2022-03-29 11:54 UTC, ozgurkececioglu commented on packages/picasso-forms/src/Form/story/Status.example.tsx
> +const Example = () => (
@vvmarulin I added back the story here: https://github.com/toptal/picasso/pull/2536/commits/65cfd154c36e57be48f19354ea124b9d8e0128bb

2022-03-29 13:20 UTC, dmaklygin commented on cypress/component/Autocomplete.spec.tsx
> +        <TestAutocomplete value='Croatia' status='error' />
the test is skipped anymore :)

2022-03-29 13:21 UTC, dmaklygin approved these changes

2022-03-29 13:21 UTC, ozgurkececioglu commented on cypress/component/Autocomplete.spec.tsx
> +        <TestAutocomplete value='Croatia' status='error' />
Wdym? I couldn't get it 🙂

2022-03-29 13:57 UTC, OndrejTuma approved these changes
Good job man 💪

2022-03-29 14:34 UTC, ozgurkececioglu commented
@toptal-bot run all

2022-03-29 15:30 UTC, merged