feat(Badge): consolidate OverlayBadge into Badge
toptal/picasso pull request #2561
Opened 2022-03-29 15:02 UTC by augustobmoura

[FX-2164](https://toptal-core.atlassian.net/browse/FX-2164)

### Description

As discussed in the issue, the only difference between `OverlayBadge` and `Badge` (the only ones that should exist) is that `OverlayBadge` overlays it's children and `Badge` is a static element that doesn't have children. We merged them together into a single `Badge` that is static without children and when it has children it overlays it. I also updated their style of them to better follow BASE 2.0

### How to test

- Checkout storybook for code examples and visual correctness, it shouldn't have an `OverlayBadge` page anymore and the `Badge` page should have an overlay example
- Attention to happo visual tests, they should have changed slightly and should be following BASE more closer

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-29 15:36 UTC, augustobmoura commented
@toptal-bot run all

2022-03-30 10:03 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +  content: number | string
let's make always `string`, for example, and make a codemod for migration? it doesn't make sense to keep both types

2022-03-30 10:04 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +    size = 'medium',
why the default size has changed?

2022-03-30 10:05 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +    <MuiBadge
can we don't use MUI component?

2022-03-30 10:34 UTC, ozgurkececioglu commented on packages/picasso/src/Badge/Badge.tsx
> +const thresholds: { [k in SizeType]: number } = {
I just wanted to know if you have better reasoning or is it just a preference for not using Record here?
```suggestion
const thresholds: Record<SizeType, number> = {
```

2022-03-30 16:42 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +    size = 'medium',
I think the motivation is that the default size for the `OverlayBadge` was `medium` instead of `large`. But you are right, I think it makes more sense to keep the default as large and change the codemod to add an explicit size in case the size prop is missing on `OverlayBadge`s

2022-03-30 16:42 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +    <MuiBadge
We could, but it would make the implementation a lot more complex

2022-03-31 00:18 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +const thresholds: { [k in SizeType]: number } = {
No reasoning, both should represent the same type. `Record` looks terser in fact, I will refactor to that

2022-03-31 02:38 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +    <MuiBadge
Do you think we should pursue removing the dependency on MuiBadge?

2022-03-31 02:39 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +    size = 'medium',
Should be back to `large` now, and the codemod should add `size` as `medium` from `OverlayBadge`s that are being refactored and are missing the `size` prop

2022-03-31 07:04 UTC, dmaklygin commented on packages/picasso-codemod/src/v20.0.0/overlay-badge/overlay-badge.ts
> +export default transform
👍

2022-03-31 07:07 UTC, dmaklygin commented on packages/picasso/src/Badge/Badge.tsx
> +  content: number | string
I also opt for string.
use cases with numbers should be handled like you said:
> We could try to parse content as a number if max is provided and then clamp it down

2022-03-31 07:10 UTC, dmaklygin commented on packages/picasso/src/Badge/Badge.tsx
> +          : format(content, size, max)
looks complex here.
wdyt if we create a separate hook and return badge content?

2022-03-31 07:14 UTC, dmaklygin commented on packages/picasso/src/Badge/styles.ts
> +      padding: '.3em',
Shouldn't we use only `rem` ?

2022-03-31 07:17 UTC, dmaklygin commented on packages/picasso/src/Badge/test.tsx
> +
let's add test cases when `titleCase` is passed

2022-03-31 07:17 UTC, dmaklygin reviewed
good job!

2022-03-31 07:44 UTC, TomasSlama commented on packages/picasso/src/Badge/Badge.tsx
> +  content: number | string
Guys, but if I remember correctly, Badge is used almost always with numbers, so we actually force our users to parse numbers to strings all the time. I don't find it as a very good experience

2022-03-31 08:01 UTC, TomasSlama requested changes
we are not following [base design](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/c06eea4f0ccc87544e40354d007ce9b220c9b0cb/files/c64770f3-7c15-4b47-be53-7e2eb1679f41/layers/1DE6B39D-9967-43F7-BC80-BA66C07F3EB6?mode=build&selected=4049135237-791762D7-78AE-4F81-9C8F-B9507A027D24) here.

Badge with two numbers should be always circle. Now medium badge with number 25 is not 16x16 as shown in base.

2022-03-31 08:02 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> +  content: number | string
for us forcing `number` type is definitely better codewise. But I would check how this prop is used in other projects and make a decision based on that

2022-03-31 08:28 UTC, denieler commented on packages/picasso/src/Badge/Badge.tsx
> -Badge.defaultProps = {
we should not remove defaultProps

2022-04-01 03:16 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +  content: number | string
Well it looks like there only two places in the organization that use OverlayBadge: [talent-portal](https://github.com/toptal/talent-portal-frontend/blob/7d335b200426c67e1b50446b4c401948d1379ad6/hosts/talent-portal/src/modules/core/components/IconWithBadge/IconWithBadge.tsx
) and [staff-portal](https://github.com/toptal/staff-portal/blob/8047b4f501b24310201c7a82662c4da53a75e1f4/namespaces/facilities/libs/operational-issues/src/containers/OperationalIssuesButton/OperationalIssuesButton.tsx
). The component `IconWithBadge` from talent-portal is only used [here](https://github.com/toptal/talent-portal-frontend/blob/ce3b8d7cef44e14f3dada40db568cf36921309b2/hosts/talent-portal/src/modules/notifications-center/components/NotificationButton/NotificationButton.tsx). So I think it can be safe to assume that the only case is using it with numbers

2022-04-01 03:23 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +          : format(content, size, max)
I splitted the logic in 2 methods, one for formatting numbers and the other for formatting text, it should make things clearer

2022-04-05 02:53 UTC, augustobmoura commented
> we are not following [base design](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/c06eea4f0ccc87544e40354d007ce9b220c9b0cb/files/c64770f3-7c15-4b47-be53-7e2eb1679f41/layers/1DE6B39D-9967-43F7-BC80-BA66C07F3EB6?mode=build&selected=4049135237-791762D7-78AE-4F81-9C8F-B9507A027D24) here.
> 
> Badge with two numbers should be always circle. Now medium badge with number 25 is not 16x16 as shown in base.

![image](https://user-images.githubusercontent.com/5845160/161669135-c541b1a4-be06-453f-9553-804ca038f461.png)

Some badge sizes can actually be in a different shape, those with 3 characters or more for example. I adjusted the padding between them to show as a circle when these requirements are met

2022-04-05 13:23 UTC, dmaklygin commented on packages/picasso/src/Badge/Badge.tsx
> +  return content > trimThreshold ? `${trimThreshold}+` : String(content)
👍

2022-04-05 13:40 UTC, augustobmoura commented on packages/picasso/src/Badge/styles.ts
> +      padding: '.3em',
`font-size` in being setted on this component, so it's indirectly related to `rem`, I don't think `rem` should be the only way to represent relative sizes. I could calculate this `em` in terms of the `font-size` value, but that would make it more magical

2022-04-05 13:40 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +  return content > trimThreshold ? `${trimThreshold}+` : String(content)
I agree, I will create a test for it

2022-04-05 13:52 UTC, ozgurkececioglu commented
<img width="925" alt="Screen Shot 2022-04-05 at 16 48 32" src="https://user-images.githubusercontent.com/7733167/161769224-4fdce5cd-8852-4d8e-b97a-ff02e83ae2bb.png">

I'm not sure it is an issue but I saw this

2022-04-05 14:57 UTC, augustobmoura commented
> <img alt="Screen Shot 2022-04-05 at 16 48 32" width="925" src="https://user-images.githubusercontent.com/7733167/161769224-4fdce5cd-8852-4d8e-b97a-ff02e83ae2bb.png">
> 
> I'm not sure if it is an issue but I saw this

Yep, I was fixing this together with other issues, should be up  now

2022-04-05 15:00 UTC, dmaklygin approved these changes

2022-04-05 15:16 UTC, denieler commented on packages/picasso/src/Badge/test.tsx
> -
why remove jest snapshots?

2022-04-05 17:28 UTC, augustobmoura commented
> in Happo visual tests Badges "jumped" a bit. It feels like it is unnecessary change thinking

The "jump" is because we switched from a simple div to using MUI `Badge`, the small differences are expected and I commented about them in the issue description. The new modifications are actually closer to what is expected in the BASE 2.0 figma page

2022-04-05 18:58 UTC, denieler commented on packages/picasso/src/Badge/test.tsx
> -
@augustobmoura yes, but there is a phrase

> For the above reasons, the use of snapshot testing is discouraged and although there are cases when they are useful (for example in [Chronicles Frontend](https://github.com/toptal/chronicles-frontend) project), other approaches to unit tests are preferred.

we found already many times snapshot testing very useful in Picasso, especially in upcoming MUI 5 upgrade it will be

2022-04-05 19:11 UTC, denieler commented on packages/picasso/src/Badge/styles.ts
> +      padding: '.1em',
why?

2022-04-06 13:39 UTC, TomasSlama approved these changes

2022-04-06 13:39 UTC, TomasSlama commented on packages/picasso/src/Badge/story/Sizes.example.tsx
>          <Container top='small' bottom='medium' flex>
```suggestion
        <Container top='small' bottom='medium' flex gap="small">
```

Since container accepts `gap`, we can simplify the examples. We could remove all the inner containers.

2022-04-06 13:39 UTC, TomasSlama commented on packages/picasso/src/Badge/test.tsx
> -
It was agreed, that we should keep snapshots of MUI components used, so when upgrading to a new version of MUI, we know exactly what changed. As I understand it, it was an issue in the past when upgrading MUI to a new major version, that they introduced unexpected changes.

2022-04-06 15:18 UTC, augustobmoura commented on packages/picasso/src/Badge/test.tsx
> -
I didn't know about the convention of keeping snapshots for MUI components, I will re-add them.

But I still think these tests are kinda useless. We shouldn't expect an HTML structure from MUI, and neither should we test if a component "renders" with snapshots

2022-04-06 15:25 UTC, augustobmoura commented on packages/picasso/src/Badge/styles.ts
> +      padding: '.1em',
This is spacing for making the shape-changing breakpoint (from a [circle to an elongated pill](https://github.com/toptal/picasso/pull/2561#issuecomment-1088215020)), MUI adds padding that is not the same as we are expecting in BASE (on [figma](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=60%3A45)), instead of using absolute numbers (there are some caveats on using the same pixel-perfect padding as on Figma) I preferred using relative units.

Why it doesn't look good? I didn't fully understand the question. Do you have a better suggestion?

2022-04-06 15:27 UTC, augustobmoura commented on packages/picasso/src/Badge/Badge.tsx
> +   */
I reverted it, my editor formatter did that

2022-04-06 15:40 UTC, augustobmoura commented on packages/picasso/src/Badge/styles.ts
> +      padding: '.1em',
For better illustration:

- This is how it looks without overriding the padding:
  ![image](https://user-images.githubusercontent.com/5845160/162012689-efab80a1-f7f6-4d14-8966-852d090ecf1f.png)
  You can see that because of the default padding from MUI we have a pill always, instead of a circle on shorter texts.
  
- Removing the padding also doesn't help:
  ![image](https://user-images.githubusercontent.com/5845160/162013006-7a6aae9d-5718-435a-a332-a10e805d77ec.png)
  Even thought now we have both circles and pills depending on the text length, it's still not quite what is [expected in BASE](https://github.com/toptal/picasso/pull/2561#issuecomment-1088215020) (3 chars length should become a pill, was thing that is not happening here).
- `0.1em` and `0.3em` for `large` was a good middle point however:
  ![image](https://user-images.githubusercontent.com/5845160/162013519-d01c7c20-22da-46f4-a76e-831c80e1ae97.png)
  A lot more closer to what the source design expects


If you have a better idea on how to solve this, please let me know

2022-04-07 07:38 UTC, ozgurkececioglu approved these changes

2022-04-07 16:50 UTC, denieler commented on packages/picasso/src/Badge/styles.ts
> +const getSizeProps = (unitInRem: string): StyleRules[keyof {}] => ({
readability of the code has being decreased

2022-04-07 20:59 UTC, augustobmoura commented
@toptal-bot run all

2022-04-08 07:40 UTC, denieler commented on packages/picasso/src/Badge/story/Variants.example.tsx
> +    <Container top='small' flex gap='small'>
👍 way better look for the example code 🙇‍♂️

2022-04-08 07:41 UTC, denieler commented on packages/picasso/src/Badge/styles.ts
> +      padding: `0 ${rem('1px')}`,
```suggestion
      padding: `0 1px`,
```
`rem` utility can end up in some float number or some rounding

2022-04-08 07:42 UTC, denieler commented on packages/picasso/src/Badge/styles.ts
> +      fontWeight: 600
```suggestion
      fontWeight: typography.fontWeights.bold
```

2022-04-08 07:42 UTC, denieler approved these changes

2022-04-08 07:42 UTC, denieler commented
@toptal-bot run all

2022-04-08 11:07 UTC, augustobmoura commented on packages/picasso/src/Badge/styles.ts
> +      padding: `0 ${rem('1px')}`,
done

2022-04-08 11:07 UTC, augustobmoura commented on packages/picasso/src/Badge/styles.ts
> +      fontWeight: 600
done

2022-04-11 09:47 UTC, denieler commented
it would be great also to add a visual test with a Badge in some component (like with Avatar) to master and to rebase this PR with that test, so we can see how this component has changed in some "context", not just isolated

2022-04-11 11:48 UTC, augustobmoura commented
@toptal-bot run all

2022-04-11 11:49 UTC, augustobmoura commented
> it would be great also to add a visual test with a Badge in some component (like with Avatar) to master and to rebase this PR with that test, so we can see how this component has changed in some "context", not just on isolatation

I will try to do it

2022-04-11 11:52 UTC, augustobmoura commented
@toptal-bot run all

2022-04-11 17:01 UTC, augustobmoura commented
> it would be great also to add a visual test with a Badge in some component (like with Avatar) to master and to rebase this PR with that test, so we can see how this component has changed in some "context", not just on isolatation

Actually, I think it's better to add new examples in new tickets. We have [this ticket](https://toptal-core.atlassian.net/browse/FX-2179) that should introduce visual tests already

2022-04-11 19:56 UTC, merged