fix: handle empty children of ReactNode
toptal/picasso pull request #2566
Opened 2022-03-30 11:15 UTC by TomasSlama

[FX-NNNN]

### Description

Update RichText stories, so it is clear how to use the RichText component. While testing in the storybook, an unhandled error occurred, when ReactNode had no children, so I had to add a small fix.

### How to test

- check stories of RichText

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/6830426/160821755-ed627a76-d727-4771-ab42-4b75b8bd9ff8.png) | ![image](https://user-images.githubusercontent.com/6830426/160821791-d348ef72-e33c-47dd-bcbb-53391be40f7f.png) |

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-30 15:29 UTC, denieler commented on .changeset/late-vans-type.md
> +handle empty children of ReactNode
```suggestion
Handle empty children of ReactNode.
```

2022-03-30 15:35 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +  const hasChildChildren = child.props.children
```suggestion
  const hasChildChildren = Boolean(child.props.children)
```
it will work even without this, but we do this for a better readability almost everywhere in the code

2022-03-30 15:39 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isEmpty =
```suggestion
    const isEmpty = React.Children.count(props.children) === 0
```
should work I guess

2022-03-30 15:40 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isSingleChild = value.children?.length === 1
```suggestion
    const isSingleChild = React.Children.only(props.children)
```
can be used, but it throws an error if not only 1 children. You also can use `React.Children.count(props.children) === 1` as well

2022-03-30 15:46 UTC, denieler commented on packages/picasso/src/RichText/story/HTML.example.tsx
> +  // return
🤔

2022-03-30 18:27 UTC, TomasSlama commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isEmpty =
@denieler I tried that, and it does not work, we don't work here with React children, but with children from AST type. I have refactored it a little bit so it is cleaner code, and I have also added unit tests to cover those errors that happened to me.

2022-03-30 18:27 UTC, TomasSlama commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isSingleChild = value.children?.length === 1
the same, we work with AST.children, not react.

2022-03-30 18:28 UTC, TomasSlama commented on packages/picasso/src/RichText/story/HTML.example.tsx
> +  // return
✅

2022-03-31 03:07 UTC, augustobmoura requested changes

2022-03-31 03:07 UTC, augustobmoura commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    if (!children || children.length === 0) {
Could be simplfied to:
```suggestion
    if (!children?.length) {
```

2022-03-31 03:07 UTC, augustobmoura commented on packages/picasso/src/RichText/story/HTML.example.tsx
> +  const [html, setHtml] = useState<string>('')
This type is unnecessary, Typescript already infers it as a `string` because of the default parameter

```suggestion
  const [html, setHtml] = useState('')
```

2022-03-31 03:07 UTC, augustobmoura commented on packages/picasso/src/RichText/story/HTML.example.tsx
> +  const onChange = useCallback((value: string) => setHtml(value), [setHtml])
`useCallback` unnecessary because setters from `useState` are already "wrapped" in `useCallback` (they are not really wrapped but they always have the same identity, see the note [in the docs](https://reactjs.org/docs/hooks-reference.html#usestate))
```suggestion
  const onChange = setHtml
```

In this case this variable is even necessary?

2022-03-31 07:56 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isEmpty =
@TomasSlama what? why then it named `children`?

2022-03-31 08:25 UTC, dmaklygin commented on packages/picasso/src/RichText/hooks/useRichText/test.tsx
> +  it('handles empty children', () => {
let's maybe rename the test case. 
I think we should test whether it handles children or not because then we have to cover as well other inputs.
Instead, I would suggest checking just two cases: when children are empty and are not empty.
The idea is to create these use cases via `describe` block and expect the result
In case when chilren are empty, the hook must return `null`

2022-03-31 08:33 UTC, dmaklygin commented on packages/picasso/src/RichText/hooks/useRichText/test.tsx
> +  it('handles undefined children', () => {
I think, this is also a case we have to cover. 
`when children are not defined`
and the response:
`returns null`

2022-03-31 08:37 UTC, dmaklygin approved these changes

2022-03-31 08:43 UTC, ozgurkececioglu approved these changes

2022-03-31 09:28 UTC, TomasSlama commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isEmpty =
@denieler [hast](https://github.com/syntax-tree/hast) also uses children, and `value` here is actually just HAST format.

2022-03-31 09:33 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const { children } = value
```suggestion
    const { children: astChildren } = value
```
what about changing to this?

2022-03-31 09:34 UTC, denieler commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const isSingleChild = children.length === 1
also further I see this code:
```
const textNodes = reactElement.props.children
return textNodes.map(picassoMapper)
```

is this about react children or again ast children?

2022-03-31 09:39 UTC, TomasSlama commented on packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
> +    const { children } = value
I can do that 👍

2022-03-31 16:33 UTC, augustobmoura approved these changes

2022-04-01 08:58 UTC, merged