refactor(Tooltip): remove variant prop
toptal/picasso pull request #2572
Opened 2022-03-31 08:25 UTC by ozgurkececioglu

[FX-2177]

### Description

- removed `variant` prop and its usages from `Tooltip` with respect to BASE 2.0
- minor improvement for `arrow` part of the `Tooltip` UI

### How to test

- `Tooltip` page can be examined 

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| <img width="149" alt="Screen Shot 2022-03-30 at 16 55 37" src="https://user-images.githubusercontent.com/7733167/161010814-f47df8b8-752f-4bd2-83c0-976429802619.png"> | <img width="149" alt="Screen Shot 2022-03-30 at 16 55 44" src="https://user-images.githubusercontent.com/7733167/161010858-b46bd88c-be13-43fe-abe2-61f03133eff2.png"> |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-03-31 08:28 UTC, ozgurkececioglu commented on packages/picasso/src/Tooltip/styles.ts
> +const ARROW_SHADOW = '0 0 2px 0 rgb(0 0 0 / 24%), 0 0 4px 0 rgb(0 0 0 / 12%)'
Custom shadow color inspired by tooltip shadow value from `theme.shadows`

2022-03-31 08:29 UTC, ozgurkececioglu commented on .changeset/two-turkeys-invite.md
> +---
I have this filename privilege 😎

2022-03-31 09:02 UTC, denieler commented on .changeset/soft-radios-deny.md
> +'@toptal/picasso-forms': major
```suggestion
'@toptal/picasso': major
```
probably?

2022-03-31 09:03 UTC, ozgurkececioglu commented on .changeset/soft-radios-deny.md
> +'@toptal/picasso-forms': major
copy+paste issue 🤦‍♂️

2022-03-31 09:08 UTC, denieler commented on packages/picasso/src/Tooltip/styles.ts
> +const ARROW_SHADOW = '0 0 2px 0 rgb(0 0 0 / 24%), 0 0 4px 0 rgb(0 0 0 / 12%)'
it would be great maybe to leave in a comment some link about where this shadow being taken 🤔 because it looks complex

2022-03-31 09:09 UTC, denieler approved these changes
Codewise - looks as very cool refactoring 🙇‍♂️ 👍

2022-03-31 11:00 UTC, TomasSlama approved these changes
LGTM 👍, just one nit comment

2022-03-31 11:09 UTC, ozgurkececioglu commented on packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
> +const isPicassoTooltipImport = (node: ImportDeclaration) =>
I thought the same thing while implementing the codemod, especially for these local names like `import Tooltip as PicassoTooltip` parts. It can be missed easily. I want to create separate PR for such a refactor 👍

2022-03-31 12:46 UTC, dmaklygin approved these changes

2022-03-31 16:46 UTC, augustobmoura commented on packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
> +const isPicassoTooltipImport = (node: ImportDeclaration) =>
I agree 100%, there's a lot of utils functions that I've wrote in my codemods that would be very useful in other codemods

2022-03-31 16:55 UTC, augustobmoura requested changes
Thinking about the visual tests that changed, maybe we should stop updating them, now that we have proper visual testing with cypress and happo, what do you guys think? We could even delete the image snapshots generated

2022-03-31 16:55 UTC, augustobmoura commented on packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
> +  return root.toSource({ quote: 'single' })
I didn't understand this code, why could it not have been just searching and removing for the element?

Something like just the last part of your code
``` typescript
    root
      .findJSXElements(COMPONENT_NAME)
      .find(j.JSXAttribute, isVariantAttribute)
      .remove()
```

2022-03-31 18:16 UTC, ozgurkececioglu commented on packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
> +  return root.toSource({ quote: 'single' })
Good point. I try to cover all possible ways, that's why I search for local names rather than the actual component name. Let's say a project using picasso and imported the Tooltip like 
```
import { Tooltip as PicassoTooltip } from '@toptal/picasso'
```
and if we leave the code like your suggestion, it won't search for `<PicassoTooltip>`. I did this because when I use MUI, I always wrap the base component with my own (like we do in picasso), and mostly I will import the MUI version as MUITooltip or something like that. Do you think it is unnecessary?

2022-04-01 03:36 UTC, augustobmoura commented on packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
> +  return root.toSource({ quote: 'single' })
Nah, I think it makes sense. We shouldn't get worried about edge cases that are not being used in other projects. But I think this one is common enough to deserve your code for finding the aliases. Thanks for explaining!

2022-04-01 03:36 UTC, augustobmoura approved these changes

2022-04-01 08:35 UTC, merged