chore(RichTextEditor): add `status` prop
toptal/picasso pull request #2588
Opened 2022-04-04 12:56 UTC by ozgurkececioglu

[FX-2510]

### Description

- added `status` prop just like other input props

### How to test

- you can check the form page to see its working

### Screenshots

no visual changes

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-05 12:44 UTC, dmaklygin commented on packages/picasso/src/RichTextEditor/RichTextEditor.tsx
> +    })
👍

2022-04-05 12:45 UTC, dmaklygin commented on packages/picasso/src/RichTextEditor/story/index.jsx
> +  .addExample('RichTextEditor/story/Status.example.tsx', 'Status') // picasso-skip-visuals
shouldn't we somehow cover status with visual tests?

2022-04-05 12:48 UTC, dmaklygin commented on packages/picasso/src/RichTextEditor/RichTextEditor.tsx
> +  status?: Exclude<Status, 'success'>
this is confusing. I would manually describe all possible values of status here. wdyt?

2022-04-05 13:29 UTC, dmaklygin commented on cypress/component/RichTextEditor.spec.tsx
> +  })
👍

2022-04-05 15:03 UTC, denieler requested changes
we need to limit `Status` typing or add `success` variant to the example

2022-04-05 15:03 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  status?: Status
🤔

2022-04-05 15:19 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  status?: Status
to me actually `'error' | 'default'` look good 🤔

2022-04-05 15:34 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  status?: Status
what about `Pick<Status, 'error' | 'default'>`?

2022-04-05 15:37 UTC, ozgurkececioglu commented on packages/picasso/src/Select/types.ts
> +  status?: Status
Slightly safer 😄 I would be ok with that. WDYT @dmaklygin ?

2022-04-06 06:58 UTC, ozgurkececioglu commented on packages/picasso/src/Select/types.ts
> +  status?: Status
@denieler new info for today. `Pick` won't work with literal types 🙂 I surprised also:
[docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys)
[playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyglgLwgFXNAvFA5AWwgEzgFccsoAfbAZxwEMAbesyre2gJwHMIsAoXuADtgEdgDNaAY2gAFdgHswVKAG9eUDVCqIIAfgBcUGXEkBrADzwkqSABpseQiWbU6jLAD5eAXyA)

2022-04-06 07:02 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  status?: Status
try `Extract` then

2022-04-06 07:25 UTC, TomasSlama approved these changes
GJ 👍

2022-04-06 08:49 UTC, denieler approved these changes

2022-04-06 09:25 UTC, LashaJini approved these changes
Tested locally and works fine :+1: .

2022-04-06 10:19 UTC, dmaklygin commented on packages/picasso/src/Select/types.ts
> +  status?: Status
yeah, Exctract is more reasonable here :)

2022-04-06 10:32 UTC, merged