Fix DatePicker disabled state
toptal/picasso pull request #2589
Opened 2022-04-04 13:38 UTC by sunRock98

[FX-X]

### Description

Fix disabled state of DatePicker, which at the moment of this PR still open calendar on input click even if disabled

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings 

https://user-images.githubusercontent.com/65539882/161556155-9dd38b21-a401-4846-a653-c2ad98612723.mov

| Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-05 10:15 UTC, denieler commented on .changeset/sour-monkeys-design.md
> +Fix disabled state of DatePicker
Please format changeset in a format of https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md

2022-04-05 10:20 UTC, denieler commented on packages/picasso/src/DatePicker/DatePicker.tsx
> +      {inputWrapperRef.current && !props.disabled && (
please add `disabled` to the list of props here https://github.com/toptal/picasso/pull/2589/files#diff-eee96e563cc335645633cd9bb0f93db4a756a3a95e1c152749121312dea6539eL111

2022-04-05 10:25 UTC, denieler commented on packages/picasso/src/DatePicker/DatePicker.tsx
> +      {inputWrapperRef.current && !props.disabled && (
I think the better solution would be to add 
```
if (disabled) {
  return
}
```
to https://github.com/toptal/picasso/blob/8f3f3363bb586c77249731f9117dbdd74276b7b7/packages/picasso/src/DatePicker/DatePicker.tsx#L341.

Because in your current solution the internal state of the component will be still changed to `setCalendarIsShown: true`

2022-04-05 12:45 UTC, augustobmoura approved these changes

2022-04-05 12:48 UTC, augustobmoura requested changes
Actually, it looks like there's a [regression in visual testing](https://happo.io/a/675/p/848/snapshot/cf3a525fd5bbd523c1eb04a4f9b5ca2e/compare/e38d4a5334a7e3747e647795eada51c2). Can you check it out?

2022-04-05 13:11 UTC, dmaklygin commented on packages/picasso/src/DatePicker/DatePicker.tsx
> +          disabled={disabled}
I would prefer not to assign a handler of `onClick` or `onFocus` if disabled is true.
wdyt?

2022-04-05 13:14 UTC, dmaklygin approved these changes

2022-04-05 13:25 UTC, OndrejTuma approved these changes
Just update the changeset to comply with guidelines, otherwise LGTM 👍

2022-04-05 13:33 UTC, sunRock98 commented on packages/picasso/src/DatePicker/DatePicker.tsx
> +          disabled={disabled}
@dmaklygin you mean sth like this: 
  ```
const handleFocusOrClick = disabled
    ? () => {
        showCalendar()
        setIsInputFocused(true)
      }
    : undefined
```

2022-04-05 14:29 UTC, ozgurkececioglu commented on packages/picasso/src/DatePicker/DatePicker.tsx
> +          disabled={disabled}
Most probably he meant passing the callback part: 
```
onClick={disabled ? undefined : handleFocusOrClick}
```

2022-04-05 15:06 UTC, denieler commented on .changeset/sour-monkeys-design.md
> +- fix disabled state of DatePicker
```suggestion
- fixed a bug, that disabled DatePicker when clicked was showing a Calendar
```

2022-04-05 15:07 UTC, denieler requested changes
We need to fix the changeset

2022-04-06 08:49 UTC, denieler approved these changes

2022-04-06 10:55 UTC, merged