feat: add collapsible feature to Sidebar
toptal/picasso pull request #2590
Opened 2022-04-05 07:58 UTC by ozgurkececioglu

[FX-1855]

### Description

PoC for a collapsible sidebar.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-05 08:07 UTC, denieler commented on packages/picasso/src/Sidebar/story/Collapsible.example.tsx
> +          {!isCollapsed && (
I would not like to leave it to a user the decision of what to render. Probably we need to hide this inside Sidebar internal logic.

2022-04-05 08:08 UTC, denieler commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      {!isSidebarCollapsed && (
is it possible to not "hide/show" this content, but to hide via opacity or something like that maybe? if many-many items are rendered in the current implementation we can have a lag during the transition, probably?

2022-04-05 08:08 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/story/Collapsible.example.tsx
> +          {!isCollapsed && (
When I saw the logo outside of Sidebar's internal logic, I thought that the user can decide what to render when it is collapsed. I'm totally fine with removing it 👍

2022-04-05 08:25 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      {!isSidebarCollapsed && (
Great idea! I checked MUI version and they are doing the same 👍 I will apply

2022-04-06 11:46 UTC, TomasSlama commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +          }
```suggestion
          {
            [classes.withIcon]: hasIcon,
            [classes.collapsedContent]: isSidebarCollapsed 
          }
```

for consistency?

2022-04-06 11:46 UTC, TomasSlama commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isSidebarCollapsed?: boolean
This name doesn't feel right to me 🤔, shouldn't it be related to the SidebarItem? Something like `isContentVisible` 🤷 What do you think?

2022-04-06 11:46 UTC, TomasSlama commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isSidebarCollapsed?: boolean
also we don't cover dropdowns
![image](https://user-images.githubusercontent.com/6830426/161967650-6cb651e7-f730-475d-a067-b5812900f8f4.png)

2022-04-06 11:54 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/test.tsx
> +  collapsible: collapsible,
For the sake of time, I left these small issues since this is just to give the idea 🙂

2022-04-06 11:55 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +      )}
Sure, good idea 👍

2022-04-06 11:57 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isSidebarCollapsed?: boolean
I asked about it to Milos and he agreed that we should work on nested menus. He will prepare a different design for this purpose. Most probably, as @OleksandrNechai suggested, we will expand the sidebar when user clicks the root of the nested menu

2022-04-06 11:59 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isSidebarCollapsed?: boolean
> This name doesn't feel right to me 🤔, shouldn't it be related to the SidebarItem? Something like `isContentVisible` 🤷 What do you think?

Yeah, `Sidebar.Item` shouldn't be knowing whether the sidebar is collapsed or not. So, the prop name can be changed 👍

2022-04-06 15:50 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isSidebarCollapsed?: boolean
I agree that isContentVisible is a better name. Another option and I think it was the original one, is [extending Sidebar context](https://toptal-core.atlassian.net/browse/FX-1430) to pass the information if the sidebar is closed or not and use it to hide the content.

But I very much prefer passing properties in this case so that we don't add a hard dependency of the component on SidebarContext, it makes it a lot simpler and easier to rationalize around it, and it makes testing a lot easier as well.

Extending the context will still be useful when the user needs their custom component being used in a Sidebar.Item to know about the collapsed state

2022-04-07 07:45 UTC, OndrejTuma commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  const [isCollapsed, setIsCollapsed] = useState<boolean>(false)
maybe would be nice to allow defaultCollapsed prop in case the settings is persistent? 🤔

2022-04-07 07:45 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  const [isCollapsed, setIsCollapsed] = useState<boolean>(false)
Good idea! I will add it to the actual PR 👍

2022-04-07 07:52 UTC, OndrejTuma commented on packages/picasso/src/SidebarMenu/SidebarMenu.tsx
> +        return React.cloneElement(sidebarItem, { variant, isSidebarCollapsed })
A have just a question here - is this solution chosen so that SidebarItem does not have to access Sidebar context? Augusto mentioned some advantages in a comment above. 
I'm wondering, because from a first glance I dont really like this 🙂

2022-04-07 08:14 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarMenu/SidebarMenu.tsx
> +        return React.cloneElement(sidebarItem, { variant, isSidebarCollapsed })
My motivation was that SidebarMenu is already accessing context for nested groups info, so no need to duplicate the access on the item level. But to be sure, I debugged it for you. 

In the first test case: I ran the page as I already implemented it. When I click to expand/shrink a nested menu, `SidebarItem` didn't re-rendered. Only SidebarMenu was re-rendered.

In the second test case: I moved the prop passing for `isSidebarCollapsed` or with the new name `isContentVisible`, to the `SidebarItem` as context usage as you suggested. In this case, when I click to expand/shrink a nested menu, both SidebarMenu and SidebarItems are re-rendered.

Conclusion 😄 For a very big sidebar with many items, it can be a performance issue even if we don't use collapse button once 🙂 I would love you to contradict me if you have a better reason 👍

2022-04-07 11:51 UTC, OndrejTuma commented on packages/picasso/src/SidebarMenu/SidebarMenu.tsx
> +        return React.cloneElement(sidebarItem, { variant, isSidebarCollapsed })
Yeah I didnt take rerendering into account here 🙇

2022-04-07 11:55 UTC, OndrejTuma commented on packages/picasso/src/SidebarLogo/SidebarLogo.tsx
> +  logoIcon?: ReactNode
maybe rename this to collapseLogo to be consistent with fullLogo

2022-04-07 11:56 UTC, OndrejTuma commented on packages/picasso/src/SidebarLogo/SidebarLogo.tsx
> +        {content ?? children}
Can't we keep both?

2022-04-07 11:58 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarLogo/SidebarLogo.tsx
> +        {content ?? children}
Hmm, I couldn't imagine the use case. I expect that user will provide logoIcon or fullLogo, another case is children directly without using these new props. I'm not sure about combining all of them 🤔 but we can let user to decide what to use. Good idea 👍

2022-04-07 13:34 UTC, dmaklygin commented on packages/picasso/src/Sidebar/story/Collapsible.example.tsx
> +export default Example
👍

2022-04-07 13:46 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/styles.ts
> +      opacity: 0
hm, why `opacity`? what's the benefit?
if I'm not mistaken, we have to hide the content if it's collapsed, why don't we use display:none or visibility: hidden?

2022-04-07 13:48 UTC, dmaklygin commented on packages/picasso/src/SidebarLogo/SidebarLogo.tsx
> +  fullLogo?: ReactNode
I'm wondering about the name of `logoIcon` and `fullLogo: both of them are icons, and the first on has suffix `Icon`, but the second one does not. Maybe use the same name for icons?

2022-04-07 15:21 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  const [isHovered, setIsHovered] = useState<boolean>(false)
Did you imagine them like a hook that just combines them and returns the values and setters?

```
  const {
    expandedItemKey,
    isCollapsed,
    isHovered,
    setExpandedItemKey,
    setIsCollapsed,
    setIsHovered
  } = useSidebarState({ defaultCollapsed })
```
Can you explain more? How will this help to simply tests 🙇‍♂️

2022-04-08 11:17 UTC, augustobmoura requested changes

2022-04-08 11:17 UTC, augustobmoura commented on packages/picasso/src/Sidebar/story/Collapsible.example.tsx
> +import { Sidebar, Tag, Logo, Container, Typography } from '@toptal/picasso'
Sidebar shouldn't be used directly, we are [removing it as an export from picasso](https://github.com/toptal/picasso/pull/2606). The correct way is to import `Page` and use it as `Page.Sidebar`

2022-04-11 08:12 UTC, ozgurkececioglu commented
Since the original PR is here: https://github.com/toptal/picasso/pull/2610, I will close this to decrease ambiguity.

2022-04-11 08:12 UTC, closed without merging