refactor(FormLabel): removed asterisks
toptal/picasso pull request #2595
Opened 2022-04-05 16:35 UTC by OndrejTuma

[FX-2175]

### Description

Removed asterisks from FormLabels, making required field appear as default.

### How to test

Open any form or input and look for required variants

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/22159416/161802852-efa1c32a-6675-43db-a280-1f7f74fde28a.png) | ![image](https://user-images.githubusercontent.com/22159416/161802937-8cb7ce9c-961f-49c2-a86a-217a66c4bc4c.png) |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-06 08:16 UTC, ozgurkececioglu commented on packages/picasso-forms/src/FormConfig/FormConfig.ts
> +export type RequiredVariant = 'default'
After removing `asterisk`, do we still need `RequiredVariant`? It is a bit confusing. I mean, let's have one decoration prop like `optionalDecoration?: boolean` and that's all. `optionalDecoration=undefined` will be the default for `required`. Am I making sense?

2022-04-06 08:56 UTC, denieler commented on packages/picasso-forms/src/FormConfig/FormConfig.ts
> +export type RequiredVariant = 'default'
yep, please remove it 🙇‍♂️

2022-04-06 08:57 UTC, denieler commented on packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
>    requiredVariant?: RequiredVariant
this one also has to be removed I think

2022-04-06 08:58 UTC, denieler commented on packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
> +  showValidState: true
I think then we need to remove https://github.com/toptal/picasso/blob/0950255bf20899b1e6e22f9fa1e7c5e0c79022e6/packages/picasso-forms/src/Form/story/Status.example.tsx#L9 example

2022-04-06 08:58 UTC, denieler requested changes
We can remove more code 😃 not enough code removed

2022-04-06 09:08 UTC, OndrejTuma commented on packages/picasso-forms/src/FormConfig/FormConfig.ts
> +export type RequiredVariant = 'default'
I was thinking about it too @ozgurkececioglu. `requiredDecoration` was used for any modification of `FormLabel`, right now its used only for one modification - adding the (optional) suffix. I only hope it will not come back in some other form later

2022-04-06 09:20 UTC, denieler commented on packages/picasso-forms/src/FormConfig/FormConfig.ts
> +export type RequiredVariant = 'default'
it shouldn't that was the only idea behind `RequiredVariant`, we can remove it without any doubts

2022-04-06 09:26 UTC, OndrejTuma commented on packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
> +  showValidState: true
Or I can extend it with `validateOnSubmit`? I'd keep Status example if anyone is interested in this particular setting

cc @denieler

2022-04-06 10:07 UTC, denieler commented on packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
> +  showValidState: true
there is also an example for validate on submit - https://github.com/toptal/picasso/blob/ee77cde12f8f7670f50958ae3973327eb513d9f9/packages/picasso-forms/src/Form/story/ValidateOnSubmit.example.tsx

2022-04-07 08:39 UTC, OndrejTuma commented on packages/picasso-forms/src/FormConfig/FormConfig.ts
> +export type RequiredVariant = 'default'
Its done @denieler @ozgurkececioglu

2022-04-07 11:01 UTC, denieler commented on packages/picasso-forms/src/Radio/test.tsx
> -  it('required with asterisk', () => {
I would probably add tests when we would see that `optional` label is shown for such "special" components like `Checkbox`, `Radio`

2022-04-07 11:02 UTC, denieler commented on packages/picasso/src/Checkbox/story/Required.example.tsx
> +      <Checkbox label='I confirm that I have legal permission from the client to feature this project.' />
I guess we can remove this example or to show here required and non-required with `optional` label

2022-04-07 11:04 UTC, denieler reviewed
Almost amazing 🎉 🕺 But I think we need to sort out Form examples for FormLevelConfiguration

2022-04-07 13:31 UTC, denieler commented on packages/picasso/src/FormField/story/Required.example.tsx
> +        <Form.Label htmlFor='city' isOptional>
I like @ozgurkececioglu suggestion 👍 but I'm ok with `isOptional` too

2022-04-07 13:42 UTC, OndrejTuma commented on packages/picasso/src/FormField/story/Required.example.tsx
> +        <Form.Label htmlFor='city' isOptional>
I agree that `optional` is a good choice here, it is a well-known word in form's context 👍 so there's no need to emphasize boolean type of the property. Thanks for suggestion @ozgurkececioglu

2022-04-08 08:56 UTC, TomasSlama approved these changes
Great Job! 👍, Daniel and Oz already left pretty cool suggestions, other than that I think it looks pretty good 💪

nit: I think it would be great to update the PR description, I was lost a little bit at begging, didn't know why we have a new prop, but after reading all comments in the conversation tab I understood.

2022-04-08 08:56 UTC, TomasSlama commented on packages/picasso/src/Checkbox/story/Required.example.tsx
> +      <Checkbox label='I confirm that I have legal permission from the client to feature this project.' />
I like more the second suggestion, add one more optional checkbox.

2022-04-11 09:14 UTC, OndrejTuma commented on packages/picasso/src/FormField/story/Required.example.tsx
> +        <Form.Label htmlFor='city' isOptional>
its done @ozgurkececioglu

2022-04-11 09:54 UTC, denieler commented on packages/picasso/src/index.ts
> +export type { FormLabelProps } from './FormLabel'
I've checked, looks like no one imports `RequiredDecoration` type from any project at Toptal 👍

2022-04-11 10:25 UTC, OndrejTuma commented on packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
> +  showValidState: true
OK so I kept the other examples and removed this customConfiguration example @denieler

2022-04-11 10:33 UTC, OndrejTuma commented on packages/picasso-forms/src/Radio/test.tsx
> -  it('required with asterisk', () => {
I added it for Checkbox component (there is required vs optional example) but for Radio it makes more sense to add (optional) to a Form.RadioGroup instead of Radios themselves. I checked that it works in reverse - by default it is optional and by adding `required` the suffix disappears.
I'm wondering if I should refactor this too @denieler 🤔

2022-04-11 10:34 UTC, OndrejTuma commented on packages/picasso/src/Checkbox/story/Required.example.tsx
> +      <Checkbox label='I confirm that I have legal permission from the client to feature this project.' />
I followed the second suggestion 👍 @denieler @TomasSlama

2022-04-11 10:35 UTC, OndrejTuma commented on packages/picasso/src/index.ts
> +export type { FormLabelProps } from './FormLabel'
Thanks for it 👍 I checked that too and probably should have written it down 🙂

2022-04-11 11:11 UTC, ozgurkececioglu approved these changes
Thanks for the updates. Looks cool 👍

2022-04-11 16:41 UTC, denieler approved these changes

2022-04-12 07:55 UTC, separatio commented
Postponed until the end of Q2.

2022-04-12 07:55 UTC, closed without merging