chore: update to react18
toptal/picasso pull request #2605
Opened 2022-04-06 16:40 UTC by TomasSlama

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-07 08:13 UTC, TomasSlama commented on packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
> +      style=""
There were unexpected changes, I looked into it and realized, that the previous snapshots were not correct, we wanted to snapshot after the modal is closed.

2022-04-07 08:13 UTC, TomasSlama commented on packages/picasso/src/Tooltip/test.tsx
> +        { timeout: TOOLTIP_SHORT_DELAY + 50 }
after update, this didn't work, needed to add a small delay

2022-04-07 08:42 UTC, denieler commented on packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
> +              aria-label="reset"
this is very weird, we need to fix this before merging this PR ☝️

2022-04-07 08:42 UTC, denieler commented on packages/picasso/src/Tooltip/test.tsx
> +        { timeout: TOOLTIP_SHORT_DELAY + 50 }
🤔 we need to find out why

2022-04-07 09:01 UTC, ozgurkececioglu commented on packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
> +              aria-label="reset"
Guys, I think jest can't find it due to its visibility. This is working:
```
      fireEvent.click(getByRole('reset', { hidden: true }))
```

2022-04-07 10:41 UTC, denieler commented on packages/picasso/src/Tooltip/test.tsx
> +        { timeout: TOOLTIP_SHORT_DELAY + 50 }
I guess even 1ms should work 🤔 but it's definitely something with our code if we need any additional delay

2022-04-07 11:35 UTC, TomasSlama commented
@toptal-bot run visual

2022-04-07 15:04 UTC, denieler commented on packages/picasso/src/Tooltip/test.tsx
> +        { timeout: TOOLTIP_SHORT_DELAY + 50 }
can we somehow justify that?

2022-04-08 11:24 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
> +              aria-label="reset"
I have used @ozgurkececioglu suggestion

2022-04-08 12:11 UTC, TomasSlama commented on packages/picasso/src/Tooltip/test.tsx
> +        { timeout: TOOLTIP_SHORT_DELAY + 50 }
There are some changes to how timers work now https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0.

To my understanding it actually makes sense. We render the component after 500ms, so when we check at 500ms it is not rendered yet, but it is in 501ms. But jest is not checking every second, but every 50ms by default. It is possible to change it to another option `interval`

2022-04-08 14:00 UTC, augustobmoura requested changes
I added some comments on the `peerDependencies` range but aside of that LGTM! :+1:

2022-04-11 08:06 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/test.tsx
> +      expect(getDisplayValue).toHaveBeenCalledTimes(30)
yeah, these tests looks weird, but I would leave it for the technical dept task I have created for Autocomplete

2022-04-11 08:15 UTC, dmaklygin commented on packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
> -      </div>
and, what about this change, is it intentional removal?

2022-04-11 08:19 UTC, dmaklygin approved these changes

2022-04-11 08:34 UTC, OndrejTuma commented on package.json
> +    "react-test-renderer": "^18.0.0",
Do you use this lib anywhere?

2022-04-11 08:44 UTC, OndrejTuma commented on packages/picasso/src/PromptModal/test.tsx
> +    await waitForElementToBeRemoved(submitModal)
👍

2022-04-11 08:56 UTC, OndrejTuma approved these changes

2022-04-11 09:16 UTC, denieler commented on package.json
> +    "react-test-renderer": "^18.0.0",
yeah, doesn't seem so

2022-04-11 09:16 UTC, denieler commented on package.json
> +    "react-test-renderer": "^18.0.0"
same here

2022-04-11 09:17 UTC, denieler commented on packages/picasso/src/Autocomplete/test.tsx
> +      // TODO: [FX-2588] figure out why renderOption is called twice
it might be due to `StrictMode` if tests rendered in this mode for react

2022-04-11 09:17 UTC, TomasSlama commented on package.json
> +    "react-test-renderer": "^18.0.0",
@OndrejTuma yes, it is even [recommended by Jest](https://jestjs.io/docs/tutorial-react). Without it we would receive lot of errors in console
![image](https://user-images.githubusercontent.com/6830426/162706096-faa9b931-83a3-43cb-8616-e4edef05b0d9.png)

2022-04-11 09:19 UTC, denieler commented on packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
> +      style=""
do we have also a snapshot of the modal in open state?

2022-04-11 09:20 UTC, denieler requested changes
I think PR is almost ready, I just think we also have to figure out those 2-renders cases - https://github.com/toptal/picasso/pull/2605/files#r844805243 in scope of this migration, and not leaving this for next generations 😃

2022-04-11 12:39 UTC, augustobmoura commented on packages/picasso/src/Autocomplete/test.tsx
> +      // TODO: [FX-2588] figure out why renderOption is called twice
Yep, it must be related to strict mode. React now re-renders everything twice for catching more bugs in development.

I don't see why we are testing the numbers of calls of this function, if it's being called on a render this will be very fragile. We can't (and shouldn't) control how many times a render function is called by React. A `.toHaveBeenCalled()` should suffice for this test in my opionion

2022-04-11 13:21 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/test.tsx
> +      // TODO: [FX-2588] figure out why renderOption is called twice
But we should control that expensive functions are not called on every render

2022-04-11 14:07 UTC, augustobmoura commented on packages/picasso/src/Autocomplete/test.tsx
> +      // TODO: [FX-2588] figure out why renderOption is called twice
I'm not sure if we should explicitly test and `expect` a function to not be called n-times if we want to test for performance, the best way to do it would be to set up benchmarks for the components.

In any case, this function in this specific line is not an expensive one, or at least shouldn't be treated as such

2022-04-11 14:29 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/test.tsx
> +      // TODO: [FX-2588] figure out why renderOption is called twice
Just to clarify, it seems that it is not caused by StrictMode.
![image](https://user-images.githubusercontent.com/6830426/162761775-612cafae-3dd1-48d1-8bc8-b6e43d22284e.png)

![image](https://user-images.githubusercontent.com/6830426/162761676-5623bdc8-2fde-4d74-8ec5-f7fad1bf0c8e.png)

2022-04-11 15:56 UTC, TomasSlama commented on packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
> +      style=""
@denieler yes, we have, but in a different test case.

2022-04-11 16:10 UTC, TomasSlama commented on package.json
> +    "react-test-renderer": "^18.0.0"
I have added `react-test-renderer` to resolutions just for consistency, because it should have always the same version as `react` and `react-dom`

2022-04-11 16:28 UTC, denieler approved these changes

2022-04-12 06:54 UTC, TomasSlama commented on package.json
> +    "react-test-renderer": "^18.0.0",
sadly no, it is internally used in `@testing-library/react-hooks`

2022-04-12 08:06 UTC, ozgurkececioglu approved these changes

2022-04-12 14:24 UTC, augustobmoura approved these changes

2022-04-12 14:48 UTC, merged