feat: add collapsible functionality to sidebar
toptal/picasso pull request #2610
Opened 2022-04-07 17:08 UTC by ozgurkececioglu

[FX-1304]

### Description

I will wait for renaming PR's to be merged first to avoid big conflicts.

- added new props to `Sidebar`: `collapsible` and `defaultCollapsed`
- added new attribute to `SidebarContext` to store collapse state
- updated `SidebarItem` to hide content when sidebar is collapsed
- updated `SidebarLogo` to change content when sidebar is collapsed

### How to test

- you can check Sidebar's page on storybook. Look for `Collapsible` subtitle

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-08 06:17 UTC, ozgurkececioglu commented
@toptal-bot run visual

2022-04-08 08:32 UTC, TomasSlama reviewed
Good job 👍, I left only few quesitons.

2022-04-08 08:32 UTC, TomasSlama commented on packages/picasso/src/Logo/Logo.tsx
> +  'data-testid'?: string
I think that `data-testid` should be already included in `BaseProps`

2022-04-08 08:32 UTC, TomasSlama commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  }
I'm wondering if it might be useful to users to do some action on collapse 🤔, did you consider adding `onCollapseChange`?

2022-04-08 08:32 UTC, TomasSlama commented on packages/picasso/src/Sidebar/test.tsx
> +        expect(container).toHaveStyle({ width: '14.75rem' })
I don't think it is a good idea to rely on CSS in tests. When we will have redesign in future, logic might be the same, but we will still have to update the tests 🤷. This should be probably handled by visual tests 🤔

2022-04-08 11:04 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  }
Hmm, nobody suggested this before. I actually implemented a function as a child approach to let the user pick whatever he/she wants based on the collapse state but daniel asked me to revert it back since function as a child is a bad pattern. I think we can achieve the same with your suggestion. Good idea man!

2022-04-08 11:05 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/test.tsx
> +        expect(container).toHaveStyle({ width: '14.75rem' })
Yeah, I wasn't happy either. Let me change it to classname check 🙂

2022-04-11 09:15 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/test.tsx
> +        expect(container).toHaveStyle({ width: '14.75rem' })
With @separatio's suggestion, I moved this integration test into cypress side.

2022-04-11 11:46 UTC, separatio commented
Manually tested. Had some issues:
1. When you collapse the sidebar, the items text disappears, then the sidebar collapses, in this order, which is fine.
But when you enlarge the sidebar, the text is there and gets re-arranged as the sidebar gets bigger.
Ideally, the behavior when closing/opening the sidebar should be the same.
2. The animation speed of close vs open seems to be different.
Is it just my imagination? Can you please check?
3. The logo shrinks when collapsing the sidebar. Ideally, it is replaced:
- when the animation of collapse starts
- when the animation of expand finishes
so that we don't have unnecessary resizes.

2022-04-12 07:45 UTC, ozgurkececioglu commented
@toptal-bot run visual

2022-04-12 07:49 UTC, ozgurkececioglu commented
@toptal-bot run all

2022-04-12 16:08 UTC, augustobmoura requested changes
I noticed that some visual tests are breaking from some padding/margin differences, I'm not sure if you mentioned it before, but maybe we should take a look

2022-04-12 16:08 UTC, augustobmoura commented on packages/picasso/src/SidebarMenu/SidebarMenu.tsx
> +    )
This could be simplified to just:
```suggestion
    const expandSidebarItem = useCallback(
      setExpandedItemKey,
      [setExpandedItemKey]
    )
```

2022-04-12 16:08 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/index.jsx
> -  .addExample('PageSidebar/story/Variants.example.tsx', 'Variants') // picasso-skip-visuals
Why you stopped ignoring these tests?

2022-04-12 16:08 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/use-sidebar-state/use-sidebar-state.tsx
> +  const [isHovered, setIsHovered] = useState<boolean>(false)
Nit: You don't need to type `useState` generics here, Typescript can infer the type from the expression

```suggestion
  const [isCollapsed, setIsCollapsed] = useState(
    Boolean(defaultCollapsed)
  )
  const [isHovered, setIsHovered] = useState(false)
```

Another nit is that I prefer using `!!` instead of calling `Boolean`, but is very minor

2022-04-13 12:04 UTC, ozgurkececioglu commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +  }
I agree that your concern is valid but I think, to start seeing weird bugs, we should have called the setter function multiple times on the sidebar or its children on some level concurrently. In that case, the current state value could be the old one. And this is not the same for the sidebar because it isn't that easy to click the collapse button more than once in a second or so.

Your case is also valid for controlled components and we would see it if we get `collapsed` as a prop and `onCollapseChange` for a parent state update. But, the sidebar is handling its own state and `handleCollapseButtonClick` doesn't call `setIsCollapsed` more than once.

If we start calling these examples "needs-to-be-refactored", we will need to touch too many places on picasso like: https://github.com//toptal/picasso/blob/b9859b6c246f582d336250b7df45e6c284902299/cypress/component/Table.spec.tsx#L126

So, IMHO, it is quite safe to use this version of setState 🤔 Is this the reason you put a `request-change`?

2022-04-13 12:20 UTC, ozgurkececioglu commented on packages/picasso/src/PageSidebar/story/index.jsx
> -  .addExample('PageSidebar/story/Variants.example.tsx', 'Variants') // picasso-skip-visuals
Because they had image snapshots before (not in happo), so I thought that until that time, it can be a good idea to have these snapshots still. WDYT?

2022-04-13 12:57 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +  }
The problem is that even though it is working now if someone else adds a new `setIsCollapsed` in any other part of the code in the future, this will most certainly break (maybe even silently).

Being an active recommendation from the React docs itself, I don't think we should ignore this

2022-04-13 13:05 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/index.jsx
> -  .addExample('PageSidebar/story/Variants.example.tsx', 'Variants') // picasso-skip-visuals
I [asked](https://github.com/toptal/picasso/pull/2610#pullrequestreview-939761287) about the difference in those visual tests as well. They are breaking because of the changes in this PR or because they were ignored for too long and things changed in the meantime?

2022-04-13 13:22 UTC, ozgurkececioglu commented on packages/picasso/src/PageSidebar/story/index.jsx
> -  .addExample('PageSidebar/story/Variants.example.tsx', 'Variants') // picasso-skip-visuals
Oh. I think I broke something while adding the hover wrapper 🤔 I will take a look once more 👍

2022-04-13 13:46 UTC, TomasSlama reviewed
As Augusto mentioned, it seems we have unexpected changes in old visual tests. Everything else looks good to me 👍

2022-04-13 13:46 UTC, TomasSlama commented on packages/picasso/src/PageSidebar/test.tsx
> +import { fireEvent, waitFor } from '@testing-library/react'
```suggestion
import { render, fireEvent, waitFor } from '@toptal/picasso/test-utils'
import { OmitInternalProps } from '@toptal/picasso-shared'
```

2022-04-13 15:33 UTC, ozgurkececioglu commented on packages/picasso/src/Sidebar/Sidebar.tsx
> +  }
Thanks to @denieler, I decided to revert back this callback since PageSidebar was an uncontrolled component. I was handling collapse value and now, we are sharing it with outside and we need to call the callback to share it. So, to be able to stay as uncontrolled component, I will remove this callback.

2022-04-14 03:56 UTC, augustobmoura approved these changes
The margin issues look good to me! :+1:

2022-04-14 06:11 UTC, separatio commented
Why is the logo so small? https://happo.io/a/675/p/848/compare/44f0fbf473386729e0dd79fea616ee6fbe81bb84/347c271465a061b64c61285b4f4fd6adca20682c?t=added#Sidebar%5C%20when%5C%20the%5C%20sidebar%5C%20is%5C%20collapsible%5C%20hides%5C%20and%5C%20shows%5C%20the%5C%20sidebar%5C%20items%5C%20text-default-2

When collapsible example:
![image](https://user-images.githubusercontent.com/8407461/163324485-47bdbe3a-b9ae-456d-9750-fdec8748ba1c.png)

When not collapsible example:
![image](https://user-images.githubusercontent.com/8407461/163324532-6d216400-b37b-4a99-a994-88598cfaed10.png)

2022-04-14 06:20 UTC, ozgurkececioglu commented
> Why is the logo so small? https://happo.io/a/675/p/848/compare/44f0fbf473386729e0dd79fea616ee6fbe81bb84/347c271465a061b64c61285b4f4fd6adca20682c?t=added#Sidebar%5C%20when%5C%20the%5C%20sidebar%5C%20is%5C%20collapsible%5C%20hides%5C%20and%5C%20shows%5C%20the%5C%20sidebar%5C%20items%5C%20text-default-2
> 
> When collapsible example: ![image](https://user-images.githubusercontent.com/8407461/163324485-47bdbe3a-b9ae-456d-9750-fdec8748ba1c.png)
> 
> When not collapsible example: ![image](https://user-images.githubusercontent.com/8407461/163324532-6d216400-b37b-4a99-a994-88598cfaed10.png)

I'm not sure. I can't reproduce it. But definitely, we should use stories as our cypress test components to eliminate providing different test cases for happo and cypress.

2022-04-14 08:07 UTC, separatio commented
Let's handle it as tech debt so you can deliver this. Add a ticket in the Picasso 2022 Tech Debt Epic please.

2022-04-14 08:17 UTC, separatio commented on packages/picasso/src/PageSidebar/test.tsx
> +        </PageSidebar.Item>
This is not needed in the unit test. You are already testing how items are being handled in Cypress. It just slows down the test.

2022-04-14 08:19 UTC, separatio commented on packages/picasso/src/PageSidebar/test.tsx
> +        expect(getByTestId('collapse-button')).toBeVisible()
This test is duplicated by the ones in Cypress. Can be removed.

2022-04-14 08:20 UTC, separatio commented on packages/picasso/src/PageSidebar/use-sidebar-state/test.ts
> +})
These are good unit tests. :tada:

2022-04-14 08:21 UTC, separatio commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isContentVisible?: boolean
What is content? Text? If yes, why is it called content? I imagine the icons are always displayed. Can it be anything other than text?

2022-04-14 08:21 UTC, separatio commented on packages/picasso/src/PageSidebar/test.tsx
> +        </PageSidebar.Item>
Since `<PageSidebar.Menu>` is the container for `PageSidebar.Item`s, that's useless here as well.

2022-04-14 08:22 UTC, separatio commented on packages/picasso/src/SidebarItem/test.tsx
> +          <PageSidebar.Menu>
The PageSidebar.Item should not be tested in the context of `PageSidebar` in Unit tests. You can mount it as-is most likely.

2022-04-14 08:24 UTC, separatio commented on packages/picasso/src/SidebarLogo/SidebarLogo.tsx
> +  collapseLogo?: ReactNode
I suggest `collapsedLogo` instead. WDYT? The reason is that it indicates a state, rather than an action.
`collapseLogo?` sounds like a boolean if the logo should get collapsed or not.

2022-04-14 08:26 UTC, separatio commented on packages/picasso/src/SidebarLogo/test.tsx
> +  describe('when sideber is collapsed', () => {
`sideber` -> `sidebar`

2022-04-14 08:27 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isContentVisible?: boolean
It can be something else. While showing icons always, we should have a prop to show/hide the content of the sidebar item. 99% of the time, it will be a text or a Badge overlaying the text.

2022-04-14 08:28 UTC, separatio commented on packages/picasso/src/SidebarLogo/test.tsx
> +  describe('when sideber is not collapsed', () => {
`sideber` -> `sidebar` - copy-pasta error. :smile:

2022-04-14 08:31 UTC, separatio commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  isContentVisible?: boolean
Then content is fine.

2022-04-14 08:33 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarLogo/test.tsx
> +    >
There is no public prop for SidebarLogo to get a collapsed state because it is reading it from SidebarContext. So, we have to mock the context provider like that.

2022-04-14 11:07 UTC, separatio approved these changes
Alright. Looks good to me, overall. Tested, checked code (especially tests).

2022-04-14 11:11 UTC, TomasSlama approved these changes
GJ 👍

2022-04-14 12:17 UTC, merged