chore: added deprecation warning to
toptal/picasso pull request #2630
Opened 2022-04-12 15:34 UTC by OndrejTuma

[FX-2614]

### Description

Added deprecation warning for `requiredDecoration` in components FormLabel, FormControlLabel, Checkbox

### How to test

Open and check if the warning appears on Form components and Check

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-12 15:45 UTC, separatio commented
It's currently used in packages/picasso-forms/src/FieldLabel/FieldLabel.tsx as well.

2022-04-12 15:53 UTC, augustobmoura requested changes
You should also put an `@deprecated` doc on the `requiredDecoration` field definition in `Props` interface. [Text editors and Typescript](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#deprecated) use this comment to show the user that he is using a deprecated functionality

Official example: https://www.typescriptlang.org/play#example/jsdoc-deprecated

``` typescript
/**
  * @deprecated <reason>
  */
```

2022-04-12 16:00 UTC, dmaklygin commented
what about [this](https://github.com/toptal/picasso/blob/b7a234e18f41a4e54a8ae76f705f2b6abb8c9d5b/packages/picasso/src/Checkbox/story/Required.example.tsx#L9) example, shouldn't it be removed or marked as deprecated?

2022-04-12 17:08 UTC, OleksandrNechai commented on packages/picasso/src/Checkbox/Checkbox.tsx
> +      description: "There will be 'optional' boolean property instead"
Hmm, I wonder maybe we need first to have that `optional` prop, and only then do we deprecate?
If we deprecate now, this would mean people will see the message and will have no chance to fix it?

2022-04-12 20:12 UTC, OndrejTuma commented on packages/picasso/src/Checkbox/Checkbox.tsx
> +      description: "There will be 'optional' boolean property instead"
Good question. There will be a codemod when major version is released. But it would be cumbersome to make optional coexist with requiredDecoration. Maybe I remove this description?
The default message would be `Checkbox's 'requiredDecoration' prop is deprecated and will be removed in the next major release of Picasso.`
cc @OleksandrNechai

2022-04-13 11:29 UTC, closed without merging

2022-04-13 11:29 UTC, OndrejTuma commented
Closing in alignment with https://toptal-core.slack.com/archives/GG3F4AS4T/p1649837425404379