chore: use davinci for unit tests
toptal/picasso pull request #2642
Opened 2022-04-14 15:10 UTC by TomasSlama

[FX-NNNN]

### Description

Use davinci-qa for unit testing

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-14 15:14 UTC, TomasSlama commented on jest.spec.js
> +  ],
withouth this option, jest is throwing error about multiple package.json files for each package, one in root and second in dist-package.

2022-04-14 15:15 UTC, TomasSlama commented on packages/picasso/src/utils/Formatters/format-amount.test.ts
> +      )
this test was never run before because it didn't match the `test.ts(x)` pattern. I have checked in the browser console, this is the expected outcome.

2022-04-14 15:24 UTC, denieler commented on jest.spec.js
> +  restoreMocks: false
why `false` for those?

2022-04-14 15:24 UTC, denieler commented on package.json
> +    "test:unit:debug": "cross-env NODE_OPTIONS=--inspect-brk davinci qa unit --config=./jest.spec.js",
does anybody use debugging with `-inspect-brk`?

2022-04-14 15:25 UTC, denieler commented on package.json
> +    "@toptal/davinci-qa": "^5.7.0",
we use `@toptal/davinci` this should be enough 👍

2022-04-14 15:26 UTC, denieler commented on package.json
> +    "test:unit": " davinci qa unit --config=./jest.spec.js",
do we really need a custom config?

2022-04-14 15:27 UTC, TomasSlama commented on package.json
> +    "test:unit": " davinci qa unit --config=./jest.spec.js",
I was trying to avoid it, but couldnt make it work without it.

2022-04-14 15:29 UTC, TomasSlama commented on package.json
> +    "@toptal/davinci-qa": "^5.7.0",
Since we are requiring davinci qa directly, we have eslint warning, that we should have in package.json

2022-04-14 15:49 UTC, dmaklygin requested changes
Let's wait for new version of davinci. It's already here: https://github.com/toptal/picasso/pull/2620
there are several updates

2022-04-14 16:10 UTC, denieler commented on package.json
> +    "@toptal/davinci-qa": "^5.7.0",
this is wrong, we should exclude this line from the check then

2022-04-19 06:25 UTC, dmaklygin commented on jest.spec.js
> +  ],
we have this path in `testPathIgnorePatterns` in davinci, worth adding this to `modulePathIgnorePatterns` as well: [testPathIgnorePatterns](https://github.com/toptal/davinci/blob/7ed96238b5d8ad9609eb255b7dc4ecbe6efae55e/packages/qa/src/configs/jest.config.js#L73)

2022-04-20 08:08 UTC, TomasSlama reviewed
@dmaklygin I approve, but since I created the PR I cannot ;-)

2022-04-20 08:08 UTC, TomasSlama commented on packages/picasso/src/TypographyOverflow/test.tsx
> +  })
leftover

2022-04-20 08:10 UTC, dmaklygin approved these changes

2022-04-20 08:12 UTC, TomasSlama commented on package.json
> +    "test:unit:debug": "cross-env NODE_OPTIONS=--inspect-brk davinci qa unit --config=./jest.spec.js",
I don't think so, but I can't be sure, it was there before, so I left it there ;-)

2022-04-20 08:22 UTC, TomasSlama commented on jest.spec.js
> +  ],
@dmaklygin I have created [PR in davinci](https://github.com/toptal/davinci/pull/1237/files) to update the config, we can then remove this customization.

2022-04-20 08:37 UTC, denieler commented on package.json
> +    "test:unit": " davinci qa unit --config=./jest.spec.js",
is it needed for aliases only?

2022-04-20 08:38 UTC, denieler commented on packages/picasso/src/MediaSkeletonLoader/test.tsx
> +  'react-content-loader',
why this mock is necessary?

2022-04-20 08:39 UTC, denieler commented on packages/picasso/src/Popper/test.tsx
> -  it('creates useStyle hook properly', () => {
why to remove this test?

2022-04-20 09:11 UTC, ozgurkececioglu approved these changes

2022-04-20 10:44 UTC, augustobmoura commented on package.json
> +    "test:unit:debug": "cross-env NODE_OPTIONS=--inspect-brk davinci qa unit --config=./jest.spec.js",
I use it, mostly on codemods

2022-04-20 14:11 UTC, TomasSlama commented on package.json
> +    "test:unit": " davinci qa unit --config=./jest.spec.js",
@denieler yes, after Dmitrys refactor of unit tests.

2022-04-20 14:16 UTC, TomasSlama commented on package.json
> +    "test:unit": " davinci qa unit --config=./jest.spec.js",
we specify `root` property to `packages/`

2022-04-20 14:19 UTC, TomasSlama commented on packages/picasso/src/Popper/test.tsx
> -  it('creates useStyle hook properly', () => {
@dmaklygin could you answer here? since you did the refactor of this file 🙇

2022-04-20 14:23 UTC, TomasSlama commented on jest.spec.js
> +  ],
PR merged in davinci, so I updated davinci to latest and removed unnecessary parts in config. 🎉

2022-04-21 12:37 UTC, separatio commented on packages/picasso/src/Popper/test.tsx
> -  it('creates useStyle hook properly', () => {
FWIW, I'm also interested about this.

2022-04-21 12:38 UTC, separatio approved these changes
Looking forward to having this merged. :+1:

2022-04-21 12:38 UTC, TomasSlama commented on packages/picasso/src/MediaSkeletonLoader/test.tsx
> +  'react-content-loader',
I have test it out and it is actually not needed 👍

2022-04-21 15:16 UTC, augustobmoura approved these changes
LGTM! :+1:

2022-04-22 08:36 UTC, denieler commented on package.json
> +    "test:unit:debug": "cross-env NODE_OPTIONS=--inspect-brk davinci qa unit --config=./jest.spec.js",
@augustobmoura this particular command?

2022-04-22 08:37 UTC, denieler commented on packages/picasso/src/TypographyOverflow/test.tsx
> +  })
☝️

2022-04-22 08:38 UTC, denieler commented on packages/picasso/src/utils/Formatters/format-amount.test.ts
> +        '1 500,00 $US'
this output value doesn't seem correct

2022-04-22 09:15 UTC, TomasSlama commented on packages/picasso/src/utils/Formatters/format-amount.test.ts
> +        '1 500,00 $US'
@denieler I was testing it locally. And it is correct.
![image](https://user-images.githubusercontent.com/6830426/164676187-26ece811-78c9-48dd-b135-006c77b45ab9.png)

2022-04-25 07:18 UTC, TomasSlama commented on packages/picasso/src/TypographyOverflow/test.tsx
> +  })
✅

2022-04-25 07:56 UTC, denieler commented on packages/picasso/src/RichTextEditor/hooks/useCounter/test.ts
> +    )
why do we need to change this test?

2022-04-25 07:57 UTC, denieler commented on packages/picasso/src/Select/hooks/use-select-state/test.ts
> +    mockedFlattenOptions.mockImplementation(() => flattenedOptions)
seems like too many mocks 🤔 it might make sense to split this component/test or use integration tests to test it

2022-04-25 07:59 UTC, TomasSlama commented on packages/picasso/src/RichTextEditor/hooks/useCounter/test.ts
> +    )
@denieler  I think Dmitry wanted to make it more explicit and clear what is the result, before it was checking `toContain('4')`

2022-04-27 22:12 UTC, TomasSlama commented
will split it into multiple smaller PRs

2022-04-27 22:12 UTC, closed without merging