chore(deps): bump d3 packackes
toptal/picasso pull request #2661
Opened 2022-04-19 11:30 UTC by TomasSlama

### Description

Update all d3 packages to the latest version.

- We still need to keep d3-arrays in resolutions, since recharts are expecting d3-arrays@2. The only breaking change to v3 is dropping support of node@12.

### How to test

**affected components:**
- Charts
- StaticTreeView
- TreeView

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-20 08:27 UTC, denieler commented on packages/picasso-charts/src/types.ts
> +export type CoordinatePayload = CategoricalChartState
why then we need this type at all?

2022-04-20 08:28 UTC, denieler commented on packages/picasso/src/TreeView/useTree.ts
> +import { hierarchy, HierarchyPointNode, tree } from 'd3' // eslint-disable-line import/no-duplicates
why do we need to have now `import/no-duplicates` rule disabled?

2022-04-20 08:37 UTC, TomasSlama commented on packages/picasso-charts/src/types.ts
> +export type CoordinatePayload = CategoricalChartState
This type is used a lot across the components, so I didn't want to make so many changes. But maybe it makes sense to change it 👍

2022-04-20 08:40 UTC, TomasSlama commented on packages/picasso-charts/src/types.ts
> +export type CoordinatePayload = CategoricalChartState
@denieler ok it was not that much at all. I removed it ✅

2022-04-20 09:26 UTC, ozgurkececioglu approved these changes
Good job 👍 tested locally, looks good

2022-04-21 08:58 UTC, denieler commented on packages/picasso-charts/src/utils/calculate-tooltip-position/calculate-tooltip-position.ts
> +import { CategoricalChartState } from 'recharts/types/chart/generateCategoricalChart'
same here

2022-04-21 08:59 UTC, denieler requested changes
I see that charts started to be wider in visual screenshots. If the behavior is the same when we use charts - this should be treated as a breaking change.

So better to avoid such changes

2022-04-21 11:55 UTC, TomasSlama commented on packages/picasso-charts/src/LineChart/LineChart.tsx
> +import { CategoricalChartState } from 'recharts/types/chart/generateCategoricalChart'
I have removed the `recharts` update from this PR because of unexpected changes in visual tests, with that, we don't need to do any changes in types.

2022-04-21 12:29 UTC, LashaJini approved these changes

2022-04-21 12:35 UTC, separatio approved these changes
I had previously checked this PR and the screenshots diffs that happened in it.

While I didn't manually test, I see tests pass and the code looks :ok:.

2022-04-21 13:02 UTC, denieler approved these changes

2022-04-21 13:52 UTC, merged