fix(Select) - click on search icon focuses the input
toptal/picasso pull request #2691
Opened 2022-04-27 07:57 UTC by TomasSlama

[FX-2668]

### Description

Follow up to [previous PR](https://github.com/toptal/picasso/pull/2233) that fixes the behavior of search input in Select.

### How to test

- Open select story with search behavior
- Click the select to open options
- Click the search icon in the search input
- Search input should be focused

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-27 10:59 UTC, denieler commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
it looks like not a necessary change, also I liked the previous version more 😃

2022-04-27 11:00 UTC, denieler commented on cypress/component/Select.spec.tsx
> -  it.skip('renders select with search', () => {
I think it makes sense to keep this test, only to remove `.skip`

2022-04-27 11:04 UTC, denieler commented on packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
> +          <Input
what was the problem of using `OutlinedInput`?

2022-04-27 11:05 UTC, denieler commented on packages/picasso/src/Select/hooks/use-select-props/use-search-blur-handler/use-search-blur-handler.ts
> +) => searchOutlineRef?.current?.contains(event.currentTarget as Node)
it doesn't look like we check for search icon in this function, however it called `isRelatedTargetSearchIcon`

2022-04-27 11:06 UTC, denieler commented on packages/picasso/src/Select/hooks/use-select-props/use-search-blur-handler/use-search-blur-handler.ts
> +        }
based on the fact, that this functionality you are fixing right now was working before, it looks to me that this is not a proper fix for the problem 🤔

2022-04-27 14:57 UTC, TomasSlama commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
@denieler I changed because of Eslint warning, we are having the same variable name in different scope.

2022-04-27 14:58 UTC, TomasSlama commented on packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
> +          <Input
With `OutlinedInput` we had the wrong `cursor: pointer` and also adornment component had a different HTML structure and disable pointer events didn't work properly.

2022-04-27 15:01 UTC, TomasSlama commented on packages/picasso/src/Select/hooks/use-select-props/use-search-blur-handler/use-search-blur-handler.ts
> +        }
@denieler this didn't work. I was checking Picasso@11 and it didn't work. Whenever you clicked on the icon, it focused the select.

2022-04-27 15:02 UTC, denieler commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
but before it was ok, I don't see we added additional `testIds` variable 🤔

2022-04-27 15:04 UTC, denieler commented on packages/picasso/src/Select/hooks/use-select-props/use-search-blur-handler/use-search-blur-handler.ts
> +        }
if the reason was the icon - here is the solution we used in other components - `disablePointerEvents` (https://github.com/toptal/picasso/blob/0950255bf20899b1e6e22f9fa1e7c5e0c79022e6/packages/picasso/src/Autocomplete/Autocomplete.tsx#L264)

2022-04-27 15:10 UTC, TomasSlama commented on packages/picasso/src/Select/hooks/use-select-props/use-search-blur-handler/use-search-blur-handler.ts
> +        }
@denieler I was trying that, it didn't solve the issue, still triggered the onBlur event

2022-04-28 09:58 UTC, denieler commented on packages/picasso/src/Select/types.ts
> +  searchOutlineRef?: React.RefObject<HTMLDivElement>
do we still need those?

2022-04-28 09:59 UTC, denieler commented on packages/picasso/src/NonNativeSelect/styles.ts
> +      pointerEvents: 'none'
I think this should be done via a prop ☝️ not via style. It will be more declarative

2022-04-28 11:33 UTC, TomasSlama commented on packages/picasso/src/NonNativeSelect/styles.ts
> +      pointerEvents: 'none'
@denieler I'm not sure I get your suggestion, I moved it to inline styles, do you think it is better 🤔?

2022-04-28 13:38 UTC, denieler commented on packages/picasso/src/NonNativeSelect/styles.ts
> +      pointerEvents: 'none'
no, I meant we use somewhere `InputAdornment` component, so we need to just pass there a prop `disablePointerEvents: true`

2022-04-29 07:39 UTC, TomasSlama commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
It was not, people just ignore eslint warnings 🤷

2022-04-29 07:40 UTC, TomasSlama commented on packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
> +          <Input
After discussion with Daniel, I have returned the OutlinedInput, it was used on purpose to not having additional div around addornment

2022-04-29 11:59 UTC, dmaklygin approved these changes
Checked locally. works!

2022-05-02 06:04 UTC, TomasSlama commented on packages/picasso/src/NonNativeSelect/styles.ts
> +      pointerEvents: 'none'
✅

2022-05-02 06:48 UTC, TomasSlama commented on packages/picasso/src/Select/types.ts
> +  searchOutlineRef?: React.RefObject<HTMLDivElement>
good catch, we don't need it anymore

2022-05-02 06:48 UTC, TomasSlama commented on packages/picasso/src/Select/types.ts
> +  searchOutlineRef?: React.RefObject<HTMLDivElement>
✅

2022-05-03 14:12 UTC, TomasSlama commented on packages/picasso/src/NonNativeSelect/styles.ts
> -    },
InputAdornment component handles this for us

2022-05-03 14:23 UTC, separatio commented on cypress/component/Select.spec.tsx
> +    it('renders', () => {
This test is redundant. You can do the screenshot in line 475. Should be the same, but you'll mount the component 1 time less. :slightly_smiling_face:

2022-05-03 14:26 UTC, separatio commented on cypress/component/Select.spec.tsx
> +    it('focuses the input on type', () => {
Since these are not unit tests, you can have all 4 tests under only one example, and mount the component only once.

You can also extract the mounted component into a const and pass it to mount, so that it's more declarative.
`mount(select)`

2022-05-03 15:10 UTC, dmaklygin approved these changes

2022-05-03 19:53 UTC, augustobmoura commented
@toptal-bot run deploy:documentation

2022-05-03 19:55 UTC, augustobmoura commented
> @toptal-bot run deploy:documentation

For some reason this command is not working, or I'm doing something wrong, one of them 🤔

2022-05-03 20:14 UTC, augustobmoura approved these changes
Manual tested it, and it works! Good job! :+1:

2022-05-04 07:28 UTC, OndrejTuma commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
I checked its only used in one test, so what about move it there? Line 301

2022-05-04 08:38 UTC, TomasSlama commented on cypress/component/Select.spec.tsx
> +const testIdsDefault = {
@OndrejTuma you are right, I have moved the declaration into the test 👍

2022-05-04 10:15 UTC, separatio approved these changes
Looks good. Tested, code reviewed.

2022-05-04 10:48 UTC, OndrejTuma approved these changes
Great work 💪 tested and works as expected

2022-05-04 10:50 UTC, OndrejTuma requested changes
The icon does not change color when blurred - see Happo screens

2022-05-04 18:50 UTC, OndrejTuma approved these changes

2022-05-05 07:05 UTC, merged