feat(SidebarItem): refactor sidebar item
toptal/picasso pull request #2697
Opened 2022-04-27 21:44 UTC by augustobmoura

[FX-1429](https://toptal-core.atlassian.net/browse/FX-1429)

**Depends on #2687 being merged**

### Description

Add badge options to `SidebarItem`s, should have different styles on collapsed and not collapsed states

### How to test

- CI should be green
- Happo tests should be affected as we added the badges to examples
- Run storybook and test the feature on PageSidebar

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/5845160/165635273-fdfef53f-8978-416d-9ac2-c77e3def3f43.png) | !![image](https://user-images.githubusercontent.com/5845160/165635842-803b99e3-c893-411a-80e4-cee89acacd9e.png) |
| ![image](https://user-images.githubusercontent.com/5845160/165635478-5a720ff5-cf08-44e1-8bfa-38d4d13d0c58.png) | ![image](https://user-images.githubusercontent.com/5845160/165635934-841d0377-b746-48f5-a5f7-c321933ee6ab.png) |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-29 06:49 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  badgeProps?: Omit<BadgeProps, 'size' | 'children'>
As far as I remember (see the [ticket](https://toptal-core.atlassian.net/browse/FX-2179)), the badge will always be red. Is it better to get badge content only as a prop to limit variant to red directly?

2022-04-29 09:47 UTC, dmaklygin commented on packages/picasso/src/utils/get-node-text-content.ts
> +import { ReactNode } from 'react'
you can create `get-node-text-content.test.ts` file, to cover only this file, instead of adding test cases to `utils.ts`

2022-04-29 09:52 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  </Typography>
I'm wondering, what if there is very long word. Do we need to cut it and overflow it with `dots` ?

2022-04-29 09:54 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
seems like a separate component, wdyt if we define it outside of `ItemContent` component?

2022-04-29 10:32 UTC, dmaklygin commented
Wondering, why new 4 screenshots in hapo. However you didn't add a new test cases in cypress.

2022-04-29 10:53 UTC, dmaklygin commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
in AC criteria, it: 
> mandatory prop, accepts only strings

2022-04-29 11:01 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
wdyt to cache this operation via useMemo?

2022-04-29 11:02 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
```suggestion
const wrappedIcon =  useMemo(() => {
let wrappedIcon
  if (isCollapsed && hasIcon) {
    wrappedIcon = (
      <Tooltip
        compact
        placement='right'
        content={getNodeTextContent(resolvedChildren)}
      >
        <div>{wrappedIcon}</div>
      </Tooltip>
    )
  }

  if (hasBadge && badgeNeedsToBeOverlay) {
    wrappedIcon = buildBadge(wrappedIcon)
  }
  
  return wrappedIcon
}, [deendencies])
  
```

2022-04-29 11:04 UTC, dmaklygin commented
Got this console error:
```
v1.js:1 Warning: React does not recognize the `badgeProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `badgeprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

2022-04-29 11:07 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      : children
According to Acceptance Criteria, the children props must be only string:
> children - accepts only strings

2022-04-29 11:10 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +
`resolvedChildren` is not needed to render when Sidebar is collapsed. wdyt?

2022-04-29 11:13 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +        {!badgeNeedsToBeOverlay && buildBadge()}
logic of rendering badges for two states (collapsed and expanded) is quite complicated.
It's quite difficult to keep it in mind. Maybe, it's only my concerns.

2022-04-29 11:14 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +        {!badgeNeedsToBeOverlay && buildBadge()}
wdyt if we just have two separate components: one for rendering expanded state, another one — for sollapsed?

2022-04-29 11:29 UTC, TomasSlama commented
> Wondering, why new 4 screenshots in hapo. However you didn't add a new test cases in cypress.

@dmaklygin it was introduced in base branch. Happo does not work properly, when not merging into the master. I think we should leave the happo tests when we will be mergin the feature branch to master.

2022-05-02 08:26 UTC, denieler commented on packages/picasso/src/SidebarItem/styles.ts
> +    },
please create a separate folder for `ItemContent` component. We started to split into multiple components, but we use the same styles file, which makes further refactoring very hard if needed

2022-05-02 08:27 UTC, denieler commented on packages/picasso/src/SidebarItem/ItemContent.tsx
>      isContentVisible,
I think visibility of the component shouldn't be handled by the component itself, rather than by the parent component

2022-05-02 08:28 UTC, denieler commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  let wrappedIcon: ReactNode = icon
```suggestion
  let wrappedIcon = icon
```

2022-05-02 08:34 UTC, denieler commented on packages/picasso/src/SidebarItem/ItemContent.tsx
>  export const ItemContent = (props: Props) => {
code in this component looks a bit messy, maybe we can split it into smaller components? there are many unclear conditions 🤔

2022-05-02 08:35 UTC, denieler commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
to be honest, not sure I like such API. Maybe 3rd level compound component for `Item.Badge`?

2022-05-03 03:37 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
I don't think we need to memoize this, it's just elements, no slow computation

2022-05-03 03:39 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
It's just building JSX elements, I don't think memoization is necessary, or advised

2022-05-03 03:40 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
This is a thing that we should discuss on the daily, I think the ticket is a bit older and it only allowed strings at the time. Maybe the use case for elements came after?

2022-05-03 03:42 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
It doesn't seem that useful as an outside component, but it definitely can be a component on the same file. We are just adding some defaults specific to Sidebar to Badge

2022-05-03 03:42 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  badgeProps?: Omit<BadgeProps, 'size' | 'children'>
Yep, I think its fair to make it red always

2022-05-03 09:06 UTC, TomasSlama commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
@augustobmoura @dmaklygin I remember we discussed this when complying the Badge with BASE, we changed the type of content to `number` because it is never used in other projects with anything else and everyone was doing `String(number)`

2022-05-03 18:13 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  </Typography>
I think we are already ellipsing long texts. You can see it on the examples:
![image](https://user-images.githubusercontent.com/5845160/166516287-32d4f576-31d4-4af2-8ac5-6015943b8cdc.png)

2022-05-03 18:15 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
Yep, I got confused on what prop @dmaklygin was talking about. We decided on only allowing numbers in badges a few weeks ago

2022-05-03 18:16 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      : children
The implementation allowing any react node was already implemented before this PR, maybe the issue was made before it was decided on allowing arbitrary nodes?

2022-05-03 18:17 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +
Makes sense, I will simplify the component and remove it when the sidebar is collapsed

2022-05-03 18:18 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +        {!badgeNeedsToBeOverlay && buildBadge()}
I will split the component in two

2022-05-03 18:18 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/styles.ts
> +    },
Done

2022-05-03 18:19 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
>      isContentVisible,
Makes sense, this is from a prior PR, I renamed it to `compact` as it makes more semantic sense. When the flag is true we hide the content, add the tooltip, and badges become overlayed

2022-05-03 18:20 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
I was just following what was specified in the [jira issue](https://toptal-core.atlassian.net/browse/FX-1429). It actually asked for a `badge` prop, but I figured `badgeProps` make it more explicit

2022-05-03 18:23 UTC, augustobmoura commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
We could also write something like `badge={10}` only allowing content to be set

2022-05-03 19:17 UTC, dmaklygin commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
okay, then if handled properly. closing the thread :)

2022-05-03 19:19 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
actually, there are complex operation: create `wrappedIcon` + wrap it with `buildBadge` function. Not sure, but I would wrap it with useMemo

2022-05-03 19:24 UTC, dmaklygin commented on packages/picasso/src/utils/test.tsx
> +    it.each([42, -12, Infinity, NaN, -0])(
👍

2022-05-03 19:32 UTC, dmaklygin commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      : children
okay, let's keep this condition!

2022-05-03 19:33 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +      : children
In any case I will update the issue description on jira

2022-05-03 19:35 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  badgeProps?: Omit<BadgeProps, 'size' | 'children'>
Actually, the jira issue explicitly asks for a `variant` prop, let's discuss this quickly on the daily

2022-05-04 08:53 UTC, denieler commented on packages/picasso/src/PageSidebar/story/Variants.example.tsx
> +      <Page.Sidebar.Item badgeProps={{ content: 5 }} icon={<LegalInfo16 />}>
`badge` looks better to me 👍

2022-05-04 08:56 UTC, denieler commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +  compact?: boolean
I think it's not clear what `compact` means 🤷‍♂️ I would either add a bigger description either add an example of how compact is different from a non-compact sidebar item

2022-05-04 08:58 UTC, denieler commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> -      testIds,
I think after we removed `testIds` and we pass it to `MenuItem` as `...rest` - would not work. Because `testIds` in this component has a pretty specific shape, which is not supported by `MenuItem` looks like

2022-05-04 09:00 UTC, denieler commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +            [classes.compactRoot]: compact,
```suggestion
            [classes.compact]: compact,
```

2022-05-04 09:03 UTC, denieler commented on packages/picasso/src/utils/get-node-text-content.ts
> +export const getNodeTextContent = (node: ReactNode): string => {
nit:

```suggestion
export const getReactNodeTextContent = (node: ReactNode): string => {
```

2022-05-04 09:23 UTC, denieler commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +  const ItemContentVariant = compact ? CompactItemContent : ExpandedItemContent
nit: as soon as we don't export those components:

```suggestion
  const ItemContentVariant = compact ? Compact : Expanded
```

2022-05-04 10:14 UTC, denieler commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +  }
```suggestion
  let wrappedIcon = hasBadge
    ? (
      <ItemContentBadge content={badgeProps.content}>
        {icon}
      </ItemContentBadge>
    )
    : icon
```

2022-05-04 10:15 UTC, denieler commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        <div>{wrappedIcon}</div>
`div` is important here, right?

2022-05-04 10:16 UTC, denieler approved these changes
I think only important change needs to be done - move tests out from utils tests 🙇‍♂️

2022-05-04 12:12 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        <div>{wrappedIcon}</div>
Yes, I don't know why, but Tooltip doesn't work directly on icons, I think it's something related to forwardRefs and our wrapper implementation. Wrapping the icon o a element makes it work

2022-05-04 12:37 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/ItemContent.tsx
> +  }
Wrap icon is just wrapping it on a JSX element:
``` javascript
// Example
<Wrapper>
  {wrappedIcon}
</Wrapper>
```

And `buildBadge` was removed, but it was just creating new JSX elements as well:
``` javascript
// Example
const buildBadge = () => (
  <div>
    Foo
  </div>
)
```

So both these examples are basically the same:
``` javascript
const Example = ({ foo }) => {
  const buildBadge = () => (
    <div>Foo</div>
  )
  
  let icon = <span>Bar</span>
  
  if (foo) {
    icon = <Wrapper>{icon}</Wrapper>
  }
  
  return (
    <div>
      {icon}
      {buildBadge()}
    </div>
  )
}
```
```javascript
const Example = ({ foo }) => {
  return (
    <div>
      {foo
        ? <Wrapper><span>Bar</span></Wrapper>
        : <span>Bar</span>}
      <div>Foo</div>
    </div>
  )
}
```

The first one is splitting the flow of the render function in an additional function and an if statement, but the result tree are the same

Creating JSX elements shouldn't be expensive, because, well, react is all about re-creating JSX elements over and over 😅

2022-05-04 13:37 UTC, augustobmoura commented on packages/picasso/src/utils/get-node-text-content.ts
> +import { ReactNode } from 'react'
[Currently](https://github.com/toptal/picasso/blob/08d0d18283a8dc00a1af8e4b7abb6abab9e5cd60/jest.config.js#L11) we only allow test files to have the exact name `test.ts`. I talked about this when writing the tests for the new codemods. I wanted to change it to a suffix instead of an exact match, but ultimately we decided on splitting the codemods in it's own repo so that it could have it's own rules

2022-05-04 13:44 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> -      testIds,
Currently, MenuItem doesn't have and `testIds` prop, if we add it in the future, typescript will throw an error if the types differ. I let it be for now in favor of having a simpler concise code

2022-05-04 13:55 UTC, augustobmoura commented
> I think only important change needs to be done - move tests out from utils tests bowing_man

I talked more about it here https://github.com/toptal/picasso/pull/2697#discussion_r864837819

2022-05-04 14:00 UTC, dmaklygin commented on packages/picasso/src/utils/get-node-text-content.ts
> +import { ReactNode } from 'react'
sure, thanks for explanation!

2022-05-04 14:08 UTC, dmaklygin commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +  )
```suggestion
  const wrappedIcon = hasBadge ? (
    <ItemContentBadge content={badgeProps.content}>
      {wrappedIcon}
    </ItemContentBadge>
  ) : (
    icon
  )
```

2022-05-04 14:09 UTC, dmaklygin commented on packages/picasso/src/SidebarItemContent/styles.ts
> +      marginLeft: '0.5rem'
inconsistency in `rem` and `em`

2022-05-04 14:18 UTC, dmaklygin commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        content={getReactNodeTextContent(children)}
I would memoize the result of `getReactNodeTextContent`

2022-05-04 14:23 UTC, dmaklygin commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        <div>{wrappedIcon}</div>
According to Props definition, the `icon` is optional, shouldn't we add a condition to render a Tooltip?

2022-05-04 15:03 UTC, TomasSlama approved these changes

2022-05-04 15:07 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        content={getReactNodeTextContent(children)}
Memoization doesn't work that well with children, because they have different identities in every rerender.
You can see an example of it [here](https://codesandbox.io/s/cool-liskov-td9db7?file=/src/App.js). Notice how 're-run memo' is logged on each render

2022-05-04 15:08 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +        <div>{wrappedIcon}</div>
Good catch! Will fix it

2022-05-04 15:15 UTC, augustobmoura commented on packages/picasso/src/utils/test.tsx
> +    it('returns an empty string, value: "%s"', () => {
Yep, I will remove it

2022-05-05 07:40 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +  const { children, titleCase: propsTitleCase, compact } = props
I think you forgot to extract and pass the `badge` prop for customization of the item.

2022-05-05 07:42 UTC, ozgurkececioglu requested changes
Badge customization is not working as expected. See the comment: https://github.com/toptal/picasso/pull/2697/files#r865630792

2022-05-05 07:50 UTC, LashaJini commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +        if (expansion) {
```suggestion
        if (shouldExpand) {
```
wdyt?

2022-05-05 07:50 UTC, LashaJini commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +        <SidebarItemContent {...props} />
We removed and re-added `testIds` but not passing it here again :thinking:

2022-05-05 07:50 UTC, LashaJini commented on packages/picasso/src/SidebarItemContent/styles.ts
> +      marginLeft: '0.875rem'
Didn't we agree to use `em` as much as possible :thinking:

2022-05-05 07:50 UTC, LashaJini commented on packages/picasso/src/utils/get-react-node-text-content.ts
> + * @see {@link https://stackoverflow.com/a/60564620/4595583} for the inspiration
:hearts:

2022-05-05 11:02 UTC, OndrejTuma commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +    )
I'm wondering whether we can achieve icon to be mandatory when Sidebar is collapsible?
If sidebar is compact and icon undefined then its just a blank space. Or maybe add a default icon?
Something 🙂 
Wdyt?

2022-05-05 11:03 UTC, OndrejTuma commented on packages/picasso/src/utils/test.tsx
> +})
very much like your tests 👍

2022-05-05 14:04 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +        <SidebarItemContent {...props} />
It's being passed on `...props`. We filtered it from `rest`

2022-05-05 14:07 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +    )
Yep, I sent a message to Milos yesterday about it, he said that we can use the placeholder icons on missing icons

2022-05-05 14:09 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
> +  const { children, titleCase: propsTitleCase, compact } = props
Good catch, I will add them

2022-05-05 14:10 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/styles.ts
> +      marginLeft: '0.875rem'
IIRC we are avoiding `em` in favor of `rem`

2022-05-05 14:15 UTC, augustobmoura commented on packages/picasso/src/SidebarItem/SidebarItem.tsx
> +        if (expansion) {
Yeah this `expansion` name is kinda weird, it means that the accordion is expanded, so I will rename it to something like `accordionExpanded`

2022-05-05 14:24 UTC, augustobmoura commented on packages/picasso/src/SidebarItemContent/styles.ts
> +      marginLeft: '0.875rem'
I talked with @denieler, and you are correct, we are using `rem` only for font-sizes and `em` for other things, I will change it

2022-05-05 14:34 UTC, ozgurkececioglu approved these changes
Tested locally. Working fine 👍

2022-05-05 14:40 UTC, dmaklygin approved these changes

2022-05-05 14:54 UTC, LashaJini approved these changes

2022-05-05 14:58 UTC, merged