chore: [FX-2607] update inline alert design
toptal/picasso pull request #2701
Opened 2022-04-28 12:15 UTC by LashaJini

[FX-2607](https://toptal-core.atlassian.net/browse/FX-2607?atlOrigin=eyJpIjoiY2ZhY2IzYmZlMzQ4NDMwMDg0OTIzY2RjNGE1NmM4NDIiLCJwIjoiaiJ9)

### Description

- Change text color so it satisfies the design
- Change font size from `14px` to `13px`
- Change font weight from `400` to `600`

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-04-28 12:47 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
We could replace `blue` with `light-blue` in the `VariantType` (which would have been more consistent with actual colors being passed), but it would have been a breaking change.

2022-04-28 13:27 UTC, TomasSlama commented on .changeset/red-socks-fly.md
> +- Add `ligt-blue` to shared color types
```suggestion
- Add `light-blue` to shared color types
```

2022-04-28 13:27 UTC, TomasSlama commented on .changeset/selfish-nails-lick.md
> +- Change line height from `22px` to `20px`
Do you think this is important for users to know? 🤔 

How about something like `- Updated styles to be compliment with BASE design`? WDYT?

2022-04-28 13:27 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
Since `inline` and `block` are values of the `display` property in CSS, how about naming this property `displayVariant`?

2022-04-28 13:27 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
>  }
```
const AlertIconsMap = {
  block: {
    red: <Exclamation16 color='red' />,
    // ...
  },
  // inline: { ... }
}

// usage
const Icon = AlertIconMap[alertVariant][variant]
```

What do you think about this approach? 🤔

2022-04-28 13:27 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
const SizeMap = {
 inline: 'small',
 block: 'medium'
}

2022-04-28 13:29 UTC, TomasSlama reviewed
Good job Lasha, I have just checked the code and left some comments. I will be checking design little bit later.

2022-04-28 13:36 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
hmm, but it's not quite related to `display` property in CSS. I just got the "inspiration" from [figma's](https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=8%3A2) variants.

2022-04-28 13:37 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
>  }
Better :+1:

2022-04-28 13:47 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
@LashaJini yeah, in figmat it is right, because it is actually `variant`, but we used it already for `color`

2022-04-28 13:48 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
but you are right, maybe `display` is not the right naming either. Maybe someone else will have better idea 🤷

2022-04-28 13:56 UTC, denieler commented on .changeset/red-socks-fly.md
> +- Add `light-blue` to shared color types
```suggestion
- Add `light-blue` color
```
🤷‍♂️

2022-04-28 13:57 UTC, denieler commented on .changeset/selfish-nails-lick.md
> +- Add `lightBlue` style
```suggestion
- Add `lightBlue` color
```
because the prop name is `color` in `Typography` component has been added

2022-04-28 18:58 UTC, dmaklygin commented on packages/picasso/src/AlertInline/__snapshots__/test.tsx.snap
> +            d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0Zm0 11a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm0-8a1 1 0 0 0-1 1v5a1 1 0 1 0 2 0V4a1 1 0 0 0-1-1Z"
fix me, but according to Figma design, icons should be kept as is. no?

2022-04-28 19:02 UTC, dmaklygin commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
let's maybe follow Figma design and name it `variant` — then it will be a breaking change

2022-04-28 19:04 UTC, dmaklygin commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
wdyt if we avoid adding this workaround and use exactly what specified in the Figma design?

2022-04-29 07:07 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
☝️ might be the optimal idea. `variant` and `color`. But then we are increasing the scope of the ticket a lot 🤔

2022-04-29 07:07 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +        size={alertVariant && typographyProps[alertVariant].size}
```suggestion
        size={typographyProps[alertVariant!].size}
```

Since we have `alertVariant` in `defaultProps`, we know that they will always be around. We will need to disable the eslint rule locally for this, but we do it a lot in the codebase.

2022-04-29 07:07 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +        size={alertVariant && typographyProps[alertVariant].size}
and we can even use `const { size, weight, color } = typographyProps[AlertVariant!]` so we have it only in one place

2022-04-29 07:15 UTC, TomasSlama commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
@dmaklygin after checking the storybook, I think this might be unnecessary, because we don't expose the `alertVariant` to public. We use `Alert` component when we need block variant and `Alert.Inline` for inline. So the breaking change is probably not necessary, WDYT?

2022-04-29 07:34 UTC, TomasSlama requested changes
@LashaJini it seems we are using different color for success alert
![image](https://user-images.githubusercontent.com/6830426/165902427-8729cab9-b564-4036-be2c-ce1c759eab02.png)
![image](https://user-images.githubusercontent.com/6830426/165902453-766c2285-ebdf-4e8d-9d0c-5377bfdb3b5e.png)

2022-04-29 07:39 UTC, LashaJini commented on packages/picasso/src/AlertInline/__snapshots__/test.tsx.snap
> +            d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0Zm0 11a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm0-8a1 1 0 0 0-1 1v5a1 1 0 1 0 2 0V4a1 1 0 0 0-1-1Z"
Well, `AlertInline` component has solid icons while `Alert` has just icons.

2022-04-29 08:38 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
could you specify wdym, please?

2022-04-29 09:25 UTC, dmaklygin commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
I'm completely confused :)
`Alert.Inline` has `alertVariant` prop which may be either `block` or `inline`, correct?

2022-04-29 09:26 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
Yes.

2022-04-29 09:26 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
And `Alert` extends `Alert.Inline`'s props as well.

2022-04-29 09:27 UTC, dmaklygin commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
I mean, if we want to keep backward compatibility, then this workaround is okay. 
But, we have to put a comment to keep in mind that `blue` is a leftover, and it exists only because we want to keep legacy here.
I just suggested to rework it, and use colors that are specified in design. And remove this `blue` color, because it's not specified in design anymore

2022-04-29 09:32 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  }
Yes, I also agree. And in the design we also have dark green, instead of regular green. I just didn't want to complicate this simple task, I will create a ticket when this one is merged:

- Replace `blue` with `light-blue`
- Replace `green` with `dark-green`
- Add `light-blue` and `dark-green` to Container (cuz we don't have them there, and we are passing colors to the container)
- Remove redundant `blue` and `green` colors
- Write codemod to do the replacing

2022-04-29 11:33 UTC, OndrejTuma commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
I dont understand why we need `block` variant for inline Alert? 🤔 
But if it's only these two variants, maybe just keep a boolean variable `inline` with true/false

2022-04-29 11:46 UTC, OndrejTuma commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
OK I checked it once more and now I think we should do separate implementation for block and for inline variant. Think seems to much tweaking for me. WDYT?

2022-04-29 11:54 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
It is indeed to much, cuz it's weird to handle `block` variant inside inline `Alert`. It needs quite amount of refactoring + breaking change + codemod.

2022-05-02 08:20 UTC, TomasSlama requested changes
![image](https://user-images.githubusercontent.com/6830426/166204975-024e5e82-928a-4a6b-8407-2ef79c1e0ddf.png)

The wrapper of SVG has 22px, it should be 20px, so it is vertically centered with text. Maybe we could discuss during our daily, if we should not refactor these alerts into two separate Components as @OndrejTuma suggested.

2022-05-02 09:49 UTC, LashaJini commented on packages/picasso/src/AlertInline/AlertInline.tsx
> +  alertVariant?: AlertVariant // undocumented prop, only for internal usage
https://github.com/toptal/picasso/pull/2701#discussion_r861643898 + separating `block` and `inline`.

2022-05-03 11:01 UTC, TomasSlama commented on packages/picasso/src/Alert/Alert.tsx
> +  iconPadding: 'small'
Why do we need this new internal prop? 🤔

2022-05-03 11:03 UTC, LashaJini commented on packages/picasso/src/Alert/Alert.tsx
> +  iconPadding: 'small'
Good point :+1: . I guess `AlertInline` will always have `xsmall`, while `Alert` will have `small` for `iconPadding`

2022-05-03 11:09 UTC, dmaklygin approved these changes

2022-05-03 11:27 UTC, augustobmoura approved these changes

2022-05-03 11:34 UTC, OndrejTuma approved these changes
Nice work!

2022-05-03 11:34 UTC, OndrejTuma commented on packages/picasso/src/Alert/Alert.tsx
> +  name: 'PicassoAlertInline'
Probably just:
```suggestion
  name: 'PicassoAlert'
```
?

2022-05-03 11:36 UTC, OndrejTuma commented on .changeset/selfish-nails-lick.md
> +- Add `InfoSolid16`, `InfoSolid24` icons
```suggestion
- Added `DoneSolid16`, `DoneSolid24` icons
- Added `InfoSolid16`, `InfoSolid24` icons
- Added `darkGreen` color 
```

2022-05-03 11:39 UTC, LashaJini commented on packages/picasso/src/Alert/Alert.tsx
> +  name: 'PicassoAlertInline'
:+1: , good catch. Thank you.

2022-05-03 11:42 UTC, LashaJini commented on .changeset/selfish-nails-lick.md
> +- Add `InfoSolid16`, `InfoSolid24` icons
Do we use past simple while writing changeset, :thinking: ? Or it does not matter?

2022-05-03 11:51 UTC, TomasSlama commented on .changeset/selfish-nails-lick.md
> +- Add `InfoSolid16`, `InfoSolid24` icons
Good question @LashaJini, maybe we should use `present simple` as in commits, we can discuss in daily

2022-05-03 11:59 UTC, LashaJini commented on .changeset/selfish-nails-lick.md
> +- Add `InfoSolid16`, `InfoSolid24` icons
We can quickly discuss it on daily :+1:

2022-05-03 12:54 UTC, merged