fea(PageSidebar)t: add new styling for dropdown menus
toptal/picasso pull request #2754
Opened 2022-05-10 19:55 UTC by augustobmoura

[FX-2753](https://toptal-core.atlassian.net/browse/FX-2753)

### Description

Following the adjustments made to the [BASE design](https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=9%3A32), we should add the new styles for the dropdown menus

### How to test

- Check the `Page` example on storybook, it now has an functioning Sidebar

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://user-images.githubusercontent.com/5845160/167711252-ac709451-a83d-4808-97ed-3b401d7242d5.png) | ![image](https://user-images.githubusercontent.com/5845160/167711108-ec082e64-561f-42e9-bee9-82c9d3f1a9b8.png) |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-05-11 06:19 UTC, denieler commented on packages/picasso/src/Page/story/Default.example.tsx
> +const SidebarMenu = () => {
I don't think we need to change our default example. Default example should be as simple as possible in my opinion

2022-05-11 06:21 UTC, denieler commented on packages/picasso/src/SidebarMenu/styles.ts
> +      padding: '8px'
should it be `0.5em`?

2022-05-11 06:27 UTC, separatio commented on packages/picasso/src/SidebarMenu/styles.ts
> +      padding: '8px'
Should it be `0.5rem` instead?

2022-05-11 06:50 UTC, ozgurkececioglu commented on packages/picasso/src/SidebarMenu/SidebarMenu.tsx
> +      )
👍

2022-05-11 07:43 UTC, TomasSlama reviewed
In design, there is a small gap between the menu item and the dropdown menu.

![image](https://user-images.githubusercontent.com/6830426/167795734-be4ba035-3f9b-4320-9045-fb6c9b881527.png)

2022-05-11 07:43 UTC, TomasSlama commented on packages/picasso/src/SidebarItem/styles.ts
> +          borderRadius: '4px',
```suggestion
          padding: `${rem(6px)} ${rem(16px)}`,
          borderRadius: sizes.borderRadius.small,
```

2022-05-11 08:42 UTC, separatio commented on packages/picasso/src/SidebarMenu/styles.ts
> +      padding: '8px'
I discussed it with Daneil. `em` is better. :+1:

2022-05-11 09:12 UTC, separatio commented on packages/picasso/src/Page/story/Default.example.tsx
> +      selectedItem === id && (!subItemId || subItemId === selectedSubItem)
This is hard to understand at a glance. Please extract to a function with adequate naming. It can also be tested separately.

2022-05-11 09:13 UTC, separatio commented on packages/picasso/src/Page/story/Default.example.tsx
> +      selectedItem === id && (!subItemId || subItemId === selectedSubItem)
https://docs.codeclimate.com/docs/cognitive-complexity

2022-05-12 05:50 UTC, denieler commented on packages/picasso/src/Page/story/Sidebar.example.tsx
> +export default Example
nit: I don't have a strong opinion about removing this example, but it feels like we showed this use case on the Sidebar example page and many other use cases of Sidebar. So probably it doesn't make sense to add an additional example on the Page example page.

2022-05-12 05:50 UTC, denieler approved these changes

2022-05-12 13:50 UTC, separatio commented
The collapse button is not clickable on the left side.
This only happens in the Page examples. Doesn't happen in PageSidebar examples.

https://user-images.githubusercontent.com/8407461/168090424-92f2d980-4cee-4f3e-ad4c-3899da4e886a.mp4

2022-05-12 14:20 UTC, separatio requested changes
Overall, the changes look good and I've manually tested it.

The issue above remains, though. Please fix it so that we can click the whole button, not just half.

2022-05-12 14:39 UTC, TomasSlama approved these changes

2022-05-12 14:42 UTC, ozgurkececioglu approved these changes

2022-05-12 14:51 UTC, augustobmoura commented on packages/picasso/src/Page/story/Sidebar.example.tsx
> +    [string?, string?]
It's quite recent, I think it was added on one of the tuple improvements releases of typescript

2022-05-12 16:43 UTC, separatio commented on packages/picasso/src/Page/story/Sidebar.example.tsx
>      }
Just a nit. I would've loved to have this accessible in a hook, in the real component, via a prop. Something like `useHighlightSelected` and use it if we should highlight items. That way, we don't need to implement such logic in examples. Feels a little weird. But again, it's just a nit.

2022-05-12 16:43 UTC, separatio approved these changes

2022-05-12 17:52 UTC, merged