chore: unskip Avatar tests
toptal/picasso pull request #2780
Opened 2022-05-17 09:41 UTC by TomasSlama

[FX-2705]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-05-18 06:04 UTC, ozgurkececioglu approved these changes
Ran in mac and ubuntu. Saw green (except mac for sidebar but it is not related) 👍

2022-05-19 14:54 UTC, denieler commented on cypress/component/Avatar.spec.tsx
> +const src = 'https://picasso.toptal.net/jacqueline-with-flowers-1954-square.jpg'
not a good idea ☝️ when Picasso started to be covered with Cloudflare such image was not loaded at all. So using relative path is necessary here (for relative path Cloudflare protection would not be initiated when you already entered the url)

2022-05-19 14:54 UTC, denieler requested changes
this would not work with Cloudflare

2022-05-19 15:03 UTC, TomasSlama commented on cypress/component/Avatar.spec.tsx
> +const src = 'https://picasso.toptal.net/jacqueline-with-flowers-1954-square.jpg'
@denieler It is correct for storybook stories, but as you can see in Happo screenshots, the images are working correctly.

2022-05-19 15:06 UTC, TomasSlama commented on cypress/component/Avatar.spec.tsx
> +const src = 'https://picasso.toptal.net/jacqueline-with-flowers-1954-square.jpg'
So in cypress, it works correctly, probably because we run it locally in CI. But for a storybook, it does not work on production, so we need to keep a relative path in stories.

2022-05-19 15:10 UTC, denieler commented on cypress/component/Avatar.spec.tsx
> +const src = 'https://picasso.toptal.net/jacqueline-with-flowers-1954-square.jpg'
no, it doesn't matter. Now Cloudflare is disabled, but it will be enabled eventually again and we will have this issue

2022-05-19 18:55 UTC, denieler commented on cypress/component/Avatar.spec.tsx
> +  console.log({ size, variant, src })
🔕

2022-05-19 18:56 UTC, denieler commented on cypress/component/Avatar.spec.tsx
> +        // eslint-disable-next-line
why do we need to disable next line for eslint?

2022-05-19 18:56 UTC, denieler approved these changes
Nice 👍

2022-05-20 07:15 UTC, TomasSlama commented on cypress/component/Avatar.spec.tsx
> +        // eslint-disable-next-line
it actually breaks two rules.
- because of the usage of `then`, eslint thinks it is a promise and expects to be wrapped in catch or return
- too many nested callbacks

2022-05-20 07:45 UTC, denieler commented on cypress/component/Avatar.spec.tsx
> +        // eslint-disable-next-line
you probably should specify the rules you are disabling in the comment

2022-05-20 08:35 UTC, merged