feat: added cube icon
toptal/picasso pull request #2809
Opened 2022-05-24 14:20 UTC by OKendigelian

We use the Cube icon for Product Manager links in the Vertical Booking Pages widget, which is not currently available in the Picasso library.
The goal of this ticket is to add this icon to the library.
The SVG for this icon is below.

```
<svg
  viewBox="0 0 24 24"
  width="24"
  height="24"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
>
  <path d="M10.5002 0.996582L21.0049 5.99917V17.9956L10.5002 23.0022L0 17.9956V5.99917L10.5002 0.996582ZM1 7.02858V17.3649L10.002 21.6566V11.3156L1 7.02858ZM20.004 7.02858L11.002 11.3146V21.6546L20.004 17.3639V7.02858ZM10.5 2.10388L1.744 6.27558L10.501 10.4456L19.259 6.27558L10.5 2.10388Z" />
</svg>
```

Figma link https://www.figma.com/file/TqaGgbpjGSUDf7qq153Isq/Product-Iconography?node-id=622%3A2

[FX-2806]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

**Breaking change**

- [x] codemod is created and showcased in the changeset
- [x] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-2806]: https://toptal-core.atlassian.net/browse/FX-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-05-24 15:16 UTC, TomasSlama commented
@OKendigelian Hello 👋, thanks for your contribution, we need also link to the base design (Figma) with this Icon, so we can check the correctness

2022-05-25 07:42 UTC, OKendigelian commented
> @OKendigelian Hello 👋, thanks for your contribution, we need also link to the base design (Figma) with this Icon, so we can check the correctness

Hi there! Sure https://www.figma.com/file/TqaGgbpjGSUDf7qq153Isq/Product-Iconography?node-id=622%3A2

2022-05-25 07:51 UTC, TomasSlama reviewed
I have left just few small comments, otherwise it looks good to me 👍

2022-05-25 07:51 UTC, TomasSlama commented on packages/picasso/src/Icon/index.ts
> +export { default as Cube16 } from './Cube16'
Designers named it `Box`, I think we should be consistent and use the same name.

2022-05-25 07:51 UTC, TomasSlama commented on .changeset/large-ways-arrive.md
> +Added Cube icon
```suggestion
Add Cube icon
```
We should write changesets the same as commits. In present simple.

2022-05-25 08:19 UTC, OKendigelian commented on packages/picasso/src/Icon/index.ts
> +export { default as Cube16 } from './Cube16'
Done!

2022-05-25 08:19 UTC, OKendigelian commented on .changeset/large-ways-arrive.md
> +Added Cube icon
Done!

2022-05-25 08:41 UTC, TomasSlama approved these changes

2022-05-25 08:41 UTC, TomasSlama commented on .changeset/large-ways-arrive.md
> +Add Cube icon
```suggestion
Add Box icon
```

2022-05-25 08:43 UTC, denieler approved these changes

2022-05-25 08:57 UTC, ozgurkececioglu commented
Code looks 👌 but I'm curious about the SVG image, as you can also realize that it is not totally aligned horizontally. Is it intended?

<img width="70" alt="Screen Shot 2022-05-25 at 11 54 22" src="https://user-images.githubusercontent.com/7733167/170223692-00850c4d-57ef-4b99-8449-5cc5ce2c5e7e.png">

2022-05-25 09:02 UTC, separatio approved these changes

2022-05-25 09:07 UTC, TomasSlama requested changes
@ozgurkececioglu is right.

In design 
![image](https://user-images.githubusercontent.com/6830426/170225657-d9ad14b5-2da0-4477-babd-c01ddf5976ff.png)
there is horizontal padding 1px from left, 2px from right.

But in our case it is not horizontally centered
![image](https://user-images.githubusercontent.com/6830426/170225814-c83594d4-57d3-4b86-a013-5fa97bafe79f.png)
0px from left, 3px from right.

2022-05-25 13:41 UTC, TomasSlama approved these changes
Base team [approved](https://toptal-core.slack.com/archives/CCC3GP6CC/p1653482547512899) the little bit smaller size of the Icon

2022-05-25 13:42 UTC, ozgurkececioglu approved these changes

2022-05-25 14:06 UTC, augustobmoura approved these changes

2022-05-26 06:54 UTC, merged