[FX-2822] Form shows incorrect valid state when submitted on Enter of dirty since last submit
toptal/picasso pull request #2831
Opened 2022-05-31 11:20 UTC by vvmarulin

[FX-2822]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-06-01 01:08 UTC, vvmarulin commented on packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
> -  if (!meta.error && !meta.submitError) {
I changed this method so it has the same list of if conditions as [`getInputStatus` from `InputField`](https://github.com/toptal/picasso/pull/2831/files#diff-0bedd03aaad2a17fcd51ff795efa785efc9be11295d3b009e0a73e4248574f2aR10)

2022-06-01 06:05 UTC, ozgurkececioglu commented on .changeset/selfish-pumas-prove.md
> +### Form
Since these changes are on the same package, can't we merge them?

2022-06-01 06:12 UTC, ozgurkececioglu commented on packages/picasso-forms/src/Form/test.tsx
> +    <Form.ConfigProvider value={{ showValidState: true }}>
I'm not sure about passing these props static. Can't we use `renderForm`s parameters for this purpose? This way, we can change the example just for the new test. Wdyt?

2022-06-01 08:37 UTC, denieler commented on packages/picasso-forms/src/Form/Form.tsx
> +    form.focus(activeField)
why do we need to do that? this will fire unnecessary and unexpected callbacks for `Form` users

2022-06-01 10:37 UTC, vvmarulin commented on packages/picasso-forms/src/Form/Form.tsx
> +    form.focus(activeField)
I moved changes related to `Form` to https://github.com/toptal/picasso/pull/2838 as was asked by @ozgurkececioglu. Let's continue the conversation there.

2022-06-01 14:11 UTC, ozgurkececioglu commented on packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
> -  if (!meta.error && !meta.submitError) {
I'm not sure about this change 🤔 these functionalities look similar but they are actually doing different things. I would keep here the same but let's ask to the team

2022-06-01 14:16 UTC, ozgurkececioglu approved these changes
Seems like it solved the bug and I couldn't find a downside of the fix. Good catch 👍

2022-06-02 11:56 UTC, TomasSlama approved these changes
LGTM 👍

2022-06-02 12:23 UTC, OndrejTuma reviewed
@vvmarulin I also noticed that if you open the temploy and start typing into input right away, then the validation check does not appear until the input is blurred.
But this is probably for another task

2022-06-02 12:23 UTC, OndrejTuma approved these changes
Tested in temploy, works as expected 🙂 good work 👍

2022-06-03 10:27 UTC, denieler requested changes
It seems after the field becomes valid it doesn't change the valid state if we change the field again:

https://user-images.githubusercontent.com/2836281/171837104-8da3389c-d989-412a-946e-2f8cde6754fd.mov

2022-06-07 07:10 UTC, vvmarulin commented
@denieler 
I've fixed the bug. Thank for pointing that out.

2022-06-07 08:02 UTC, separatio approved these changes
Tested. Looks good.

2022-06-07 09:46 UTC, denieler commented
@vvmarulin I see we fixed the bug, but it seems we've not added a test to cover this case. Can you please add it? 🙇‍♂️

2022-06-07 13:43 UTC, denieler commented
@vvmarulin it seems it stopped showing to me the valid state for the `validateOnSubmit` variant:

https://user-images.githubusercontent.com/2836281/172395537-21e141b4-9cf2-4b9a-980c-4fd24dfe70b8.mov

2022-06-09 08:36 UTC, denieler requested changes
It seems there is still a bug:

https://user-images.githubusercontent.com/2836281/172803281-3a1f7faf-d5fd-44c6-b89d-1df8656d8ef4.mov

2022-06-13 07:46 UTC, vvmarulin commented on packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
> -  if (!meta.error && !meta.submitError) {
From my POV, it'll be easy to avoid accidental bugs if we have a similar set of conditions in this method and in `getInputStatus`. By using a similar set of checks we make it much easier to read and to change, i.e. if you change in one place, then do the similar change in another.

2022-06-14 04:04 UTC, vvmarulin commented on packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
> +  return null
I didn't change the logic here. Only refactored it so the `if`s have the same checks as in `getInputStatus`. That's why there is no need in new tests, it's just a refactoring.

2022-06-14 04:34 UTC, vvmarulin commented on packages/picasso-forms/src/InputField/test.ts
> +      })
There is a test for that scenario. I changed the message as you suggested in your code snippet to make it clear.
https://github.com/toptal/picasso/pull/2831/files#diff-65b8e5dad8631a521eeeb7d53be0c0fe5dc931842506a06bd09bfa66beeded23R26-R34

2022-06-14 06:35 UTC, denieler commented on packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
> +  return null
if we don't do any changes I would keep the code the same

2022-06-14 06:38 UTC, denieler requested changes

2022-06-14 06:38 UTC, denieler commented on packages/picasso/package.json
> +    "@toptal/picasso-provider": "1.2.0",
I don't think we need to change `picasso-provider` version anyhow in this PR 🤔 it seems as a non-related change

2022-06-14 06:48 UTC, TomasSlama commented on packages/picasso/package.json
> +    "@toptal/picasso-provider": "1.2.0",
I think syncpack did this, let me fix it in master

2022-06-15 07:30 UTC, denieler approved these changes

2022-06-15 07:42 UTC, merged