docs: add Cypress Tests Visual Tests coverage RFC
toptal/picasso pull request #2870
Opened 2022-06-08 11:24 UTC by separatio

[FX-2641]

### Description

This decision attempts to showcase and clarify how visual tests in Cypress should be added, and how they affect the whole test stack of Picasso.

### How to test

- Read the doc, of course!
- You can also apply it to some of your PRs if you're interested in the flow, and ask questions here. Nothing beats real life examples.

- [ ] Self reviewed

2022-06-08 11:25 UTC, separatio commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +Checking the test pyramid, it can be noticed that the Visual Testing level is on top of the Integration Testing one.
I should probably paste a test pyramid image here. :thinking:

2022-06-08 11:36 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +The `./05-visual-tests-placing.md` decision stated when to decide between Cypress and Storybook tests.
I would expect this PR to actually extend the previous `05` doc instead of referencing that

2022-06-08 11:36 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +However, it is not entirely clear which components need screenshots, for which states, and how to combine them, so that Picasso can have visual testing done efficiently.
I think this text does not bring a lot of value in long run

2022-06-08 11:38 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +The following definition should be kept in mind at all times:
I believe removing these two phrases would not change the essence of the message. Hence they can be considered as a noise

2022-06-08 11:39 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +A visual test (a screenshot comparison) asserts one or more non-overlapping states of the component under test.
```suggestion
A visual test (a screenshot comparison) asserts one or more non-overlapping visual states of the component under test.
```

2022-06-08 11:42 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +Checking the test pyramid, it can be noticed that the Visual Testing level is on top of the Integration Testing one.
Yeah... I would actually delete all this text. To me it is mostly noise.  The signal is: it is OK to combine few visual tests together to reduce the cost.

2022-06-08 11:51 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +This not only maximizes the coverage, but also decreases the number of screenshots needed.
How combining maximises the coverage? :) I guess it rather reduces number of screenshots and at the same time does not reduce the coverage.

2022-06-08 11:52 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +To help with test case discovery, the chain of actions before adding Cypress Visual Screenshots for any given component is as follows:
```suggestion
Before writing tests:
```

2022-06-08 11:52 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +- ensure adequate test coverage is already done via Jest and Cypress assertions
what is adequate test coverage?

2022-06-08 11:53 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +- check the current Storybook visual tests coverage
check for what?

2022-06-08 11:55 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +- Are there any Cypress visual tests that only test a single visual aspect of the component and can it be combined with another?
This doc is a strategy. I would like to see answers/guidelines what to do not questions.

2022-06-08 11:59 UTC, OleksandrNechai commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +Only after the conditions above are satisfied, and the questions are answered, it is time to add, remove, or combine visual tests in Cypress.
I don't see any conditions above. And again, if we delete this and next line, no changes to the strategy. Hence to me this is also a nose. It is also confusing to see `evaluating the screenshots`. Do we evaluate them? What is their value then? How do we `measure` their value?

2022-06-08 12:00 UTC, OleksandrNechai requested changes
To me the only useful info here is: `please combine visual tests to reduce cost and keep coverage unchanged`.

2022-06-08 12:43 UTC, denieler commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +The `./05-visual-tests-placing.md` decision stated when to decide between Cypress and Storybook tests.
```suggestion
The [./05-visual-tests-placing.md](./05-visual-tests-placing.md) decision stated when to decide between Cypress and Storybook tests.
```

2022-06-08 12:46 UTC, denieler reviewed
To me RFC is a decision making document, so we need to have a strict decision or list of steps we directly should follow, but this document gives a lot of freedom for the reader 🤔

2022-06-12 21:44 UTC, separatio commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +This not only maximizes the coverage, but also decreases the number of screenshots needed.
Changed to ```This reduces the number of screenshots needed while maintaining and improving coverage.```

2022-06-12 21:45 UTC, separatio commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +- ensure adequate test coverage is already done via Jest and Cypress assertions
I tried avoiding vague descriptions. The text has been re-done.

2022-06-12 21:46 UTC, separatio commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +- check the current Storybook visual tests coverage
Check for disabled Storybook visual tests. Updated in text.

2022-06-12 21:47 UTC, separatio commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +Only after the conditions above are satisfied, and the questions are answered, it is time to add, remove, or combine visual tests in Cypress.
Screenshots need to be manually checked for correctness in Happo reports. I will add a clarification.

2022-06-13 06:16 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +- do not interact with the DOM before taking the screenshot
this is not clear to me: the component is transformed into DOM element, before taking a screenshot. What do you mean, it does not interact with the DOM?

2022-06-13 06:19 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +- do not duplicate the existing Storybook stories screenshots
They might duplicate, but we shouldn't do it :)

2022-06-13 06:21 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +- if a test is particularly flaky in Storybook, it should be migrated to Cypress for stability, where there is more control
so, the manual (Cypress) tests have a higher rate than Storybook's 👍

2022-06-13 06:26 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +### Doing Visual Tests outside of Storybook
does it mean, `Doing Visual Tests via Cypress` ?

2022-06-13 06:27 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +- existing Cypress visual tests
Points 1 and 3 seem to be having the same mention about Cypress visual tests

2022-06-13 10:52 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +### Doing Visual Tests outside of Storybook
I initially phrased it like that. However, when doing visual tests, we are looking at the whole stack, not just Cypress.

Hence, I thought it would be better to write it as `outside of Storybook`.
Do you think it's overkill @dmaklygin ?

2022-06-13 10:53 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +- if a test is particularly flaky in Storybook, it should be migrated to Cypress for stability, where there is more control
At the very least, we have more control and we can make them less flaky.

2022-06-13 10:55 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +- do not duplicate the existing Storybook stories screenshots
Maybe the phrasing is not the best, but it shows where we should place which tests. Maybe the ### Placement naming is bad. I should change that.

2022-06-13 14:30 UTC, denieler commented on docs/decisions/06-cypress-visual-tests-coverage.md
> +The `./05-visual-tests-placing.md` decision stated when to decide between Cypress and Storybook tests.
@OleksandrNechai we actually can't modify already approved and merged RFCs:

https://en.wikipedia.org/wiki/Request_for_Comments

![Screenshot 2022-06-13 at 17 25 33](https://user-images.githubusercontent.com/2836281/173376650-635f6ca0-17c6-4733-93de-adbb819ce501.png)

But if we want to make some change we need to deprecate the previous RFC and create, approve and merge another RFC 🙇 I would propose just having a bunch of small RFCs and creating a full-scale document based on them. But not to approve full-testing strategy, which might be a very long discussion 🙇‍♂️

2022-06-16 14:45 UTC, TomasSlama commented on docs/decisions/05-picasso-test-strategy.md
> +Picasso provides two tools for visual tests:
shouldn't we also mention Happo? 🤔

2022-06-16 14:45 UTC, TomasSlama commented on docs/decisions/05-picasso-test-strategy.md
> +```
```suggestion
> A visual test (a screenshot comparison) asserts one or more non-overlapping visual states of the component under test.
```

2022-06-16 14:45 UTC, TomasSlama commented on docs/decisions/05-picasso-test-strategy.md
> +```
It seems as a quote, not code

2022-06-16 14:45 UTC, TomasSlama commented on docs/decisions/05-picasso-test-strategy.md
> +- do not interact with the DOM before taking the screenshot
how about to add some easy example,

storybook screenshot: Button renders with some props
cypress screenshot: Click on Button than take screenshot

2022-06-17 07:12 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +### Doing Visual Tests outside of Storybook
actually, you mentioned about 2 possible tools: Storybook and Cypress.
doing visual tests outside of Storybook, for me, means usage of Cypress.
But I got your proposition. Let's keep it as is.

2022-06-17 07:14 UTC, dmaklygin commented on docs/decisions/05-picasso-test-strategy.md
> +- do not interact with the DOM before taking the screenshot
yeah, Storybook does not tests behaviors, only states :)

2022-06-17 07:21 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +### Doing Visual Tests outside of Storybook
:+1: To clarify, I mentioned 2 possible tools for visual testing, but the whole test stack has more than 2 tools for testing.

2022-07-01 10:40 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +Picasso provides two tools for visual tests:
Since I can't modify the existing RFC, I will resolve this comment. I will address that later.

I see things a little differently. Happo is the provider. Storybook and Cypress are the tools.

2022-07-01 10:40 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +```
I only wanted to isolate it. Using ``` seemed good to me. I'll try `> `.

2022-07-01 10:41 UTC, separatio commented on docs/decisions/05-picasso-test-strategy.md
> +- do not interact with the DOM before taking the screenshot
The Drawer tests are the example.

2022-07-01 10:43 UTC, separatio commented
After so long, this PR has become stale, and there is a lot of noise. I squashed everything into 1 commit that was relevant.

2022-07-04 07:14 UTC, ozgurkececioglu approved these changes
LGTM 👍

2022-07-04 10:51 UTC, OleksandrNechai commented on docs/decisions/08-cypress-visual-tests-coverage.md
> +There are 5 bottom-up steps to follow:
Maybe convince me, but to me strategy is about some principle that we need to stick to. Here we have a set steps that I find very hard to read. If I don't `write the missing test cases` but instead calculate them in my head? What if I first do step 5 and then step 4? Am I violating strategy?

I would formulate the principle, show example and leave people to decide on their own how to make it.

2022-07-04 10:54 UTC, dmaklygin approved these changes

2022-07-04 11:18 UTC, separatio commented on docs/decisions/08-cypress-visual-tests-coverage.md
> +There are 5 bottom-up steps to follow:
The test strategy should explain test design and determines **how** testing needs to be done.
It's not that you are "violating" the strategy, but you are also not following it.

You'd be a poor tactician if you don't apply the strategy.

Anyone should be able follow a clear-cut strategy, hence the strict steps.
You can stray away from the strategy and do things differently, as long as you can execute it perfectly first.

Making an analogy with chess, you can know a strategy to win a game. Applying it and actually winning is a different matter. Hence, only after you win a few times with a strategy can you learn from it and do things better on your own.

The principle is to follow simple steps of the laid out strategy. There's no formulation for that. :slightly_smiling_face:

2022-07-04 13:46 UTC, OndrejTuma commented on docs/decisions/08-cypress-visual-tests-coverage.md
> +The `./05-visual-tests-placing.md` decision stated when to decide between Cypress and Storybook tests.
It'd be nice if this was a link 🙂

2022-07-05 08:31 UTC, separatio commented on docs/decisions/08-cypress-visual-tests-coverage.md
> +2. Write the missing test cases for visual state transition results due to interacting with the component
Note to self: Tests in Cypress can be for visual state transitions and for visual tests that are not suited to be tested in Storybook.

2022-07-05 08:32 UTC, separatio commented on docs/decisions/08-cypress-visual-tests-coverage.md
> +3. Combine the written test cases for different aspects of the same component; *e.g. size and color*
Note to self: Not just the written tests/ test cases need to be combined. The existing ones need revision as well.

2022-07-05 14:24 UTC, OleksandrNechai commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +> A _test_ is the whole test, with the code block.
nit: Not sure about quotes. I would go with simple text.

2022-07-05 14:24 UTC, OleksandrNechai approved these changes

2022-07-05 18:06 UTC, ozgurkececioglu commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Happo screenshot validation is the comparison between a Happo screenshot of a component and its Picasso Temploy live version and accepting or rejecting the .
I think you forgot to finish this sentence 🙂

2022-07-05 19:15 UTC, dmaklygin commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Happo screenshot validation is the comparison between a Happo screenshot of a component and its Picasso Temploy live version and accepting or rejecting the .
I thought, the validation is the comparing the difference between the current screenshot of the previous one,

2022-07-05 19:23 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Happo screenshot validation is the comparison between a Happo screenshot of a component and its Picasso Temploy live version and accepting or rejecting the .
Yes. I totally forgot to finish it. :facepalm: I will amend this definition.

2022-07-05 19:24 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Happo screenshot validation is the comparison between a Happo screenshot of a component and its Picasso Temploy live version and accepting or rejecting the .
@dmaklygin What about new screenshots? :slightly_smiling_face: I will rephrase it.

2022-07-05 20:19 UTC, OndrejTuma approved these changes
🙇

2022-07-05 20:20 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +2. Merge the **identified missing test cases** with the **existing test cases** for different aspects of the same component; _e.g. size and color_
`of the same component` is redundant. Will be removed.

2022-07-06 10:39 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +A _test_ is the whole test, with the code block.
```suggestion
A _test_ is the whole test, within the code block.
```

2022-07-06 10:43 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Assuming a component is newly implemented along with Storybook examples, but without Cypress visual tests:
I would add somewhere here a statement that "Modifying Storybook examples in favor of doing better coverage for visual tests is prohibited. Storybook examples main and the only purpose - to show how the component should be used."

2022-07-06 10:45 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +4. Disable redundant Storybook visual tests
we probably also want to say that we prefer Storybook visual tests if they exist and should cover by Cypress tests if Storybook visual tests don't exist or adding them don't give any new information about usage of the component in Picasso Storybook

2022-07-06 10:47 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +- finding existing CSS assertions in Jest and Cypress
in my opinion, CSS assertions must be prohibited ❌

2022-07-06 10:49 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Minimize the number of screenshots by maximizing test cases covered per screenshot.
I would add maybe here more principles would give more clarify for people:
- Cover by visual tests all important views of the component
- Cover by visual tests important tricky combinations of components (Modal + Tooltip, Drawer + Notification, etc.)

2022-07-06 11:16 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +A _test_ is the whole test, with the code block.
Actually, the test is the whole thing. With the code block. It's both the test case and its execution.

2022-07-06 11:16 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Assuming a component is newly implemented along with Storybook examples, but without Cypress visual tests:
I agree we should do that somewhere, but that is not the scope of this RFC.

2022-07-06 11:17 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +4. Disable redundant Storybook visual tests
At this point, I should probably talk about visual tests in Storybook. I thought it was not needed, but perhaps a new RFC for that is needed, considering your points.

2022-07-06 11:17 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +- finding existing CSS assertions in Jest and Cypress
I agree, but we also have a few. Hence, I mentioned it here in the RFC.
As long as we don't have a linter rule prohibiting them, we can't do anything about it.

2022-07-06 11:18 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Minimize the number of screenshots by maximizing test cases covered per screenshot.
I am trying to focus on simple visual tests here. I will talk about that in the (or one of the) Integration Testing RFC(s).

2022-07-06 11:27 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +A _test_ is the whole test, with the code block.
@separatio ah, that what you meant 🙇‍♂️ 👍 sorry, didn't get it from the beginning

2022-07-06 11:28 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +4. Disable redundant Storybook visual tests
nit: @separatio maybe we can change this document to `09-visual-tests-strategy`?

2022-07-06 11:30 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +- finding existing CSS assertions in Jest and Cypress
@separatio if we agree that we must not do that, then we don't need to encounter cases when some people did that eventually, because it was wrong in the first place. So if we don't want to say here that we prohibit such tests, at least I would remove from docs all the mentions of such

2022-07-06 11:30 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +4. Disable redundant Storybook visual tests
We could, but then I'd have to include Storybook in it, make the PR bigger, get reviews from Oleksandr again, and we won't merge it until mid-August. :slightly_smiling_face: So I prefer to merge this with as little changes as possible, and have another doc for Storybook. WDYT?

2022-07-06 11:31 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +4. Disable redundant Storybook visual tests
Don't get me wrong. It's not a bad thing to have reviews, but it changes the scope of the PR so much that I'd have to request re-reviews from everyone, actually.

2022-07-06 11:32 UTC, denieler commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Minimize the number of screenshots by maximizing test cases covered per screenshot.
if I would be reading this document, I would love probably to have a link to that `Integration Testing RFC(s).`, but as soon as RFCs are unchangeable, maybe it's worth mentioning in this doc at least briefly or drop a phrase, like, 
"And include the Integration Testing principles"

2022-07-06 11:33 UTC, denieler approved these changes

2022-07-07 15:54 UTC, separatio commented on docs/decisions/09-cypress-visual-tests-strategy.md
> +Minimize the number of screenshots by maximizing test cases covered per screenshot.
Since I am focusing per-component here, I will include that part of visual testing in the integration testing docs.

2022-12-20 13:22 UTC, separatio commented
Closing this PR for now. I don't know when work will be done on it to finish it. :( It's already mentioned in https://toptal-core.atlassian.net/browse/FX-2916 so it won't be forgotten. :crossed_fingers:

2022-12-20 13:22 UTC, closed without merging