chore: migrate TagSelector story snapshots with effects on cypress side
toptal/picasso pull request #2873
Opened 2022-06-09 11:41 UTC by ozgurkececioglu

[FX-2845]

### Description

Migrate Dropdown stories with effects on cypress side

### How to test

- code review, green CI and approving Happo would be enough

### Development checks

- Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- Annotate all `props` in component with documentation
- Create `examples` for component
- Ensure that deployed demo has expected results and good examples
- [x] Ensure that all PR checks are green
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-06-13 12:53 UTC, TomasSlama approved these changes
Looks good, I have approved the happo screenshots

2022-06-13 13:51 UTC, denieler commented
I think for `Custom label rendering` screenshot it would make more sense to take a screenshot with hovered link (because this is what actually distinguishes this example from others):

Probably the desired screenshot:
![Screenshot 2022-06-13 at 16 49 46](https://user-images.githubusercontent.com/2836281/173368662-fb7b9e5e-3225-4e3c-a88f-882b6fa7f11e.png)

The screenshot now:
![Screenshot 2022-06-13 at 16 49 59](https://user-images.githubusercontent.com/2836281/173368669-f424a440-6bdb-4fe3-9e05-d43f5bd06740.png)

2022-06-13 13:56 UTC, denieler commented on cypress/component/TagSelector.spec.tsx
> +    cy.get('@combobox-input').type('test').get('body').happoScreenshot({
nit: ```suggestion
    cy.get('@combobox-input').type('not existing item text').get('body').happoScreenshot({
```

2022-06-13 13:57 UTC, denieler commented on cypress/component/TagSelector.spec.tsx
> +    cy.get('@combobox-input').type('test').get('body').happoScreenshot({
nit:
```suggestion
    cy.get('@combobox-input').type('not existing item text').get('body').happoScreenshot({
```

2022-06-13 14:00 UTC, denieler commented on cypress/component/TagSelector.spec.tsx
> +      mount(<TagSelectorExample status='success' options={countryOptions} />)
nit: I would pass a value also, because valid empty TagSelector looks a bit unnatural

2022-06-13 14:01 UTC, denieler commented on cypress/component/TagSelector.spec.tsx
> +const getDisplayValue = (item: AutocompleteItem | null) =>
nit: can't we just reuse `getCountryDisplayValue`? or maybe use this one in that example instead?

2022-06-13 14:02 UTC, denieler commented on cypress/component/TagSelector.spec.tsx
> +const basicOptions = [
nit: we can probably use Country options instead of `basicOptions` to make test smaller

2022-06-13 15:04 UTC, separatio reviewed
Missing `x` icon, to remove the item, in this screenshot:

![image](https://user-images.githubusercontent.com/8407461/173384346-f98f8884-ce29-4f69-9dc3-4415306d43a3.png)

2022-06-13 15:06 UTC, separatio commented on cypress/component/TagSelector.spec.tsx
> +      variant: 'other-option/after-clicked-new-option',
This visual test does not add much. You can simply assert the text and see it was added. Otherwise, it's just like any other option. We shouldn't add a screenshot for this.

2022-06-13 15:08 UTC, separatio requested changes
Some screenshots are not accurate, and you should remove the 2 tests I left comments for. Let me know if you have any questions. :bow:

2022-06-13 21:06 UTC, separatio commented on cypress/component/TagSelector.spec.tsx
> +      variant: 'other-option/after-clicked-new-option',
But the visuals do not change. We simply add a new option that looks the same as if we clicked it. Am I missing something here @denieler ?

2022-06-14 06:37 UTC, ozgurkececioglu commented on cypress/component/TagSelector.spec.tsx
> +      mount(<TagSelectorExample status='success' options={countryOptions} />)
As @separatio pointed out here https://github.com/toptal/picasso/pull/2873#discussion_r895836643, I will remove this test

2022-06-14 06:50 UTC, ozgurkececioglu commented
> Missing `x` icon, to remove the item, in this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/8407461/173384346-f98f8884-ce29-4f69-9dc3-4415306d43a3.png)

This is because it is using a custom label and if you check out the `LinkTag`, you will see that it is a custom implementation. So, there shouldn't be a remove icon for that tag. If you think this customization is not necessary, we can discuss.

2022-06-14 08:18 UTC, OndrejTuma approved these changes

2022-06-15 07:14 UTC, merged