fix: refactor creating formats
toptal/picasso pull request #2930
Opened 2022-06-24 11:27 UTC by alexvcasillas

[COMM-1067]

### Description

Format creation for RichTextEditor needed a refactor to make it more efficient

### How to test

- Access the temploy/preview.
- RichTextEditor should work as expected
- CI should be 💚 

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-06-24 11:30 UTC, alexvcasillas commented
@toptal-bot run all
@toptal-bot run build

2022-06-24 11:49 UTC, kml commented
@toptal-anvil ping reviewers

2022-06-24 12:06 UTC, kml commented
@toptal-anvil ping reviewers

2022-06-24 15:58 UTC, OndrejTuma approved these changes
LGTM 👍

2022-06-27 07:46 UTC, alexvcasillas commented
@toptal-bot run all
@toptal-bot run build
@toptal-bot run package:alpha-release

2022-06-27 07:59 UTC, alexvcasillas commented
@toptal-anvil ping reviewers

2022-06-27 08:50 UTC, LashaJini commented on .changeset/swift-trainers-applaud.md
> +Refactor format creation to avoid possible bug when recreating the format global class
```suggestion
### RichTextEditor

- Refactor format creation to avoid possible bug when recreating the format global class
```

2022-06-27 08:50 UTC, LashaJini commented on yarn.lock
>    resolved "https://registry.npmjs.org/npm-normalize-package-bin/-/npm-normalize-package-bin-1.0.1.tgz"
Why `yarn.lock` was updated :thinking: ?

2022-06-27 11:42 UTC, alexvcasillas commented on yarn.lock
>    resolved "https://registry.npmjs.org/npm-normalize-package-bin/-/npm-normalize-package-bin-1.0.1.tgz"
Maybe it came from `master` when I rebased this morning?

2022-06-27 11:43 UTC, alexvcasillas commented on .changeset/swift-trainers-applaud.md
> +Refactor format creation to avoid possible bug when recreating the format global class
Addressed :)

2022-06-27 11:44 UTC, alexvcasillas commented
@toptal-bot run all
@toptal-bot run build

2022-06-27 11:44 UTC, alexvcasillas commented on yarn.lock
>    resolved "https://registry.npmjs.org/npm-normalize-package-bin/-/npm-normalize-package-bin-1.0.1.tgz"
I just rebased from `master` and the file has gone @LashaJini :)

2022-06-27 12:31 UTC, augustobmoura requested changes
I found just a small bug, but the code looks good overall! Nicely done! :+1:

2022-06-27 12:31 UTC, augustobmoura commented on packages/picasso/src/QuillEditor/formats/bold.ts
> +      )
I don't think joining them with commas works as expected here, its adding a single CSS class with all the typographic classes joined by `,`. You can see on [this sandbox](https://codesandbox.io/s/nice-voice-hs5reh?file=/src/index.js) that `#app` gets a `foo,bar` CSS class

![image](https://user-images.githubusercontent.com/5845160/175941495-5303ab1d-9e07-4cc9-b533-0c456f51b597.png)

The function accepts n-arguments that would be the class names, so you can use the spread operator here:
```suggestion
      node.classList.add(
        ...getTypographyClassName(typographyClasses, {
          variant: 'body',
          size: 'inherit',
          weight: 'semibold',
        })
        	.split(' ')
      )
```

This is also valid for the other occurrences of `nodeList.add()` in the code

2022-06-27 12:57 UTC, alexvcasillas commented on packages/picasso/src/QuillEditor/formats/bold.ts
> +      )
Good catch. As `add` doesn't accept spaces I was going to split it but I accidentally joined them back with `,`

2022-06-27 13:01 UTC, alexvcasillas commented on packages/picasso/src/QuillEditor/formats/bold.ts
> +      )
Addressed :)

2022-06-27 13:44 UTC, augustobmoura approved these changes
LGTM! Thanks for your contribution @alexvcasillas! :+1:

2022-06-27 13:46 UTC, merged

2022-06-27 15:10 UTC, denieler commented on packages/picasso/src/QuillEditor/formats/bold.ts
> +const makeBoldFormat = (typographyClasses: Classes) =>
why do we want to provide a class as a result of the function execution? 😃