chore: improve cypress happo screenshots (part 1)
toptal/picasso pull request #2937
Opened 2022-06-27 07:24 UTC by ozgurkececioglu

[FX-2850]

### Description

Cypress tests with happo screenshots are being improved. In this PR, I focused on 7 components:
* Accordion
* ApplicationUpdateNotification
* Autocomplete
* Avatar
* AvatarGroup
* Badge
* BarChart

### How to test

- I separated commits to ease reviewing process
- happo review and code review would be enough

### Screenshots

happo reports are our screenshots

### Development checks

- Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- Annotate all `props` in component with documentation
- Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- Covered with tests

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-06-27 09:52 UTC, separatio requested changes
Some few things need adjusting. Especially autocomplete. We should be testing for both the dropdown menu in it, and the input, right? Am I missing something?

2022-06-27 09:52 UTC, separatio commented on packages/picasso/src/Autocomplete/story/index.jsx
> -    title: 'Initially set value',
The title should not be different from the file name, or vice-versa. The file name should not be different from the title. Either variants work, as long as they're the same. It's easier to find them in the future.

2022-06-27 09:52 UTC, separatio commented on packages/picasso/src/Autocomplete/story/index.jsx
> +  .addExample('Autocomplete/story/MenuWidth.example.tsx', 'Menu width')
Quick question. This Story basically changes the menu width. That means clicking the autocomplete, and then we check the menuwidth. Shouldn't this be in Cypress instead, because of the action we need to take? Same with the other autocomplete stories.

2022-06-27 10:22 UTC, ozgurkececioglu commented on packages/picasso/src/Autocomplete/story/index.jsx
> +  .addExample('Autocomplete/story/MenuWidth.example.tsx', 'Menu width')
Oh, right! My bad, I will revert it back. Good catch!

2022-06-27 10:53 UTC, ozgurkececioglu commented on cypress/component/Autocomplete.spec.tsx
> +        <TestAutocomplete icon={<Check16 />} startAdornment={<Globe16 />} />
Definitely agree 👍 I will move them to storybook then

2022-06-27 15:03 UTC, separatio approved these changes
Ok. This looks good now.

2022-06-27 15:05 UTC, separatio commented on cypress/component/Autocomplete.spec.tsx
> +        <TestAutocomplete icon={<Check16 />} startAdornment={<Globe16 />} />
We should probably add one. But I'd ask the team about it as well. Let's wait for the mob review.

2022-06-28 13:54 UTC, TomasSlama reviewed
It seems we have discovered one unrelated bug in Autocomplete and I didn't find a screenshot with a custom expand icon for Accordion.

2022-06-28 13:54 UTC, TomasSlama commented on cypress/component/Accordion.spec.tsx
> +        expandIcon={<Check16 />}
Hm, even though it should be there, I don't see the screenshot with `Check16`
![image](https://user-images.githubusercontent.com/6830426/176194381-72e0f5d1-0ccc-4559-a928-4f03b9b41450.png)

2022-06-28 13:54 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/story/index.jsx
> +    'Autocomplete/story/WithAdornments.example.tsx',
It seems we have a bug in the variant with adornments

![image](https://user-images.githubusercontent.com/6830426/176195822-99d13ba2-8970-4ed4-86e3-b68da8f095f2.png)

2022-06-28 13:54 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/story/index.jsx
> +    'Autocomplete/story/WithAdornments.example.tsx',
there is no spacing between adornment and placeholder

2022-06-28 13:56 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/story/index.jsx
> +    'Autocomplete/story/WithAdornments.example.tsx',
I have created separate ticket for it https://toptal-core.atlassian.net/browse/FX-2907

2022-06-28 14:00 UTC, augustobmoura commented on cypress/component/Accordion.spec.tsx
> +        expandIcon={<Check16 />}
Isn't the icon on the far right?
![image](https://user-images.githubusercontent.com/5845160/176197795-f18b1630-baa6-4932-811d-33bff3323912.png)

Also, I didn't even find this screenshot on happo :sweat_smile:

2022-06-28 14:17 UTC, augustobmoura approved these changes
Examples are working on the Storybook demo and code looks good! :+1:

2022-06-28 14:18 UTC, ozgurkececioglu commented on packages/picasso/src/Autocomplete/story/index.jsx
> +    'Autocomplete/story/WithAdornments.example.tsx',
It may be also possible to see this bug in Input component. I think you can check and update the ticket description 🙇‍♂️ 
<img width="349" alt="Screen Shot 2022-06-28 at 17 17 56" src="https://user-images.githubusercontent.com/7733167/176201978-2c059149-907a-47c1-82c0-231496c98282.png">

2022-06-28 14:35 UTC, ozgurkececioglu commented on cypress/component/Accordion.spec.tsx
> +        expandIcon={<Check16 />}
Ok, @TomasSlama I added the custom expand icon test back 👍 good catch 🙇‍♂️

2022-06-29 07:32 UTC, TomasSlama commented on packages/picasso/src/Autocomplete/story/index.jsx
> +    'Autocomplete/story/WithAdornments.example.tsx',
I have updated the task description, thanks Oz

2022-06-29 07:35 UTC, TomasSlama approved these changes
Good job Oz 👍

2022-06-29 07:41 UTC, merged