chore: bump notistack to 1.0.10
toptal/picasso pull request #2959
Opened 2022-07-01 08:15 UTC by OndrejTuma

### Description

After [conversation with Tiago](https://toptal-core.slack.com/archives/CERF5NHT3/p1656618387544099) we realized `notistack` needs a bump to version `1.0.10`

### How to test

- CR is enough

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- Annotate all `props` in component with documentation
- Create `examples` for component
- Ensure that deployed demo has expected results and good examples
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- Covered with tests

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-07-01 08:16 UTC, separatio approved these changes

2022-07-01 08:43 UTC, TomasSlama approved these changes
I did not test Notifications manually, but the code looks good.

2022-07-01 10:02 UTC, vvmarulin requested changes
I've tested notification on the temploy and now there is no margin between multiple notifications

![image](https://user-images.githubusercontent.com/3861498/176873109-150ce5f0-3732-409f-9f58-1ba941b0e11e.png)

How it looks on picasso.toptal.net

![image](https://user-images.githubusercontent.com/3861498/176873264-1af6b547-562e-4c18-afe9-231c7419ef1d.png)

2022-07-01 14:27 UTC, tiagoporto commented on packages/picasso-provider/package.json
> +    "notistack": "1.0.10",
Hi @OndrejTuma, why not set it to "^1.0.10" as classnames?
This will avoid issues like that in the future.

2022-07-01 14:28 UTC, tiagoporto reviewed
Adding a suggestion.

2022-07-01 15:39 UTC, OndrejTuma commented on packages/picasso-provider/package.json
> +    "notistack": "1.0.10",
I can do that, but it'll make no difference, notistack already has v2 and alpha v3

2022-07-01 15:45 UTC, OndrejTuma commented on packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
> +  wrapper: '& > div > div',
I'm open to any other suggestion as to how to approach this selector.
You can check out the [PR that introduced the bug](https://github.com/iamhosseindhv/notistack/pull/376/files) and see what type of selector is being used:
```js
const collapse = {
    container: '& > .MuiCollapse-container',
    wrapper: '& > .MuiCollapse-container > .MuiCollapse-wrapper',
}
```
But this selector does not match the generated hash in classname and therefore does not work.
I have some blind spots in styled components and I hope there's a better way.
I'm open to suggestions 🙏

2022-07-01 15:47 UTC, OndrejTuma commented on packages/picasso-provider/package.json
> +    "notistack": "1.0.10",
And it seems that even patch bumps can introduce a bug in notistack 🙂

2022-07-04 07:26 UTC, OndrejTuma commented
> I've tested notifications on the demo and now there is no margin between multiple notifications
> 
> ![image](https://user-images.githubusercontent.com/3861498/176873109-150ce5f0-3732-409f-9f58-1ba941b0e11e.png)
> 
> How it looks on picasso.toptal.net
> 
> ![image](https://user-images.githubusercontent.com/3861498/176873264-1af6b547-562e-4c18-afe9-231c7419ef1d.png)

@vvmarulin Thanks for noticing! It was actually a bigger mess than I expected by just bumping patch version 🙂 I made some changes, please check it out 🙏

2022-07-04 08:11 UTC, ozgurkececioglu approved these changes
Tested locally. Looking good 👍

2022-07-04 08:37 UTC, OndrejTuma commented on packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
> +  wrapper: '& > div > div',
I moved the styles to the `Notification` component, that works just as well 👍 I'll test that it doesnt break anything

2022-07-04 12:03 UTC, OndrejTuma commented on packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
> -  },
`marginWithDrawer` wasnt applied before (possibly due to changes in notistack). Now its applied but is not sufficient - drawer has several types of widths so we need to update this, but rather in separate task

2022-07-04 14:16 UTC, OndrejTuma commented on packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
> -  },
Spoken with BASE team, we do not support margins for notification since custom widths for drawer were introduced. So this is safe to remove

2022-07-04 15:24 UTC, dmaklygin approved these changes

2022-07-05 05:39 UTC, vvmarulin approved these changes

2022-07-05 08:29 UTC, merged