feat: add options prop
toptal/picasso pull request #3158
Opened 2022-10-16 20:04 UTC by ybouhjira

[PRI-150]

### Description

Add `minimumFractionDigits` and `maximumFractionDigits` options to `<Amount />` component

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

![image](https://user-images.githubusercontent.com/3225392/196055629-5f9ebd72-00db-4efb-b26e-1b80d518b1b1.png)

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-10-17 10:35 UTC, TomasSlama reviewed
I have tested it in the storybook and it works well. I think we are only missing a changeset here, since this is a new feature of the component, we should introduce a `minor` release

2022-10-17 10:36 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2022-10-17 10:47 UTC, mkrl requested changes
Nice job, thank you! :ok_hand: 
Tested manually, the code looks good. Left some remarks, please kindly take a look and don't forget to add a missing `minor` changeset for Picasso :bow:

2022-10-17 10:47 UTC, mkrl commented on packages/picasso/src/Amount/Amount.tsx
> +  maximumFractionDigits?: number
```suggestion
  /** The minimum number of fraction digits to display */
  minimumFractionDigits?: number
  /** The maximum number of fraction digits to display */
  maximumFractionDigits?: number
```

Looks like extra asterisks here cause them to be the part of a prop description in storybook
![image](https://user-images.githubusercontent.com/18409292/196157652-85c47973-fb4a-4149-848b-389e899927f0.png)

2022-10-17 10:47 UTC, mkrl commented on packages/picasso/src/Amount/story/index.jsx
> +  .addExample('Amount/story/Decimals.example.tsx', 'Decimal digits')
```suggestion
  .addExample('Amount/story/Decimals.example.tsx', 'Fractional digits')
```

I reckon this would make more sense as a title, WDYT?

2022-10-17 19:33 UTC, ybouhjira commented
@toptal-anvil ping reviewers

2022-10-18 07:46 UTC, OndrejTuma approved these changes
Code looks good, checked in temploy 👍 
just update the changeset and you're good to go 🎉 
Thanks for contribution

2022-10-18 08:12 UTC, dmaklygin approved these changes

2022-10-18 11:09 UTC, merged