chore: showcase vertical tabs with userBadge
toptal/picasso pull request #3196
Opened 2022-11-04 10:19 UTC by TomasSlama

[FX-3220]

### Description

Update vertical tabs to follow the latest BASE design. Add examples to showcase usage with UserBadge

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-11-07 07:47 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2022-11-07 07:47 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2022-11-07 10:47 UTC, ozgurkececioglu reviewed
Tested locally and UI looks pretty good 👏 

I am confused about what to check in the PR. I think, you will introduce the new compound component (as `Tab.UserItem`) later in another PR and this was just a PoC to show the UI, right?

2022-11-07 10:47 UTC, ozgurkececioglu commented on packages/picasso/src/Tab/styles.ts
> +      transition: 'all 190ms ease-in-out',
This made the UI fancy, nice work 👍 should we also let Matt to document this in BASE? or do we already have it 🤔

2022-11-07 10:47 UTC, ozgurkececioglu commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
why did `em`s become `rem`s now?

2022-11-07 11:08 UTC, TomasSlama commented on packages/picasso/src/Tab/styles.ts
> +      transition: 'all 190ms ease-in-out',
I'm discussing this with Matt

2022-11-07 11:08 UTC, TomasSlama commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
good point, I can keep it in `em`

2022-11-07 11:10 UTC, TomasSlama commented
@ozgurkececioglu exactly, I was just trying if we can achieve the desired design with the current implementation. When I was doing the storybook example I realized that it does not seem super developer friendly and I wanted to discuss it first before implementing it.

2022-11-09 11:40 UTC, separatio reviewed
Left a few nits and questions. Will finish a second more thorough review in a bit.

2022-11-09 11:40 UTC, separatio commented on docs/decisions/12-vertical-tabs.md
> +- [Proof of Concept](https://picasso.toptal.net/fx-3220-vertical-tabs/?path=/story/layout-tabs--tabs#vertical-with-users))
```suggestion
- [Proof of Concept](https://picasso.toptal.net/fx-3220-vertical-tabs/?path=/story/layout-tabs--tabs#vertical-with-users)
```

2022-11-09 11:40 UTC, separatio commented on docs/decisions/12-vertical-tabs.md
> +- Not Flexible, but also might be good thing to force consistency
> might be good thing to force consistency
Is this a drawback or limitation? If no, it shouldn't be here.

2022-11-09 11:40 UTC, separatio commented on docs/decisions/12-vertical-tabs.md
> +Prepare an example in the storybook and users can copy the solution. Such example can be seen in the [Proof of Concept](https://picasso.toptal.net/fx-3220-vertical-tabs/?path=/story/layout-tabs--tabs
```suggestion
Prepare an example in the storybook and users can copy the solution. Such example can be seen in the [Proof of Concept](https://picasso.toptal.net/fx-3220-vertical-tabs/?path=/story/layout-tabs--tabs#vertical-with-users)
```

2022-11-09 11:40 UTC, separatio commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
Shouldn't we always use `rem` though? :smile:

2022-11-09 11:40 UTC, separatio commented on packages/picasso/src/Tab/styles.ts
> +      transition: 'all 190ms ease-in-out',
What's the outcome of the discussion?

2022-11-09 11:41 UTC, separatio commented on docs/decisions/12-vertical-tabs.md
> +**Variant B**
Instead of having Variant A and B, how about you go for one variant in the Proposal (either A or B) and put the other in `Alternatives`.

2022-11-09 11:44 UTC, TomasSlama commented on packages/picasso/src/Tab/styles.ts
> +      transition: 'all 190ms ease-in-out',
I still don't have a complete answer from Matt. "`Ill see if we can add it in figma. We normally dont go about and add layouts yet, part of it the complexities it adds to figma when it comes to resizing and adjusting to different screens.`"

So for now, I will add it only as an example and I will show it directly to Matt again and decide with him how to proceed.

2022-11-09 11:45 UTC, TomasSlama commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
I think we still don't have a decision about it, but I agree with Oz, that it is unnecessary to change it here.

2022-11-09 11:47 UTC, separatio requested changes
When testing, I realized that the design is not respected. The color of the label when the tab is hovered should be black. It's currently grey.

2022-11-09 11:47 UTC, TomasSlama commented on docs/decisions/12-vertical-tabs.md
> +**Variant B**
Good idea, I was thinking to gather feedback first and than change the RFC according to what we decide

2022-11-09 11:49 UTC, separatio approved these changes
Since this is just a POC, I really like variant B, for what it's worth. I'd definitely reuse the current Tab component.

2022-11-09 11:50 UTC, separatio commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
Topic for the retrospective. :joy:

2022-11-09 12:42 UTC, augustobmoura commented on packages/picasso/src/Tab/styles.ts
> +      padding: '0.5rem 1rem',
We did decide on not using `rem`, some teams had problems using Picasso as libraries in other pages (like Toptal's Linkedin extension), where the "root" font-size (from Linkedin itself) was different of what Picasso expects and everything was borked

2022-11-09 12:43 UTC, augustobmoura commented on packages/picasso/src/Tabs/story/index.jsx
> +  // })
We are gonna uncomment these before merging right?

2022-11-09 12:45 UTC, TomasSlama commented on packages/picasso/src/Tabs/story/index.jsx
> +  // })
@augustobmoura this is just PoC that we can manage with the current implementation. While working on this I have realized that we should not only prepare examples but somehow make this reusable for better DX. This PR will eventually only merge the RFC. Right now it seems that we will go with variant B and I'm currently working on updating the RFC to reflect this decision.

2022-11-09 12:46 UTC, augustobmoura commented on docs/decisions/12-vertical-tabs.md
> +  </Tabs>
I don't understand what it is the difference between Variant A and variant B?
On B we don't have `Tabs.Content`?

2022-11-09 12:49 UTC, TomasSlama commented on docs/decisions/12-vertical-tabs.md
> +  </Tabs>
@augustobmoura 
variant A proposes to create a new sub component `Tabs.UserItem` (probably we would need a better name)
variant B proposes to reuse `Tab.Item` where we would conditionally render one component for the vertical variant and another for horizontal

2022-11-09 16:16 UTC, ozgurkececioglu approved these changes
looking good 👍

2022-11-10 15:50 UTC, augustobmoura approved these changes
Thanks 👍

2022-11-10 16:02 UTC, merged