feat(PageSidebar): make sidebar sticky
toptal/picasso pull request #3282
Opened 2022-12-07 22:00 UTC by OndrejTuma

[FX-3290]

### Description

Add sticky header

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-12-08 15:54 UTC, separatio requested changes
Will check the code later. This does not look ideal. Should be fixed.

![image](https://user-images.githubusercontent.com/8407461/206494780-5c2d0d1f-ea97-41e3-a4b5-d08dc3a20c4a.png)

2022-12-09 08:14 UTC, ozgurkececioglu commented
https://user-images.githubusercontent.com/7733167/206655833-291e1510-c3b1-44e3-80ea-c73107fa199a.mov

The hamburger menu is not working on small and large mobile now.

2022-12-13 07:38 UTC, OndrejTuma commented
> Will check the code later. This does not look ideal. Should be fixed.
> 
> ![image](https://user-images.githubusercontent.com/8407461/206494780-5c2d0d1f-ea97-41e3-a4b5-d08dc3a20c4a.png)

It was fixed by removing scrollbar on collapsed, content remains scrollable. Although not ideal, its the best I can do right now. We can discuss if you have better ideas 🙇

2022-12-13 09:15 UTC, TomasSlama commented on .changeset/afraid-queens-drive.md
> +<Page.Sidebar sticky={false}>
```suggestion
<Page.Sidebar disableSticky>
```

I think it is good practice to have default properties set to false so that when someone needs to opt-out from the default value, he can just write `disableSticky` instead of `sticky={false}`

2022-12-13 09:24 UTC, OndrejTuma commented
> The hamburger menu is not working on small and large mobile now.

@ozgurkececioglu I added custom hamburgerId, thanks for the catch 🙇

2022-12-13 09:40 UTC, OndrejTuma commented on .changeset/afraid-queens-drive.md
> +<Page.Sidebar sticky={false}>
Makes sense. Done ✅

2022-12-13 12:36 UTC, OndrejTuma commented
> Great job 👍, tested it in the temploy and it works pretty smoothly 💪. Do we want to cover this new functionality with visual tests? 🤔

@TomasSlama I added simple visual tests in cypress for scroll states, please check it out 🙇

2022-12-13 12:41 UTC, ozgurkececioglu approved these changes
I also tested with temploy and seems working as expected 💪 good job 💯 

I have also one nit comment 🙇‍♂️

2022-12-13 12:48 UTC, TomasSlama approved these changes
Thank you Ondra 👍

2022-12-13 12:49 UTC, OndrejTuma commented
@toptal-bot run package:alpha-release

2022-12-13 15:02 UTC, OndrejTuma commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +        direction='column'
You're right, I tested it and looks like it behaves the same 👍 
Thanks for simplifying the code

2022-12-13 15:02 UTC, OndrejTuma commented
@toptal-bot run package:alpha-release

2022-12-14 11:07 UTC, separatio reviewed
I had some questions. I think we have a missing test for `disableSticky`. Overall the code looks ok, and didn't test. Will approve after questions are answered.

2022-12-14 11:07 UTC, separatio commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +    wrapperStyle,
If I understand correctly, adding this makes it possible for users to pass `wrapperStyle` to the sidebar, therefore customizing the component.

Because of that, I don't think this is a good practice. Is it ok to customize a component with style via props like this? It feels weird to me.

2022-12-14 11:20 UTC, separatio commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +    wrapperStyle,
I am just adding one more thought.

I see this implementation as something potentially very troublesome in the long run.
It can affect the way we customize components, or rather, the way others customize our components.
And we won't even catch it with metrics. To me, it's also an open invitation to abuse custom styling.

2022-12-14 11:46 UTC, OndrejTuma commented on cypress/component/Page.spec.tsx
> +      <Page.Sidebar.Item icon={<Billing16 />} disabled>
I'm not convinced the rendering time will be much faster 🤔

2022-12-14 12:29 UTC, OndrejTuma commented on cypress/component/Page.spec.tsx
> +    it('sticks to TopBar on scroll', () => {
Good call @separatio ✅

2022-12-14 13:07 UTC, separatio commented on cypress/component/Page.spec.tsx
> +      <Page.Sidebar.Item icon={<Billing16 />} disabled>
Let's do the math. 10ms faster.
Let's say tests run:
- 20 times per day (and this is conservative)
- 20 days per month

10ms * 20 * 20 = 4 seconds gained on a monthly basis.
This is 4 seconds for each such test. So while this test on its own, and the improvement is not huge, overall it will bring some impact long-term.

2022-12-14 13:33 UTC, separatio approved these changes
As discussed, only maxWidth will be passed and customizable, instead of the wrapper with the style object. :+1:

2022-12-14 15:48 UTC, OndrejTuma commented on cypress/component/Page.spec.tsx
> +      <Page.Sidebar.Item icon={<Billing16 />} disabled>
Allright, lets go all in and remove all the icons 👍

2022-12-14 15:49 UTC, OndrejTuma commented on packages/picasso/src/PageSidebar/PageSidebar.tsx
> +    wrapperStyle,
So like we agreed, I only added one private prop that makes you tweak maxHeight of the wrapper 👌

2022-12-14 16:05 UTC, merged