fix: hide ShowMore if not needed
toptal/picasso pull request #3300
Opened 2022-12-21 18:06 UTC by OndrejTuma

[FX-3351]

### Description

Do not display "Show more" button if there's nothing to show.

### How to test

- check temploy example and try to play with content length and rows

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [ ] Covered with tests

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2022-12-23 10:42 UTC, mkrl approved these changes

2022-12-23 10:42 UTC, mkrl commented on .changeset/little-sloths-live.md
> +'@toptal/picasso': patch
I am actually not quite sure if it should be a patch. This will create DOM changes in some places, can break snapshots, visual tests and possibly some integration tests.

While it is technically a small bugfix, it may require some changes on the user side when updating :thinking: 

But this is for a very rare scenario, just a FYI

2022-12-23 12:01 UTC, separatio approved these changes
I agree this should be a minor version. Otherwise the PR is ok.

2022-12-26 08:03 UTC, ozgurkececioglu requested changes
I tested locally and asked @mkrl to try again and both we saw that the local goes into an infinite loop. It should be fixed some other way.

2022-12-26 13:32 UTC, ozgurkececioglu approved these changes
Thanks to @mkrl, we are now aware that the component is broken on master only for dev environments. So, this PR is not introducing any new bug but it is fixing an existing one. So, no reason to not merge it.

2022-12-26 13:34 UTC, ozgurkececioglu commented on .changeset/little-sloths-live.md
> +'@toptal/picasso': patch
As decided in the daily, our users shouldn't be watching for our DOM elements except testids. So, DOM changes should be a reason for a breaking change.

2022-12-26 14:50 UTC, merged