Fx 3698 carousel
toptal/picasso pull request #3389
Opened 2023-02-21 10:32 UTC by TomasSlama

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-02-23 10:56 UTC, OleksandrNechai requested changes
Thanks for the effort! I feel the author put a lot of energy into making the code great 🌹 
However, IMO we can and should do better. 
I tested, though not systematically. What is concerning it, dots jumping when you scroll; we saw it together on mob review yesterday. Other than that seems to work 👍

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/getIsOnLastSlide.ts
> +  const diff = slidesToShow - slidesToShowRoundedDown
```suggestion
  const diff = slidesToShow % 1
```

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/test.ts
> +})
GPT came up with 9 testcases. Also when I asked added more boundary tests:

```ts
  it('returns false when currentSlide is less than slidesCount - slidesToShow for non-integer slidesToShow where diff > 0.5', () => {
    const props = {
      currentSlide: 7,
      slidesCount: 10,
      slidesToShow: 3.8,
    };
    expect(getIsOnLastSlide(props)).toBe(false);
  });

  it('returns true when currentSlide is equal to slidesCount - slidesToShow - 1 for non-integer slidesToShow where diff <= 0.5', () => {
    const props = {
      currentSlide: 6,
      slidesCount: 10,
      slidesToShow: 3.2,
    };
    expect(getIsOnLastSlide(props)).toBe(true);
  });
```

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/utils/useOnScreen/use-on-screen.ts
> +const useOnScreen = (ref: React.RefObject<HTMLElement>) => {
This is actually good hook 👍

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/hooks/useAutoplay/test.ts
> +import { act, renderHook } from '@testing-library/react-hooks'
I hope the hooks will be refactored and we will not need these huge and complicated tests

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +      // make sure that carousel is initialized
The code below the comment does not really check if it is initiated, but rather checks if default controls are ok

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +      // make sure that carousel is initialized
again?

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +          // make sure that carousel is initialized
again??

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +            variant: 'rewind-enabled/first-item',
I can't understand where we set up the test to check the first item. So far, it was just initialization.

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +            variant: 'arrow/after-hovered',
After or during hovering?

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +          cy.getByTestId(testIds.dots).should('exist')
Hmmm, can it really happen that in all other tests, it is initiated and in this one, it does not? I am really baffled to see so many same checks.

2023-02-23 10:56 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +        cy.get('@dotTwo').click()
How does this work? I mean, how It knows which is dotTwo?

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +  })
![image](https://user-images.githubusercontent.com/14070311/220882333-4e68eafe-a584-4023-a8a6-c7d40b53469f.png)
I refactored the code above - works like a charm. 
`useMouseOver` and `useInterval` I generated with chatGPT.

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +    }
```suggestion
onSlide?.(currentSlide)
```

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +  }, [currentSlide, onSlide])
Most likely, this hook is not needed. We could have a function
```ts
const handleSlide = (newSlide) = > {
   setCurrentSlide(newSlide);
   onSlide(newSlide)
}
```
later...

```ts
if (value === 'prev') {
  handleSlide(currentSlide - 1)
}
```

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +        dots={dotsRef.current}
This is a pretty weird approach for React to handle things through refs. Is it a requirement of the Glider library we are using?

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +              disabled={rewind ? false : isOnLastSlide}
I am not sure if it can be improved, but so much of negativity, I need to turn on my boolean engine in the brain :) `disabled={...false...}`

2023-02-23 10:56 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/story/Navigation.example.jsx
> +    <Container style={{ maxWidth: 370 }}>
I would add some space between containers:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/14070311/220887402-537c4665-d26f-4ef1-a969-7292e5fd6c25.png">

2023-02-23 10:59 UTC, dmaklygin commented on .changeset/shiny-cooks-flow.md
> +- add new component
It would be great if you could expand the description of your post and include more details such as specifications, features, and other relevant information. This would help our users better understand the value and benefits of the component we are sharing.

2023-02-23 11:30 UTC, TomasSlama commented on packages/picasso/src/Carousel/story/Navigation.example.jsx
> +      <Carousel hideDots>
Because the dots and arrows are visible by default and it felt better to use `<Carousel hideDots />` than `<Carousel withArrows={false} />`

2023-02-23 11:32 UTC, TomasSlama commented on packages/picasso/src/Carousel/story/Navigation.example.jsx
> +        style={{ maxWidth: '100%' }}
I think we use `style` in examples quite often to not overwhelm them with CSS in JS

2023-02-23 11:34 UTC, TomasSlama commented on packages/picasso/src/Carousel/story/Responsive.example.jsx
> +      responsive={[
But how can carousel know how many items to show on different breakpoints, designers need to set this up for each use case.

For example the team that requests the Carousel, they will hide it <=768

2023-02-23 11:41 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getCurrentSlideOnDotEvent/getCurrentSlideOnDotEvent.ts
> +  return currentSlide
the current one

2023-02-23 11:42 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getCurrentSlideOnDotEvent/getCurrentSlideOnDotEvent.ts
> +const getCurrentSlideOnDotEvent = ({ slidesToShow, currentDot }: Props) => {
this function is called whenever someone uses dots to scroll

2023-02-23 11:44 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/getIsOnLastSlide.ts
> +const getIsOnLastSlide = ({
I don't know, I would expect, that `isOnLastSlide` is boolean 🤔. And the usage right now is `const isOnLastSlide = getIsOnLastSlide()` 🤔

2023-02-23 11:45 UTC, mkrl commented on cypress/component/Carousel.spec.tsx
> +        cy.get('@dotTwo').click()
Line 183, it's using `as` constraint to later refer to the element with a shortcut selector

2023-02-23 11:46 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/getIsOnLastSlide.ts
> +  slidesToShow: number
I'm not sure, `slidesToShow` is common naming in most of the carousel libraries.

2023-02-23 11:46 UTC, mkrl commented on packages/picasso/src/Carousel/Carousel.tsx
> +  pauseAutoplayOnHover = true,
I think the default is true in the ticket requirements, discussed with BASE

2023-02-23 11:47 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/getIsOnLastSlide.ts
> +    return currentSlide >= slidesCount - slidesToShow
well it is the last slide, you cannot slide any further, right? 🤔 But I don't mind your suggestions too, I will change it

2023-02-23 11:49 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/getIsOnLastSlide/getIsOnLastSlide.ts
> +  const slidesToShowRoundedDown = slidesToShow | 0
actually yes, thanks for suggestion

2023-02-23 12:59 UTC, dmaklygin commented on packages/picasso/src/utils/useOnScreen/use-on-screen.ts
> +      ),
shouldn't we also pass available options: `root, rootMargin, threshold,` ?
It might be helpful to expose these options as additional arguments to the useOnScreen hook.

2023-02-23 13:02 UTC, dmaklygin commented on packages/picasso/src/utils/useOnScreen/use-on-screen.ts
> +  return isIntersecting
wdyt to return a callback instead of a boolean value?

```
const onScreen = useCallback(callback => {
    if (typeof callback !== 'function') {
      return;
    }
    callback(isIntersecting);
  }, [isIntersecting]);


return onScreen
```

Instead of returning a boolean value, the hook could return a callback function that takes the current intersection status as an argument. This would allow the calling component to take action based on the intersection status, and could also reduce unnecessary re-renders.

2023-02-23 13:07 UTC, dmaklygin commented on packages/picasso/src/Carousel/types.ts
> +}
this is what ChatGPT says about this code: "Overall, the code appears to be well-structured and readable."

2023-02-23 13:17 UTC, dmaklygin commented on packages/picasso/src/Carousel/Carousel.tsx
> +      <Glider
For me, `glider-react` is quite small library that implements `Glider.js` functionality.
i've checked their code: https://github.com/kevinfarrugia/react-glider/blob/master/src/index.tsx
and seems, having this library brings small impact. We could reuse `Glider.js` directly
wdyt?

2023-02-23 13:19 UTC, dmaklygin commented on packages/picasso/src/Carousel/story/index.jsx
> +import PicassoBook from '~/.storybook/components/PicassoBook'
shouldn't this file be in `tsx` extension?

2023-02-23 13:21 UTC, dmaklygin commented on packages/picasso/src/Carousel/story/Responsive.example.jsx
> +        { breakpoint: 768, settings: { slidesToScroll: 2, slidesToShow: 2 } },
let's maybe create a separate variable, called breakpoints and make it reexportable from picasso-shared, for example?

2023-02-23 13:23 UTC, dmaklygin commented on packages/picasso/src/Carousel/story/Navigation.example.jsx
> +      <Carousel hideDots>
`withDots` and `withArrows` looks good to me. by default they might be `true`

2023-02-23 13:24 UTC, dmaklygin commented on packages/picasso/src/Carousel/story/Events.example.jsx
> +    <div>
I would also remove this `div`

2023-02-23 14:18 UTC, TomasSlama commented on packages/picasso/src/Carousel/story/index.jsx
> +import PicassoBook from '~/.storybook/components/PicassoBook'
probably yes, it was generated by davinci-code, so we probably have some issue in the template in picasso 👍

2023-02-23 15:31 UTC, OleksandrNechai commented on packages/picasso/src/Carousel/Carousel.tsx
> +  pauseAutoplayOnHover = true,
could be, worth negotiate, they might not care but for us it could be slightly better API

2023-02-27 10:06 UTC, TomasSlama reviewed
I discussed today with Matt and he asked me to also add gradient on left side when we are on last page and slidesToShow % 1 > 0.

2023-02-27 10:13 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2023-02-27 10:25 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  rewind: boolean
I would add more context to this variable — `rewind`

2023-02-27 10:28 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  rewind: boolean
hm, but we already have it in Carousel.tsx, that we expose to the world 🤔 
![image](https://user-images.githubusercontent.com/6830426/221539321-cf2cf63f-32c8-4e54-a25e-3da011267f7c.png)

2023-02-27 11:12 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +          })
Comment says move to last item. How is it moving?

2023-02-27 11:14 UTC, OleksandrNechai commented on cypress/component/Carousel.spec.tsx
> +  describe('slides to show', () => {
Some describes have spaces above them, some not

2023-02-27 11:17 UTC, TomasSlama commented on cypress/component/Carousel.spec.tsx
> +  describe('slides to show', () => {
✅ I added spacing everywhere 🙇

2023-02-27 11:17 UTC, TomasSlama commented on cypress/component/Carousel.spec.tsx
> +          })
✅ moved it to the right line

2023-02-27 11:40 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +  isPaused?: boolean
wdyt to exclude this prop from a hook? 
We've already provided tools to leverage interval: `pauseInterval` and `resumeInterval`

2023-02-27 11:41 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +  const savedCallback = useRef<() => void>()
can we initialize savedCallback with `callback` right here?

2023-02-27 11:43 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +      const tick = () => savedCallback.current!()
moreover, can we pass `savedCallback.current` directly to `setInterval` ? Without creating additional `tick` function?

2023-02-27 11:46 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    savedDelay.current = delay
if `useInterval` will be called twice:
1. The first time with `delay` = 5000
2. The second time with `delay` = 1000

Will the initial interval retain its 5000 millisecond tick delay?

2023-02-27 11:50 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  rewind: boolean
Anyway, such comments would be valuable, even it hook is just internally used inside the Component :)

2023-02-27 12:37 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +    !autoplay || !isOnScreen || isMouseOver || (!rewind && isLastPage)
As far as I got, `useOnScreen` and `useMouseEnter` are only used to specify `isPaused` variable, which in its turn is only used to specify `useInterval` behavior. 

for me, such hooks, should be dedicated to another hook, like `useAutoplay`

2023-02-27 12:42 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  useInterval({
seems, the output `{ pauseInterval, resumeInterval }` is not needed anymore?

2023-02-27 12:43 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  useInterval({
And, this is right,
The only one concern is the name of `isPaused`, let's maybe turn it over to `isActive` ?

2023-02-27 12:48 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    }
I think, this callback depends on `intervalId` as well

2023-02-27 12:49 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    }
however, we can avoid it

2023-02-27 12:51 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    if (intervalId.current) {
you've already checked the existance of intervalId.current [here](https://github.com/toptal/picasso/pull/3389/commits/e00cfa660994e91a64ff3aa113ccf4ebd375cdc8#diff-a7ea7bf358955f075f315ff4cef0b4449946bfb1acd61bd318c40814a27ecf1dR35)

2023-02-27 12:57 UTC, TomasSlama commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    }
yes, but it is ref and it has no effect in dependency list

2023-02-27 12:58 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  useInterval({
yeah, why not

2023-02-27 13:01 UTC, dmaklygin commented on packages/picasso/src/utils/useMouseEnter/use-mouse-enter.ts
> +export default useMouseEnter
wdyt to reuse? https://github.com/streamich/react-use/blob/master/src/useHover.ts

2023-02-27 13:04 UTC, dmaklygin commented on packages/picasso/src/utils/useMouseEnter/use-mouse-enter.ts
> +export default useMouseEnter
Worth mentioning about this one as well : https://usehooks-ts.com/react-hook/use-hover

2023-02-27 13:39 UTC, TomasSlama commented on packages/picasso/src/utils/useMouseEnter/use-mouse-enter.ts
> +export default useMouseEnter
https://bundlephobia.com/package/react-use@17.4.0 I think the hook is quite easy, 20kB seems too much

2023-02-27 16:42 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  rewind: boolean
✅

2023-02-27 16:43 UTC, TomasSlama commented on packages/picasso/src/utils/useInterval/use-interval.ts
> +    savedDelay.current = delay
I did refactor the hook to make it more clear how it works

2023-02-27 16:47 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  useInterval({
@dmaklygin I tried it out and I had to move it back to `isPaused`.

The interval is active by default and it is much easier to define when to pause it `const isPaused = isNotVisible || isMouseEntered`, we have multiple such conditions and any of them will pause the interval. If I reverse it I have to tell it when it is active `const isActive = autoplay && isVisible && !isMouseEntered` and so on. With multiple conditions it started to look ugly and not clear

2023-02-27 18:05 UTC, OleksandrNechai approved these changes
Looks good enough 😃

2023-02-28 11:18 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +    !autoplay || !isOnScreen || isMouseOver || (!rewind && isLastPage)
✅

2023-02-28 11:23 UTC, TomasSlama commented on packages/picasso/src/CarouselGradient/utils/calculateGradientWidth/test.ts
> +import calculateGradientWidth from './calculateGradientWidth'
✅

2023-03-01 07:55 UTC, dmaklygin commented on packages/picasso/src/Carousel/utils/isOnLastPage/isOnLastPage.ts
> +  }
can we join them together?
doesn't `slidesToShow % 1 <= 0.5` cover `Number.isInteger(slidesToShow)` as well?

2023-03-01 07:56 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +const calculateGradientWidth = (slidesToShow: number) => {
shouldn't we rename the file to `calculateGradientWidth`?

2023-03-01 07:59 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +const calculateGradientWidth = (slidesToShow: number) => {
I would also add a comment to this function:

```
/**
 * Calculates the width of the gradient that fades out the edges of the slider.
 * @param slidesToShow The number of slides to show in the slider.
 * @returns The width of the gradient
 */
```

2023-03-01 08:02 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +  const slideWidth = 100 / slidesToShow
why 100?

2023-03-01 08:04 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/test.ts
> +
I would also add `expect(callback).toHaveBeenCalledTimes(5)` here, so we know that it ticket 5 times

2023-03-01 08:06 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/test.ts
> +  it('pauses and resumes the interval', () => {
```suggestion
  describe('when `isPause` parameter changes its state', () => {
    it('pauses and resumes the interval', () => {
```

2023-03-01 08:07 UTC, dmaklygin commented on packages/picasso/src/utils/useInterval/test.ts
> +  })
I think, we've already covered this case above

2023-03-01 08:20 UTC, dmaklygin commented on packages/picasso/src/utils/useOnScreen/use-on-screen.ts
> +  return isIntersecting
yeah, we have to listen to a state. then, it won't work

2023-03-01 08:20 UTC, TomasSlama commented on packages/picasso/src/Carousel/utils/isOnLastPage/isOnLastPage.ts
> +  }
we could add `||` there

2023-03-01 08:21 UTC, dmaklygin commented on packages/picasso/src/utils/useMouseEnter/test.ts
> +  it('should update isMouseOver state when mouse enters and leaves element', () => {
use please `describe('when...') + it('updates...')`

2023-03-01 08:21 UTC, TomasSlama commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +const calculateGradientWidth = (slidesToShow: number) => {
good idea with the comment, I will rename the function to `gradientWidth` it was suggested by Oleksandr, I forgot to rename the function

2023-03-01 08:22 UTC, TomasSlama commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +  const slideWidth = 100 / slidesToShow
it is in % maybe I should mention it somehwere

2023-03-01 08:22 UTC, dmaklygin commented on packages/picasso/src/CarouselNavigation/CarouselNavigation.tsx
> +export default memo(CarouselNavigation)
👍

2023-03-01 08:23 UTC, dmaklygin commented on packages/picasso/src/CarouselNavigation/CarouselNavigation.tsx
> +          getDotsProps={getDotsProps}
`Dots` expect `getDotsProps` as a prop, however, for `ButtonCircular` we spread `getPrevProps()` to props.
Maybe we should use a consistent solution?

2023-03-01 08:24 UTC, dmaklygin commented on packages/picasso/src/CarouselNavigation/CarouselNavigation.tsx
> +))
as `CarouselNavigation` is already memoized, maybe we could avoid memoizing `Dots`?

2023-03-01 08:27 UTC, dmaklygin commented on packages/picasso/src/CarouselNavigation/CarouselNavigation.tsx
> +      justifyContent={getJustifyContent(hasArrows, hasDots)}
I would solve such cases inside styles file, if it's possible. Is it possible? :)

2023-03-01 08:29 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/CarouselGradient.tsx
> +export default CarouselGradient
why not to cover it with `memo` as well?

2023-03-01 08:38 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/utils/gradientWidth/gradientWidth.ts
> +  }
you've already covered this case [here](https://github.com/toptal/picasso/pull/3389/files#diff-f9e17172d856bec0926b05b38e8b0fb33820400ddc5df004b8369d695e70fb8aR24)

2023-03-01 08:43 UTC, dmaklygin commented on packages/picasso/src/CarouselGradient/CarouselGradient.tsx
> +  }
```suggestion
  const hasGradient = !Number.isInteger(slidesToShow)
  if (!hasGradient) {
    return null
  }

  const gradientWidth = `${gradientWidth(numSlidesToShow)}%`
  const showNextGradient = !isLastPage
  const showPrevGradient = isLastPage

```

wdyt?
with memoized component, we can avoid using `useMemo` for `gradientWidth`

2023-03-01 09:06 UTC, TomasSlama commented on packages/picasso/src/CarouselNavigation/CarouselNavigation.tsx
> +      justifyContent={getJustifyContent(hasArrows, hasDots)}
We could replace it with three classes, I think this is a better solution since we will not generate additional class names. `<Container justifyContent />` should generate only one class name that will be used across the whole Picasso. If I create custom classes in this component it will add new class names to bundle

2023-03-01 09:11 UTC, TomasSlama commented on packages/picasso/src/CarouselGradient/CarouselGradient.tsx
> +export default CarouselGradient
We can, we will safe rerenders on hover

2023-03-01 09:14 UTC, TomasSlama commented on packages/picasso/src/CarouselGradient/CarouselGradient.tsx
> +  }
I don't think so, `gradientWidth` is recalculated only when `slidesToShow` changes, which in the real app will never be. Even if we memoize the component, it will still rerender when `isLastPage` changes.

2023-03-01 10:07 UTC, TomasSlama commented on packages/picasso/src/utils/useMouseEnter/test.ts
> +  it('should update isMouseOver state when mouse enters and leaves element', () => {
✅

2023-03-01 10:07 UTC, TomasSlama commented on packages/picasso/src/utils/useMouseEnter/use-mouse-enter.ts
> +      node.addEventListener('mouseenter', handleMouseEnter)
✅

2023-03-01 11:49 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +    }
```suggestion
    const item = isLastPage ? 0 : currentSlide + slidesToScroll
    glider?.scrollItem(item, false)
```

2023-03-01 11:51 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +    }
```suggestion
    const item = currentSlide === 0 ? lastPage : prevSlide
    glider?.scrollItem(item, false)
```

2023-03-01 11:52 UTC, dmaklygin commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  )
What's the point to have props as a function, not as an object?
We could also memoize props in an object

2023-03-01 11:54 UTC, TomasSlama commented on packages/picasso/src/Carousel/hooks/useCarousel/useCarousel.ts
> +  )
This pattern was suggested by Oleksandr, to me, it seems the same, right? passing object or function. This pattern also was used in downshift

2023-03-01 11:56 UTC, dmaklygin commented on packages/picasso/src/utils/useMouseEnter/use-mouse-enter.ts
> +      }
```suggestion
      setIsMouseOver(event.type === 'mouseenter')
```

2023-03-01 11:57 UTC, dmaklygin approved these changes
Good work. Left some minor comments

2023-03-01 13:16 UTC, merged