fix(Dropdown): remove RootRef
toptal/picasso pull request #3434
Opened 2023-03-20 12:38 UTC by mkrl

[FX-3750](https://toptal-core.atlassian.net/browse/FX-3750)

### Description

Remove RootRef relying on the deprecated `findDOMNode`

### How to test

- Visual tests should pass with no difference
- CI should be green

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| [imagine any dropdown] | [imagine any dropdown again, looks exactly the same] |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-03-20 12:46 UTC, TomasSlama requested changes
seems there is some issue 
![image](https://user-images.githubusercontent.com/6830426/226342754-3e572367-9352-4112-ad0a-2becdce29c09.png)

2023-03-22 11:20 UTC, mkrl commented on packages/picasso/src/Dropdown/Dropdown.tsx
> +    if (firstChild && firstChild.firstChild?.focus) {
Original behavior was to focus on the first item in the dropdown. Since we have changed the first item to be the `div` that holds `ref`, focus now has to be triggered one more node deeper

2023-03-22 12:32 UTC, TomasSlama approved these changes

2023-03-27 11:26 UTC, mkrl commented
@toptal-anvil ping reviewers

2023-03-27 11:28 UTC, sashuk approved these changes
Code and overall reasoning look good!

2023-03-27 11:56 UTC, merged