feat(BarChart): add vertical layout
toptal/picasso pull request #3468
Opened 2023-03-30 12:00 UTC by zorguiala

[TI-1191](https://toptal-core.atlassian.net/browse/TI-1191)

### Description

add vertical layout to the `barChart` component 

### How to test

- navigate to the `BarChart` component try and edit the code and add the prop `layout='vertical'` 

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-03-31 08:15 UTC, sashuk reviewed
@zorguiala Can you please add changeset and Storybook example for the introduced property?

2023-03-31 08:46 UTC, sashuk commented on packages/picasso-charts/src/utils/constants.ts
> +  left: chartConstants.DEFAULT_MARGIN,
As far as I understand, this was done to avoid problems with labels

<img width="406" alt="Screenshot 2023-03-31 at 11 41 55" src="https://user-images.githubusercontent.com/1390758/229071596-8f75f6a3-4bdd-4c7f-9df3-f537d85ac9e3.png">

In fact it also fixed the problem with labels in some of the example in `master`, for example, you can check out the https://picasso.toptal.net/?path=/story/picasso-charts-linechart--linechart and `Multiple Lines` case

<img width="888" alt="Screenshot 2023-03-31 at 11 45 21" src="https://user-images.githubusercontent.com/1390758/229072061-85468f2d-b0c4-4784-88e4-3bff78fe79e1.png">

As a consequence, all charts shrinked, so the visual tests are failing.

2023-03-31 09:14 UTC, sashuk commented on packages/picasso-charts/src/utils/constants.ts
> +  left: chartConstants.DEFAULT_MARGIN,
@toptal/frontend-experience-eng Do you agree that this looks like a bug for charts in `master`? Basically Picasso should provide ways for consumers to configure `margin` so labels are fully visible, as [right now charts do not support this out of the box](https://stackoverflow.com/questions/69757570/prevent-recharts-y-axis-labels-from-wrapping)

<img width="602" alt="Screenshot 2023-03-31 at 12 13 10" src="https://user-images.githubusercontent.com/1390758/229078870-a4879a02-49ca-4faf-b5ca-c54948aa5139.png">

2023-03-31 12:31 UTC, sashuk commented
@zorguiala As @TomasSlama mentioned, can you please check with BASE first?

2023-03-31 15:22 UTC, zorguiala commented
> We need a new story for this variant, missing a changeset. Also, was this discussed with the BASE team? I don't see design for it in https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=8523-21640&t=MbWby2Nmf5HYfoiq-0

- I created a new story for the new variant
- I don't think this was discussed with the BASE team I'm from the talent-insights team and we need a vertical `barChart` for our `testing platform` so I looked it up and I found out that `recharts` has a `vertical` `barChart` and Picasso is using it  so I created this PR

2023-03-31 15:46 UTC, sashuk reviewed
Code looks good now, but first let's wait for confirmation from Matt Vella in https://toptal-core.slack.com/archives/CERF5NHT3/p1680276672842469

After we have confirmation, then I think it is fine to remove any `margin` manipulations, as there is a bug created to address this problem on charts library level (https://toptal-core.atlassian.net/browse/FX-3849) – current implementation affects the scale of charts which is not acceptable

2023-04-03 11:41 UTC, TomasSlama requested changes
It looks great, but since we disable the default visual test in the storybook with `takeScreenshot: false`, we need to add a visual test in Cypress. `/cypress/component/BarChart.spec.tsx`. Could you please add a simple example there? 🙇 

Just to explain, we need to disable the default one, because it used to be flaky because of the render animations.

2023-04-03 11:41 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/story/VerticalBar.example.tsx
> +      margin={{
It seems `BarChart` does not have `margin` property

2023-04-03 11:45 UTC, sashuk commented on packages/picasso-charts/src/BarChart/story/VerticalBar.example.tsx
> +      margin={{
Yep, `margin` changes should be removed completely as they will be addressed in another ticket

2023-04-03 11:48 UTC, TomasSlama commented
![image](https://user-images.githubusercontent.com/6830426/229500510-5361852a-4975-4b61-a29d-fb26f32155e2.png)
also I think this change is not expected ☝️

2023-04-03 11:55 UTC, sashuk commented
> ![image](https://user-images.githubusercontent.com/6830426/229500510-5361852a-4975-4b61-a29d-fb26f32155e2.png) also I think this change is not expected ☝️

This is coming from margins, charts got shrinked because of that and broke all the visual tests 🙂

2023-04-04 09:18 UTC, sashuk commented
@zorguiala Can you please check why labels disappeared and why charts have different size (I've ran your branch locally)?

https://user-images.githubusercontent.com/1390758/229746563-fcb4d71f-3101-47ca-b33e-894b6e6a1bdd.mp4

2023-04-04 09:21 UTC, TomasSlama requested changes
I still believe that something is wrong, margins will be fixed in different PR, so horizontal visual tests should not be affected at all 🤔

2023-04-04 14:57 UTC, zorguiala commented
it the same now I fixed it the only difference is the `0` 

![image](https://user-images.githubusercontent.com/25435884/229833443-67917300-ba49-4271-a258-26b6e266305d.png)

2023-04-04 20:33 UTC, zorguiala commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> -          /* Hide first tick */
@sashuk because when it's vertical layout it removes the first label YAxies

2023-04-05 00:05 UTC, zorguiala commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> -          /* Hide first tick */
why did you remove the first one by the way?

2023-04-05 06:52 UTC, TomasSlama approved these changes
Looks good, even though there is a small change in the horizontal variant, it looks to me like it was a bug before

2023-04-05 08:45 UTC, sashuk commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> -          /* Hide first tick */
@zorguiala It is coming from BASE design for charts (https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=5246-39155&t=Hzwt3rSR62ElaIBc-0 and https://toptal-core.atlassian.net/browse/FX-1602), as they do not have the first tick over there.

I think the final step should be to have conditional styling as we do want to keep the vertical charts the same way they are defined in base, but let's confirm with Matt Vella in https://toptal-core.slack.com/archives/CERF5NHT3/p1680684302910579 first

2023-04-05 09:05 UTC, sashuk approved these changes
Thank you for your dedication and patience, great work!

2023-04-05 09:39 UTC, merged