feat(comm): extend application update notification component to match new BASE
toptal/picasso pull request #3725
Opened 2023-07-14 08:09 UTC by alexvcasillas

[COMM-2458]

### Description

When it comes to displaying the user that there’s a mandatory update and that they need to refresh whether they like it or not, we should be using the ApplicationUpdateNotification component provided by Picasso that follows BASE. But this component is not extensible enough and it does not give room for customization as we have various requirements that need to be fulfilled in order to be able to satisfy the requirements that we’re aiming for with the Force Refresh initiative.

### How to test

- Access Storybook
- Check that all of the acceptance criteria in the attached Jira Ticket is met
- CI should be 💚 

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://github.com/toptal/picasso/assets/9496960/6648ca31-4e16-4af3-8453-f658edccf54b)
![image](https://github.com/toptal/picasso/assets/9496960/34de4500-323b-4a96-b728-ab847c190ed5) | ![image](https://github.com/toptal/picasso/assets/9496960/08644c8e-0bab-455e-a68a-1c44d8e64395) ![image](https://github.com/toptal/picasso/assets/9496960/720749f1-9857-4a60-b3cb-7c95451ca9be) ![image](https://github.com/toptal/picasso/assets/9496960/e9dcf3ff-54a0-4601-80c2-b9530183fb06) ![image](https://github.com/toptal/picasso/assets/9496960/6f487580-a6a2-4c9d-9406-7903eabafe2e) ![image](https://github.com/toptal/picasso/assets/9496960/0578acc7-cda9-4d09-b1d5-0193501211e0) ![image](https://github.com/toptal/picasso/assets/9496960/4bc523f3-b569-45cc-995f-8dc0ddbce4a6) ![image](https://github.com/toptal/picasso/assets/9496960/12e119e1-35b3-4c24-b301-c9ed49529bab) |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-07-14 08:20 UTC, alexvcasillas commented
@toptal-anvil ping reviewers

2023-07-14 11:07 UTC, alexvcasillas commented
Note: Until we have the BASE specs for this updated component we should not merge this

2023-09-28 07:24 UTC, TomasSlama commented
Hey @alexvcasillas any update on this?

2023-09-28 07:26 UTC, alexvcasillas commented
> Hey @alexvcasillas any update on this?

Yes @TomasSlama , we're going to be working on this in the next sprint :)

2023-10-02 09:41 UTC, alexvcasillas commented
@toptal-anvil ping reviewers

2023-10-02 11:59 UTC, TomasSlama reviewed
Small comment, that needs to be addressed. I'm also not sure about the `actionsAlignment`, I want to know opinion about it from my colleagues, I will raise it today on daily, I will let you know

2023-10-03 07:47 UTC, alexvcasillas commented
> Small comment, that needs to be addressed. I'm also not sure about the `actionsAlignment`, I want to know opinion about it from my colleagues, I will raise it today on daily, I will let you know

Hey @TomasSlama I've added that property so we can have some room for flexibility because on the early design of this component, the buttons were alignment on the left on the initial state of the dismissable modal and on the right when the modal becomes undismissable :)

2023-10-03 09:01 UTC, TomasSlama commented on packages/picasso/src/ApplicationUpdateNotification/story/index.jsx
> +    takeScreenshot: false,
I think we should allow screenshots, for default we have screenshot in the cypress component test

2023-10-03 09:03 UTC, TomasSlama commented on packages/picasso/src/ApplicationUpdateNotification/ApplicationUpdateNotification.tsx
> +  actionsAlignment?: 'left' | 'right'
As we discussed in the meeting, for the future, it would be better to have an `Actions` component that would be the container and we could pass it to the `ąctions`

```jsx
actions={
      <ApplicationUpdateNotification.Actions justifyContent='right' alignItems=''>
        <Button
          key='btn-update-now'
          variant='secondary'
          onClick={() => console.log('Update Now')}
        >
          Update Now
        </Button>
      </ApplicationUpdateNotification.Actions>
    }
```

2023-10-10 08:08 UTC, alexvcasillas commented
@toptal-anvil ping reviewers

2023-10-11 13:54 UTC, dmaklygin commented on packages/picasso/src/ApplicationUpdateNotificationActions/test.tsx
> +  it('renders children when passed', () => {
we usually use another notation:

```
describe('when ...', () => {
  it('renders children', () => {
```

2023-10-11 13:55 UTC, dmaklygin commented on packages/picasso/src/ApplicationUpdateNotificationActions/__snapshots__/test.tsx.snap
> +`;
this snapshot, actually, not so informative. We cannot read here any useful information.
I would remove it

2023-10-11 13:57 UTC, dmaklygin commented on packages/picasso/src/ApplicationUpdateNotificationActions/ApplicationUpdateNotificationActions.tsx
> +  children: ReactNode | ReactNode[]
I think, `ReactNode` is completely enough here.
So we won't use `ts-ignore` below

2023-10-11 13:57 UTC, dmaklygin commented on packages/picasso/src/ApplicationUpdateNotification/test.tsx
> +  it('when click on a close modal action the corresponding callback is called', () => {
use `describe + it` blocks please :)

2023-10-11 14:04 UTC, dmaklygin reviewed
Left some minor comments

2023-10-12 10:27 UTC, dmaklygin approved these changes

2023-10-12 14:32 UTC, mkrl requested changes
Thanks for addressing all the suggestions!
I have one final thing that I think should be fixed and then we can merge it :muscle:

2023-10-12 14:32 UTC, mkrl commented on packages/picasso/src/ApplicationUpdateNotification/story/index.jsx
> +      takeScreenshot: true,
It looks like this story, along with several others showscases notifications in their collapsed state.

If we need them in collapsed state for the story demo, I would suggest to disable screenshots for those since brings no purpose and consumes the Happo quota.

![image](https://github.com/toptal/picasso/assets/18409292/af434635-7302-4a10-b0e2-f5b1bfbd8e5e)

I suggest to disable screenshots for `In Action` , `In Action not Dismissable` and `In Action with Action Buttons`

2023-10-12 14:34 UTC, alexvcasillas commented on packages/picasso/src/ApplicationUpdateNotification/story/index.jsx
> +      takeScreenshot: true,
Yes, I agree that this screenshots does not actually make any sense as they only display the trigger button

2023-10-12 14:51 UTC, mkrl approved these changes
Nice job :+1:

2023-10-12 15:42 UTC, merged