fix: aa
toptal/picasso pull request #3736
Opened 2023-07-20 18:51 UTC by sashuk

[FX-4090]

# 🔴 Please do not review

### Description

Describe the changes and motivations for the pull request.

### How to test

- Temploy
- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-07-24 10:31 UTC, sashuk commented
@toptal-bot run package:alpha-release

2023-07-25 09:30 UTC, sashuk commented
@toptal-anvil ping reviewers

2023-07-25 09:47 UTC, TomasSlama requested changes
it does not create expected images 
![image](https://github.com/toptal/picasso/assets/6830426/d63c83c8-4822-4282-a67d-c7411368c69d)

2023-07-25 15:17 UTC, sashuk commented
@TomasSlama Thank you for noticing, addressed!

<img width="917" alt="Screenshot 2023-07-25 at 17 16 55" src="https://github.com/toptal/picasso/assets/1390758/20678fad-9191-438c-8e1f-67c8992f9b55">

2023-07-26 07:25 UTC, TomasSlama reviewed
Looks good, I think your new screenshot revealed a style bug
 
![image](https://github.com/toptal/picasso/assets/6830426/68aa0cb3-2022-40a3-89c4-7beb38ed7265)
we are missing bottom spacing in the header.

Also I think that the one `diff` is not expected
![image](https://github.com/toptal/picasso/assets/6830426/74de4565-cde6-4ac7-8b63-1360ea0ce6e8)

2023-07-26 09:58 UTC, sashuk commented
@TomasSlama

> Looks good, I think your new screenshot revealed a style bug

Will be fixed in https://github.com/toptal/picasso/pull/3743, thanks!

> Also I think that the one diff is not expected

The test is flaky, I've put additional conditions so we take screenshots when the menu is actually opened

2023-07-26 11:24 UTC, mkrl approved these changes
Awesome job. I've looked through the new screenshots and it looks solid. I have left one question (not critical)

2023-07-26 11:24 UTC, mkrl commented on cypress/component/Page.spec.tsx
> +const responsiveHappoTargets = [400, 600, 800, 1279, 1280, 1800].reduce<
By the way, are there any guidelines as why those targets are selected? I was thinking we could get the list of desired breakpoints from `breakpoints.ts`, subtract N pixels and use that. There also seems to be more ranges that we support. Are there any components that use breakpoints we don't support?

2023-07-26 11:51 UTC, sashuk commented on cypress/component/Page.spec.tsx
> +const responsiveHappoTargets = [400, 600, 800, 1279, 1280, 1800].reduce<
@mkasperowicz Great idea, thanks! The selection of resolutions where we want to check component (_checkpoints_) was automated based on the `breakpoints.ts` and the comment about special breakpoint of `1280px` was added

2023-07-26 12:59 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
> +  breakpoints[breakpointKeys.slice(-1) as unknown as BreakpointKeys] + 5,
What is the purpose of this code? I'm a bit confused by the constants, maybe we could add some comments or name the magic numbers?

2023-07-26 13:45 UTC, augustobmoura reviewed
I added some comments, mostly on documenting the workarounds and non-obvious choices

2023-07-26 13:45 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
> +  ]
I think I understood this code, but maybe we could make it more clear if we simplified and add some comments to it, wdyt?
```suggestion
  const breakpointValues = Object.values(breakpoints).sort()

  return [
    ...breakpointValues
      .slice(1) // First breakpoint (0 to x) doesn't generate a checkpoint, as it is comprehends anything lower than the second
      .map(breakpoint => breakpoint - offset), // We subtract an offset so the width would be inside the range
    breakpointValues.slice(-1)[0] + offset,
```

2023-07-26 13:45 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
> +  const offset = 5
I would be even safer and use `1` as the offset, as having it with `5` would miss off-by-one errors. If possible I would even go as far as having a decimal offset, something like 0.01, or similar
```suggestion
  const offset = 1
```

2023-07-26 13:45 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
I would split the logic for the checkpoints on a different file, maybe even inside Picasso provider itself, as it is useful in multiple places. I could use this function on Storybook Happo settings, for example

2023-07-26 13:45 UTC, augustobmoura commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      offset={{ top: 0.4 }}
I would name this magic number so people in the future know it is about, maybe `LINE_POSITIONING_OFFSET` or something that makes better sense

2023-07-26 13:45 UTC, augustobmoura commented on packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap
> -    </div>
Does moving the hamburger outside of the portal make any noticeable difference?

2023-07-26 13:45 UTC, augustobmoura commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      disablePortal
I would also add some explanation on why we are disabling the portal here, in specific explain the bug we hit, and when we expect it to be fixed, maybe a link to a cypress issue or a JIRA ticket

2023-07-26 13:46 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
> +  ]
We could also use named functions instead of line comments, to convey the motivation behind the choices, that are not obvious at first glance

2023-07-26 13:48 UTC, sashuk commented on packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap
> -    </div>
@augustobmoura Yep, as it renders it in a different place

2023-07-26 13:51 UTC, sashuk commented on cypress/component/Page.spec.tsx
@augustobmoura I think checkpoints belong to testing only, so Picasso should not be aware of them, what do you think?

2023-07-26 13:52 UTC, augustobmoura commented on cypress/component/Page.spec.tsx
Yeah, I was not sure about having it on picasso provider, but I think we could put it inside a util file at least, so we can use it on other stories and on happo config

2023-07-26 14:02 UTC, sashuk commented on cypress/component/Page.spec.tsx
> +  ]
@augustobmoura Comment were added, thanks!

2023-07-26 14:02 UTC, sashuk commented on cypress/component/Page.spec.tsx
> +  const offset = 5
@augustobmoura Changed to `1`, thanks!

2023-07-26 14:02 UTC, sashuk commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      offset={{ top: 0.4 }}
@augustobmoura It was completely removed, thanks!

2023-07-26 14:03 UTC, sashuk commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      disablePortal
@augustobmoura The comment was added, but the problem itself goes down to the React itself, so even if we create ticket we probable never going to address it

2023-07-26 14:32 UTC, augustobmoura commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      disablePortal
Did it work outside of Cypress? It worked when ran/deployed manually right? Wouldn't that already narrow the bug to either Cypress or Happo screenshots?

2023-07-26 14:36 UTC, sashuk commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      disablePortal
@augustobmoura It breaks only in Cypress, so the problem is related to Cypress. The problem comes from `createPortal()` and @mkrl researched it even more and it is something wrong with React itself. 

Adding `disablePortal` does not affect consumers, so it seems to be a better option as the research will take significant amount of resources.

2023-07-26 14:42 UTC, sashuk commented
@toptal-bot run package:alpha-release

2023-07-26 14:46 UTC, augustobmoura commented on packages/picasso/src/PageHamburger/PageHamburger.tsx
> +      disablePortal
Yeah, I don't think we should spend too much time on cypress-specific problems, but maybe we could create an issue upstream so the project maintainers can know about it or help with debugging the problem. They can even check Picasso for problems

2023-07-26 14:53 UTC, sashuk commented on packages/picasso/src/test-utils/get-checkpoints.ts
> +  const breakpointKeys = Object.keys(breakpoints)
@augustobmoura Fixed, thanks!

2023-07-26 15:06 UTC, augustobmoura approved these changes
Nice work @sashuk :+1:

2023-07-26 18:33 UTC, merged