fix: initialize editor with empty paragraph if root is empty
toptal/picasso pull request #3745
Opened 2023-07-26 11:02 UTC by mkrl

[FX-4190](https://toptal-core.atlassian.net/browse/FX-4190)

### Description

When `{ root: { children: [] } }` is provided as a default value to the RichTextEditor, the internal editor state is initialized without an empty paragraph. According to Lexical docs, this is not a valid state, there should always be at least one paragraph node by default.
This causes the editor to crash when trying to append items to the root node (for example, creating an empty list in editor with an empty default value).

### How to test

- Temploy
- Story for `RichText` can be used for testing
- Change the `HTML` story example code to have the default value of `root: { children: [] } `
- Without doing anything else, click on any list button in the editor

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-07-26 11:17 UTC, TomasSlama requested changes
![image](https://github.com/toptal/picasso/assets/6830426/c55c9f1a-1e98-4cb2-af06-839701083226)

It does not crash, but the default value is not working at all ;-)

2023-07-27 11:35 UTC, mkrl commented
@TomasSlama it looks like we have previously not been checking for empty value in the correct way at all.
`root.isEmpty()` is always `true` because `value` is not yet converted and appended to the root node in Lexical. I've updated the example to check for value instead.

2023-07-27 12:59 UTC, TomasSlama approved these changes
tested in the temploy 👍

2023-07-27 15:55 UTC, augustobmoura approved these changes
The code is simple enough, nice change! :+1: 

The happo problem must be an flaky test

2023-07-27 18:36 UTC, dmaklygin approved these changes
👍

2023-07-28 00:09 UTC, merged