feat: add support for standalone links
toptal/picasso pull request #3761
Opened 2023-07-31 12:51 UTC by mkrl

[FX-NNNN](https://toptal-core.atlassian.net/browse/FX-4180)

### Description

This PR makes it possible to insert a link while no text is selected. In this case, a link will be inserted as a new `LinkNode` with text content being the link itself.

### How to test

- Temploy
- Check out the `Links` story for `RichTextEditor`
- Try to insert the link with nothing selected
- Try different combinations of inserting (next to other nodes, next to lists, inside/outside other formats)

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-07-31 13:07 UTC, mkrl commented
@toptal-anvil ping reviewers

2023-07-31 14:45 UTC, dmaklygin commented on packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx
> +    })
Are we going to cover it with tests somehow?

2023-07-31 14:49 UTC, dmaklygin requested changes
I was not able to add a link: 
![image](https://github.com/toptal/picasso/assets/1824723/6fd1c7e5-a2d7-482f-9f4c-402e03af8f76)
MacOS, Chrome

2023-07-31 14:52 UTC, mkrl commented on packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx
> +    })
I think we can cover this in a cypress spec for the RTE. I'll add some test cases (the entire LinkPlugin is untested so it's a good idea to add some coverage)

2023-07-31 15:03 UTC, mkrl commented
> I was not able to add a link: ![image](https://user-images.githubusercontent.com/1824723/257258807-6fd1c7e5-a2d7-482f-9f4c-402e03af8f76.png) MacOS, Chrome

@dmaklygin looks like I've overlooked the most simple of all the cases, thank you :)
Should be fixed now

2023-07-31 16:33 UTC, sashuk commented
@mkrl When the link is inserted in the middle of paragraph, it is inserted in the end, is it expected?

https://github.com/toptal/picasso/assets/1390758/06d837b9-4793-4591-ab30-194289e51442

2023-07-31 16:39 UTC, mkrl commented
@sashuk nope, I've just discovered this as well. I think we'll need some node splitting logic (there is already something in Lexical for that). I wanted to keep it as simple as possible, but it looks like more code is needed. I'll update the PR.

2023-08-02 11:11 UTC, mkrl commented on packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx
> +    })
Added multiple test cases (and a new screenshot) for links in RTE

2023-08-02 11:13 UTC, mkrl commented
The PR has been updated to include Cypress coverage for all cases for LinkPlugin + a new way of inserting LinkNodes that should allow for inserting anywhere.

2023-08-02 11:14 UTC, mkrl commented on cypress/component/RichTextEditor/LinkPlugin.spec.tsx
> +        cy.stub(win, 'prompt').returns('https://toptal.com/')
There is no way to interact with `window.prompt` in Cypress so I stubbed a return value

2023-08-02 11:18 UTC, sashuk commented on cypress/component/RichTextEditor/LinkPlugin.spec.tsx
> +  cy.getByTestId(linkPluginButton).as('linkPluginButton')
Is this line needed (as it duplicated the previous one)?

2023-08-02 11:19 UTC, sashuk commented on cypress/component/RichTextEditor/LinkPlugin.spec.tsx
> +      // Link is inserted into unordered list
NIT: Maybe this test could be split in multiple test cases?

2023-08-02 11:59 UTC, sashuk approved these changes
Tested on temploy, works as expected! Left a couple of comments

2023-08-02 14:04 UTC, mkrl commented on cypress/component/RichTextEditor/LinkPlugin.spec.tsx
> +      // Link is inserted into unordered list
I wanted to have one single screenshot for the different cases and I'm not sure if I can do it outside the test. Let me check.

2023-08-02 14:04 UTC, mkrl commented on cypress/component/RichTextEditor/LinkPlugin.spec.tsx
> +  cy.getByTestId(linkPluginButton).as('linkPluginButton')
Might not be, good point, I'll check it

2023-08-03 07:52 UTC, TomasSlama approved these changes
manually tested, good job

2023-08-03 09:23 UTC, merged