docs: add decision on responsive spacing properties
toptal/picasso pull request #3802
Opened 2023-08-12 10:59 UTC by sashuk

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request.

### How to test

- Temploy
- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-08-14 10:25 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +# RFC Template
The 18th RFC is located in a different pull request https://github.com/toptal/picasso/pull/3801

2023-08-14 14:09 UTC, dmaklygin commented on docs/decisions/19-responsive-spacing-properties.md
> +Responsive spacing tokens with different values depending on the screen size is one of the approaches used on the market (as an example, [Audi Design System](https://react.ui.audi/?path=/docs/brand-i
Could you describe a little bit more about responsive spacing tokens? namely, why is it complex?
I think, from the user perspective, they would not care about responsiveness if it's already adjusted in Picasso's components

2023-08-14 14:10 UTC, dmaklygin commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
allowing multiple ways to specify margins may bring complexity and inconsistency in future, so we will try reworking it very hard later on.

2023-08-14 14:12 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +Responsive spacing tokens with different values depending on the screen size is one of the approaches used on the market (as an example, [Audi Design System](https://react.ui.audi/?path=/docs/brand-i
@whymancreates Can you please elaborate why BASE design decided to go without responsive spacing tokens?

2023-08-14 14:15 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
@dmaklygin Do you mean deprecating spacing constants like `'small'`, `'medium'`, etc.?

2023-08-15 08:46 UTC, OleksandrNechai commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
To me,` top={{ md: 1}}` looks strange. What does this mean?

2023-08-15 09:31 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
@OleksandrNechai It means `1rem`, the same way we define `top`, `right`, etc. properties of [Container](https://picasso.toptal.net/?path=/story/layout-container--container) that have `SpacingType`. I propose to keep them consistent

```
// Current approach
<Container top='small'/> 
..
<Container top={1}/> 

// Introducing responsive spacings
<Container top={{ md: 'small' }}/> 
..
<Container top={{ md: 1 }}/> 
```

2023-08-15 10:26 UTC, sashuk commented
@toptal-anvil ping reviewers

2023-08-15 11:15 UTC, mkrl commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
It would be nice to have numbers correspond to spacing tokens, not `rem` directly.
Ideally, we would only have pre-defined amount of spacing, then the numbers would be `1` for `0.25`, `10` for `2.5`, etc.
But again, that breaks compatibility and this is probably the best we can do without annoying breaking changes. There is no good way to map existing "out of design system" spacing to tokens.

We could make a codemod that replaces the ones that are matched with proper token values and then have an alert after codemod is run to clean up manual "non-standard" spacing.

2023-08-15 12:05 UTC, dmaklygin commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
According to this guildeline for spacing: https://toptal-core.atlassian.net/wiki/spaces/Base/pages/3217031216/Spacing
we have a predefined set of spacing and I think, the extra spacing should not be allowed. WDYT?

2023-08-15 14:42 UTC, augustobmoura commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
If we would need to allow arbitrary spacing, maybe we could do it in a well typed manner, maybe having units as proper custom classes (vide [comment](https://github.com/toptal/picasso/pull/3801/files#r1294674871)). We would solve the confusion around units by having them explicit and would make the API a lot more flexibe, what do you guys think?

```ts
import { spacing } from "@toptal/picasso";

const container = (
  <Container
    top={{
      md: spacing.rem(2),
      sm: spacing.px(32),
    }}
  />
);
```

2023-08-15 17:11 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
@mkrl 

> It would be nice to have numbers correspond to spacing tokens, not rem directly.

Please see the https://github.com/toptal/picasso/pull/3801#discussion_r1294818682 (no need to expose the implementation and units), I'll double check with @whymancreates though

@augustobmoura 

> Maybe we should allow only the [spacing design tokens](https://github.com/toptal/picasso/pull/3801/files) for responsive objects, wdyt?

I'd keep it as it is, as this will break the consistency with existing `top`, `right`, etc. spacing properties, plus it will be a breaking change. The overall goal is to provide the same spacing tokens that are used in design, so it will be easier for engineers to implement the designs using Picasso.

> If we would need to allow arbitrary spacing, maybe we could do it in a well typed manner, maybe having units as proper custom classes (vide [comment](https://github.com/toptal/picasso/pull/3801/files#r1294674871)). We would solve the confusion around units by having them explicit and would make the API a lot more flexibe, what do you guys think?

I think it is a great implementation idea, but at the same time it looks a bit like an overkill for me, as consumers need a spacing identifier that they have in designs so the ability to convert it to different units will only confuse (more flexibility leads to more confusion). So, the goal is not to break current API and provide the same tokens from design guidelines

2023-08-16 07:44 UTC, whymancreates commented on docs/decisions/19-responsive-spacing-properties.md
> +Responsive spacing tokens with different values depending on the screen size is one of the approaches used on the market (as an example, [Audi Design System](https://react.ui.audi/?path=/docs/brand-i
@sashuk and @dmaklygin I think right now, my main challenge is that I am blindsided to how a space-10 on desktop should adjust to what space-N on mobile. If FX team sees this as a benefit for engineers then lets work on it and have something similar to the audi system. thoughts??

2023-08-16 09:06 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +Responsive spacing tokens with different values depending on the screen size is one of the approaches used on the market (as an example, [Audi Design System](https://react.ui.audi/?path=/docs/brand-i
@whymancreates @dmaklygin Thank you, let's continue this discussion in the dedicated pull request (https://github.com/toptal/picasso/pull/3801#issuecomment-1680236058)!

2023-08-16 20:49 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
Just for the record, the decision on responsive tokens is mentioned in https://github.com/toptal/picasso/pull/3801#issuecomment-1680236058

2023-08-16 20:57 UTC, sashuk commented
@toptal-anvil ping reviewers

2023-08-17 10:25 UTC, OleksandrNechai requested changes

2023-08-17 10:25 UTC, OleksandrNechai commented on docs/decisions/19-responsive-spacing-properties.md
> +Taking into account planned Picasso migration to TailwindCSS and problems that rise in case of using workaround, the technical implementation of API proposal is postponed until TailwindCSS migration
Does this mean we are making a decision on API now but we are not going to implement it?

2023-08-17 10:25 UTC, OleksandrNechai commented on docs/decisions/19-responsive-spacing-properties.md
> +### Technical challenges
This RFC proposes to change API. How is the following discussion useful to make this decision?

2023-08-17 10:25 UTC, OleksandrNechai commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
1) I tend to agree with Augusto. Responsive objects should take tokens only. Making it hard to do wrong things. It will not break anything if we continue to support this: `<Container top={5} bottom={5} left={5} right={5}>`, but if you want to go responsive you should follow responsive guidelines.
2) It is not specified what happens with the old API variant:  `<Container top={5} bottom={5} left={5} right={5}>`
3) It is not specified what happens to `gap` and `padded` properties. Also not clear what happens with `bottom`, `left` and `right`?

2023-08-17 10:25 UTC, OleksandrNechai commented on docs/decisions/19-responsive-spacing-properties.md
> +# RFC Template
Number is ok, we will put it in later, but what about the name of the RFC?

2023-08-17 14:31 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +Taking into account planned Picasso migration to TailwindCSS and problems that rise in case of using workaround, the technical implementation of API proposal is postponed until TailwindCSS migration
@OleksandrNechai Yes, we are waiting for TailwindCSS

2023-08-17 14:32 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +### Technical challenges
@OleksandrNechai I think it will be useful to have it here to answer the question why we need to wait for TailwindCSS

2023-08-17 14:34 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +# RFC Template
@OleksandrNechai The title and the file name were updated, can you please check?

2023-08-17 14:48 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/>
@OleksandrNechai 

> 1. I tend to agree with Augusto. Responsive objects should take tokens only. Making it hard to do wrong things. It will not break anything if we continue to support this: <Container top={5} bottom={5} left={5} right={5}>, but if you want to go responsive you should follow responsive guidelines.

I think that if we change the type of spacing properties (`top={..}` or `top={{ md: .... }}`) we should be consistent, so both types of spacing properties should have the same type. Yes, we will leave only BASE spacings as described in https://github.com/toptal/picasso/pull/3801, but I can easily imagine the confusion when we introduce responsive `top` property and people start asking why `top={..}` or `top={{ md: .... }}` have different types. But let's proceed with BASE spacings then.

> 2. It is not specified what happens with the old API variant: <Container top={5} bottom={5} left={5} right={5}>

I propose to keep it working the same as now, this case was added to the RFC

> (added) ... The existing way of specifying spacing properties should work the same, `top={spacing[2]}` sets `spacing[2]` for all screen sizes.

> 3. It is not specified what happens to gap and padded properties. Also not clear what happens with bottom, left and right?

Thanks a lot for bringing up the `gap` and `padded` properties! Added them to the RFC as well.

`left`, `bottom`, and `right` properties are mentioned in the beginning of the RFC (please see the **Problem** section).

2023-08-17 15:06 UTC, sashuk commented on docs/decisions/19-container-responsive-spacing-properties.md
> +# RFC Template
Change

2023-08-17 15:12 UTC, OleksandrNechai commented on docs/decisions/19-container-responsive-spacing-properties.md
> +The scale of the problem is large enough for measures to be taken. According to the research in [Container properties usages section](#container-properties-usage), 8% of the `Container.top` spacing p
The Container's spacing props are not responsive while it is required by users.

2023-08-17 15:26 UTC, OleksandrNechai commented on docs/decisions/19-container-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/> // throws TypeScript error
Proposal:
1) The following change goes for properties: gap, bottom....
2) extend spacing properties to accept object:
```ts
export type SpacingType =
  | number
  | SizeType<'xsmall' | 'small' | 'medium' | 'large' | 'xlarge'>
```
changes to:

2023-08-17 18:02 UTC, sashuk commented on docs/decisions/19-responsive-spacing-properties.md
> +# RFC Template
Discussed during the sync-up, fixed

2023-08-17 18:07 UTC, sashuk commented on docs/decisions/19-container-responsive-spacing-properties.md
> +<Container top={{ md: 1, lg: 'large' }}/> // throws TypeScript error
@OleksandrNechai Resolved, thank you! Please see the https://github.com/toptal/picasso/blob/FX-4426-document-responsive-api/docs/decisions/19-responsive-component-spacing-properties.md#api-changes

2023-08-17 18:07 UTC, sashuk commented on docs/decisions/19-container-responsive-spacing-properties.md
> +The scale of the problem is large enough for measures to be taken. According to the research in [Container properties usages section](#container-properties-usage), 8% of the `Container.top` spacing p
@OleksandrNechai Fixed, thank you!

2023-08-18 08:40 UTC, OleksandrNechai commented on docs/decisions/19-responsive-component-spacing-properties.md
> +## Current situation
Usually this is called `Context`

2023-08-18 08:44 UTC, sashuk commented on docs/decisions/19-responsive-component-spacing-properties.md
> +## Current situation
@OleksandrNechai Fixed in both PRs, thanks!

2023-08-18 08:47 UTC, OleksandrNechai approved these changes
I still would prefer less words and more formal definitions, but at this point I guess it is good enough. Good job 👍

2023-08-18 14:34 UTC, sashuk commented
@toptal-anvil ping reviewers

2023-08-18 15:33 UTC, merged