feat: [FX-4259] add new spacing values to picasso
toptal/picasso pull request #3835
Opened 2023-08-30 11:16 UTC by dmaklygin

[FX-4259]

### Description

Add new spacing values to Picasso, described in BASE. 

RFC: https://github.com/toptal/picasso/blob/master/docs/decisions/18-spacings.md#technical-details

- [ ] BASE spacings are exported according to RFC
- [ ] BASE spacings are exported via theme, so they can be used in custom styles

### How to test

- Use temploy to play with SPACING variables

Example:
```
import { SPACING_4, SPACING_6 } from '@toptal/picasso/utils'

const Example = () => (
  <div>
    <Container bottom={SPACING_6}>Some text</Container>
    <Container left={SPACING_4}>Some more text with a small margin</Container>
  </div>
)
```

Example of new `spacings` variable coming from the theme:

```
export default ({ palette, sizes: { borderRadius }, spacings: { SPACING_6 } }: Theme) => {
  ...

}
```

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-08-30 11:17 UTC, dmaklygin commented
@toptal-bot run package:alpha-release

2023-08-30 11:58 UTC, dmaklygin commented on packages/shared/src/types.ts
> -
as picasso-shared depends on picasso-provider, we should move definitions of spacings types and helprs to provider and then re-export them from picasso-provider package.

2023-08-30 11:59 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +export { isNumericSpacing, spacingToRem }
Decided to move those functions from `types.ts` file, which is definitely not a proper place for utils

2023-08-30 12:00 UTC, dmaklygin commented
@toptal-anvil ping reviewers

2023-08-30 15:08 UTC, sashuk commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +export { isNumericSpacing, spacingToRem }
Do you think there could be a unit tests for those helpers?

2023-08-30 15:10 UTC, sashuk commented on packages/picasso-provider/src/Picasso/PicassoProvider.tsx
> +  spacings,
Just in case, we have discussed that `spacings` word sounds weird – however, it is actually grammatically correct https://www.wordhippo.com/what-is/the-plural-of/spacing.html / https://simple.wiktionary.org/wiki/spacings (so, we have different _types_ of spacing)

2023-08-30 15:11 UTC, sashuk commented on .changeset/lovely-socks-cheat.md
> +- add new Spacing values to picasso's theme and to `picasso-shared`. See RFC: https://github.com/toptal/picasso/blob/master/docs/decisions/18-spacings.md#technical-details
NIT: 

```suggestion
- add new spacing values to picasso's theme and to `picasso-shared`. See RFC: https://github.com/toptal/picasso/blob/master/docs/decisions/18-spacings.md#technical-details
```

2023-08-30 15:23 UTC, sashuk commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +    acc[`SPACING_${index}`] = PicassoSpacing.create(value)
Can you please elaborate why `new PicassoSpacing()` is not used here?

2023-08-30 15:33 UTC, sashuk commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +    acc[`SPACING_${index}`] = PicassoSpacing.create(value)
Using `index` does not work for all constants according to https://toptal-core.atlassian.net/wiki/spaces/Base/pages/3217031216/Spacing – for example, `SPACING_8` is `2rem` value, but the index will be `7` (so the `SPACING_7` constant will be generated)

<img width="983" alt="Screenshot 2023-08-30 at 17 32 40" src="https://github.com/toptal/picasso/assets/1390758/7559225b-f715-46e1-8260-88fb05ef8026">

2023-08-31 04:06 UTC, augustobmoura requested changes
The implementation should work, but I still think we are leaking too much information for users as of now. The intention of using classes is to prevent users from depending on the values directly, so we should keep the design of the API as [poka-yoke](https://en.wikipedia.org/wiki/Poka-yoke) as possible

2023-08-31 04:06 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +  return typeof spacing === 'number' || spacing instanceof PicassoSpacing
When `spacing instanceof PicassoSpacing`, spacing wouldn't be `number`, did you mean `!(spacing instanceof PicassoSpacing)`?

2023-08-31 04:06 UTC, augustobmoura commented on packages/picasso/src/Container/Container.tsx
> +        ...(isNumericSpacing(right) && { marginRight: spacingToRem(right) }),
These `isNumericSpacing` checks are unnecessary, as `spacingToRem` already treats all spacing cases

2023-08-31 04:06 UTC, augustobmoura commented on packages/picasso/src/utils/index.ts
> +}
You could simplify it to:
```suggestion
export const {
  SPACING_0,
  SPACING_1,
  SPACING_2,
  SPACING_3,
  SPACING_4,
  SPACING_5,
  SPACING_6,
  SPACING_7,
  SPACING_8,
} = spacings
```

2023-08-31 12:53 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/PicassoProvider.tsx
> +  spacings,
It's not weird, there were thoughts about incorrect notation.

2023-08-31 12:55 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +    acc[`SPACING_${index}`] = PicassoSpacing.create(value)
static method is useful if we want to add additional logic or checks when creating an instance in the future

2023-08-31 12:57 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +export class PicassoSpacing {
then we wouldn't check the exact type of the value, no?

2023-08-31 13:08 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +export default spacings
In a technical details: https://github.com/toptal/picasso/blob/master/docs/decisions/18-spacings.md#technical-details
we should export them as constants. Since, your suggestion exports an array of elements, not exact constants, user cannot import a single constant using:

```
import { SPACING_0 } from '@toptal/picasso/utils'
```

I would keep my solution

2023-08-31 13:11 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +  return typeof spacing === 'number' || spacing instanceof PicassoSpacing
nope, we expect that `spacing` is a number, either is a primitive number or an instance of `PicassoSpacing`

2023-08-31 13:12 UTC, dmaklygin commented on packages/picasso/src/Container/Container.tsx
> +        ...(isNumericSpacing(right) && { marginRight: spacingToRem(right) }),
yeah, for this particular case it's necessary. We shouldn't render them if `spacing` is a string

2023-08-31 13:37 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +export class PicassoSpacing {
If we want to test if a value is of `PicassoSpacing` type, we export a
type-guard from the module and still keep the class constructor inaccessible
outside the module:
```ts
export const isPicassoSpacing = (target: unknown): target is PicassoSpacing =>
  target instanceof PicassoSpacingImpl
```

2023-08-31 13:39 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/config/spacings.ts
> +export default spacings
That's true, I missed an `export` keyword on the suggestion, what I wanted to write was:
```suggestion
const spacings = [
  new PicassoSpacingImpl(0),
  new PicassoSpacingImpl(0.25),
  // ...
  new PicassoSpacingImpl(3),
]

export const [
  SPACING_0,
  SPACING_1,
  // ...
  SPACING_12,
] = spacings

export default spacings
```

2023-08-31 13:40 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +  return typeof spacing === 'number' || spacing instanceof PicassoSpacing
`PicassoSpacing` is not a primitive `number`, I don't see why we "lie" to Typescript here and tell the class is a `number`, do we really need this method? :thinking:

2023-08-31 13:44 UTC, augustobmoura commented on packages/picasso/src/Container/Container.tsx
> +        ...(isNumericSpacing(right) && { marginRight: spacingToRem(right) }),
Why though? There's nothing on the right-hand side of the `&&` operand that
would not accept any spacing, meaning the code below is the same as the current
one:
```ts
        ...(left && { marginLeft: spacingToRem(left) }),
        ...(right && { marginRight: spacingToRem(right) }),
```

2023-08-31 13:54 UTC, augustobmoura commented on packages/picasso/src/Container/Container.tsx
> +        ...(isNumericSpacing(right) && { marginRight: spacingToRem(right) }),
I see, then I would just change the signature of `isNumericSpacing` to:
```ts
const isNumericSpacing = (a: SpacingType): boolean =>
```

Instead of a type guard asserting that the type is a number:
```ts
const isNumericSpacing = (a: SpacingType): a is number =>
```

2023-08-31 13:56 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +  if (!spacing) {
This will fail when spacing is `0`, which is not what we want for this case, we still need to provide a margin/padding of `0` in that case, here we need to specifically test for nullity:
```suggestion
  if (spacing != null) {
```

2023-08-31 15:36 UTC, dmaklygin commented on packages/picasso-provider/src/Picasso/utils/spacings.ts
> +export { isNumericSpacing, spacingToRem }
yes!

2023-08-31 16:06 UTC, dmaklygin commented
@toptal-anvil ping reviewers

2023-09-01 02:54 UTC, augustobmoura approved these changes
LGTM!

2023-09-01 07:56 UTC, merged