Cpt 993 fe create query builder library
toptal/picasso pull request #3872
Opened 2023-09-15 12:40 UTC by rasitozcan

[CPT-994](https://toptal-core.atlassian.net/browse/CPT-994)
[CPT-1216](https://toptal-core.atlassian.net/browse/CPT-1216)
[CPT-993](https://toptal-core.atlassian.net/browse/CPT-993)

### Description

This is a draft PR atm. [CPT-994](https://toptal-core.atlassian.net/browse/CPT-994) and [CPT-1216](https://toptal-core.atlassian.net/browse/CPT-1216) can be checked from this branch.

QueryBuilder library will be moved from Staff Portal to  Picasso. Initial files and stories are added in ths PR.

PR will get out of draft status when [CPT-993](https://toptal-core.atlassian.net/browse/CPT-993) is completed. (And will ping the reviewers with it.)

### How to test

- Temploy
- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2023-09-18 15:19 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/MultiSelect/styles.ts
same here as for other styles.ts/styles.tsx files

2023-09-18 15:19 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/OperatorSelector/styles.ts
same here as for other styles.ts/styles.tsx files

2023-09-18 15:32 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/Select/Select.tsx
> +  const formatedOptions = generateSelectOptions(options)
```suggestion
  const formattedOptions = generateSelectOptions(options)
```

2023-09-18 15:33 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +const invalidValidationResult = {
wdyth ?
```suggestion
const invalidResult = {
```

2023-09-18 15:34 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +const validValidationResult = {
```suggestion
const validResult = {
```

2023-09-18 15:35 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +  describe('when called with a valid validationResult', () => {
wdyth ?
```suggestion
  describe('when called with a validResult', () => {
```

2023-09-18 15:35 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +        validationResult: validValidationResult,
```suggestion
        validationResult: validResult,
```

2023-09-18 15:35 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +  describe('when called with an invalid validationResult', () => {
```suggestion
  describe('when called with an invalidResult', () => {
```

2023-09-18 15:35 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +        validationResult: invalidValidationResult,
```suggestion
        validationResult: invalidResult,
```

2023-09-18 15:37 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/generate-select-options.test.ts
> +  describe('when options is undefined', () => {
```suggestion
  describe('when options are undefined', () => {
```

2023-09-18 15:38 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/generate-select-options.test.ts
> +    it('returns options properly formatted', () => {
```suggestion
    it('returns properly formatted options', () => {
```

2023-09-18 15:38 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/generate-select-options.test.ts
> +    it('returns options properly formatted', () => {
```suggestion
    it('returns properly formatted options', () => {
```

2023-09-18 15:41 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/validate-value-editor.test.ts
> +      describe('and valid is true', () => {
wdyth ?
```suggestion
      describe('when valid is true', () => {
```

2023-09-18 15:42 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/validate-value-editor.test.ts
> +      describe('and valid is false', () => {
the same here
```suggestion
      describe('when valid is false', () => {
```

2023-09-18 15:43 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/validate-value-editor.test.ts
> +      describe('and valid is true', () => {
```suggestion
      describe('when valid is true', () => {
```

2023-09-18 15:43 UTC, angelinastavniiciuc commented on packages/picasso-query-builder/src/utils/validate-value-editor.test.ts
> +      describe('and valid is false', () => {
```suggestion
      describe('when valid is false', () => {
```

2023-09-20 13:40 UTC, rasitozcan commented on packages/picasso-query-builder/CHANGELOG.md
I think it is generated automatically with conventional commits on release.

2023-09-20 13:42 UTC, rasitozcan commented on packages/picasso-query-builder/src/AutoComplete/styles.ts
Kept the styles files,  converting them to jss in place.

2023-09-20 13:42 UTC, rasitozcan commented on packages/picasso-query-builder/src/CombinatorSelector/styles.tsx
Kept the styles files,  converting them to jss in place.

2023-09-20 13:43 UTC, rasitozcan commented on packages/picasso-query-builder/src/MultiSelect/styles.ts
Kept the styles files,  converting them to jss in place.

2023-09-20 13:43 UTC, rasitozcan commented on packages/picasso-query-builder/src/OperatorSelector/styles.ts
Kept the styles files,  converting them to jss in place.

2023-09-20 13:54 UTC, rasitozcan commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
> +  describe('when called with a valid validationResult', () => {
`when called with a valid result` sounds better

2023-09-21 12:40 UTC, rasitozcan commented on packages/picasso-query-builder/CHANGELOG.md
My statement above seems to be wrong, I have discussed with @dmaklygin , and it is cleat that I will create Changelog manually.

2023-09-22 12:41 UTC, toptalwadiibasmi reviewed
I left a few comments. I wonder if we should opt for the onEvent notation (for example the buttons), unless it is inherited from React query builder component props (MultiSelect as an example).

2023-09-22 13:03 UTC, rasitozcan commented
@toptal-anvil ping reviewers

2023-09-25 14:37 UTC, rasitozcan commented on packages/picasso-query-builder/src/AddGroupButton/AddGroupButton.tsx
> +  handleOnClick,
This is an underlying prop of the core react-querybuilder's  AddGroupButton , which we do not expose and I believe it is not necessary to change.

2023-09-25 14:50 UTC, rasitozcan commented on packages/picasso-query-builder/src/AddGroupButton/AddGroupButton.tsx
> +  handleOnClick,
I will resolve the rest of your similar comments, if you do not agree please comment.

2023-09-26 07:36 UTC, rasitozcan commented
@toptal-anvil ping reviewers

2023-09-26 08:02 UTC, TomasSlama reviewed
Good job, I only went manually through the code, I haven't tested it in the storybook yet, will do it in next iteration 🙇

2023-09-26 08:02 UTC, TomasSlama commented on packages/picasso-query-builder/src/utils/get-query-depth.ts
> +}
```suggestion
export const getQueryDepth = (arr: RuleGroupTypeAny): number => {
  if (Array.isArray(arr)) {
    return 1 + Math.max(...arr.map(getQueryDepth));
  }

  if (typeof arr === 'object') {
    return Math.max(...Object.values(arr).map(getQueryDepth));
  }

  return 0;
}
```

Maybe it is only me, but even this function is pretty small, it is hard to read.

2023-09-26 10:14 UTC, rasitozcan commented on packages/picasso-query-builder/package.json
> +    "@toptal/picasso": "^38.0.0",
Yes it makes sense, changed the version to `^>=38.0.0`

2023-09-26 10:20 UTC, rasitozcan commented on packages/picasso-query-builder/package.json
> +    "@material-ui/core": "4.12.4",
Yes, I am also not sure if we can rely on `@material-ui/core` to be a peer dependency. Other occurrences in the repo made me think that it was discussed and decided before. But I will update it to be a dependency for now.

2023-09-27 08:45 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +import { QueryBuilderDnD } from '@react-querybuilder/dnd'
Is there a specific way to conditionally import in the repo?

2023-09-27 08:50 UTC, rasitozcan commented on packages/picasso-query-builder/src/PicassoContext/PicassoContext.tsx
> +export const PicassoContext = getCompatContextProvider({
We can change it for sure,  but it is also not the QueryBuilderContext. When the lib was in the staff portal it made sense, but here I understand your concern. I renamed it to `ControlElementsContext`.

2023-09-27 08:52 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +        data-testid='ananas'
Removed it, totally forgotten in development.

2023-09-27 08:54 UTC, rasitozcan commented on packages/picasso-query-builder/src/utils/get-query-depth.ts
> +}
Yes i do not like the double ternary operator either.

2023-09-27 11:03 UTC, TomasSlama commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +import { QueryBuilderDnD } from '@react-querybuilder/dnd'
https://chat.openai.com/share/d697466b-3b9d-49aa-a099-e53601499c92 Can you access this?

2023-09-28 04:28 UTC, TomasSlama reviewed
left a few more small comments, tested it in the temploy, looks good! If there are any issues with my previous comment about dynamic importing the DND library, we can discuss, or we can wait for other reviewers, maybe they might have different idea 🤔

2023-09-28 04:28 UTC, TomasSlama commented on packages/picasso-query-builder/package.json
> +    "@toptal/picasso": "^>=38.0.0",
```suggestion
    "@toptal/picasso": "^>=38.0.0",
```
![image](https://github.com/toptal/picasso/assets/6830426/611d5967-802a-4735-a9b5-7dbe8465c9a0)
https://jubianchi.github.io/semver-check/#/constraint/^%3E%3D38.0.0

2023-09-28 04:28 UTC, TomasSlama commented on packages/picasso-query-builder/src/QueryBuilder/story/Callback.example.tsx
> +  type RuleGroupTypeAny,
should this be moved to the second line for consistency?

2023-09-28 13:28 UTC, rasitozcan commented on packages/picasso-query-builder/package.json
> +    "@toptal/picasso": "^>=38.0.0",
Updated as `"@toptal/picasso": "^38.0.0",`

2023-09-28 13:29 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/story/Callback.example.tsx
> +  type RuleGroupTypeAny,
Yes, I had some issues regarding dynamic importing, we can discuss later, I can ping about it.

2023-09-28 14:58 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-09-28 16:16 UTC, sashuk commented on packages/picasso-query-builder/src/constants.ts
> +const musicalInstruments: OptionGroup[] = [
Instruments are also defined in examples (https://github.com/toptal/picasso/pull/3872/files#diff-47a90dfbcc63fb195811530382fc1666768722ef9d8280d9eab7fa6c0a4bb9ecR15), is there a need to keep it in packages/picasso-query-builder/src/constants.ts (as it seems to be need for testing and demoing)?

2023-09-29 06:53 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-09-29 06:59 UTC, rasitozcan commented on packages/picasso-query-builder/src/constants.ts
> +const musicalInstruments: OptionGroup[] = [
Yep forgot to remove it when I moved contents to stories, only necessary constant left, and moved the `constants.ts` to utils folder.

2023-09-29 07:26 UTC, rasitozcan commented on packages/picasso-query-builder/src/AutoComplete/styles.ts
> +      width: '206px',
AutoComplete is a custom value editor built on top of picasso's tag selector. There must be some kind of edge case scenario since the with is set so specifically, can not recall what it is atm. But the rest of the fields are flexible to the container.

2023-09-29 07:39 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-09-29 08:04 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-09-29 08:49 UTC, dmaklygin commented on yarn.lock
> +  version "4.2.1"
oh :)

2023-09-29 09:06 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [onQueryChange, onQueryReset])
Given that `onQueryChange` is always called immediately after `onQueryReset`, and with a specific argument (`emptyQueryBuilderQuery`) that denotes a reset, I would consider it as redundant to have a separate `onQueryReset` prop for notifying about the reset action.
do you think, `onQueryReset` is still necessary here or redundant?

2023-09-29 10:17 UTC, sashuk commented on packages/picasso-query-builder/src/AutoComplete/styles.ts
> +      width: '206px',
Got it, thanks! Is the overall design of the Query Builder approved by Design Team?

2023-09-29 10:47 UTC, sashuk commented on packages/picasso-query-builder/README.md
> +- `PicassoContext` - context provider that is used as a wrapper to QB and provides
Should it be replaced with `ControlElementsContext`?

2023-09-29 10:48 UTC, sashuk commented on packages/picasso-query-builder/README.md
> +  Besides props QB uses some components that helps with customization and
If this is an internal information on how library works, then I'd move the description to the corresponding files

2023-09-29 10:49 UTC, sashuk commented on packages/picasso-query-builder/README.md
> +   By default is set to 3.
```suggestion
   By default it is set to 3.
```

2023-09-29 10:50 UTC, sashuk commented on packages/picasso-query-builder/README.md
> +   Props that are accepted by the QueryBuilder:
Wondering if there is a need to duplicate the list of properties here if we already have good description in `packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx` (this will be also used for Storybook)?

2023-09-29 10:55 UTC, sashuk commented on packages/picasso-query-builder/src/AutoComplete/AutoComplete.tsx
> +export const AutoComplete = ({
NIT: What do you think about keeping the name unified with Picasso Autocomplete? Otherwise it might cause confusion, I think

<img width="497" alt="Screenshot 2023-09-29 at 12 54 11" src="https://github.com/toptal/picasso/assets/1390758/a8852288-7a35-413c-ba09-1aef0150ba00">

2023-09-29 11:40 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +  const fieldValidatorMap = useMemo(() => {
I would specify type for this `fieldValidatorMap`.

2023-09-29 11:47 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }
I would not have this condition, I would instead use `queryBuilderValidator` returned by a `useQueryBuilderValidator` hook.
`customValidator` should be passed to `useQueryBuilderValidator` hook, so the hook should handle custom validation

2023-09-29 11:48 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }
this handler should be inside `useQueryBuilderValidator` hook

2023-09-29 11:51 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +  if (rules) {
I would have an explicit function that determines whether rule is a group or a single group, so it should return a proper type

2023-09-29 11:52 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +) => {
I would specify a return type for the function

2023-09-29 11:53 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +  }
to have a consistent types definition, I would use either `Record` or `{[key]}` here.
[Here](https://github.com/toptal/picasso/pull/3872/files#diff-43b04066c501b8cef005177fe793afaf1226f1475f27a99107ba0acb14faffcdR15), we use `Record`

2023-09-29 12:06 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +      .map(rule => validateQuery(rule as RuleGroupTypeAny, fieldValidatorMap))
I would not set a type here: `as RuleGroupTypeAny`. compiler should know exact type of rule here. So we do not need to do it

2023-09-29 12:06 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +    const result = rules
Please, define a type for `result`

2023-09-29 12:21 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +      onValidationResultChange?.(validationResult)
I would expect calling only a single callback. We could pass an object, like:
```
{
  isValid,
  validationResult
}
```

2023-09-29 12:22 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +): {
We should specify a return type for this function

2023-09-29 12:42 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +}
```suggestion
  const { field, id } = rule
  const fieldValidator = fieldValidatorMap[field]

  return {
    [id as string]: fieldValidator ? fieldValidator(rule) : true
  }
}
```
```

2023-09-29 12:48 UTC, dmaklygin commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.test.ts
> +  describe('when query is valid', () => {
actually, we should cover as much as possible cases:
1. When query is a group of rules
2. When a query is a single rule
3. When fields are empty
4. etc

2023-09-29 12:53 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    onValidationResultChange: setValidationErrors,
I think, having two callbacks that are called exactly at the same time, is quite odd. I would keep only a single callback.

2023-10-02 09:45 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/styles.ts
> +      ...queryBuilderGlobalStyles(),
I think we could call this function only once and use cached value here

2023-10-02 10:13 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }}
I would wrap it within `useCallback`.
Also, I would create a default `getDefaultOperators` function and use it by default, if `getOperators` prop is not passed

2023-10-02 10:17 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbDndHoverCopyBorderBottomColor = '#669933'
I would use specified global colors only, do not specify them separately here

2023-10-02 10:18 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbSmallSpacing = '1rem'
the same for spacing: we have a predefined set of global spacings. I would use it

2023-10-02 10:19 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  getOperators,
```suggestion
  getOperators = getDefaultOperators,
```

2023-10-02 10:21 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    if (onSubmit && query) {
is it possible to have a NULLED or undefined query here?

2023-10-02 10:23 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    setSubmitButtonClicked(true)
seem to be, we want to emulate form submission here:
so we try to disable `submit` button, but we also have to handle success and failed state of form submission and "restore" button's state, here, in this function.

2023-10-02 10:26 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  customValueEditor,
```suggestion
  customValueEditor = ValueEditor,
```

2023-10-02 10:26 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }}
```suggestion
            controlElements={{
              valueEditor,
            }}
```

2023-10-02 10:27 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  customValueEditor?: ComponentType<ValueEditorProps>
I would use a common word `valueEditor `

2023-10-02 10:38 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  resetOnFieldChange?: boolean
shouldn't we set a default value?

2023-10-02 10:46 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  totalCountLoading?: boolean
these two props are confusing: the first of is a number that is used by internal component to show the total number of results. 
I think it was created especially to show this number inside a QueryBuilder. 

isn't `totalCount` a maximum number of results in a response?

2023-10-02 10:47 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  )
I wouldn't keep logic inside a component, I would rather move it to a separate hook

2023-10-02 10:47 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [queryBuilderValid])
this also maybe be moved to a separate React hook

2023-10-02 10:54 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +                submitButtonClicked,
actually, the name of `submitButtonClicked` may confuse. What it is needed for?

2023-10-02 10:56 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +                submitButtonClicked,
react final form provides a good attribute `meta` which contains several information: valid, dirty state etc.
wdyt to reuse it and group relative attributes under `meta`?

2023-10-02 15:25 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/story/MaxDepth.example.tsx
> +export default Example
I think this example is redundant.

2023-10-02 15:26 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/story/Loading.example.tsx
> +export default Example
this example is all odd. Let's skip it

2023-10-02 15:34 UTC, dmaklygin commented on packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
> +  const toValue = (value as RangeValue).to ?? ''
I would use `isRangeValue` function here with specified return value

2023-10-02 15:42 UTC, dmaklygin commented on packages/picasso-query-builder/src/RangeInput/styles.ts
> +      alignSelf: '1 0 50px',
better to use `rems`

2023-10-02 15:43 UTC, dmaklygin commented on packages/picasso-query-builder/src/RemoveGroupButton/RemoveGroupButton.tsx
> +  }
I wouldn't pass context, instead, use this context via `useContext` or similar hook

2023-10-02 15:46 UTC, dmaklygin commented on packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
> +  handleOnClick,
I would use `onClick` here, we usually use `on` prefix for props

2023-10-02 15:49 UTC, dmaklygin commented on packages/picasso-query-builder/src/RunQueryButton/RunQueryButton.tsx
> +  totalCountLoading,
I would also take loading, totalCount and totalCountLoading from the context

2023-10-02 16:00 UTC, dmaklygin commented on packages/picasso-query-builder/src/Select/Select.tsx
> +  extends Omit<VersatileSelectorProps, 'path' | 'level' | 'schema'>,
these props ('path' | 'level' | 'schema') are defined in react-querybuilder, why do we need to omit them?

2023-10-02 16:09 UTC, dmaklygin commented on packages/picasso-query-builder/src/BooleanInput/BooleanInput.tsx
> +  <Select {...props} options={OPTIONS as unknown as SelectProps['options']} />
this is actually a bad practic, to set to unknown: we hide potential issue

2023-10-02 16:11 UTC, dmaklygin commented on packages/picasso-query-builder/src/ValueEditor/styles.ts
> +      flex: '1 0 150px',
use `rems` please

2023-10-02 16:28 UTC, dmaklygin requested changes
Left quite many comments.
To be honest, this PR is too big, I would ask you to split it on logic parts:
1. Core functionality
2. Custom components
3. Custom validation

2023-10-03 07:44 UTC, TomasSlama commented on packages/picasso-query-builder/package.json
> +    "@toptal/picasso": "^>=38.0.0",
sorry, now I can see, that I had a mistake in my first proposition 🙇  "@toptal/picasso": ">=38.0.0"

2023-10-03 07:48 UTC, TomasSlama commented on packages/picasso-query-builder/src/QueryBuilder/story/MaxDepth.example.tsx
> +export default Example
@dmaklygin these tests were my suggestion, we usually try to showcase the usage of all props of components. Do you think it is not needed?

2023-10-04 07:06 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbDndHoverCopyBorderBottomColor = '#669933'
Global styles are provided from core library, the styles we provide/override have global colors, isn't that enough? Do we still need to update global styles?

2023-10-04 07:07 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbSmallSpacing = '1rem'
When we agree to change global styles [here](https://github.com/toptal/picasso/pull/3872#discussion_r1345298006), I will make the change also. Not sure if it is necessary to update them atm.

2023-10-04 07:18 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    if (onSubmit && query) {
Yes it can be undefined

2023-10-04 09:22 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  customValueEditor,
Did not change the prop name for now but provided the default value as suggested. May change the prop name in another ticket since it introduces a breaking change.

2023-10-04 09:26 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }}
Since I[ did not change the prop name](https://github.com/toptal/picasso/pull/3872#discussion_r1345486100), finalized it as:
`controlElements={{
              valueEditor: customValueEditor,
            }}`

2023-10-05 07:28 UTC, rasitozcan commented on packages/picasso-query-builder/src/Select/Select.tsx
> +  extends Omit<VersatileSelectorProps, 'path' | 'level' | 'schema'>,
If we ever allowed a fallback option (like picasso is not availble as a dependency), we would return default ValueSelector from 'react-querybuilder',  and it would need path, schema and level props, but we do not render conditionally, we always return picasso Select.

2023-10-05 07:40 UTC, rasitozcan commented on packages/picasso-query-builder/src/ValueEditor/styles.ts
> +      flex: '1 0 150px',
Updated as `flex: '1 0 9.25rem'`

2023-10-05 07:41 UTC, rasitozcan commented on packages/picasso-query-builder/src/Select/styles.ts
> +      flex: '1 0 100px',
Updated as `flex: '1 0 6.25rem'`

2023-10-05 07:48 UTC, rasitozcan commented on packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
> +  handleOnClick,
This prop is provided directly from `react-querybuilder` to control elements

2023-10-05 07:50 UTC, rasitozcan commented on packages/picasso-query-builder/src/RemoveGroupButton/RemoveGroupButton.tsx
> +  }
This prop is provided by `react-querybuilder` to every component. [docs](https://react-querybuilder.js.org/docs/components/querybuilder#context)

2023-10-05 07:51 UTC, rasitozcan commented on packages/picasso-query-builder/src/RangeInput/styles.ts
> +      alignSelf: '1 0 50px',
Updated as ` alignSelf: '1 0 3rem'`

2023-10-05 09:48 UTC, rasitozcan commented on packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
> +  const toValue = (value as RangeValue).to ?? ''
Not sure this is necessary, we know the values are RangeValue but we do not want to provide undefined values as a result.

2023-10-05 10:04 UTC, rasitozcan commented on packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
> +}
Moved it to types, makes more sense for sure.

2023-10-05 12:30 UTC, rasitozcan commented on packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
> +  handleOnClick,
@TomasSlama @OleksandrNechai ping

2023-10-05 12:32 UTC, TomasSlama commented on packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
> +  handleOnClick,
I'm not sure why I'm pinged in this comment ;-)

2023-10-06 06:32 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  resetOnFieldChange?: boolean
set to true

2023-10-06 06:34 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  totalCountLoading?: boolean
Yes it is intended to show total number of results in a response. Would you suggest a prop name change or else?

2023-10-06 07:24 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  loading?: boolean
Async work is done out of library if required and we can get loading state  as a prop and intentionally done this way, advice to improve?

2023-10-06 07:58 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [queryBuilderValid])
Will  move it in next ticket

2023-10-06 07:59 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/story/Loading.example.tsx
> +export default Example
It was requested in a prev comment to list all props as an example

2023-10-06 08:12 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  getOperators,
made some changes but did not provide a default value

2023-10-06 09:07 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    onValidationResultChange: setValidationErrors,
will update in the upcoming ticket

2023-10-06 09:10 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  customValueEditor?: ComponentType<ValueEditorProps>
May be changed later right?

2023-10-06 09:22 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +                submitButtonClicked,
Sure but need to make a bit of research first

2023-10-06 09:35 UTC, rasitozcan commented on packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
> +  handleOnClick,
@dmaklygin asked me to ping, he will probably discuss it with you :)

2023-10-06 09:42 UTC, rasitozcan commented on packages/picasso-query-builder/src/BooleanInput/BooleanInput.tsx
> +  <Select {...props} options={OPTIONS as unknown as SelectProps['options']} />
manually converted value from string to boolean.

2023-10-06 09:43 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  )
done

2023-10-06 14:23 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }
handled in the hook

2023-10-06 14:27 UTC, rasitozcan commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.ts
> +      onValidationResultChange?.(validationResult)
made similar change, instead of running callbacks, now hook returns both validatior and validationResult  like;
`{validator, valitaionResult}`

2023-10-09 08:10 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  loading?: boolean
if we expect a async work. the Callback should be async and return promise. So, we will not and catch the following states:
1. Submitting/Requesting event (we can set loading to true)
2. Success state (we can set loading to false)
3. Failed state (we can also set loading to false)

2023-10-09 08:14 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +    onValidationResultChange: setValidationErrors,
Okay, if it's intentional to be done in the next ticket. Let's skip it right now

2023-10-09 08:16 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }
Seem to be, it's not changed

2023-10-09 08:18 UTC, dmaklygin commented on packages/picasso-query-builder/src/OperatorSelector/styles.ts
> +      flexBasis: '100px',
Please, search for all occurrences of PX dimensions and replace them with REM

2023-10-09 08:21 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  resetOnFieldChange?: boolean
sorry, but I couldn't see changes. Have you pushed them?

2023-10-09 08:21 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +                submitButtonClicked,
@TomasSlama wdyt to have such names?
if they are internal, we could keep them as is.

2023-10-10 07:06 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/story/MaxDepth.example.tsx
> +export default Example
I think, such extra cases overflow the storybook.

2023-10-10 07:09 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }}
it's still old. have you pushed updates?

2023-10-10 13:25 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +            }
forgot, pushed it.

2023-10-11 06:25 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [onQueryChange, onQueryReset])
`onQueryReset` explicitly presents that reset button clicked, but it also triggers change, this does not seem like redundant.

2023-10-11 06:32 UTC, rasitozcan commented on packages/picasso-query-builder/README.md
> +  Besides props QB uses some components that helps with customization and
Yes this is some internal information, removed it.

2023-10-11 08:39 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [onQueryChange, onQueryReset])
Decided to keep `onQueryReset`

2023-10-11 16:16 UTC, dmaklygin commented on packages/picasso-query-builder/src/AutoComplete/styles.ts
> +      width: '206px',
I also think it should be in REMs, and 206 looks strange, since we use numbers divided by 5, usually

2023-10-11 16:22 UTC, dmaklygin commented on packages/picasso-query-builder/src/FieldSelector/FieldSelector.tsx
> +        resetSubmitButtonClicked()
I still think, `resetSubmitButtonClicked` should not be here, we cannot handle all events, better to have a single point to manipulate submitButton states

2023-10-11 16:28 UTC, dmaklygin commented on packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
> +  })
hope, it's not a heavy operation, we don't need to wrap it with useMemo

2023-10-11 16:31 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  totalCountLoading?: boolean
I actually, wanted to allow customize `submit button`. So, users will be able to customize it by adding total count or other customization.
I would not provide those props, but just provide an Storybook example how to customize `submitButton`

2023-10-11 16:32 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  const removeGroup = useCallback(
we usually use `handle` as a prefix for handlers

2023-10-11 16:34 UTC, dmaklygin commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +              } as QueryBuilderContext
if we have a separate React hook, which specifies and returns all these functions, we will be able to squash Component size, and split view and logic, which will make this code more readable. WDYT?

2023-10-11 16:40 UTC, dmaklygin commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
> +    )
wdyt, can we wrap it with useMemo?

2023-10-11 16:41 UTC, dmaklygin commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
> +          )
seems to be this is a second `filter` iteration? I hope, we can move this filter [upstairs](https://github.com/toptal/picasso/pull/3872/files#diff-fc180fd3bf5f71732d98b279103dc1eb124a75eaafe47a6fe6214410eaa51a0cR15)

2023-10-11 16:43 UTC, dmaklygin commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
> +              {reasons?.map((reason, index) => (
this is a third loop.
I would rather use a flat map of `reasons` in the component, returned by a single loop.
I think we can do it:
```
Object.keys(validationResult)
    .reduce(...)
```

2023-10-11 16:44 UTC, dmaklygin commented on packages/picasso-query-builder/src/ValueEditor/ValueEditor.tsx
> +          handleOnChange={handleOnChange}
some components use `handleOnChange`, some of them `onChange`. I would have a consistent name for handlers

2023-10-11 16:50 UTC, dmaklygin reviewed
Good job. Left some comments.
The only doubts I have about `totalCount`'s props. I think, it's not necessary to keep them

2023-10-12 06:39 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbDndHoverCopyBorderBottomColor = '#669933'
Replaced static colors with the picasso palatte .

2023-10-12 06:50 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/query-builder-global-styles.ts
> +const rqbSmallSpacing = '1rem'
Made the spacing changes also, is that ok to use spacing values like below:
`const rqbSpacing = `${SPACING_6}rem``

2023-10-12 07:15 UTC, rasitozcan commented on packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
> +  })
You did not mean the `validateValueEditor` right?

2023-10-13 07:07 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  totalCountLoading?: boolean
Currently it is not customizable, form controls to the query builder are added as a custom element already. But we do not allow overriding/customizing existing controls atm. I will create a ticket for that feature which we can create a separate module for form controls and allow customization.

2023-10-13 07:12 UTC, rasitozcan commented on packages/picasso-query-builder/src/utils/use-query-builder-validator.test.ts
> +  describe('when query is valid', () => {
Added more test cases, will increase them with the upcoming ticket.

2023-10-13 07:29 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  totalCountLoading?: boolean
https://toptal-core.atlassian.net/browse/CPT-1313

2023-10-13 08:13 UTC, rasitozcan commented on packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
> +              {reasons?.map((reason, index) => (
I will create another ticket for this, since we had some issues related to this before, I would like this  to be tested extensively and not miss anything.

2023-10-13 09:00 UTC, rasitozcan commented on packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
> +  const toValue = (value as RangeValue).to ?? ''
I think i did not get it right, it would result sth like this; 
`const fromValue = (isRange(value) && value.from) ? value.from : ''
  const toValue = (isRange(value) && value.to) ? value.from : ''`
And it increases complexity, is that what you suggested?

2023-10-16 08:11 UTC, dmaklygin approved these changes

2023-10-16 08:18 UTC, TomasSlama approved these changes
great job! Sorry for keeping you waiting for so long

2023-10-16 14:21 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-10-19 10:20 UTC, toptalwadiibasmi approved these changes
Looks good to me!

2023-10-19 18:30 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-10-19 21:22 UTC, rasitozcan commented
@toptal-bot run package:alpha-release

2023-10-23 08:19 UTC, rasitozcan commented on packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
> +  }, [queryBuilderValid])
Needed to revert this, creating a ticket for this also to be resolved later.

2023-10-24 12:01 UTC, merged