fix(picasso-charts): fix BarChart for cases with 0 values
toptal/picasso pull request #3926
Opened 2023-10-20 10:00 UTC by ievgrafov

[SDE-1274]

### Description

Hi guys! We in Service Delivery are using `BarChart` to render spend chart and add label to all columns which are related to periods with breaks.

In some cases it may happen that we don't have spend data for given period but still want to show breaks icon. Currently it looks incorrect (see the original ticket). The reason for this is inability of BarChart to determine correct boundaries for value axis. In this PR I introduce a property that allows controlling boundaries of the axis manually.

Please let me know if the change is incorrect or there's a better way to achieve it. My goal here is to fix the bug so I'm pretty flexible with choosing the way to do it.

Update:
following comments to the PR I changed the implementation. Now instead of adding a prop to customize boundaries we just set default ones in case of too few ticks (0 or 1).

### How to test

- [Temploy](https://picasso.toptal.net/sde-1274-allow-passing-max-value-to-bar-chart)
- check example [here](https://picasso.toptal.net/sde-1274-allow-passing-max-value-to-bar-chart/?path=/story/picasso-charts-barchart--barchart#adjust-value-axis-boundaries)

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![image](https://github.com/toptal/picasso/assets/2178320/571cba0a-a826-47f9-b9c6-e8f61afc6bf3) | ![image](https://github.com/toptal/picasso/assets/2178320/f66fffaf-ecfd-4c4d-ae41-f6ae2102153e) |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [n/a] codemod is created and showcased in the changeset
- [n/a] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[SDE-1274]: https://toptal-core.atlassian.net/browse/SDE-1274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-23 10:38 UTC, TomasSlama requested changes

2023-10-23 10:38 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/BarChart.tsx
I don't like adding new property for this, I looked into recharts how this issue should be handled. It seems for this case we should use `domain` property of `YAxis`.

This could be the change on line 180
```
const defaultDomain = [ticks[0], ticks[ticks.length - 1]]
  const valueAxisProps = {
    width: Y_AXIS_WIDTH,
    ticks: ticks,
    domain: ticks.length === 0 ? [0, 'dataMax + 10'] : defaultDomain,
    tickFormatter: valueAxisTickFormatter,
  }
```

WDYT? we would not need to add new property, we would just fix it for everyone

2023-10-23 10:38 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/story/CustomValueAxisBoundaries.example.tsx
> +  Amazon: { color: palette.purple.main, label: 'E' },
```suggestion
  Apple: { color: palette.purple.main, label: 'E' },
```

2023-10-23 10:38 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/story/index.jsx
> +    takeScreenshot: false,
If we decide to not add new propety we will not need this example, but I would treat it as a bug of BarChart and we should cover this case with visual test in cypress. Look for `BarChart.spec.ts`

2023-10-23 10:52 UTC, ievgrafov commented on packages/picasso-charts/src/BarChart/BarChart.tsx
I saw an answer on SO that suggested to fix it with domain, yeah. But since we don't have something existing for this in `BarChart` props, I thought that would be better to add more flexible solution while we're anyway touching this part. But if you think it would better to just fix it here without introducing new prop, sure, I'll update the PR now, it's even simpler :+1:

2023-10-23 10:54 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/BarChart.tsx
👍, I would agree to add flexibility, but it looks like a bug to me, I don't think that the current implementation is usable anywhere 🤔, so we would just increase complexity for no reason

2023-10-23 13:47 UTC, ievgrafov commented on packages/picasso-charts/src/BarChart/BarChart.tsx
@TomasSlama I made the changes you requested, could you please take another look?

2023-10-23 13:52 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> +    ticks.length >= 2 ? ticks[ticks.length - 1] : BOTTOM_DOMAIN + 10,
```suggestion
    ticks.length >= 2 ? ticks[ticks.length - 1] : 'dataMax + 10',
```
wdyt?

2023-10-24 03:57 UTC, ievgrafov commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> +    ticks.length >= 2 ? ticks[ticks.length - 1] : BOTTOM_DOMAIN + 10,
typechecks fail with it https://github.com/toptal/picasso/actions/runs/6616543696/job/17971041119?pr=3926, so I changed to calculating same value here and passing it as number

2023-10-24 04:19 UTC, ievgrafov commented on packages/picasso-charts/src/BarChart/BarChart.tsx
> +    ticks.length >= 2 ? ticks[ticks.length - 1] : BOTTOM_DOMAIN + 10,
hmm, looking at [screenshot](https://happo.io/a/675/p/848/compare/7d934fa29545d40b99d4600596d5a32b38fa6902/ab47d3c95c88c2444ad40bf767bae2f37bf75930?t=added) in happo I'd say it doesn't fix the issue :thinking: . This one is for this commit https://github.com/toptal/picasso/pull/3926/commits/ab47d3c95c88c2444ad40bf767bae2f37bf75930 . I also checked code of `findTopDomain` and it returns `Math.max(calculatedMax, 10)` so I believe it should already handle such problem :confused: I'll try to investigate further, looks weird so far

2023-10-24 04:34 UTC, ievgrafov commented on packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts
> +  return Math.max(topDomain || 0, 10)
`topDomain` can be NaN because of line 43: when `roundedMaxValue` is 0, `maxValue / roundedMaxValue` is NaN. And this NaN then goes all the way down to value axis domain :man_shrugging: So I guess best is to catch it here

2023-10-24 07:13 UTC, ievgrafov commented
@toptal-anvil ping reviewers

2023-10-24 07:44 UTC, TomasSlama approved these changes

2023-10-24 07:44 UTC, TomasSlama commented on packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts
> +  return Math.max(topDomain || 0, 10)
nice!, great solution

2023-10-24 07:44 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2023-10-24 08:01 UTC, sashuk commented on cypress/component/BarChart.spec.tsx
> +  it('renders custom chart with customized indicators when values are 0s', () => {
NIT: Can you please move condition to a separate `describe` block (https://toptal-core.atlassian.net/wiki/spaces/ENG/pages/1120830304/Frontend+Testing+-+Unit+testing#Describe)?

2023-10-24 08:02 UTC, sashuk approved these changes
Left a minor comment, code looks good!

2023-10-24 09:04 UTC, ievgrafov commented on cypress/component/BarChart.spec.tsx
> +  it('renders custom chart with customized indicators when values are 0s', () => {
thanks, I updated it now

2023-10-24 09:04 UTC, ievgrafov commented
@toptal-anvil ping reviewers

2023-10-24 09:08 UTC, sashuk approved these changes

2023-10-24 09:55 UTC, ievgrafov commented
@sashuk @TomasSlama folks, what should I do to get this one merged? There's failing check in happo but it looks unrelated to the PR itself

2023-10-24 10:00 UTC, merged