[FX-4598] Migrate Notification to TailwindCSS
toptal/picasso pull request #4299
Opened 2024-05-13 08:10 UTC by AdrianContiu

[FX-4598]

### Description

This PR changes the Notification component to use the Snackbar from the MUI Base UI and applies styles using TailwindCSS.

**_Note:_** - There is also a change of the role attribute from `alert` to `presentation`. This was done due to an issue with the screen reader in Firefox. More details can be found [here](https://github.com/mui/material-ui/issues/29080). It will also be included in the changeset file.

### How to test

- Temploy
- Check the [production](https://picasso.toptal.net/?path=/story/components-notification--notification) and compare it with the temploy

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| ![Picasso - Notification - Google Chrome 2024-05-13 at 11 04 38 AM](https://github.com/toptal/picasso/assets/100089376/9a74e93d-77d6-44a9-a33b-f15cab46f6e4) | Insert screenshots or screen recordings |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- ~Annotate all `props` in component with documentation~
- ~Create `examples` for component~
- ~Ensure that deployed demo has expected results and good examples~
- ~Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).~
- [x] Self reviewed
- ~Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)~

**Breaking change**

- ~codemod is created and showcased in the changeset~
- ~test alpha package of Picasso in StaffPortal~

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2024-05-14 09:48 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/Notification.tsx
> +    event: Event | SyntheticEvent<HTMLButtonElement, Event> | null
The `onClose` event type was changed in the MUI/Base [Snackbar API](https://mui.com/base-ui/react-snackbar/components-api/#snackbar-prop-onClose)

2024-05-14 09:48 UTC, AdrianContiu commented on cypress/component/Form.spec.tsx
> +    cy.getByRole('presentation')
The `role` attribute changed from `alert` to `presentation` due to an issue with the screen readers in Firefox ([https://github.com/mui/material-ui/issues/29080](related issue))

2024-05-14 09:49 UTC, TomasSlama commented on packages/base/Notification/src/Notification/Notification.tsx
>          )}
```suggestion
        className={twJoin(
          'min-w-[1.5em] mr-[1em] basis-[1.5em]',
          variant === 'yellow' ? 'h-[1em] min-w-[1em] mt-[2px] basis-0' : 'h-[1.5em]'
        )}
```

Here we are using `twMerge` only for the `h-*` className, I think we can just have simple condition instead of using twMerge.

2024-05-14 09:49 UTC, TomasSlama commented on packages/base/Notification/src/Notification/Notification.tsx
> +    icon={<CloseMinor16 className='fill-graphite-700' />}
we will have conflicts here when rebasing with master. This button was already migrated in the Button ticket, could you revert the changes so we don't have the conflict in the feature branch? 🙇

2024-05-14 14:19 UTC, OleksandrNechai requested changes
I am concerned with twMerge usage, and `!`. When those are fixed or proben needed, I am good to go!

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/Notification.tsx
> +      className='flex w-full my-0 mx-auto p-0 max-w-[75em] min-w-[0]'
```suggestion
      className='flex w-full my-0 mx-auto p-0 max-w-[75em] min-w-0'
```

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/Notification.tsx
>          )}
twMerge is not fee, please read closely: https://github.com/dcastil/tailwind-merge/blob/v2.3.0/docs/when-and-how-to-use-it.md

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/Notification.tsx
>            variant === 'yellow' ? '!mt-0' : '!mt-[1px]'
why `!`?

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/Notification.tsx
> +    const variantClasses: Classes = {
```suggestion
    const classByVariant: Classes = {
```

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/Notification.tsx
> +        className={twMerge(
why `twMerge`?

2024-05-14 14:19 UTC, OleksandrNechai commented on packages/base/Notification/src/Notification/utils/index.ts
> +export const capitalizeFirst = (text: string) =>
This sounds to be generic enough for top level utils of picasso

2024-05-14 14:53 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/Notification.tsx
>          )}
Yes, I'm aware that `twMerge` consumes resources and should only be used in specific cases, but I haven't seen the refactoring so that I can apply `twJoin`. I have updated the className, thanks both for your suggestions.

2024-05-14 15:49 UTC, TomasSlama commented on packages/base/Notification/src/Notification/Notification.tsx
>            variant === 'yellow' ? '!mt-0' : '!mt-[1px]'
it is needed till https://toptal-core.atlassian.net/browse/FX-5185 will be done

2024-05-15 08:35 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/Notification.tsx
> +        className={twMerge(
I used twMerge because of the `className` prop so that it can override the previous styles in case of conflicting classes. I think this is how it was before.

2024-05-15 09:06 UTC, dmaklygin commented on packages/base/Notification/src/Notification/Notification.tsx
> +    event: Event | SyntheticEvent<HTMLButtonElement, Event> | null
Could you please clarify how it's possible to have `event` argument being in type `Event`?
what kind of cases it may be?

2024-05-15 09:13 UTC, dmaklygin commented on packages/base/Notification/src/use-notification/use-notifications.tsx
> +          variant === 'white' && 'w-[27.5em]'
potential collission between `w-[20em]` and `w-[27.5em]`: either reuse twMerge or do the following:

```
'max-w-full',
variant === 'white' ? 'w-[27.5em]' : 'w-[20em]'
```

2024-05-15 10:57 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/utils/index.ts
> +export const capitalizeFirst = (text: string) =>
I replaced the `capitalize` function from `material-ui` in `Picasso/packages/base/Utils`.

2024-05-15 11:57 UTC, AdrianContiu commented on packages/base/Notification/src/use-notification/use-notifications.tsx
> +          variant === 'white' && 'w-[27.5em]'
I decided to refactor as you suggested because `twMerge` consumes resources.

2024-05-16 07:24 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/Notification.tsx
> +    event: Event | SyntheticEvent<HTMLButtonElement, Event> | null
This is the [onClose](https://mui.com/base-ui/react-snackbar/components-api/#snackbar-prop-onClose) signature to include native browser events as well. If I'm removing `Event`, Snackbar throws a type error. I could only make the type more specific like 'Event | React.SyntheticEvent<HTMLButtonElement>'.

2024-05-16 08:11 UTC, OleksandrNechai approved these changes

2024-05-16 08:32 UTC, TomasSlama approved these changes

2024-05-16 08:49 UTC, dmaklygin commented on packages/base/Notification/src/Notification/Notification.tsx
> +    event: Event | SyntheticEvent<HTMLButtonElement, Event> | null
Yeah, I know, it's defined in Mui/Base, I'm mostly wondered why it's like that?
What kind of cases it may be when `event` is passed as  `Event` type?

2024-05-16 09:31 UTC, AdrianContiu commented on packages/base/Notification/src/Notification/Notification.tsx
> +    event: Event | SyntheticEvent<HTMLButtonElement, Event> | null
I guess it is added so that it can provide access to methods of generic browser events like mouseover/mouseclose, keydown/keyup, focus, blur, etc.

2024-05-16 10:58 UTC, dmaklygin approved these changes

2024-05-16 11:01 UTC, merged