[FX-5055] Remove Typography overrides
toptal/picasso pull request #4368
Opened 2024-06-18 03:43 UTC by augustobmoura

[FX-5055]

### Description

Removing leftover Typography overrides

### How to test

- Temploy
- Happo and temploy

### Screenshots

No scrrenshots

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [ ] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [ ] Self reviewed
- [ ] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [ ] codemod is created and showcased in the changeset
- [ ] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2024-06-18 08:38 UTC, TomasSlama commented on packages/base/Typography/src/Typography/Typography.tsx
> +    xlarge: '', // Body xlarge size is not defined on BASE
@augustobmoura I believe this was added for backward compatibilities. Even though it should not work like this, Client Portal was using it this way. @mkrl please confirm 🙇

2024-06-18 16:22 UTC, augustobmoura commented on packages/base/Typography/src/Typography/Typography.tsx
> +    xlarge: '', // Body xlarge size is not defined on BASE
I took a look at the previous version, and couldn't find any [styles](https://github.com/toptal/picasso/blob/4889e37bc57ee8a05128a343afe6fcf5d753358c/packages/base/Typography/src/Typography/styles.ts) for `body` `xlarge`, this is why I reverted it

2024-06-21 08:24 UTC, TomasSlama commented on packages/base/Typography/src/Typography/Typography.tsx
> +    xlarge: '', // Body xlarge size is not defined on BASE
I believe this is how it worked with MUI. When someone used bad input (it was not enforced), it was fallbacking to this.

2024-06-21 10:19 UTC, mkrl commented on packages/base/Typography/src/Typography/Typography.tsx
> +    xlarge: '', // Body xlarge size is not defined on BASE
The reason for it was definitely visual tests failing is client-portal. You can see `body xlarge` used [here](https://github.com/toptal/client-portal/blob/926d50d7e32ed2ee9f17067e6721edd8d9f62d65/hosts/client-portal/containers/pages/Interview/components/PreviousInterviews/components/InterviewInsightsDrawer/components/VideoBox/VideoBox.tsx#L49) and it is expected that this size is smaller. This is not the only place it is used in. I am not sure where exactly the styles for the size wer originally coming from, but I would strongly advise against changing this.

While it is semantically wrong, we should follow a breaking change process if we what to drastically change how a text of a certain size looks like

2024-06-21 14:26 UTC, augustobmoura commented
@toptal-anvil ping reviewers

2024-06-21 14:27 UTC, augustobmoura commented
@toptal-anvil ping reviewers

2024-06-24 01:21 UTC, augustobmoura commented on packages/base/Typography/src/Typography/Typography.tsx
> +    xlarge: '', // Body xlarge size is not defined on BASE
Ok, I reverted the change and add a comment explaining it

2024-06-24 02:25 UTC, augustobmoura commented
test

2024-06-24 02:28 UTC, augustobmoura commented
test

2024-06-24 09:25 UTC, TomasSlama approved these changes

2024-06-24 11:55 UTC, mkrl requested changes

2024-06-24 11:55 UTC, mkrl commented on packages/picasso-provider/src/Picasso/PicassoProvider.tsx
> -      },
I think we might also need a package changeset here.
Without a changeset this will not be published since it does not depend on any of the changed packages.

2024-06-25 03:32 UTC, augustobmoura commented on packages/picasso-provider/src/Picasso/PicassoProvider.tsx
> -      },
Added :+1:

2024-06-25 03:33 UTC, augustobmoura commented
@toptal-anvil ping reviewers

2024-06-25 11:37 UTC, mkrl approved these changes
Looks good, thank you!

2024-06-25 13:09 UTC, merged