[FX-5530] Migrate EnvironmentBanner to Tailwind
toptal/picasso pull request #4430
Opened 2024-07-31 11:15 UTC by sashuk

[FX-5530]

### Description

This pull request migrates https://picasso.toptal.net/?path=/story/components-environmentbanner--environmentbanner to Tailwind.

### How to test

- Temploy
- Compare with `master`, use https://chromewebstore.google.com/detail/synchronize-tab-scrolling/phceoocamipnafpgnchbfhkdlbleeafc for easier tab scrolling

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [N/A] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [N/A] Annotate all `props` in component with documentation
- [N/A] Create `examples` for component
- [N/A] Ensure that deployed demo has expected results and good examples
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2024-07-31 11:16 UTC, sashuk commented on .changeset/dirty-glasses-cover.md
> +- breaking change: the `environment` property now allows only values that are actually supported by component (`production` and `test` values will trigger TypeScript error)
I found it strange that component allows more enums that it in fact supports, so the API was changed

2024-07-31 11:17 UTC, sashuk commented on packages/base/EnvironmentBanner/package.json
> +    "@toptal/picasso-tailwind": ">=2.8.0",
Depend on "next" minor version of `@toptal/picasso-tailwind` to have access to introduced snackbar `zIndex` value

2024-07-31 11:24 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +            'px-2 py-1',
Confirmed in https://toptal-core.slack.com/archives/CCC3GP6CC/p1722424510310499?thread_ts=1722359068.060219&cid=CCC3GP6CC

2024-07-31 11:42 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-07-31 15:47 UTC, mkrl commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +      (environment as ExtendedEnvironmentType) || configEnvironment
I think this type cast is irrelevant. Moreover, `configEnvironment` will never be accessed (`environment` from props is always defined as it is a required prop).

I think we might have 2 options here:

1. Make `environment` prop optional and remove `as ExtendedEnvironmentType` cast. This will allow to render this with no prop and get env value from config
2. Remove all code related to reading app config entirely and have the prop required (as it is now). Trying to read app config is dead code in this case because the prop is required and guaranteed to be present.

2024-07-31 15:48 UTC, mkrl requested changes

2024-07-31 15:48 UTC, mkrl commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +      (environment as ExtendedEnvironmentType) || configEnvironment
I think this type cast is irrelevant. Moreover, `configEnvironment` will never be accessed (`environment` from props is always defined as it is a required prop).

I think we might have 2 options here:

1. Make `environment` prop optional and remove `as ExtendedEnvironmentType` cast. This will allow to render this with no prop and get env value from config
2. Remove all code related to reading app config entirely and have the prop required (as it is now). Trying to read app config is dead code in this case because the prop is required and guaranteed to be present.

2024-07-31 16:19 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +      (environment as ExtendedEnvironmentType) || configEnvironment
@mkrl Thank you for noticing! I think it is safe to go with the first option, as `environment` is already mandatory – the cleanup was done in https://github.com/toptal/picasso/pull/4430/commits/ab11c3368828c84246aaaa2d8877e4789714ce98

2024-07-31 16:20 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-07-31 16:28 UTC, mkrl commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +      (environment as ExtendedEnvironmentType) || configEnvironment
This works, thank you :+1: 
The only downside as I see it is that most our products use some form of `<EnvironmentBanner environment={app.env}/>`. After the new version is released safeguards to not render this component in a particular env will be required on the consumer side, which is more work.

Do you think that maybe keeping the prop value the same as on master is worth it? Just having some second thoughts :smile:

2024-07-31 16:46 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +      (environment as ExtendedEnvironmentType) || configEnvironment
@mkrl Thank you!

Yeah, I am hesitant on this too – from one side, this does not make sense to allow something and then return null for some of the values, and on another side this a breaking change that we are trying to avoid.

Taking into account your concerns, the API is reverted to the original one in https://github.com/toptal/picasso/pull/4430/commits/aa6ab9fcc262827bbc3609bf3f909f63a1f35013

2024-07-31 21:04 UTC, mkrl approved these changes
Thanks for addressing all the feedback! Looks good, tested on temploy.

2024-08-01 09:17 UTC, AdrianContiu commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +          'pointer-events-none'
Before `line-height` was 1.5em but for `text-xxs` is by default 1.125rem. Maybe it should be changed to `text-xxs[1.5em]`.

2024-08-01 10:21 UTC, AdrianContiu approved these changes
I left some small comments. Please take a look before merging and decide their relevance.

2024-08-01 10:21 UTC, AdrianContiu commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +            'cursor-pointer',
For some reason `cursor-pointer` doesn't have any effect.

2024-08-01 10:21 UTC, AdrianContiu commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +const getBorderTopClasses = (environment: SupportedEnvironments) =>
I was wondering if a function is needed here and below. Besides the color, the rest of the border properties are the same, so maybe the constant is enough.

2024-08-01 11:41 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +          'pointer-events-none'
@AdrianContiu Thanks for noticing, fixed!

2024-08-01 11:41 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +            'cursor-pointer',
@AdrianContiu This was due to `pointer-events-none` applied in parent component, fixed, thank you!

2024-08-01 11:41 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +const getBorderTopClasses = (environment: SupportedEnvironments) =>
@AdrianContiu Deleted the function, thanks!

2024-08-01 11:42 UTC, sashuk commented on packages/base/EnvironmentBanner/src/EnvironmentBanner/EnvironmentBanner.tsx
> +            'pointer-events-[initial]'
@AdrianContiu Fixed (used `pointer-events-auto` due to similar functionality) as part of https://github.com/toptal/picasso/pull/4430#discussion_r1700000181, thank you!

2024-08-01 13:28 UTC, TomasSlama requested changes

2024-08-01 13:28 UTC, TomasSlama commented on .changeset/dirty-glasses-cover.md
> +'@toptal/picasso-environment-banner': major
```suggestion
'@toptal/picasso-environment-banner': major
'@toptal/picasso': major
```
This also needs to be major for Picasso main package as without updated tailwind config it will not work when somobdy is using banner from the main package

2024-08-01 13:56 UTC, TomasSlama commented on .changeset/dirty-glasses-cover.md
> +'@toptal/picasso-environment-banner': major
so we need to update the peer dependency of picasso-tailwind to future version also on `@toptal/picasso` level

2024-08-01 14:14 UTC, sashuk commented on .changeset/dirty-glasses-cover.md
> +'@toptal/picasso-environment-banner': major
@TomasSlama Added, thanks!

2024-08-01 14:15 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-08-01 14:38 UTC, TomasSlama approved these changes

2024-08-01 18:15 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-08-01 18:18 UTC, sashuk commented
@toptal-bot run package:alpha-release

2024-08-01 18:53 UTC, merged