Update changeset guidelines
toptal/picasso pull request #4510
Opened 2024-08-27 07:38 UTC by AdrianContiu

[FX-NNNN]

### Description

Update changeset guidelines to include a reference to `'@toptal/picasso': patch` for major bumps.

### How to test

- Temploy
- FIXME: Add the steps describing how to verify your changes

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2024-08-27 07:42 UTC, AdrianContiu commented
@toptal-anvil ping reviewers

2024-08-27 07:48 UTC, dmaklygin commented on docs/contribution/changeset-guidelines.md
> +'@toptal/picasso': patch
I'm afraid this comment will always be visible

2024-08-27 08:26 UTC, AdrianContiu commented on docs/contribution/changeset-guidelines.md
> +'@toptal/picasso': patch
That's correct! :)
I've changed it, Thx!

2024-08-27 09:10 UTC, sashuk commented on docs/contribution/changeset-guidelines.md
> +'@toptal/picasso': patch
If the https://github.com/toptal/picasso/blob/master/packages/topkit-analytics-charts/package.json is bumped, we do not need to bump `@toptal/picasso` as it does not depend on it. Should there be some kind of specification that `@toptal/picasso` should be bumped not in 100% if cases (as `@toptal/picasso` does not depend on _all_ packages in https://github.com/toptal/picasso)

2024-09-03 11:13 UTC, TomasSlama commented on docs/contribution/changeset-guidelines.md
> +'@toptal/picasso': patch
Let's also mention, that when we add the patch for Picasso, we should also include the heading for giving context in the Picasso release notes

2024-09-05 12:20 UTC, AdrianContiu commented
@toptal-anvil ping reviewers

2024-09-05 12:37 UTC, dmaklygin commented on docs/contribution/changeset-guidelines.md
> +//if the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
I didn't get this: `packages that depend on picasso` — maybe we are talking about packages that Picasso depends on?

2024-09-05 12:49 UTC, AdrianContiu commented on docs/contribution/changeset-guidelines.md
> +//if the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
You are right! I will reformulate accordingly! Thx!

2024-09-06 09:59 UTC, TomasSlama commented on docs/contribution/changeset-guidelines.md
> +//if the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
When introducing changes to Picasso, it's important to distinguish between updates that require user action and those that don't.

For example, in the case of a Tailwind migration, since Picasso already includes a peer dependency on picasso-tailwind, users don't need to take any additional steps when new components are migrated. Therefore, such changes can be considered non-breaking, and a patch update would suffice.

However, for breaking changes—such as an API modification (e.g., removing the icon property from the List component)—these changes would require users to adjust their implementations. In these cases, a major version bump for Picasso is necessary, rather than a patch.

2024-09-06 12:21 UTC, OleksandrNechai commented on docs/contribution/changeset-guidelines.md
> +//if the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
```suggestion
// if the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is only required for packages that Picasso depends on, usually of the form `@toptal/picasso-package-name`.
```

2024-10-08 09:06 UTC, AdrianContiu commented
@toptal-anvil ping reviewers

2024-10-08 09:16 UTC, sashuk commented on docs/contribution/changeset-guidelines.md
> +> If the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
NIT

```suggestion
> If the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is required for packages that Picasso depends on, usually these packages have name like `@toptal/picasso-package-name`.
```

2024-10-08 09:16 UTC, sashuk approved these changes
Added small NIT comment, overall looks good!

2024-10-08 12:22 UTC, TomasSlama commented on docs/contribution/changeset-guidelines.md
> +> If the version bump is major, please also add `'@toptal/picasso': patch` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is o
```suggestion
> If the version bump is major, please also add `'@toptal/picasso': patch | minor | major` and don't forget to include the heading to have the changeset comments visible in the Picasso patch release notes. This is only required for packages that Picasso depends on, usually of the form `@toptal/picasso-package-name`.
```

2024-10-08 13:55 UTC, TomasSlama approved these changes

2024-10-08 18:00 UTC, OleksandrNechai commented on docs/contribution/changeset-guidelines.md
> +
Unfortunately I could not understand this note. 
1) Maybe better to put it after the format itself? The text earlier says "Please use this format:" and then note comes as if it is format 🤔 
2) `version bump is major, please also add `'@toptal/picasso': patch | minor | major` does not make sense to me. Add where? How do I pick between  patch | minor | major?
3) `don't forget to include the heading` include where? what heading?
4) `Picasso patch release notes` could be a link.
5) `usually these packages have name like` how do I know if I am in unusual case? What if my package is called differently but Picasso depends on it? How do I know?

General note. This is technical documentation, IMO it has to be very terse and clear, without "please" and "don't forget". Here is and example I did with ChatGPT:
```
For major version bumps, add '@toptal/picasso': patch | minor | major and include the heading to display the changeset comments in the Picasso patch release notes. This applies to Picasso dependent packages, typically named @toptal/picasso-package-name.
```

2024-10-08 18:03 UTC, OleksandrNechai requested changes
Thanks for improving documentation! I think it is good overall, but I think there is room for improvement. Please, make the text more clear and in tech docs style and we will be good to go ;)

2025-02-14 12:33 UTC, closed without merging