[FX-5908] Fix initial position of Slider
toptal/picasso pull request #4572
Opened 2024-09-20 10:09 UTC by TomasSlama

[FX-5908]

### Description

Fix initial position of Slider when rendered directly on visible screen. `useOnScreen` is returning `false` by default, so before the `IntersectionObserver` actually starts observing, the tooltip blinks from the bottom to the top. I enhanced the hook to also return `isObserved`, so the component can check if the returned value is correct.

### How to test

- Temploy
- Go to the slider default story and add `tooltip='on'`
- there should not be any jumping of the tooltip

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Insert screenshots or screen recordings | Insert screenshots or screen recordings |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- Annotate all `props` in component with documentation
- Create `examples` for component
- Ensure that deployed demo has expected results and good examples
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

2024-09-25 15:04 UTC, ruslan-sed requested changes
Works nice. However, some changes seem unnecessary. Maybe it is some kind of leftover, or I am missing something. Lets double check.

2024-09-25 15:04 UTC, ruslan-sed commented on packages/base/Slider/src/SliderValueLabel/SliderValueLabel.tsx
> +  }, [isOverlaped, index, xPlacement, value, tooltip])
It also works fine without this change. Do we need it?

2024-10-03 10:13 UTC, TomasSlama commented on tailwind.config.js
> +    'packages/base/*/src/**/*.{ts,tsx}',
Hey Ruslan, it is defenitely out of scope of this  PR, the problem is that after updating to the latest TailwindCSS there was a warning in the console, that Tailwind is reading folders that are not needed, so to get rid of the warning and also slightly speed up the compilation I added it.

2024-10-03 10:13 UTC, TomasSlama commented on packages/base/Slider/src/SliderValueLabel/SliderValueLabel.tsx
> +  }, [isOverlaped, index, xPlacement, value, tooltip])
removed, thanks

2024-10-03 10:14 UTC, TomasSlama commented on packages/base/Slider/src/Slider/Slider.tsx
> +  const [tooltip, setTooltip] = React.useState('off')
you are right, it was leftover

2024-10-03 10:14 UTC, TomasSlama commented on packages/base/Utils/src/utils/useOnScreen/use-on-screen.ts
> +  const [isOnScreen, setIntersecting] = useState(false)
done

2024-10-03 10:14 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2024-10-03 13:43 UTC, ruslan-sed commented
@TomasSlama is it intentional that the label is shifted to right instead of being centered as before?

![image](https://github.com/user-attachments/assets/b5c976d8-d00c-45e6-b9a0-e1062c221ebd)

2024-10-03 14:37 UTC, TomasSlama commented
it is not, thank you for noticing, I will take a look

2024-10-09 11:48 UTC, TomasSlama commented
@toptal-anvil ping reviewers

2024-10-09 11:49 UTC, TomasSlama commented on packages/base/Slider/src/SliderValueLabel/SliderValueLabel.tsx
> +  }, [isOverlaped, index, xPlacement, value, tooltip])
I had to put this back. On first render the tooltip is 'off' and we update it to proper value only after it is observed. Because of this, we need to recalculate the position after the tooltip is changed.

2024-10-09 12:29 UTC, ruslan-sed commented on packages/base/Slider/src/SliderValueLabel/SliderValueLabel.tsx
> +  }, [isOverlaped, index, xPlacement, value, tooltip])
Ok, I got it 👍  

But I think we should refactor it, because according to [React useEffect documentation](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes) `useEfect` should not be used in case like this. 

Also having a comment that explains why it should be recalculated when `tooltip` is changed would be beneficial in the future.

2024-10-09 12:41 UTC, ruslan-sed approved these changes
Good job!

2024-10-09 12:41 UTC, ruslan-sed commented on packages/base/Slider/src/Slider/hooks/use-label-overlap.ts
> +  }, [
This can also be refactored someday for the same reason

2024-10-09 16:42 UTC, sashuk approved these changes
Code looks good, compared both staging and temploy, works as expected!

2024-10-10 09:52 UTC, sashuk commented
Merging anyway, as the problem is only with docs deployment, so CI issue 

```
10:23:01  Identity added: /var/lib/jenkins/jenkins_root/workspace/picasso-docs@tmp/_____REDACTED_____.key (/var/lib/jenkins/jenkins_root/workspace/picasso-docs@tmp/_____REDACTED_____.key)
10:23:01  [ssh-agent] Started.
10:23:01  [Pipeline] {
10:23:01  [Pipeline] sh
10:23:01  + rsync -avz --delete -e ssh /var/lib/jenkins/jenkins_root/workspace/picasso-docs/deploy-docs/ '_____REDACTED_____:~/docs/picasso/fx-5908-slider'
10:23:02  Host key verification failed.
10:23:02  rsync: connection unexpectedly closed (0 bytes received so far) [sender]
10:23:02  rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]
```

2024-10-10 09:52 UTC, merged